import { defineConfig } from "oxlint";

export default defineConfig({
  categories: {
    correctness: "warn",
    perf: "warn",
    suspicious: "warn",
    pedantic: "off",
    style: "off",
    restriction: "off",
    nursery: "off",
  },
  env: {
    browser: true,
    builtin: true,
    es2026: true,
    node: true,
    "shared-node-browser": true,
  },
  ignorePatterns: [
    "pnpm-lock.yaml",
    ".astro/",
    "dist/",
    "node_modules/",
    "playwright-report/",
    "test-results/",
    "src/**/*.astro",
  ],
  plugins: ["typescript", "unicorn", "oxc", "eslint", "import", "node", "promise"],
  options: {
    denyWarnings: true,
    reportUnusedDisableDirectives: "error",
    typeAware: true,
  },
  rules: {
    "capitalized-comments": "off",
    curly: ["error", "all"],
    "id-length": "off",
    "import/no-duplicates": "error",
    "import/no-named-as-default": "warn",
    "import/no-named-as-default-member": "warn",
    "max-statements": "off",
    "no-array-constructor": "error",
    // Documentation generators and browser acceptance intentionally serialize stateful I/O.
    "no-await-in-loop": "off",
    "no-case-declarations": "error",
    "no-empty": "error",
    "no-fallthrough": "error",
    "no-prototype-builtins": "error",
    "no-redeclare": "error",
    "no-regex-spaces": "error",
    "no-unexpected-multiline": "off",
    "no-unused-expressions": "error",
    "no-useless-call": "error",
    "no-var": "error",
    "oxc/no-accumulating-spread": "error",
    "prefer-rest-params": "error",
    "prefer-spread": "error",
    "typescript/ban-ts-comment": "error",
    "typescript/no-empty-object-type": "error",
    "typescript/no-explicit-any": "warn",
    "typescript/no-namespace": "error",
    "typescript/no-require-imports": "error",
    "typescript/no-unnecessary-type-constraint": "error",
    "typescript/no-unsafe-function-type": "error",
    "typescript/no-unused-vars": [
      "warn",
      {
        argsIgnorePattern: "^_",
        caughtErrorsIgnorePattern: "^_",
        destructuredArrayIgnorePattern: "^_",
        ignoreRestSiblings: true,
        varsIgnorePattern: "^_",
      },
    ],
    "typescript/prefer-as-const": "error",
    "typescript/triple-slash-reference": "off",
    "unicorn/consistent-function-scoping": "off",
    "unicorn/no-empty-file": "off",
    "unicorn/prefer-array-find": "error",
    "unicorn/prefer-set-has": "error",
  },
});
