# Generated by tools/schema/generate.py; do not edit by hand.
# Source: tools/schema/schema.json (normalized from the pinned canonical TL schema)
from __future__ import annotations

from dataclasses import dataclass
from typing import Any, ClassVar, Self

from miniproto.raw.base import TLField, TLFlagGroup, TLRequest
from miniproto.tl.codec import (
    TLCodecError,
    decode_bool,
    decode_bytes,
    decode_constructor_id,
    decode_double,
    decode_int,
    decode_int128,
    decode_int256,
    decode_long,
    decode_object,
    decode_string,
    decode_value,
    decode_vector,
    encode_bool,
    encode_bytes,
    encode_constructor_id,
    encode_double,
    encode_int,
    encode_int128,
    encode_int256,
    encode_long,
    encode_string,
    encode_value,
    encode_vector,
)


@dataclass(frozen=True, slots=True, kw_only=True)
class AuthFinishPasskeyLogin(TLRequest):
    credential: Any
    from_dc_id: int | None = None
    from_auth_key_id: int | None = None
    CONSTRUCTOR_ID: ClassVar[int] = 0x9857AD07
    QUALNAME: ClassVar[str] = "auth.finishPasskeyLogin"
    RESULT_TYPE: ClassVar[str] = "auth.Authorization"
    TL_FIELDS: ClassVar[tuple[TLField, ...]] = (
        TLField(
            name="credential",
            python_name="credential",
            type="InputPasskeyCredential",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="from_dc_id",
            python_name="from_dc_id",
            type="int",
            flag="flags",
            flag_index=0,
            is_optional=True,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="from_auth_key_id",
            python_name="from_auth_key_id",
            type="long",
            flag="flags",
            flag_index=0,
            is_optional=True,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
    )
    TL_FLAG_GROUPS: ClassVar[tuple[TLFlagGroup, ...]] = (
        TLFlagGroup(name="flags", python_name="flags", before_field_index=0),
    )

    def serialize(self) -> bytes:
        return self._serialize(boxed=True)

    def _serialize(self, *, boxed: bool = True) -> bytes:
        output = bytearray()
        if boxed:
            output.extend(encode_constructor_id(self.CONSTRUCTOR_ID))
        flags = 0
        if self.from_dc_id is not None:
            flags |= 1
        if self.from_auth_key_id is not None:
            flags |= 1
        output.extend(encode_int(flags))
        output.extend(encode_value("InputPasskeyCredential", self.credential))
        if self.from_dc_id is not None:
            output.extend(encode_int(self.from_dc_id))
        if self.from_auth_key_id is not None:
            output.extend(encode_long(self.from_auth_key_id))
        return bytes(output)

    @classmethod
    def deserialize(cls, data: bytes | memoryview) -> Self:
        obj, offset = cls._deserialize(data)
        if offset != len(data):
            raise TLCodecError("TL object payload has trailing bytes")
        return obj

    @classmethod
    def _deserialize(cls, data: bytes | memoryview, offset: int = 0, *, boxed: bool = True) -> tuple[Self, int]:
        raw_data = data
        cursor = offset
        if boxed:
            constructor_id, cursor = decode_constructor_id(raw_data, cursor)
            if constructor_id != cls.CONSTRUCTOR_ID:
                raise TLCodecError(f"expected constructor 0x{cls.CONSTRUCTOR_ID:08x}, got 0x{constructor_id:08x}")
        flags = 0
        flags, cursor = decode_int(raw_data, cursor)
        _value_credential, cursor = decode_value("InputPasskeyCredential", raw_data, cursor)
        if bool(flags & 1):
            _value_from_dc_id, cursor = decode_int(raw_data, cursor)
        else:
            _value_from_dc_id = None
        if bool(flags & 1):
            _value_from_auth_key_id, cursor = decode_long(raw_data, cursor)
        else:
            _value_from_auth_key_id = None
        return cls(
            credential=_value_credential, from_dc_id=_value_from_dc_id, from_auth_key_id=_value_from_auth_key_id
        ), cursor


@dataclass(frozen=True, slots=True, kw_only=True)
class AccountResetNotifySettings(TLRequest):
    pass
    CONSTRUCTOR_ID: ClassVar[int] = 0xDB7E1747
    QUALNAME: ClassVar[str] = "account.resetNotifySettings"
    RESULT_TYPE: ClassVar[str] = "Bool"
    TL_FIELDS: ClassVar[tuple[TLField, ...]] = ()
    TL_FLAG_GROUPS: ClassVar[tuple[TLFlagGroup, ...]] = ()

    def serialize(self) -> bytes:
        return self._serialize(boxed=True)

    def _serialize(self, *, boxed: bool = True) -> bytes:
        output = bytearray()
        if boxed:
            output.extend(encode_constructor_id(self.CONSTRUCTOR_ID))
        return bytes(output)

    @classmethod
    def deserialize(cls, data: bytes | memoryview) -> Self:
        obj, offset = cls._deserialize(data)
        if offset != len(data):
            raise TLCodecError("TL object payload has trailing bytes")
        return obj

    @classmethod
    def _deserialize(cls, data: bytes | memoryview, offset: int = 0, *, boxed: bool = True) -> tuple[Self, int]:
        raw_data = data
        cursor = offset
        if boxed:
            constructor_id, cursor = decode_constructor_id(raw_data, cursor)
            if constructor_id != cls.CONSTRUCTOR_ID:
                raise TLCodecError(f"expected constructor 0x{cls.CONSTRUCTOR_ID:08x}, got 0x{constructor_id:08x}")
        return cls(), cursor


@dataclass(frozen=True, slots=True, kw_only=True)
class AccountGetPaidMessagesRevenue(TLRequest):
    parent_peer: Any | None = None
    user_id: Any
    CONSTRUCTOR_ID: ClassVar[int] = 0x19BA4A67
    QUALNAME: ClassVar[str] = "account.getPaidMessagesRevenue"
    RESULT_TYPE: ClassVar[str] = "account.PaidMessagesRevenue"
    TL_FIELDS: ClassVar[tuple[TLField, ...]] = (
        TLField(
            name="parent_peer",
            python_name="parent_peer",
            type="InputPeer",
            flag="flags",
            flag_index=0,
            is_optional=True,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="user_id",
            python_name="user_id",
            type="InputUser",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
    )
    TL_FLAG_GROUPS: ClassVar[tuple[TLFlagGroup, ...]] = (
        TLFlagGroup(name="flags", python_name="flags", before_field_index=0),
    )

    def serialize(self) -> bytes:
        return self._serialize(boxed=True)

    def _serialize(self, *, boxed: bool = True) -> bytes:
        output = bytearray()
        if boxed:
            output.extend(encode_constructor_id(self.CONSTRUCTOR_ID))
        flags = 0
        if self.parent_peer is not None:
            flags |= 1
        output.extend(encode_int(flags))
        if self.parent_peer is not None:
            output.extend(encode_value("InputPeer", self.parent_peer))
        output.extend(encode_value("InputUser", self.user_id))
        return bytes(output)

    @classmethod
    def deserialize(cls, data: bytes | memoryview) -> Self:
        obj, offset = cls._deserialize(data)
        if offset != len(data):
            raise TLCodecError("TL object payload has trailing bytes")
        return obj

    @classmethod
    def _deserialize(cls, data: bytes | memoryview, offset: int = 0, *, boxed: bool = True) -> tuple[Self, int]:
        raw_data = data
        cursor = offset
        if boxed:
            constructor_id, cursor = decode_constructor_id(raw_data, cursor)
            if constructor_id != cls.CONSTRUCTOR_ID:
                raise TLCodecError(f"expected constructor 0x{cls.CONSTRUCTOR_ID:08x}, got 0x{constructor_id:08x}")
        flags = 0
        flags, cursor = decode_int(raw_data, cursor)
        if bool(flags & 1):
            _value_parent_peer, cursor = decode_value("InputPeer", raw_data, cursor)
        else:
            _value_parent_peer = None
        _value_user_id, cursor = decode_value("InputUser", raw_data, cursor)
        return cls(parent_peer=_value_parent_peer, user_id=_value_user_id), cursor


@dataclass(frozen=True, slots=True, kw_only=True)
class ContactsExportContactToken(TLRequest):
    pass
    CONSTRUCTOR_ID: ClassVar[int] = 0xF8654027
    QUALNAME: ClassVar[str] = "contacts.exportContactToken"
    RESULT_TYPE: ClassVar[str] = "ExportedContactToken"
    TL_FIELDS: ClassVar[tuple[TLField, ...]] = ()
    TL_FLAG_GROUPS: ClassVar[tuple[TLFlagGroup, ...]] = ()

    def serialize(self) -> bytes:
        return self._serialize(boxed=True)

    def _serialize(self, *, boxed: bool = True) -> bytes:
        output = bytearray()
        if boxed:
            output.extend(encode_constructor_id(self.CONSTRUCTOR_ID))
        return bytes(output)

    @classmethod
    def deserialize(cls, data: bytes | memoryview) -> Self:
        obj, offset = cls._deserialize(data)
        if offset != len(data):
            raise TLCodecError("TL object payload has trailing bytes")
        return obj

    @classmethod
    def _deserialize(cls, data: bytes | memoryview, offset: int = 0, *, boxed: bool = True) -> tuple[Self, int]:
        raw_data = data
        cursor = offset
        if boxed:
            constructor_id, cursor = decode_constructor_id(raw_data, cursor)
            if constructor_id != cls.CONSTRUCTOR_ID:
                raise TLCodecError(f"expected constructor 0x{cls.CONSTRUCTOR_ID:08x}, got 0x{constructor_id:08x}")
        return cls(), cursor


@dataclass(frozen=True, slots=True, kw_only=True)
class MessagesAddChatUser(TLRequest):
    chat_id: int
    user_id: Any
    fwd_limit: int
    CONSTRUCTOR_ID: ClassVar[int] = 0xCBC6D107
    QUALNAME: ClassVar[str] = "messages.addChatUser"
    RESULT_TYPE: ClassVar[str] = "messages.InvitedUsers"
    TL_FIELDS: ClassVar[tuple[TLField, ...]] = (
        TLField(
            name="chat_id",
            python_name="chat_id",
            type="long",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="user_id",
            python_name="user_id",
            type="InputUser",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="fwd_limit",
            python_name="fwd_limit",
            type="int",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
    )
    TL_FLAG_GROUPS: ClassVar[tuple[TLFlagGroup, ...]] = ()

    def serialize(self) -> bytes:
        return self._serialize(boxed=True)

    def _serialize(self, *, boxed: bool = True) -> bytes:
        output = bytearray()
        if boxed:
            output.extend(encode_constructor_id(self.CONSTRUCTOR_ID))
        output.extend(encode_long(self.chat_id))
        output.extend(encode_value("InputUser", self.user_id))
        output.extend(encode_int(self.fwd_limit))
        return bytes(output)

    @classmethod
    def deserialize(cls, data: bytes | memoryview) -> Self:
        obj, offset = cls._deserialize(data)
        if offset != len(data):
            raise TLCodecError("TL object payload has trailing bytes")
        return obj

    @classmethod
    def _deserialize(cls, data: bytes | memoryview, offset: int = 0, *, boxed: bool = True) -> tuple[Self, int]:
        raw_data = data
        cursor = offset
        if boxed:
            constructor_id, cursor = decode_constructor_id(raw_data, cursor)
            if constructor_id != cls.CONSTRUCTOR_ID:
                raise TLCodecError(f"expected constructor 0x{cls.CONSTRUCTOR_ID:08x}, got 0x{constructor_id:08x}")
        _value_chat_id, cursor = decode_long(raw_data, cursor)
        _value_user_id, cursor = decode_value("InputUser", raw_data, cursor)
        _value_fwd_limit, cursor = decode_int(raw_data, cursor)
        return cls(chat_id=_value_chat_id, user_id=_value_user_id, fwd_limit=_value_fwd_limit), cursor


@dataclass(frozen=True, slots=True, kw_only=True)
class MessagesGetBotCallbackAnswer(TLRequest):
    game: bool = False
    peer: Any
    msg_id: int
    data: bytes | None = None
    password: Any | None = None
    CONSTRUCTOR_ID: ClassVar[int] = 0x9342CA07
    QUALNAME: ClassVar[str] = "messages.getBotCallbackAnswer"
    RESULT_TYPE: ClassVar[str] = "messages.BotCallbackAnswer"
    TL_FIELDS: ClassVar[tuple[TLField, ...]] = (
        TLField(
            name="game",
            python_name="game",
            type="true",
            flag="flags",
            flag_index=1,
            is_optional=True,
            is_true_flag=True,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="peer",
            python_name="peer",
            type="InputPeer",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="msg_id",
            python_name="msg_id",
            type="int",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="data",
            python_name="data",
            type="bytes",
            flag="flags",
            flag_index=0,
            is_optional=True,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="password",
            python_name="password",
            type="InputCheckPasswordSRP",
            flag="flags",
            flag_index=2,
            is_optional=True,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
    )
    TL_FLAG_GROUPS: ClassVar[tuple[TLFlagGroup, ...]] = (
        TLFlagGroup(name="flags", python_name="flags", before_field_index=0),
    )

    def serialize(self) -> bytes:
        return self._serialize(boxed=True)

    def _serialize(self, *, boxed: bool = True) -> bytes:
        output = bytearray()
        if boxed:
            output.extend(encode_constructor_id(self.CONSTRUCTOR_ID))
        flags = 0
        if self.game:
            flags |= 2
        if self.data is not None:
            flags |= 1
        if self.password is not None:
            flags |= 4
        output.extend(encode_int(flags))
        output.extend(encode_value("InputPeer", self.peer))
        output.extend(encode_int(self.msg_id))
        if self.data is not None:
            output.extend(encode_bytes(self.data))
        if self.password is not None:
            output.extend(encode_value("InputCheckPasswordSRP", self.password))
        return bytes(output)

    @classmethod
    def deserialize(cls, data: bytes | memoryview) -> Self:
        obj, offset = cls._deserialize(data)
        if offset != len(data):
            raise TLCodecError("TL object payload has trailing bytes")
        return obj

    @classmethod
    def _deserialize(cls, data: bytes | memoryview, offset: int = 0, *, boxed: bool = True) -> tuple[Self, int]:
        raw_data = data
        cursor = offset
        if boxed:
            constructor_id, cursor = decode_constructor_id(raw_data, cursor)
            if constructor_id != cls.CONSTRUCTOR_ID:
                raise TLCodecError(f"expected constructor 0x{cls.CONSTRUCTOR_ID:08x}, got 0x{constructor_id:08x}")
        flags = 0
        flags, cursor = decode_int(raw_data, cursor)
        _value_game = bool(flags & 2)
        _value_peer, cursor = decode_value("InputPeer", raw_data, cursor)
        _value_msg_id, cursor = decode_int(raw_data, cursor)
        if bool(flags & 1):
            _value_data, cursor = decode_bytes(raw_data, cursor)
        else:
            _value_data = None
        if bool(flags & 4):
            _value_password, cursor = decode_value("InputCheckPasswordSRP", raw_data, cursor)
        else:
            _value_password = None
        return cls(
            game=_value_game, peer=_value_peer, msg_id=_value_msg_id, data=_value_data, password=_value_password
        ), cursor


@dataclass(frozen=True, slots=True, kw_only=True)
class MessagesUnpinAllMessages(TLRequest):
    peer: Any
    top_msg_id: int | None = None
    saved_peer_id: Any | None = None
    CONSTRUCTOR_ID: ClassVar[int] = 0x062DD747
    QUALNAME: ClassVar[str] = "messages.unpinAllMessages"
    RESULT_TYPE: ClassVar[str] = "messages.AffectedHistory"
    TL_FIELDS: ClassVar[tuple[TLField, ...]] = (
        TLField(
            name="peer",
            python_name="peer",
            type="InputPeer",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="top_msg_id",
            python_name="top_msg_id",
            type="int",
            flag="flags",
            flag_index=0,
            is_optional=True,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="saved_peer_id",
            python_name="saved_peer_id",
            type="InputPeer",
            flag="flags",
            flag_index=1,
            is_optional=True,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
    )
    TL_FLAG_GROUPS: ClassVar[tuple[TLFlagGroup, ...]] = (
        TLFlagGroup(name="flags", python_name="flags", before_field_index=0),
    )

    def serialize(self) -> bytes:
        return self._serialize(boxed=True)

    def _serialize(self, *, boxed: bool = True) -> bytes:
        output = bytearray()
        if boxed:
            output.extend(encode_constructor_id(self.CONSTRUCTOR_ID))
        flags = 0
        if self.top_msg_id is not None:
            flags |= 1
        if self.saved_peer_id is not None:
            flags |= 2
        output.extend(encode_int(flags))
        output.extend(encode_value("InputPeer", self.peer))
        if self.top_msg_id is not None:
            output.extend(encode_int(self.top_msg_id))
        if self.saved_peer_id is not None:
            output.extend(encode_value("InputPeer", self.saved_peer_id))
        return bytes(output)

    @classmethod
    def deserialize(cls, data: bytes | memoryview) -> Self:
        obj, offset = cls._deserialize(data)
        if offset != len(data):
            raise TLCodecError("TL object payload has trailing bytes")
        return obj

    @classmethod
    def _deserialize(cls, data: bytes | memoryview, offset: int = 0, *, boxed: bool = True) -> tuple[Self, int]:
        raw_data = data
        cursor = offset
        if boxed:
            constructor_id, cursor = decode_constructor_id(raw_data, cursor)
            if constructor_id != cls.CONSTRUCTOR_ID:
                raise TLCodecError(f"expected constructor 0x{cls.CONSTRUCTOR_ID:08x}, got 0x{constructor_id:08x}")
        flags = 0
        flags, cursor = decode_int(raw_data, cursor)
        _value_peer, cursor = decode_value("InputPeer", raw_data, cursor)
        if bool(flags & 1):
            _value_top_msg_id, cursor = decode_int(raw_data, cursor)
        else:
            _value_top_msg_id = None
        if bool(flags & 2):
            _value_saved_peer_id, cursor = decode_value("InputPeer", raw_data, cursor)
        else:
            _value_saved_peer_id = None
        return cls(peer=_value_peer, top_msg_id=_value_top_msg_id, saved_peer_id=_value_saved_peer_id), cursor


@dataclass(frozen=True, slots=True, kw_only=True)
class MessagesSendBotRequestedPeer(TLRequest):
    peer: Any
    msg_id: int | None = None
    webapp_req_id: str | None = None
    button_id: int
    requested_peers: tuple[Any, ...]
    CONSTRUCTOR_ID: ClassVar[int] = 0x6C5CF2A7
    QUALNAME: ClassVar[str] = "messages.sendBotRequestedPeer"
    RESULT_TYPE: ClassVar[str] = "Updates"
    TL_FIELDS: ClassVar[tuple[TLField, ...]] = (
        TLField(
            name="peer",
            python_name="peer",
            type="InputPeer",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="msg_id",
            python_name="msg_id",
            type="int",
            flag="flags",
            flag_index=0,
            is_optional=True,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="webapp_req_id",
            python_name="webapp_req_id",
            type="string",
            flag="flags",
            flag_index=1,
            is_optional=True,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="button_id",
            python_name="button_id",
            type="int",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="requested_peers",
            python_name="requested_peers",
            type="Vector<InputPeer>",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=True,
            vector_item_type="InputPeer",
        ),
    )
    TL_FLAG_GROUPS: ClassVar[tuple[TLFlagGroup, ...]] = (
        TLFlagGroup(name="flags", python_name="flags", before_field_index=0),
    )

    def serialize(self) -> bytes:
        return self._serialize(boxed=True)

    def _serialize(self, *, boxed: bool = True) -> bytes:
        output = bytearray()
        if boxed:
            output.extend(encode_constructor_id(self.CONSTRUCTOR_ID))
        flags = 0
        if self.msg_id is not None:
            flags |= 1
        if self.webapp_req_id is not None:
            flags |= 2
        output.extend(encode_int(flags))
        output.extend(encode_value("InputPeer", self.peer))
        if self.msg_id is not None:
            output.extend(encode_int(self.msg_id))
        if self.webapp_req_id is not None:
            output.extend(encode_string(self.webapp_req_id))
        output.extend(encode_int(self.button_id))
        output.extend(encode_vector(self.requested_peers, "InputPeer"))
        return bytes(output)

    @classmethod
    def deserialize(cls, data: bytes | memoryview) -> Self:
        obj, offset = cls._deserialize(data)
        if offset != len(data):
            raise TLCodecError("TL object payload has trailing bytes")
        return obj

    @classmethod
    def _deserialize(cls, data: bytes | memoryview, offset: int = 0, *, boxed: bool = True) -> tuple[Self, int]:
        raw_data = data
        cursor = offset
        if boxed:
            constructor_id, cursor = decode_constructor_id(raw_data, cursor)
            if constructor_id != cls.CONSTRUCTOR_ID:
                raise TLCodecError(f"expected constructor 0x{cls.CONSTRUCTOR_ID:08x}, got 0x{constructor_id:08x}")
        flags = 0
        flags, cursor = decode_int(raw_data, cursor)
        _value_peer, cursor = decode_value("InputPeer", raw_data, cursor)
        if bool(flags & 1):
            _value_msg_id, cursor = decode_int(raw_data, cursor)
        else:
            _value_msg_id = None
        if bool(flags & 2):
            _value_webapp_req_id, cursor = decode_string(raw_data, cursor)
        else:
            _value_webapp_req_id = None
        _value_button_id, cursor = decode_int(raw_data, cursor)
        _value_requested_peers, cursor = decode_vector(raw_data, cursor, "InputPeer")
        return cls(
            peer=_value_peer,
            msg_id=_value_msg_id,
            webapp_req_id=_value_webapp_req_id,
            button_id=_value_button_id,
            requested_peers=_value_requested_peers,
        ), cursor


@dataclass(frozen=True, slots=True, kw_only=True)
class MessagesReorderPinnedSavedDialogs(TLRequest):
    force: bool = False
    order: tuple[Any, ...]
    CONSTRUCTOR_ID: ClassVar[int] = 0x8B716587
    QUALNAME: ClassVar[str] = "messages.reorderPinnedSavedDialogs"
    RESULT_TYPE: ClassVar[str] = "Bool"
    TL_FIELDS: ClassVar[tuple[TLField, ...]] = (
        TLField(
            name="force",
            python_name="force",
            type="true",
            flag="flags",
            flag_index=0,
            is_optional=True,
            is_true_flag=True,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="order",
            python_name="order",
            type="Vector<InputDialogPeer>",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=True,
            vector_item_type="InputDialogPeer",
        ),
    )
    TL_FLAG_GROUPS: ClassVar[tuple[TLFlagGroup, ...]] = (
        TLFlagGroup(name="flags", python_name="flags", before_field_index=0),
    )

    def serialize(self) -> bytes:
        return self._serialize(boxed=True)

    def _serialize(self, *, boxed: bool = True) -> bytes:
        output = bytearray()
        if boxed:
            output.extend(encode_constructor_id(self.CONSTRUCTOR_ID))
        flags = 0
        if self.force:
            flags |= 1
        output.extend(encode_int(flags))
        output.extend(encode_vector(self.order, "InputDialogPeer"))
        return bytes(output)

    @classmethod
    def deserialize(cls, data: bytes | memoryview) -> Self:
        obj, offset = cls._deserialize(data)
        if offset != len(data):
            raise TLCodecError("TL object payload has trailing bytes")
        return obj

    @classmethod
    def _deserialize(cls, data: bytes | memoryview, offset: int = 0, *, boxed: bool = True) -> tuple[Self, int]:
        raw_data = data
        cursor = offset
        if boxed:
            constructor_id, cursor = decode_constructor_id(raw_data, cursor)
            if constructor_id != cls.CONSTRUCTOR_ID:
                raise TLCodecError(f"expected constructor 0x{cls.CONSTRUCTOR_ID:08x}, got 0x{constructor_id:08x}")
        flags = 0
        flags, cursor = decode_int(raw_data, cursor)
        _value_force = bool(flags & 1)
        _value_order, cursor = decode_vector(raw_data, cursor, "InputDialogPeer")
        return cls(force=_value_force, order=_value_order), cursor


@dataclass(frozen=True, slots=True, kw_only=True)
class MessagesReorderQuickReplies(TLRequest):
    order: tuple[int, ...]
    CONSTRUCTOR_ID: ClassVar[int] = 0x60331907
    QUALNAME: ClassVar[str] = "messages.reorderQuickReplies"
    RESULT_TYPE: ClassVar[str] = "Bool"
    TL_FIELDS: ClassVar[tuple[TLField, ...]] = (
        TLField(
            name="order",
            python_name="order",
            type="Vector<int>",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=True,
            vector_item_type="int",
        ),
    )
    TL_FLAG_GROUPS: ClassVar[tuple[TLFlagGroup, ...]] = ()

    def serialize(self) -> bytes:
        return self._serialize(boxed=True)

    def _serialize(self, *, boxed: bool = True) -> bytes:
        output = bytearray()
        if boxed:
            output.extend(encode_constructor_id(self.CONSTRUCTOR_ID))
        output.extend(encode_vector(self.order, "int"))
        return bytes(output)

    @classmethod
    def deserialize(cls, data: bytes | memoryview) -> Self:
        obj, offset = cls._deserialize(data)
        if offset != len(data):
            raise TLCodecError("TL object payload has trailing bytes")
        return obj

    @classmethod
    def _deserialize(cls, data: bytes | memoryview, offset: int = 0, *, boxed: bool = True) -> tuple[Self, int]:
        raw_data = data
        cursor = offset
        if boxed:
            constructor_id, cursor = decode_constructor_id(raw_data, cursor)
            if constructor_id != cls.CONSTRUCTOR_ID:
                raise TLCodecError(f"expected constructor 0x{cls.CONSTRUCTOR_ID:08x}, got 0x{constructor_id:08x}")
        _value_order, cursor = decode_vector(raw_data, cursor, "int")
        return cls(order=_value_order), cursor


@dataclass(frozen=True, slots=True, kw_only=True)
class MessagesGetEmojiGameInfo(TLRequest):
    pass
    CONSTRUCTOR_ID: ClassVar[int] = 0xFB7E8CA7
    QUALNAME: ClassVar[str] = "messages.getEmojiGameInfo"
    RESULT_TYPE: ClassVar[str] = "messages.EmojiGameInfo"
    TL_FIELDS: ClassVar[tuple[TLField, ...]] = ()
    TL_FLAG_GROUPS: ClassVar[tuple[TLFlagGroup, ...]] = ()

    def serialize(self) -> bytes:
        return self._serialize(boxed=True)

    def _serialize(self, *, boxed: bool = True) -> bytes:
        output = bytearray()
        if boxed:
            output.extend(encode_constructor_id(self.CONSTRUCTOR_ID))
        return bytes(output)

    @classmethod
    def deserialize(cls, data: bytes | memoryview) -> Self:
        obj, offset = cls._deserialize(data)
        if offset != len(data):
            raise TLCodecError("TL object payload has trailing bytes")
        return obj

    @classmethod
    def _deserialize(cls, data: bytes | memoryview, offset: int = 0, *, boxed: bool = True) -> tuple[Self, int]:
        raw_data = data
        cursor = offset
        if boxed:
            constructor_id, cursor = decode_constructor_id(raw_data, cursor)
            if constructor_id != cls.CONSTRUCTOR_ID:
                raise TLCodecError(f"expected constructor 0x{cls.CONSTRUCTOR_ID:08x}, got 0x{constructor_id:08x}")
        return cls(), cursor


@dataclass(frozen=True, slots=True, kw_only=True)
class ChannelsCreateChannel(TLRequest):
    broadcast: bool = False
    megagroup: bool = False
    for_import: bool = False
    forum: bool = False
    title: str
    about: str
    geo_point: Any | None = None
    address: str | None = None
    ttl_period: int | None = None
    CONSTRUCTOR_ID: ClassVar[int] = 0x91006707
    QUALNAME: ClassVar[str] = "channels.createChannel"
    RESULT_TYPE: ClassVar[str] = "Updates"
    TL_FIELDS: ClassVar[tuple[TLField, ...]] = (
        TLField(
            name="broadcast",
            python_name="broadcast",
            type="true",
            flag="flags",
            flag_index=0,
            is_optional=True,
            is_true_flag=True,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="megagroup",
            python_name="megagroup",
            type="true",
            flag="flags",
            flag_index=1,
            is_optional=True,
            is_true_flag=True,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="for_import",
            python_name="for_import",
            type="true",
            flag="flags",
            flag_index=3,
            is_optional=True,
            is_true_flag=True,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="forum",
            python_name="forum",
            type="true",
            flag="flags",
            flag_index=5,
            is_optional=True,
            is_true_flag=True,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="title",
            python_name="title",
            type="string",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="about",
            python_name="about",
            type="string",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="geo_point",
            python_name="geo_point",
            type="InputGeoPoint",
            flag="flags",
            flag_index=2,
            is_optional=True,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="address",
            python_name="address",
            type="string",
            flag="flags",
            flag_index=2,
            is_optional=True,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="ttl_period",
            python_name="ttl_period",
            type="int",
            flag="flags",
            flag_index=4,
            is_optional=True,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
    )
    TL_FLAG_GROUPS: ClassVar[tuple[TLFlagGroup, ...]] = (
        TLFlagGroup(name="flags", python_name="flags", before_field_index=0),
    )

    def serialize(self) -> bytes:
        return self._serialize(boxed=True)

    def _serialize(self, *, boxed: bool = True) -> bytes:
        output = bytearray()
        if boxed:
            output.extend(encode_constructor_id(self.CONSTRUCTOR_ID))
        flags = 0
        if self.broadcast:
            flags |= 1
        if self.megagroup:
            flags |= 2
        if self.for_import:
            flags |= 8
        if self.forum:
            flags |= 32
        if self.geo_point is not None:
            flags |= 4
        if self.address is not None:
            flags |= 4
        if self.ttl_period is not None:
            flags |= 16
        output.extend(encode_int(flags))
        output.extend(encode_string(self.title))
        output.extend(encode_string(self.about))
        if self.geo_point is not None:
            output.extend(encode_value("InputGeoPoint", self.geo_point))
        if self.address is not None:
            output.extend(encode_string(self.address))
        if self.ttl_period is not None:
            output.extend(encode_int(self.ttl_period))
        return bytes(output)

    @classmethod
    def deserialize(cls, data: bytes | memoryview) -> Self:
        obj, offset = cls._deserialize(data)
        if offset != len(data):
            raise TLCodecError("TL object payload has trailing bytes")
        return obj

    @classmethod
    def _deserialize(cls, data: bytes | memoryview, offset: int = 0, *, boxed: bool = True) -> tuple[Self, int]:
        raw_data = data
        cursor = offset
        if boxed:
            constructor_id, cursor = decode_constructor_id(raw_data, cursor)
            if constructor_id != cls.CONSTRUCTOR_ID:
                raise TLCodecError(f"expected constructor 0x{cls.CONSTRUCTOR_ID:08x}, got 0x{constructor_id:08x}")
        flags = 0
        flags, cursor = decode_int(raw_data, cursor)
        _value_broadcast = bool(flags & 1)
        _value_megagroup = bool(flags & 2)
        _value_for_import = bool(flags & 8)
        _value_forum = bool(flags & 32)
        _value_title, cursor = decode_string(raw_data, cursor)
        _value_about, cursor = decode_string(raw_data, cursor)
        if bool(flags & 4):
            _value_geo_point, cursor = decode_value("InputGeoPoint", raw_data, cursor)
        else:
            _value_geo_point = None
        if bool(flags & 4):
            _value_address, cursor = decode_string(raw_data, cursor)
        else:
            _value_address = None
        if bool(flags & 16):
            _value_ttl_period, cursor = decode_int(raw_data, cursor)
        else:
            _value_ttl_period = None
        return cls(
            broadcast=_value_broadcast,
            megagroup=_value_megagroup,
            for_import=_value_for_import,
            forum=_value_forum,
            title=_value_title,
            about=_value_about,
            geo_point=_value_geo_point,
            address=_value_address,
            ttl_period=_value_ttl_period,
        ), cursor


@dataclass(frozen=True, slots=True, kw_only=True)
class ChannelsDeleteHistory(TLRequest):
    for_everyone: bool = False
    channel: Any
    max_id: int
    CONSTRUCTOR_ID: ClassVar[int] = 0x9BAA9647
    QUALNAME: ClassVar[str] = "channels.deleteHistory"
    RESULT_TYPE: ClassVar[str] = "Updates"
    TL_FIELDS: ClassVar[tuple[TLField, ...]] = (
        TLField(
            name="for_everyone",
            python_name="for_everyone",
            type="true",
            flag="flags",
            flag_index=0,
            is_optional=True,
            is_true_flag=True,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="channel",
            python_name="channel",
            type="InputChannel",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="max_id",
            python_name="max_id",
            type="int",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
    )
    TL_FLAG_GROUPS: ClassVar[tuple[TLFlagGroup, ...]] = (
        TLFlagGroup(name="flags", python_name="flags", before_field_index=0),
    )

    def serialize(self) -> bytes:
        return self._serialize(boxed=True)

    def _serialize(self, *, boxed: bool = True) -> bytes:
        output = bytearray()
        if boxed:
            output.extend(encode_constructor_id(self.CONSTRUCTOR_ID))
        flags = 0
        if self.for_everyone:
            flags |= 1
        output.extend(encode_int(flags))
        output.extend(encode_value("InputChannel", self.channel))
        output.extend(encode_int(self.max_id))
        return bytes(output)

    @classmethod
    def deserialize(cls, data: bytes | memoryview) -> Self:
        obj, offset = cls._deserialize(data)
        if offset != len(data):
            raise TLCodecError("TL object payload has trailing bytes")
        return obj

    @classmethod
    def _deserialize(cls, data: bytes | memoryview, offset: int = 0, *, boxed: bool = True) -> tuple[Self, int]:
        raw_data = data
        cursor = offset
        if boxed:
            constructor_id, cursor = decode_constructor_id(raw_data, cursor)
            if constructor_id != cls.CONSTRUCTOR_ID:
                raise TLCodecError(f"expected constructor 0x{cls.CONSTRUCTOR_ID:08x}, got 0x{constructor_id:08x}")
        flags = 0
        flags, cursor = decode_int(raw_data, cursor)
        _value_for_everyone = bool(flags & 1)
        _value_channel, cursor = decode_value("InputChannel", raw_data, cursor)
        _value_max_id, cursor = decode_int(raw_data, cursor)
        return cls(for_everyone=_value_for_everyone, channel=_value_channel, max_id=_value_max_id), cursor


@dataclass(frozen=True, slots=True, kw_only=True)
class BotsInvokeWebViewCustomMethod(TLRequest):
    bot: Any
    custom_method: str
    params: Any
    CONSTRUCTOR_ID: ClassVar[int] = 0x087FC5E7
    QUALNAME: ClassVar[str] = "bots.invokeWebViewCustomMethod"
    RESULT_TYPE: ClassVar[str] = "DataJSON"
    TL_FIELDS: ClassVar[tuple[TLField, ...]] = (
        TLField(
            name="bot",
            python_name="bot",
            type="InputUser",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="custom_method",
            python_name="custom_method",
            type="string",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="params",
            python_name="params",
            type="DataJSON",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
    )
    TL_FLAG_GROUPS: ClassVar[tuple[TLFlagGroup, ...]] = ()

    def serialize(self) -> bytes:
        return self._serialize(boxed=True)

    def _serialize(self, *, boxed: bool = True) -> bytes:
        output = bytearray()
        if boxed:
            output.extend(encode_constructor_id(self.CONSTRUCTOR_ID))
        output.extend(encode_value("InputUser", self.bot))
        output.extend(encode_string(self.custom_method))
        output.extend(encode_value("DataJSON", self.params))
        return bytes(output)

    @classmethod
    def deserialize(cls, data: bytes | memoryview) -> Self:
        obj, offset = cls._deserialize(data)
        if offset != len(data):
            raise TLCodecError("TL object payload has trailing bytes")
        return obj

    @classmethod
    def _deserialize(cls, data: bytes | memoryview, offset: int = 0, *, boxed: bool = True) -> tuple[Self, int]:
        raw_data = data
        cursor = offset
        if boxed:
            constructor_id, cursor = decode_constructor_id(raw_data, cursor)
            if constructor_id != cls.CONSTRUCTOR_ID:
                raise TLCodecError(f"expected constructor 0x{cls.CONSTRUCTOR_ID:08x}, got 0x{constructor_id:08x}")
        _value_bot, cursor = decode_value("InputUser", raw_data, cursor)
        _value_custom_method, cursor = decode_string(raw_data, cursor)
        _value_params, cursor = decode_value("DataJSON", raw_data, cursor)
        return cls(bot=_value_bot, custom_method=_value_custom_method, params=_value_params), cursor


@dataclass(frozen=True, slots=True, kw_only=True)
class PaymentsCanPurchaseStore(TLRequest):
    purpose: Any
    CONSTRUCTOR_ID: ClassVar[int] = 0x4FDC5EA7
    QUALNAME: ClassVar[str] = "payments.canPurchaseStore"
    RESULT_TYPE: ClassVar[str] = "Bool"
    TL_FIELDS: ClassVar[tuple[TLField, ...]] = (
        TLField(
            name="purpose",
            python_name="purpose",
            type="InputStorePaymentPurpose",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
    )
    TL_FLAG_GROUPS: ClassVar[tuple[TLFlagGroup, ...]] = ()

    def serialize(self) -> bytes:
        return self._serialize(boxed=True)

    def _serialize(self, *, boxed: bool = True) -> bytes:
        output = bytearray()
        if boxed:
            output.extend(encode_constructor_id(self.CONSTRUCTOR_ID))
        output.extend(encode_value("InputStorePaymentPurpose", self.purpose))
        return bytes(output)

    @classmethod
    def deserialize(cls, data: bytes | memoryview) -> Self:
        obj, offset = cls._deserialize(data)
        if offset != len(data):
            raise TLCodecError("TL object payload has trailing bytes")
        return obj

    @classmethod
    def _deserialize(cls, data: bytes | memoryview, offset: int = 0, *, boxed: bool = True) -> tuple[Self, int]:
        raw_data = data
        cursor = offset
        if boxed:
            constructor_id, cursor = decode_constructor_id(raw_data, cursor)
            if constructor_id != cls.CONSTRUCTOR_ID:
                raise TLCodecError(f"expected constructor 0x{cls.CONSTRUCTOR_ID:08x}, got 0x{constructor_id:08x}")
        _value_purpose, cursor = decode_value("InputStorePaymentPurpose", raw_data, cursor)
        return cls(purpose=_value_purpose), cursor


@dataclass(frozen=True, slots=True, kw_only=True)
class PaymentsCreateStarGiftCollection(TLRequest):
    peer: Any
    title: str
    stargift: tuple[Any, ...]
    CONSTRUCTOR_ID: ClassVar[int] = 0x1F4A0E87
    QUALNAME: ClassVar[str] = "payments.createStarGiftCollection"
    RESULT_TYPE: ClassVar[str] = "StarGiftCollection"
    TL_FIELDS: ClassVar[tuple[TLField, ...]] = (
        TLField(
            name="peer",
            python_name="peer",
            type="InputPeer",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="title",
            python_name="title",
            type="string",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="stargift",
            python_name="stargift",
            type="Vector<InputSavedStarGift>",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=True,
            vector_item_type="InputSavedStarGift",
        ),
    )
    TL_FLAG_GROUPS: ClassVar[tuple[TLFlagGroup, ...]] = ()

    def serialize(self) -> bytes:
        return self._serialize(boxed=True)

    def _serialize(self, *, boxed: bool = True) -> bytes:
        output = bytearray()
        if boxed:
            output.extend(encode_constructor_id(self.CONSTRUCTOR_ID))
        output.extend(encode_value("InputPeer", self.peer))
        output.extend(encode_string(self.title))
        output.extend(encode_vector(self.stargift, "InputSavedStarGift"))
        return bytes(output)

    @classmethod
    def deserialize(cls, data: bytes | memoryview) -> Self:
        obj, offset = cls._deserialize(data)
        if offset != len(data):
            raise TLCodecError("TL object payload has trailing bytes")
        return obj

    @classmethod
    def _deserialize(cls, data: bytes | memoryview, offset: int = 0, *, boxed: bool = True) -> tuple[Self, int]:
        raw_data = data
        cursor = offset
        if boxed:
            constructor_id, cursor = decode_constructor_id(raw_data, cursor)
            if constructor_id != cls.CONSTRUCTOR_ID:
                raise TLCodecError(f"expected constructor 0x{cls.CONSTRUCTOR_ID:08x}, got 0x{constructor_id:08x}")
        _value_peer, cursor = decode_value("InputPeer", raw_data, cursor)
        _value_title, cursor = decode_string(raw_data, cursor)
        _value_stargift, cursor = decode_vector(raw_data, cursor, "InputSavedStarGift")
        return cls(peer=_value_peer, title=_value_title, stargift=_value_stargift), cursor


@dataclass(frozen=True, slots=True, kw_only=True)
class PaymentsUpdateStarGiftCollection(TLRequest):
    peer: Any
    collection_id: int
    title: str | None = None
    delete_stargift: tuple[Any, ...] | None = None
    add_stargift: tuple[Any, ...] | None = None
    order: tuple[Any, ...] | None = None
    CONSTRUCTOR_ID: ClassVar[int] = 0x4FDDBEE7
    QUALNAME: ClassVar[str] = "payments.updateStarGiftCollection"
    RESULT_TYPE: ClassVar[str] = "StarGiftCollection"
    TL_FIELDS: ClassVar[tuple[TLField, ...]] = (
        TLField(
            name="peer",
            python_name="peer",
            type="InputPeer",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="collection_id",
            python_name="collection_id",
            type="int",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="title",
            python_name="title",
            type="string",
            flag="flags",
            flag_index=0,
            is_optional=True,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="delete_stargift",
            python_name="delete_stargift",
            type="Vector<InputSavedStarGift>",
            flag="flags",
            flag_index=1,
            is_optional=True,
            is_true_flag=False,
            is_vector=True,
            vector_item_type="InputSavedStarGift",
        ),
        TLField(
            name="add_stargift",
            python_name="add_stargift",
            type="Vector<InputSavedStarGift>",
            flag="flags",
            flag_index=2,
            is_optional=True,
            is_true_flag=False,
            is_vector=True,
            vector_item_type="InputSavedStarGift",
        ),
        TLField(
            name="order",
            python_name="order",
            type="Vector<InputSavedStarGift>",
            flag="flags",
            flag_index=3,
            is_optional=True,
            is_true_flag=False,
            is_vector=True,
            vector_item_type="InputSavedStarGift",
        ),
    )
    TL_FLAG_GROUPS: ClassVar[tuple[TLFlagGroup, ...]] = (
        TLFlagGroup(name="flags", python_name="flags", before_field_index=0),
    )

    def serialize(self) -> bytes:
        return self._serialize(boxed=True)

    def _serialize(self, *, boxed: bool = True) -> bytes:
        output = bytearray()
        if boxed:
            output.extend(encode_constructor_id(self.CONSTRUCTOR_ID))
        flags = 0
        if self.title is not None:
            flags |= 1
        if self.delete_stargift is not None:
            flags |= 2
        if self.add_stargift is not None:
            flags |= 4
        if self.order is not None:
            flags |= 8
        output.extend(encode_int(flags))
        output.extend(encode_value("InputPeer", self.peer))
        output.extend(encode_int(self.collection_id))
        if self.title is not None:
            output.extend(encode_string(self.title))
        if self.delete_stargift is not None:
            output.extend(encode_vector(self.delete_stargift, "InputSavedStarGift"))
        if self.add_stargift is not None:
            output.extend(encode_vector(self.add_stargift, "InputSavedStarGift"))
        if self.order is not None:
            output.extend(encode_vector(self.order, "InputSavedStarGift"))
        return bytes(output)

    @classmethod
    def deserialize(cls, data: bytes | memoryview) -> Self:
        obj, offset = cls._deserialize(data)
        if offset != len(data):
            raise TLCodecError("TL object payload has trailing bytes")
        return obj

    @classmethod
    def _deserialize(cls, data: bytes | memoryview, offset: int = 0, *, boxed: bool = True) -> tuple[Self, int]:
        raw_data = data
        cursor = offset
        if boxed:
            constructor_id, cursor = decode_constructor_id(raw_data, cursor)
            if constructor_id != cls.CONSTRUCTOR_ID:
                raise TLCodecError(f"expected constructor 0x{cls.CONSTRUCTOR_ID:08x}, got 0x{constructor_id:08x}")
        flags = 0
        flags, cursor = decode_int(raw_data, cursor)
        _value_peer, cursor = decode_value("InputPeer", raw_data, cursor)
        _value_collection_id, cursor = decode_int(raw_data, cursor)
        if bool(flags & 1):
            _value_title, cursor = decode_string(raw_data, cursor)
        else:
            _value_title = None
        if bool(flags & 2):
            _value_delete_stargift, cursor = decode_vector(raw_data, cursor, "InputSavedStarGift")
        else:
            _value_delete_stargift = None
        if bool(flags & 4):
            _value_add_stargift, cursor = decode_vector(raw_data, cursor, "InputSavedStarGift")
        else:
            _value_add_stargift = None
        if bool(flags & 8):
            _value_order, cursor = decode_vector(raw_data, cursor, "InputSavedStarGift")
        else:
            _value_order = None
        return cls(
            peer=_value_peer,
            collection_id=_value_collection_id,
            title=_value_title,
            delete_stargift=_value_delete_stargift,
            add_stargift=_value_add_stargift,
            order=_value_order,
        ), cursor


@dataclass(frozen=True, slots=True, kw_only=True)
class StickersCreateStickerSet(TLRequest):
    masks: bool = False
    emojis: bool = False
    text_color: bool = False
    user_id: Any
    title: str
    short_name: str
    thumb: Any | None = None
    stickers: tuple[Any, ...]
    software: str | None = None
    CONSTRUCTOR_ID: ClassVar[int] = 0x9021AB67
    QUALNAME: ClassVar[str] = "stickers.createStickerSet"
    RESULT_TYPE: ClassVar[str] = "messages.StickerSet"
    TL_FIELDS: ClassVar[tuple[TLField, ...]] = (
        TLField(
            name="masks",
            python_name="masks",
            type="true",
            flag="flags",
            flag_index=0,
            is_optional=True,
            is_true_flag=True,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="emojis",
            python_name="emojis",
            type="true",
            flag="flags",
            flag_index=5,
            is_optional=True,
            is_true_flag=True,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="text_color",
            python_name="text_color",
            type="true",
            flag="flags",
            flag_index=6,
            is_optional=True,
            is_true_flag=True,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="user_id",
            python_name="user_id",
            type="InputUser",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="title",
            python_name="title",
            type="string",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="short_name",
            python_name="short_name",
            type="string",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="thumb",
            python_name="thumb",
            type="InputDocument",
            flag="flags",
            flag_index=2,
            is_optional=True,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="stickers",
            python_name="stickers",
            type="Vector<InputStickerSetItem>",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=True,
            vector_item_type="InputStickerSetItem",
        ),
        TLField(
            name="software",
            python_name="software",
            type="string",
            flag="flags",
            flag_index=3,
            is_optional=True,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
    )
    TL_FLAG_GROUPS: ClassVar[tuple[TLFlagGroup, ...]] = (
        TLFlagGroup(name="flags", python_name="flags", before_field_index=0),
    )

    def serialize(self) -> bytes:
        return self._serialize(boxed=True)

    def _serialize(self, *, boxed: bool = True) -> bytes:
        output = bytearray()
        if boxed:
            output.extend(encode_constructor_id(self.CONSTRUCTOR_ID))
        flags = 0
        if self.masks:
            flags |= 1
        if self.emojis:
            flags |= 32
        if self.text_color:
            flags |= 64
        if self.thumb is not None:
            flags |= 4
        if self.software is not None:
            flags |= 8
        output.extend(encode_int(flags))
        output.extend(encode_value("InputUser", self.user_id))
        output.extend(encode_string(self.title))
        output.extend(encode_string(self.short_name))
        if self.thumb is not None:
            output.extend(encode_value("InputDocument", self.thumb))
        output.extend(encode_vector(self.stickers, "InputStickerSetItem"))
        if self.software is not None:
            output.extend(encode_string(self.software))
        return bytes(output)

    @classmethod
    def deserialize(cls, data: bytes | memoryview) -> Self:
        obj, offset = cls._deserialize(data)
        if offset != len(data):
            raise TLCodecError("TL object payload has trailing bytes")
        return obj

    @classmethod
    def _deserialize(cls, data: bytes | memoryview, offset: int = 0, *, boxed: bool = True) -> tuple[Self, int]:
        raw_data = data
        cursor = offset
        if boxed:
            constructor_id, cursor = decode_constructor_id(raw_data, cursor)
            if constructor_id != cls.CONSTRUCTOR_ID:
                raise TLCodecError(f"expected constructor 0x{cls.CONSTRUCTOR_ID:08x}, got 0x{constructor_id:08x}")
        flags = 0
        flags, cursor = decode_int(raw_data, cursor)
        _value_masks = bool(flags & 1)
        _value_emojis = bool(flags & 32)
        _value_text_color = bool(flags & 64)
        _value_user_id, cursor = decode_value("InputUser", raw_data, cursor)
        _value_title, cursor = decode_string(raw_data, cursor)
        _value_short_name, cursor = decode_string(raw_data, cursor)
        if bool(flags & 4):
            _value_thumb, cursor = decode_value("InputDocument", raw_data, cursor)
        else:
            _value_thumb = None
        _value_stickers, cursor = decode_vector(raw_data, cursor, "InputStickerSetItem")
        if bool(flags & 8):
            _value_software, cursor = decode_string(raw_data, cursor)
        else:
            _value_software = None
        return cls(
            masks=_value_masks,
            emojis=_value_emojis,
            text_color=_value_text_color,
            user_id=_value_user_id,
            title=_value_title,
            short_name=_value_short_name,
            thumb=_value_thumb,
            stickers=_value_stickers,
            software=_value_software,
        ), cursor


@dataclass(frozen=True, slots=True, kw_only=True)
class PhoneSetCallRating(TLRequest):
    user_initiative: bool = False
    peer: Any
    rating: int
    comment: str
    CONSTRUCTOR_ID: ClassVar[int] = 0x59EAD627
    QUALNAME: ClassVar[str] = "phone.setCallRating"
    RESULT_TYPE: ClassVar[str] = "Updates"
    TL_FIELDS: ClassVar[tuple[TLField, ...]] = (
        TLField(
            name="user_initiative",
            python_name="user_initiative",
            type="true",
            flag="flags",
            flag_index=0,
            is_optional=True,
            is_true_flag=True,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="peer",
            python_name="peer",
            type="InputPhoneCall",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="rating",
            python_name="rating",
            type="int",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="comment",
            python_name="comment",
            type="string",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
    )
    TL_FLAG_GROUPS: ClassVar[tuple[TLFlagGroup, ...]] = (
        TLFlagGroup(name="flags", python_name="flags", before_field_index=0),
    )

    def serialize(self) -> bytes:
        return self._serialize(boxed=True)

    def _serialize(self, *, boxed: bool = True) -> bytes:
        output = bytearray()
        if boxed:
            output.extend(encode_constructor_id(self.CONSTRUCTOR_ID))
        flags = 0
        if self.user_initiative:
            flags |= 1
        output.extend(encode_int(flags))
        output.extend(encode_value("InputPhoneCall", self.peer))
        output.extend(encode_int(self.rating))
        output.extend(encode_string(self.comment))
        return bytes(output)

    @classmethod
    def deserialize(cls, data: bytes | memoryview) -> Self:
        obj, offset = cls._deserialize(data)
        if offset != len(data):
            raise TLCodecError("TL object payload has trailing bytes")
        return obj

    @classmethod
    def _deserialize(cls, data: bytes | memoryview, offset: int = 0, *, boxed: bool = True) -> tuple[Self, int]:
        raw_data = data
        cursor = offset
        if boxed:
            constructor_id, cursor = decode_constructor_id(raw_data, cursor)
            if constructor_id != cls.CONSTRUCTOR_ID:
                raise TLCodecError(f"expected constructor 0x{cls.CONSTRUCTOR_ID:08x}, got 0x{constructor_id:08x}")
        flags = 0
        flags, cursor = decode_int(raw_data, cursor)
        _value_user_initiative = bool(flags & 1)
        _value_peer, cursor = decode_value("InputPhoneCall", raw_data, cursor)
        _value_rating, cursor = decode_int(raw_data, cursor)
        _value_comment, cursor = decode_string(raw_data, cursor)
        return cls(
            user_initiative=_value_user_initiative, peer=_value_peer, rating=_value_rating, comment=_value_comment
        ), cursor


@dataclass(frozen=True, slots=True, kw_only=True)
class StatsGetMegagroupStats(TLRequest):
    dark: bool = False
    channel: Any
    CONSTRUCTOR_ID: ClassVar[int] = 0xDCDF8607
    QUALNAME: ClassVar[str] = "stats.getMegagroupStats"
    RESULT_TYPE: ClassVar[str] = "stats.MegagroupStats"
    TL_FIELDS: ClassVar[tuple[TLField, ...]] = (
        TLField(
            name="dark",
            python_name="dark",
            type="true",
            flag="flags",
            flag_index=0,
            is_optional=True,
            is_true_flag=True,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="channel",
            python_name="channel",
            type="InputChannel",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
    )
    TL_FLAG_GROUPS: ClassVar[tuple[TLFlagGroup, ...]] = (
        TLFlagGroup(name="flags", python_name="flags", before_field_index=0),
    )

    def serialize(self) -> bytes:
        return self._serialize(boxed=True)

    def _serialize(self, *, boxed: bool = True) -> bytes:
        output = bytearray()
        if boxed:
            output.extend(encode_constructor_id(self.CONSTRUCTOR_ID))
        flags = 0
        if self.dark:
            flags |= 1
        output.extend(encode_int(flags))
        output.extend(encode_value("InputChannel", self.channel))
        return bytes(output)

    @classmethod
    def deserialize(cls, data: bytes | memoryview) -> Self:
        obj, offset = cls._deserialize(data)
        if offset != len(data):
            raise TLCodecError("TL object payload has trailing bytes")
        return obj

    @classmethod
    def _deserialize(cls, data: bytes | memoryview, offset: int = 0, *, boxed: bool = True) -> tuple[Self, int]:
        raw_data = data
        cursor = offset
        if boxed:
            constructor_id, cursor = decode_constructor_id(raw_data, cursor)
            if constructor_id != cls.CONSTRUCTOR_ID:
                raise TLCodecError(f"expected constructor 0x{cls.CONSTRUCTOR_ID:08x}, got 0x{constructor_id:08x}")
        flags = 0
        flags, cursor = decode_int(raw_data, cursor)
        _value_dark = bool(flags & 1)
        _value_channel, cursor = decode_value("InputChannel", raw_data, cursor)
        return cls(dark=_value_dark, channel=_value_channel), cursor


@dataclass(frozen=True, slots=True, kw_only=True)
class StoriesSearchPosts(TLRequest):
    hashtag: str | None = None
    area: Any | None = None
    peer: Any | None = None
    offset: str
    limit: int
    CONSTRUCTOR_ID: ClassVar[int] = 0xD1810907
    QUALNAME: ClassVar[str] = "stories.searchPosts"
    RESULT_TYPE: ClassVar[str] = "stories.FoundStories"
    TL_FIELDS: ClassVar[tuple[TLField, ...]] = (
        TLField(
            name="hashtag",
            python_name="hashtag",
            type="string",
            flag="flags",
            flag_index=0,
            is_optional=True,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="area",
            python_name="area",
            type="MediaArea",
            flag="flags",
            flag_index=1,
            is_optional=True,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="peer",
            python_name="peer",
            type="InputPeer",
            flag="flags",
            flag_index=2,
            is_optional=True,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="offset",
            python_name="offset",
            type="string",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="limit",
            python_name="limit",
            type="int",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
    )
    TL_FLAG_GROUPS: ClassVar[tuple[TLFlagGroup, ...]] = (
        TLFlagGroup(name="flags", python_name="flags", before_field_index=0),
    )

    def serialize(self) -> bytes:
        return self._serialize(boxed=True)

    def _serialize(self, *, boxed: bool = True) -> bytes:
        output = bytearray()
        if boxed:
            output.extend(encode_constructor_id(self.CONSTRUCTOR_ID))
        flags = 0
        if self.hashtag is not None:
            flags |= 1
        if self.area is not None:
            flags |= 2
        if self.peer is not None:
            flags |= 4
        output.extend(encode_int(flags))
        if self.hashtag is not None:
            output.extend(encode_string(self.hashtag))
        if self.area is not None:
            output.extend(encode_value("MediaArea", self.area))
        if self.peer is not None:
            output.extend(encode_value("InputPeer", self.peer))
        output.extend(encode_string(self.offset))
        output.extend(encode_int(self.limit))
        return bytes(output)

    @classmethod
    def deserialize(cls, data: bytes | memoryview) -> Self:
        obj, offset = cls._deserialize(data)
        if offset != len(data):
            raise TLCodecError("TL object payload has trailing bytes")
        return obj

    @classmethod
    def _deserialize(cls, data: bytes | memoryview, offset: int = 0, *, boxed: bool = True) -> tuple[Self, int]:
        raw_data = data
        cursor = offset
        if boxed:
            constructor_id, cursor = decode_constructor_id(raw_data, cursor)
            if constructor_id != cls.CONSTRUCTOR_ID:
                raise TLCodecError(f"expected constructor 0x{cls.CONSTRUCTOR_ID:08x}, got 0x{constructor_id:08x}")
        flags = 0
        flags, cursor = decode_int(raw_data, cursor)
        if bool(flags & 1):
            _value_hashtag, cursor = decode_string(raw_data, cursor)
        else:
            _value_hashtag = None
        if bool(flags & 2):
            _value_area, cursor = decode_value("MediaArea", raw_data, cursor)
        else:
            _value_area = None
        if bool(flags & 4):
            _value_peer, cursor = decode_value("InputPeer", raw_data, cursor)
        else:
            _value_peer = None
        _value_offset, cursor = decode_string(raw_data, cursor)
        _value_limit, cursor = decode_int(raw_data, cursor)
        return cls(
            hashtag=_value_hashtag, area=_value_area, peer=_value_peer, offset=_value_offset, limit=_value_limit
        ), cursor


@dataclass(frozen=True, slots=True, kw_only=True)
class StoriesGetAlbums(TLRequest):
    peer: Any
    hash: int
    CONSTRUCTOR_ID: ClassVar[int] = 0x25B3EAC7
    QUALNAME: ClassVar[str] = "stories.getAlbums"
    RESULT_TYPE: ClassVar[str] = "stories.Albums"
    TL_FIELDS: ClassVar[tuple[TLField, ...]] = (
        TLField(
            name="peer",
            python_name="peer",
            type="InputPeer",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="hash",
            python_name="hash",
            type="long",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
    )
    TL_FLAG_GROUPS: ClassVar[tuple[TLFlagGroup, ...]] = ()

    def serialize(self) -> bytes:
        return self._serialize(boxed=True)

    def _serialize(self, *, boxed: bool = True) -> bytes:
        output = bytearray()
        if boxed:
            output.extend(encode_constructor_id(self.CONSTRUCTOR_ID))
        output.extend(encode_value("InputPeer", self.peer))
        output.extend(encode_long(self.hash))
        return bytes(output)

    @classmethod
    def deserialize(cls, data: bytes | memoryview) -> Self:
        obj, offset = cls._deserialize(data)
        if offset != len(data):
            raise TLCodecError("TL object payload has trailing bytes")
        return obj

    @classmethod
    def _deserialize(cls, data: bytes | memoryview, offset: int = 0, *, boxed: bool = True) -> tuple[Self, int]:
        raw_data = data
        cursor = offset
        if boxed:
            constructor_id, cursor = decode_constructor_id(raw_data, cursor)
            if constructor_id != cls.CONSTRUCTOR_ID:
                raise TLCodecError(f"expected constructor 0x{cls.CONSTRUCTOR_ID:08x}, got 0x{constructor_id:08x}")
        _value_peer, cursor = decode_value("InputPeer", raw_data, cursor)
        _value_hash, cursor = decode_long(raw_data, cursor)
        return cls(peer=_value_peer, hash=_value_hash), cursor


class account:
    GetPaidMessagesRevenue = AccountGetPaidMessagesRevenue
    ResetNotifySettings = AccountResetNotifySettings


class auth:
    FinishPasskeyLogin = AuthFinishPasskeyLogin


class bots:
    InvokeWebViewCustomMethod = BotsInvokeWebViewCustomMethod


class channels:
    CreateChannel = ChannelsCreateChannel
    DeleteHistory = ChannelsDeleteHistory


class contacts:
    ExportContactToken = ContactsExportContactToken


class messages:
    AddChatUser = MessagesAddChatUser
    GetBotCallbackAnswer = MessagesGetBotCallbackAnswer
    GetEmojiGameInfo = MessagesGetEmojiGameInfo
    ReorderPinnedSavedDialogs = MessagesReorderPinnedSavedDialogs
    ReorderQuickReplies = MessagesReorderQuickReplies
    SendBotRequestedPeer = MessagesSendBotRequestedPeer
    UnpinAllMessages = MessagesUnpinAllMessages


class payments:
    CanPurchaseStore = PaymentsCanPurchaseStore
    CreateStarGiftCollection = PaymentsCreateStarGiftCollection
    UpdateStarGiftCollection = PaymentsUpdateStarGiftCollection


class phone:
    SetCallRating = PhoneSetCallRating


class stats:
    GetMegagroupStats = StatsGetMegagroupStats


class stickers:
    CreateStickerSet = StickersCreateStickerSet


class stories:
    GetAlbums = StoriesGetAlbums
    SearchPosts = StoriesSearchPosts


ALL_FUNCTIONS: tuple[type[TLRequest], ...] = (
    AuthFinishPasskeyLogin,
    AccountResetNotifySettings,
    AccountGetPaidMessagesRevenue,
    ContactsExportContactToken,
    MessagesAddChatUser,
    MessagesGetBotCallbackAnswer,
    MessagesUnpinAllMessages,
    MessagesSendBotRequestedPeer,
    MessagesReorderPinnedSavedDialogs,
    MessagesReorderQuickReplies,
    MessagesGetEmojiGameInfo,
    ChannelsCreateChannel,
    ChannelsDeleteHistory,
    BotsInvokeWebViewCustomMethod,
    PaymentsCanPurchaseStore,
    PaymentsCreateStarGiftCollection,
    PaymentsUpdateStarGiftCollection,
    StickersCreateStickerSet,
    PhoneSetCallRating,
    StatsGetMegagroupStats,
    StoriesSearchPosts,
    StoriesGetAlbums,
)
CONSTRUCTOR_ID_MAP: dict[int, type[TLRequest]] = {entry.CONSTRUCTOR_ID: entry for entry in ALL_FUNCTIONS}
NAME_MAP: dict[str, type[TLRequest]] = {entry.QUALNAME: entry for entry in ALL_FUNCTIONS}
__all__ = (
    "AuthFinishPasskeyLogin",
    "AccountResetNotifySettings",
    "AccountGetPaidMessagesRevenue",
    "ContactsExportContactToken",
    "MessagesAddChatUser",
    "MessagesGetBotCallbackAnswer",
    "MessagesUnpinAllMessages",
    "MessagesSendBotRequestedPeer",
    "MessagesReorderPinnedSavedDialogs",
    "MessagesReorderQuickReplies",
    "MessagesGetEmojiGameInfo",
    "ChannelsCreateChannel",
    "ChannelsDeleteHistory",
    "BotsInvokeWebViewCustomMethod",
    "PaymentsCanPurchaseStore",
    "PaymentsCreateStarGiftCollection",
    "PaymentsUpdateStarGiftCollection",
    "StickersCreateStickerSet",
    "PhoneSetCallRating",
    "StatsGetMegagroupStats",
    "StoriesSearchPosts",
    "StoriesGetAlbums",
    "account",
    "auth",
    "bots",
    "channels",
    "contacts",
    "messages",
    "payments",
    "phone",
    "stats",
    "stickers",
    "stories",
    "CONSTRUCTOR_ID_MAP",
    "NAME_MAP",
)
