# Generated by tools/schema/generate.py; do not edit by hand.
# Source: tools/schema/schema.json (normalized from the pinned canonical TL schema)
from __future__ import annotations

from dataclasses import dataclass
from typing import Any, ClassVar, Self, cast

from miniproto.raw.base import TLField, TLFlagGroup, TLRequest
from miniproto.tl.codec import (
    TLCodecError,
    decode_bool,
    decode_bytes,
    decode_constructor_id,
    decode_double,
    decode_int,
    decode_int128,
    decode_int256,
    decode_long,
    decode_object,
    decode_string,
    decode_value,
    decode_vector,
    encode_bool,
    encode_bytes,
    encode_constructor_id,
    encode_double,
    encode_int,
    encode_int128,
    encode_int256,
    encode_long,
    encode_string,
    encode_value,
    encode_vector,
)


@dataclass(frozen=True, slots=True, kw_only=True)
class InitConnection(TLRequest):
    api_id: int
    device_model: str
    system_version: str
    app_version: str
    system_lang_code: str
    lang_pack: str
    lang_code: str
    proxy: Any | None = None
    params: Any | None = None
    query: Any
    CONSTRUCTOR_ID: ClassVar[int] = 0xC1CD5EA9
    QUALNAME: ClassVar[str] = "initConnection"
    RESULT_TYPE: ClassVar[str] = "X"
    TL_FIELDS: ClassVar[tuple[TLField, ...]] = (
        TLField(
            name="api_id",
            python_name="api_id",
            type="int",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="device_model",
            python_name="device_model",
            type="string",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="system_version",
            python_name="system_version",
            type="string",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="app_version",
            python_name="app_version",
            type="string",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="system_lang_code",
            python_name="system_lang_code",
            type="string",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="lang_pack",
            python_name="lang_pack",
            type="string",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="lang_code",
            python_name="lang_code",
            type="string",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="proxy",
            python_name="proxy",
            type="InputClientProxy",
            flag="flags",
            flag_index=0,
            is_optional=True,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="params",
            python_name="params",
            type="JSONValue",
            flag="flags",
            flag_index=1,
            is_optional=True,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="query",
            python_name="query",
            type="!X",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
    )
    TL_FLAG_GROUPS: ClassVar[tuple[TLFlagGroup, ...]] = (
        TLFlagGroup(name="flags", python_name="flags", before_field_index=0),
    )

    def serialize(self) -> bytes:
        return self._serialize(boxed=True)

    def _serialize(self, *, boxed: bool = True) -> bytes:
        output = bytearray()
        if boxed:
            output.extend(encode_constructor_id(self.CONSTRUCTOR_ID))
        flags = 0
        if self.proxy is not None:
            flags |= 1
        if self.params is not None:
            flags |= 2
        output.extend(encode_int(flags))
        output.extend(encode_int(self.api_id))
        output.extend(encode_string(self.device_model))
        output.extend(encode_string(self.system_version))
        output.extend(encode_string(self.app_version))
        output.extend(encode_string(self.system_lang_code))
        output.extend(encode_string(self.lang_pack))
        output.extend(encode_string(self.lang_code))
        if self.proxy is not None:
            output.extend(encode_value("InputClientProxy", self.proxy))
        if self.params is not None:
            output.extend(encode_value("JSONValue", self.params))
        output.extend(encode_value("!X", self.query))
        return bytes(output)

    @classmethod
    def deserialize(cls, data: bytes | memoryview) -> Self:
        obj, offset = cls._deserialize(data)
        if offset != len(data):
            raise TLCodecError("TL object payload has trailing bytes")
        return obj

    @classmethod
    def _deserialize(cls, data: bytes | memoryview, offset: int = 0, *, boxed: bool = True) -> tuple[Self, int]:
        raw_data = data
        cursor = offset
        if boxed:
            constructor_id, cursor = decode_constructor_id(raw_data, cursor)
            if constructor_id != cls.CONSTRUCTOR_ID:
                raise TLCodecError(f"expected constructor 0x{cls.CONSTRUCTOR_ID:08x}, got 0x{constructor_id:08x}")
        flags = 0
        flags, cursor = decode_int(raw_data, cursor)
        _value_api_id, cursor = decode_int(raw_data, cursor)
        _value_device_model, cursor = decode_string(raw_data, cursor)
        _value_system_version, cursor = decode_string(raw_data, cursor)
        _value_app_version, cursor = decode_string(raw_data, cursor)
        _value_system_lang_code, cursor = decode_string(raw_data, cursor)
        _value_lang_pack, cursor = decode_string(raw_data, cursor)
        _value_lang_code, cursor = decode_string(raw_data, cursor)
        if bool(flags & 1):
            _value_proxy, cursor = decode_value("InputClientProxy", raw_data, cursor)
        else:
            _value_proxy = None
        if bool(flags & 2):
            _value_params, cursor = decode_value("JSONValue", raw_data, cursor)
        else:
            _value_params = None
        _value_query, cursor = decode_value("!X", raw_data, cursor)
        return cls(
            api_id=_value_api_id,
            device_model=_value_device_model,
            system_version=_value_system_version,
            app_version=_value_app_version,
            system_lang_code=_value_system_lang_code,
            lang_pack=_value_lang_pack,
            lang_code=_value_lang_code,
            proxy=_value_proxy,
            params=_value_params,
            query=_value_query,
        ), cursor


@dataclass(frozen=True, slots=True, kw_only=True)
class AuthImportWebTokenAuthorization(TLRequest):
    api_id: int
    api_hash: str
    web_auth_token: str
    CONSTRUCTOR_ID: ClassVar[int] = 0x2DB873A9
    QUALNAME: ClassVar[str] = "auth.importWebTokenAuthorization"
    RESULT_TYPE: ClassVar[str] = "auth.Authorization"
    TL_FIELDS: ClassVar[tuple[TLField, ...]] = (
        TLField(
            name="api_id",
            python_name="api_id",
            type="int",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="api_hash",
            python_name="api_hash",
            type="string",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="web_auth_token",
            python_name="web_auth_token",
            type="string",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
    )
    TL_FLAG_GROUPS: ClassVar[tuple[TLFlagGroup, ...]] = ()

    def serialize(self) -> bytes:
        return self._serialize(boxed=True)

    def _serialize(self, *, boxed: bool = True) -> bytes:
        output = bytearray()
        if boxed:
            output.extend(encode_constructor_id(self.CONSTRUCTOR_ID))
        output.extend(encode_int(self.api_id))
        output.extend(encode_string(self.api_hash))
        output.extend(encode_string(self.web_auth_token))
        return bytes(output)

    @classmethod
    def deserialize(cls, data: bytes | memoryview) -> Self:
        obj, offset = cls._deserialize(data)
        if offset != len(data):
            raise TLCodecError("TL object payload has trailing bytes")
        return obj

    @classmethod
    def _deserialize(cls, data: bytes | memoryview, offset: int = 0, *, boxed: bool = True) -> tuple[Self, int]:
        raw_data = data
        cursor = offset
        if boxed:
            constructor_id, cursor = decode_constructor_id(raw_data, cursor)
            if constructor_id != cls.CONSTRUCTOR_ID:
                raise TLCodecError(f"expected constructor 0x{cls.CONSTRUCTOR_ID:08x}, got 0x{constructor_id:08x}")
        _value_api_id, cursor = decode_int(raw_data, cursor)
        _value_api_hash, cursor = decode_string(raw_data, cursor)
        _value_web_auth_token, cursor = decode_string(raw_data, cursor)
        return cls(api_id=_value_api_id, api_hash=_value_api_hash, web_auth_token=_value_web_auth_token), cursor


@dataclass(frozen=True, slots=True, kw_only=True)
class AccountInstallWallPaper(TLRequest):
    wallpaper: Any
    settings: Any
    CONSTRUCTOR_ID: ClassVar[int] = 0xFEED5769
    QUALNAME: ClassVar[str] = "account.installWallPaper"
    RESULT_TYPE: ClassVar[str] = "Bool"
    TL_FIELDS: ClassVar[tuple[TLField, ...]] = (
        TLField(
            name="wallpaper",
            python_name="wallpaper",
            type="InputWallPaper",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="settings",
            python_name="settings",
            type="WallPaperSettings",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
    )
    TL_FLAG_GROUPS: ClassVar[tuple[TLFlagGroup, ...]] = ()

    def serialize(self) -> bytes:
        return self._serialize(boxed=True)

    def _serialize(self, *, boxed: bool = True) -> bytes:
        output = bytearray()
        if boxed:
            output.extend(encode_constructor_id(self.CONSTRUCTOR_ID))
        output.extend(encode_value("InputWallPaper", self.wallpaper))
        output.extend(encode_value("WallPaperSettings", self.settings))
        return bytes(output)

    @classmethod
    def deserialize(cls, data: bytes | memoryview) -> Self:
        obj, offset = cls._deserialize(data)
        if offset != len(data):
            raise TLCodecError("TL object payload has trailing bytes")
        return obj

    @classmethod
    def _deserialize(cls, data: bytes | memoryview, offset: int = 0, *, boxed: bool = True) -> tuple[Self, int]:
        raw_data = data
        cursor = offset
        if boxed:
            constructor_id, cursor = decode_constructor_id(raw_data, cursor)
            if constructor_id != cls.CONSTRUCTOR_ID:
                raise TLCodecError(f"expected constructor 0x{cls.CONSTRUCTOR_ID:08x}, got 0x{constructor_id:08x}")
        _value_wallpaper, cursor = decode_value("InputWallPaper", raw_data, cursor)
        _value_settings, cursor = decode_value("WallPaperSettings", raw_data, cursor)
        return cls(wallpaper=_value_wallpaper, settings=_value_settings), cursor


@dataclass(frozen=True, slots=True, kw_only=True)
class AccountGetChatThemes(TLRequest):
    hash: int
    CONSTRUCTOR_ID: ClassVar[int] = 0xD638DE89
    QUALNAME: ClassVar[str] = "account.getChatThemes"
    RESULT_TYPE: ClassVar[str] = "account.Themes"
    TL_FIELDS: ClassVar[tuple[TLField, ...]] = (
        TLField(
            name="hash",
            python_name="hash",
            type="long",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
    )
    TL_FLAG_GROUPS: ClassVar[tuple[TLFlagGroup, ...]] = ()

    def serialize(self) -> bytes:
        return self._serialize(boxed=True)

    def _serialize(self, *, boxed: bool = True) -> bytes:
        output = bytearray()
        if boxed:
            output.extend(encode_constructor_id(self.CONSTRUCTOR_ID))
        output.extend(encode_long(self.hash))
        return bytes(output)

    @classmethod
    def deserialize(cls, data: bytes | memoryview) -> Self:
        obj, offset = cls._deserialize(data)
        if offset != len(data):
            raise TLCodecError("TL object payload has trailing bytes")
        return obj

    @classmethod
    def _deserialize(cls, data: bytes | memoryview, offset: int = 0, *, boxed: bool = True) -> tuple[Self, int]:
        raw_data = data
        cursor = offset
        if boxed:
            constructor_id, cursor = decode_constructor_id(raw_data, cursor)
            if constructor_id != cls.CONSTRUCTOR_ID:
                raise TLCodecError(f"expected constructor 0x{cls.CONSTRUCTOR_ID:08x}, got 0x{constructor_id:08x}")
        _value_hash, cursor = decode_long(raw_data, cursor)
        return cls(hash=_value_hash), cursor


@dataclass(frozen=True, slots=True, kw_only=True)
class AccountSaveMusic(TLRequest):
    unsave: bool = False
    id: Any
    after_id: Any | None = None
    CONSTRUCTOR_ID: ClassVar[int] = 0xB26732A9
    QUALNAME: ClassVar[str] = "account.saveMusic"
    RESULT_TYPE: ClassVar[str] = "Bool"
    TL_FIELDS: ClassVar[tuple[TLField, ...]] = (
        TLField(
            name="unsave",
            python_name="unsave",
            type="true",
            flag="flags",
            flag_index=0,
            is_optional=True,
            is_true_flag=True,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="id",
            python_name="id",
            type="InputDocument",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="after_id",
            python_name="after_id",
            type="InputDocument",
            flag="flags",
            flag_index=1,
            is_optional=True,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
    )
    TL_FLAG_GROUPS: ClassVar[tuple[TLFlagGroup, ...]] = (
        TLFlagGroup(name="flags", python_name="flags", before_field_index=0),
    )

    def serialize(self) -> bytes:
        return self._serialize(boxed=True)

    def _serialize(self, *, boxed: bool = True) -> bytes:
        output = bytearray()
        if boxed:
            output.extend(encode_constructor_id(self.CONSTRUCTOR_ID))
        flags = 0
        if self.unsave:
            flags |= 1
        if self.after_id is not None:
            flags |= 2
        output.extend(encode_int(flags))
        output.extend(encode_value("InputDocument", self.id))
        if self.after_id is not None:
            output.extend(encode_value("InputDocument", self.after_id))
        return bytes(output)

    @classmethod
    def deserialize(cls, data: bytes | memoryview) -> Self:
        obj, offset = cls._deserialize(data)
        if offset != len(data):
            raise TLCodecError("TL object payload has trailing bytes")
        return obj

    @classmethod
    def _deserialize(cls, data: bytes | memoryview, offset: int = 0, *, boxed: bool = True) -> tuple[Self, int]:
        raw_data = data
        cursor = offset
        if boxed:
            constructor_id, cursor = decode_constructor_id(raw_data, cursor)
            if constructor_id != cls.CONSTRUCTOR_ID:
                raise TLCodecError(f"expected constructor 0x{cls.CONSTRUCTOR_ID:08x}, got 0x{constructor_id:08x}")
        flags = 0
        flags, cursor = decode_int(raw_data, cursor)
        _value_unsave = bool(flags & 1)
        _value_id, cursor = decode_value("InputDocument", raw_data, cursor)
        if bool(flags & 2):
            _value_after_id, cursor = decode_value("InputDocument", raw_data, cursor)
        else:
            _value_after_id = None
        return cls(unsave=_value_unsave, id=_value_id, after_id=_value_after_id), cursor


@dataclass(frozen=True, slots=True, kw_only=True)
class AccountGetUniqueGiftChatThemes(TLRequest):
    offset: str
    limit: int
    hash: int
    CONSTRUCTOR_ID: ClassVar[int] = 0xE42CE9C9
    QUALNAME: ClassVar[str] = "account.getUniqueGiftChatThemes"
    RESULT_TYPE: ClassVar[str] = "account.ChatThemes"
    TL_FIELDS: ClassVar[tuple[TLField, ...]] = (
        TLField(
            name="offset",
            python_name="offset",
            type="string",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="limit",
            python_name="limit",
            type="int",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="hash",
            python_name="hash",
            type="long",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
    )
    TL_FLAG_GROUPS: ClassVar[tuple[TLFlagGroup, ...]] = ()

    def serialize(self) -> bytes:
        return self._serialize(boxed=True)

    def _serialize(self, *, boxed: bool = True) -> bytes:
        output = bytearray()
        if boxed:
            output.extend(encode_constructor_id(self.CONSTRUCTOR_ID))
        output.extend(encode_string(self.offset))
        output.extend(encode_int(self.limit))
        output.extend(encode_long(self.hash))
        return bytes(output)

    @classmethod
    def deserialize(cls, data: bytes | memoryview) -> Self:
        obj, offset = cls._deserialize(data)
        if offset != len(data):
            raise TLCodecError("TL object payload has trailing bytes")
        return obj

    @classmethod
    def _deserialize(cls, data: bytes | memoryview, offset: int = 0, *, boxed: bool = True) -> tuple[Self, int]:
        raw_data = data
        cursor = offset
        if boxed:
            constructor_id, cursor = decode_constructor_id(raw_data, cursor)
            if constructor_id != cls.CONSTRUCTOR_ID:
                raise TLCodecError(f"expected constructor 0x{cls.CONSTRUCTOR_ID:08x}, got 0x{constructor_id:08x}")
        _value_offset, cursor = decode_string(raw_data, cursor)
        _value_limit, cursor = decode_int(raw_data, cursor)
        _value_hash, cursor = decode_long(raw_data, cursor)
        return cls(offset=_value_offset, limit=_value_limit, hash=_value_hash), cursor


@dataclass(frozen=True, slots=True, kw_only=True)
class AccountToggleWebBrowserSettingsException(TLRequest):
    delete: bool = False
    open_external_browser: bool | None = None
    url: str
    CONSTRUCTOR_ID: ClassVar[int] = 0x60ED4229
    QUALNAME: ClassVar[str] = "account.toggleWebBrowserSettingsException"
    RESULT_TYPE: ClassVar[str] = "Updates"
    TL_FIELDS: ClassVar[tuple[TLField, ...]] = (
        TLField(
            name="delete",
            python_name="delete",
            type="true",
            flag="flags",
            flag_index=1,
            is_optional=True,
            is_true_flag=True,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="open_external_browser",
            python_name="open_external_browser",
            type="Bool",
            flag="flags",
            flag_index=0,
            is_optional=True,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="url",
            python_name="url",
            type="string",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
    )
    TL_FLAG_GROUPS: ClassVar[tuple[TLFlagGroup, ...]] = (
        TLFlagGroup(name="flags", python_name="flags", before_field_index=0),
    )

    def serialize(self) -> bytes:
        return self._serialize(boxed=True)

    def _serialize(self, *, boxed: bool = True) -> bytes:
        output = bytearray()
        if boxed:
            output.extend(encode_constructor_id(self.CONSTRUCTOR_ID))
        flags = 0
        if self.delete:
            flags |= 2
        if self.open_external_browser is not None:
            flags |= 1
        output.extend(encode_int(flags))
        if self.open_external_browser is not None:
            output.extend(encode_bool(self.open_external_browser))
        output.extend(encode_string(self.url))
        return bytes(output)

    @classmethod
    def deserialize(cls, data: bytes | memoryview) -> Self:
        obj, offset = cls._deserialize(data)
        if offset != len(data):
            raise TLCodecError("TL object payload has trailing bytes")
        return obj

    @classmethod
    def _deserialize(cls, data: bytes | memoryview, offset: int = 0, *, boxed: bool = True) -> tuple[Self, int]:
        raw_data = data
        cursor = offset
        if boxed:
            constructor_id, cursor = decode_constructor_id(raw_data, cursor)
            if constructor_id != cls.CONSTRUCTOR_ID:
                raise TLCodecError(f"expected constructor 0x{cls.CONSTRUCTOR_ID:08x}, got 0x{constructor_id:08x}")
        flags = 0
        flags, cursor = decode_int(raw_data, cursor)
        _value_delete = bool(flags & 2)
        if bool(flags & 1):
            _value_open_external_browser, cursor = decode_bool(raw_data, cursor)
        else:
            _value_open_external_browser = None
        _value_url, cursor = decode_string(raw_data, cursor)
        return cls(delete=_value_delete, open_external_browser=_value_open_external_browser, url=_value_url), cursor


@dataclass(frozen=True, slots=True, kw_only=True)
class UsersGetSavedMusicByID(TLRequest):
    id: Any
    documents: tuple[Any, ...]
    CONSTRUCTOR_ID: ClassVar[int] = 0x7573A4E9
    QUALNAME: ClassVar[str] = "users.getSavedMusicByID"
    RESULT_TYPE: ClassVar[str] = "users.SavedMusic"
    TL_FIELDS: ClassVar[tuple[TLField, ...]] = (
        TLField(
            name="id",
            python_name="id",
            type="InputUser",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="documents",
            python_name="documents",
            type="Vector<InputDocument>",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=True,
            vector_item_type="InputDocument",
        ),
    )
    TL_FLAG_GROUPS: ClassVar[tuple[TLFlagGroup, ...]] = ()

    def serialize(self) -> bytes:
        return self._serialize(boxed=True)

    def _serialize(self, *, boxed: bool = True) -> bytes:
        output = bytearray()
        if boxed:
            output.extend(encode_constructor_id(self.CONSTRUCTOR_ID))
        output.extend(encode_value("InputUser", self.id))
        output.extend(encode_vector(self.documents, "InputDocument"))
        return bytes(output)

    @classmethod
    def deserialize(cls, data: bytes | memoryview) -> Self:
        obj, offset = cls._deserialize(data)
        if offset != len(data):
            raise TLCodecError("TL object payload has trailing bytes")
        return obj

    @classmethod
    def _deserialize(cls, data: bytes | memoryview, offset: int = 0, *, boxed: bool = True) -> tuple[Self, int]:
        raw_data = data
        cursor = offset
        if boxed:
            constructor_id, cursor = decode_constructor_id(raw_data, cursor)
            if constructor_id != cls.CONSTRUCTOR_ID:
                raise TLCodecError(f"expected constructor 0x{cls.CONSTRUCTOR_ID:08x}, got 0x{constructor_id:08x}")
        _value_id, cursor = decode_value("InputUser", raw_data, cursor)
        _value_documents, cursor = decode_vector(raw_data, cursor, "InputDocument")
        return cls(id=_value_id, documents=_value_documents), cursor


@dataclass(frozen=True, slots=True, kw_only=True)
class MessagesGetFavedStickers(TLRequest):
    hash: int
    CONSTRUCTOR_ID: ClassVar[int] = 0x04F1AAA9
    QUALNAME: ClassVar[str] = "messages.getFavedStickers"
    RESULT_TYPE: ClassVar[str] = "messages.FavedStickers"
    TL_FIELDS: ClassVar[tuple[TLField, ...]] = (
        TLField(
            name="hash",
            python_name="hash",
            type="long",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
    )
    TL_FLAG_GROUPS: ClassVar[tuple[TLFlagGroup, ...]] = ()

    def serialize(self) -> bytes:
        return self._serialize(boxed=True)

    def _serialize(self, *, boxed: bool = True) -> bytes:
        output = bytearray()
        if boxed:
            output.extend(encode_constructor_id(self.CONSTRUCTOR_ID))
        output.extend(encode_long(self.hash))
        return bytes(output)

    @classmethod
    def deserialize(cls, data: bytes | memoryview) -> Self:
        obj, offset = cls._deserialize(data)
        if offset != len(data):
            raise TLCodecError("TL object payload has trailing bytes")
        return obj

    @classmethod
    def _deserialize(cls, data: bytes | memoryview, offset: int = 0, *, boxed: bool = True) -> tuple[Self, int]:
        raw_data = data
        cursor = offset
        if boxed:
            constructor_id, cursor = decode_constructor_id(raw_data, cursor)
            if constructor_id != cls.CONSTRUCTOR_ID:
                raise TLCodecError(f"expected constructor 0x{cls.CONSTRUCTOR_ID:08x}, got 0x{constructor_id:08x}")
        _value_hash, cursor = decode_long(raw_data, cursor)
        return cls(hash=_value_hash), cursor


@dataclass(frozen=True, slots=True, kw_only=True)
class MessagesGetDialogFilters(TLRequest):
    pass
    CONSTRUCTOR_ID: ClassVar[int] = 0xEFD48C89
    QUALNAME: ClassVar[str] = "messages.getDialogFilters"
    RESULT_TYPE: ClassVar[str] = "messages.DialogFilters"
    TL_FIELDS: ClassVar[tuple[TLField, ...]] = ()
    TL_FLAG_GROUPS: ClassVar[tuple[TLFlagGroup, ...]] = ()

    def serialize(self) -> bytes:
        return self._serialize(boxed=True)

    def _serialize(self, *, boxed: bool = True) -> bytes:
        output = bytearray()
        if boxed:
            output.extend(encode_constructor_id(self.CONSTRUCTOR_ID))
        return bytes(output)

    @classmethod
    def deserialize(cls, data: bytes | memoryview) -> Self:
        obj, offset = cls._deserialize(data)
        if offset != len(data):
            raise TLCodecError("TL object payload has trailing bytes")
        return obj

    @classmethod
    def _deserialize(cls, data: bytes | memoryview, offset: int = 0, *, boxed: bool = True) -> tuple[Self, int]:
        raw_data = data
        cursor = offset
        if boxed:
            constructor_id, cursor = decode_constructor_id(raw_data, cursor)
            if constructor_id != cls.CONSTRUCTOR_ID:
                raise TLCodecError(f"expected constructor 0x{cls.CONSTRUCTOR_ID:08x}, got 0x{constructor_id:08x}")
        return cls(), cursor


@dataclass(frozen=True, slots=True, kw_only=True)
class MessagesDeletePhoneCallHistory(TLRequest):
    revoke: bool = False
    CONSTRUCTOR_ID: ClassVar[int] = 0xF9CBE409
    QUALNAME: ClassVar[str] = "messages.deletePhoneCallHistory"
    RESULT_TYPE: ClassVar[str] = "messages.AffectedFoundMessages"
    TL_FIELDS: ClassVar[tuple[TLField, ...]] = (
        TLField(
            name="revoke",
            python_name="revoke",
            type="true",
            flag="flags",
            flag_index=0,
            is_optional=True,
            is_true_flag=True,
            is_vector=False,
            vector_item_type=None,
        ),
    )
    TL_FLAG_GROUPS: ClassVar[tuple[TLFlagGroup, ...]] = (
        TLFlagGroup(name="flags", python_name="flags", before_field_index=0),
    )

    def serialize(self) -> bytes:
        return self._serialize(boxed=True)

    def _serialize(self, *, boxed: bool = True) -> bytes:
        output = bytearray()
        if boxed:
            output.extend(encode_constructor_id(self.CONSTRUCTOR_ID))
        flags = 0
        if self.revoke:
            flags |= 1
        output.extend(encode_int(flags))
        return bytes(output)

    @classmethod
    def deserialize(cls, data: bytes | memoryview) -> Self:
        obj, offset = cls._deserialize(data)
        if offset != len(data):
            raise TLCodecError("TL object payload has trailing bytes")
        return obj

    @classmethod
    def _deserialize(cls, data: bytes | memoryview, offset: int = 0, *, boxed: bool = True) -> tuple[Self, int]:
        raw_data = data
        cursor = offset
        if boxed:
            constructor_id, cursor = decode_constructor_id(raw_data, cursor)
            if constructor_id != cls.CONSTRUCTOR_ID:
                raise TLCodecError(f"expected constructor 0x{cls.CONSTRUCTOR_ID:08x}, got 0x{constructor_id:08x}")
        flags = 0
        flags, cursor = decode_int(raw_data, cursor)
        _value_revoke = bool(flags & 1)
        return cls(revoke=_value_revoke), cursor


@dataclass(frozen=True, slots=True, kw_only=True)
class MessagesSetChatTheme(TLRequest):
    peer: Any
    theme: Any
    CONSTRUCTOR_ID: ClassVar[int] = 0x081202C9
    QUALNAME: ClassVar[str] = "messages.setChatTheme"
    RESULT_TYPE: ClassVar[str] = "Updates"
    TL_FIELDS: ClassVar[tuple[TLField, ...]] = (
        TLField(
            name="peer",
            python_name="peer",
            type="InputPeer",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="theme",
            python_name="theme",
            type="InputChatTheme",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
    )
    TL_FLAG_GROUPS: ClassVar[tuple[TLFlagGroup, ...]] = ()

    def serialize(self) -> bytes:
        return self._serialize(boxed=True)

    def _serialize(self, *, boxed: bool = True) -> bytes:
        output = bytearray()
        if boxed:
            output.extend(encode_constructor_id(self.CONSTRUCTOR_ID))
        output.extend(encode_value("InputPeer", self.peer))
        output.extend(encode_value("InputChatTheme", self.theme))
        return bytes(output)

    @classmethod
    def deserialize(cls, data: bytes | memoryview) -> Self:
        obj, offset = cls._deserialize(data)
        if offset != len(data):
            raise TLCodecError("TL object payload has trailing bytes")
        return obj

    @classmethod
    def _deserialize(cls, data: bytes | memoryview, offset: int = 0, *, boxed: bool = True) -> tuple[Self, int]:
        raw_data = data
        cursor = offset
        if boxed:
            constructor_id, cursor = decode_constructor_id(raw_data, cursor)
            if constructor_id != cls.CONSTRUCTOR_ID:
                raise TLCodecError(f"expected constructor 0x{cls.CONSTRUCTOR_ID:08x}, got 0x{constructor_id:08x}")
        _value_peer, cursor = decode_value("InputPeer", raw_data, cursor)
        _value_theme, cursor = decode_value("InputChatTheme", raw_data, cursor)
        return cls(peer=_value_peer, theme=_value_theme), cursor


@dataclass(frozen=True, slots=True, kw_only=True)
class MessagesToggleBotInAttachMenu(TLRequest):
    write_allowed: bool = False
    bot: Any
    enabled: bool
    CONSTRUCTOR_ID: ClassVar[int] = 0x69F59D69
    QUALNAME: ClassVar[str] = "messages.toggleBotInAttachMenu"
    RESULT_TYPE: ClassVar[str] = "Bool"
    TL_FIELDS: ClassVar[tuple[TLField, ...]] = (
        TLField(
            name="write_allowed",
            python_name="write_allowed",
            type="true",
            flag="flags",
            flag_index=0,
            is_optional=True,
            is_true_flag=True,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="bot",
            python_name="bot",
            type="InputUser",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="enabled",
            python_name="enabled",
            type="Bool",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
    )
    TL_FLAG_GROUPS: ClassVar[tuple[TLFlagGroup, ...]] = (
        TLFlagGroup(name="flags", python_name="flags", before_field_index=0),
    )

    def serialize(self) -> bytes:
        return self._serialize(boxed=True)

    def _serialize(self, *, boxed: bool = True) -> bytes:
        output = bytearray()
        if boxed:
            output.extend(encode_constructor_id(self.CONSTRUCTOR_ID))
        flags = 0
        if self.write_allowed:
            flags |= 1
        output.extend(encode_int(flags))
        output.extend(encode_value("InputUser", self.bot))
        output.extend(encode_bool(self.enabled))
        return bytes(output)

    @classmethod
    def deserialize(cls, data: bytes | memoryview) -> Self:
        obj, offset = cls._deserialize(data)
        if offset != len(data):
            raise TLCodecError("TL object payload has trailing bytes")
        return obj

    @classmethod
    def _deserialize(cls, data: bytes | memoryview, offset: int = 0, *, boxed: bool = True) -> tuple[Self, int]:
        raw_data = data
        cursor = offset
        if boxed:
            constructor_id, cursor = decode_constructor_id(raw_data, cursor)
            if constructor_id != cls.CONSTRUCTOR_ID:
                raise TLCodecError(f"expected constructor 0x{cls.CONSTRUCTOR_ID:08x}, got 0x{constructor_id:08x}")
        flags = 0
        flags, cursor = decode_int(raw_data, cursor)
        _value_write_allowed = bool(flags & 1)
        _value_bot, cursor = decode_value("InputUser", raw_data, cursor)
        _value_enabled, cursor = decode_bool(raw_data, cursor)
        return cls(write_allowed=_value_write_allowed, bot=_value_bot, enabled=_value_enabled), cursor


@dataclass(frozen=True, slots=True, kw_only=True)
class MessagesTranscribeAudio(TLRequest):
    peer: Any
    msg_id: int
    CONSTRUCTOR_ID: ClassVar[int] = 0x269E9A49
    QUALNAME: ClassVar[str] = "messages.transcribeAudio"
    RESULT_TYPE: ClassVar[str] = "messages.TranscribedAudio"
    TL_FIELDS: ClassVar[tuple[TLField, ...]] = (
        TLField(
            name="peer",
            python_name="peer",
            type="InputPeer",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="msg_id",
            python_name="msg_id",
            type="int",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
    )
    TL_FLAG_GROUPS: ClassVar[tuple[TLFlagGroup, ...]] = ()

    def serialize(self) -> bytes:
        return self._serialize(boxed=True)

    def _serialize(self, *, boxed: bool = True) -> bytes:
        output = bytearray()
        if boxed:
            output.extend(encode_constructor_id(self.CONSTRUCTOR_ID))
        output.extend(encode_value("InputPeer", self.peer))
        output.extend(encode_int(self.msg_id))
        return bytes(output)

    @classmethod
    def deserialize(cls, data: bytes | memoryview) -> Self:
        obj, offset = cls._deserialize(data)
        if offset != len(data):
            raise TLCodecError("TL object payload has trailing bytes")
        return obj

    @classmethod
    def _deserialize(cls, data: bytes | memoryview, offset: int = 0, *, boxed: bool = True) -> tuple[Self, int]:
        raw_data = data
        cursor = offset
        if boxed:
            constructor_id, cursor = decode_constructor_id(raw_data, cursor)
            if constructor_id != cls.CONSTRUCTOR_ID:
                raise TLCodecError(f"expected constructor 0x{cls.CONSTRUCTOR_ID:08x}, got 0x{constructor_id:08x}")
        _value_peer, cursor = decode_value("InputPeer", raw_data, cursor)
        _value_msg_id, cursor = decode_int(raw_data, cursor)
        return cls(peer=_value_peer, msg_id=_value_msg_id), cursor


@dataclass(frozen=True, slots=True, kw_only=True)
class MessagesGetSavedHistory(TLRequest):
    parent_peer: Any | None = None
    peer: Any
    offset_id: int
    offset_date: int
    add_offset: int
    limit: int
    max_id: int
    min_id: int
    hash: int
    CONSTRUCTOR_ID: ClassVar[int] = 0x998AB009
    QUALNAME: ClassVar[str] = "messages.getSavedHistory"
    RESULT_TYPE: ClassVar[str] = "messages.Messages"
    TL_FIELDS: ClassVar[tuple[TLField, ...]] = (
        TLField(
            name="parent_peer",
            python_name="parent_peer",
            type="InputPeer",
            flag="flags",
            flag_index=0,
            is_optional=True,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="peer",
            python_name="peer",
            type="InputPeer",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="offset_id",
            python_name="offset_id",
            type="int",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="offset_date",
            python_name="offset_date",
            type="int",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="add_offset",
            python_name="add_offset",
            type="int",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="limit",
            python_name="limit",
            type="int",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="max_id",
            python_name="max_id",
            type="int",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="min_id",
            python_name="min_id",
            type="int",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="hash",
            python_name="hash",
            type="long",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
    )
    TL_FLAG_GROUPS: ClassVar[tuple[TLFlagGroup, ...]] = (
        TLFlagGroup(name="flags", python_name="flags", before_field_index=0),
    )

    def serialize(self) -> bytes:
        return self._serialize(boxed=True)

    def _serialize(self, *, boxed: bool = True) -> bytes:
        output = bytearray()
        if boxed:
            output.extend(encode_constructor_id(self.CONSTRUCTOR_ID))
        flags = 0
        if self.parent_peer is not None:
            flags |= 1
        output.extend(encode_int(flags))
        if self.parent_peer is not None:
            output.extend(encode_value("InputPeer", self.parent_peer))
        output.extend(encode_value("InputPeer", self.peer))
        output.extend(encode_int(self.offset_id))
        output.extend(encode_int(self.offset_date))
        output.extend(encode_int(self.add_offset))
        output.extend(encode_int(self.limit))
        output.extend(encode_int(self.max_id))
        output.extend(encode_int(self.min_id))
        output.extend(encode_long(self.hash))
        return bytes(output)

    @classmethod
    def deserialize(cls, data: bytes | memoryview) -> Self:
        obj, offset = cls._deserialize(data)
        if offset != len(data):
            raise TLCodecError("TL object payload has trailing bytes")
        return obj

    @classmethod
    def _deserialize(cls, data: bytes | memoryview, offset: int = 0, *, boxed: bool = True) -> tuple[Self, int]:
        raw_data = data
        cursor = offset
        if boxed:
            constructor_id, cursor = decode_constructor_id(raw_data, cursor)
            if constructor_id != cls.CONSTRUCTOR_ID:
                raise TLCodecError(f"expected constructor 0x{cls.CONSTRUCTOR_ID:08x}, got 0x{constructor_id:08x}")
        flags = 0
        flags, cursor = decode_int(raw_data, cursor)
        if bool(flags & 1):
            _value_parent_peer, cursor = decode_value("InputPeer", raw_data, cursor)
        else:
            _value_parent_peer = None
        _value_peer, cursor = decode_value("InputPeer", raw_data, cursor)
        _value_offset_id, cursor = decode_int(raw_data, cursor)
        _value_offset_date, cursor = decode_int(raw_data, cursor)
        _value_add_offset, cursor = decode_int(raw_data, cursor)
        _value_limit, cursor = decode_int(raw_data, cursor)
        _value_max_id, cursor = decode_int(raw_data, cursor)
        _value_min_id, cursor = decode_int(raw_data, cursor)
        _value_hash, cursor = decode_long(raw_data, cursor)
        return cls(
            parent_peer=_value_parent_peer,
            peer=_value_peer,
            offset_id=_value_offset_id,
            offset_date=_value_offset_date,
            add_offset=_value_add_offset,
            limit=_value_limit,
            max_id=_value_max_id,
            min_id=_value_min_id,
            hash=_value_hash,
        ), cursor


@dataclass(frozen=True, slots=True, kw_only=True)
class MessagesToggleDialogFilterTags(TLRequest):
    enabled: bool
    CONSTRUCTOR_ID: ClassVar[int] = 0xFD2DDA49
    QUALNAME: ClassVar[str] = "messages.toggleDialogFilterTags"
    RESULT_TYPE: ClassVar[str] = "Bool"
    TL_FIELDS: ClassVar[tuple[TLField, ...]] = (
        TLField(
            name="enabled",
            python_name="enabled",
            type="Bool",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
    )
    TL_FLAG_GROUPS: ClassVar[tuple[TLFlagGroup, ...]] = ()

    def serialize(self) -> bytes:
        return self._serialize(boxed=True)

    def _serialize(self, *, boxed: bool = True) -> bytes:
        output = bytearray()
        if boxed:
            output.extend(encode_constructor_id(self.CONSTRUCTOR_ID))
        output.extend(encode_bool(self.enabled))
        return bytes(output)

    @classmethod
    def deserialize(cls, data: bytes | memoryview) -> Self:
        obj, offset = cls._deserialize(data)
        if offset != len(data):
            raise TLCodecError("TL object payload has trailing bytes")
        return obj

    @classmethod
    def _deserialize(cls, data: bytes | memoryview, offset: int = 0, *, boxed: bool = True) -> tuple[Self, int]:
        raw_data = data
        cursor = offset
        if boxed:
            constructor_id, cursor = decode_constructor_id(raw_data, cursor)
            if constructor_id != cls.CONSTRUCTOR_ID:
                raise TLCodecError(f"expected constructor 0x{cls.CONSTRUCTOR_ID:08x}, got 0x{constructor_id:08x}")
        _value_enabled, cursor = decode_bool(raw_data, cursor)
        return cls(enabled=_value_enabled), cursor


@dataclass(frozen=True, slots=True, kw_only=True)
class MessagesComposeMessageWithAI(TLRequest):
    proofread: bool = False
    emojify: bool = False
    text: Any
    translate_to_lang: str | None = None
    tone: Any | None = None
    CONSTRUCTOR_ID: ClassVar[int] = 0xDAECC589
    QUALNAME: ClassVar[str] = "messages.composeMessageWithAI"
    RESULT_TYPE: ClassVar[str] = "messages.ComposedMessageWithAI"
    TL_FIELDS: ClassVar[tuple[TLField, ...]] = (
        TLField(
            name="proofread",
            python_name="proofread",
            type="true",
            flag="flags",
            flag_index=0,
            is_optional=True,
            is_true_flag=True,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="emojify",
            python_name="emojify",
            type="true",
            flag="flags",
            flag_index=3,
            is_optional=True,
            is_true_flag=True,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="text",
            python_name="text",
            type="TextWithEntities",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="translate_to_lang",
            python_name="translate_to_lang",
            type="string",
            flag="flags",
            flag_index=1,
            is_optional=True,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="tone",
            python_name="tone",
            type="InputAiComposeTone",
            flag="flags",
            flag_index=2,
            is_optional=True,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
    )
    TL_FLAG_GROUPS: ClassVar[tuple[TLFlagGroup, ...]] = (
        TLFlagGroup(name="flags", python_name="flags", before_field_index=0),
    )

    def serialize(self) -> bytes:
        return self._serialize(boxed=True)

    def _serialize(self, *, boxed: bool = True) -> bytes:
        output = bytearray()
        if boxed:
            output.extend(encode_constructor_id(self.CONSTRUCTOR_ID))
        flags = 0
        if self.proofread:
            flags |= 1
        if self.emojify:
            flags |= 8
        if self.translate_to_lang is not None:
            flags |= 2
        if self.tone is not None:
            flags |= 4
        output.extend(encode_int(flags))
        output.extend(encode_value("TextWithEntities", self.text))
        if self.translate_to_lang is not None:
            output.extend(encode_string(self.translate_to_lang))
        if self.tone is not None:
            output.extend(encode_value("InputAiComposeTone", self.tone))
        return bytes(output)

    @classmethod
    def deserialize(cls, data: bytes | memoryview) -> Self:
        obj, offset = cls._deserialize(data)
        if offset != len(data):
            raise TLCodecError("TL object payload has trailing bytes")
        return obj

    @classmethod
    def _deserialize(cls, data: bytes | memoryview, offset: int = 0, *, boxed: bool = True) -> tuple[Self, int]:
        raw_data = data
        cursor = offset
        if boxed:
            constructor_id, cursor = decode_constructor_id(raw_data, cursor)
            if constructor_id != cls.CONSTRUCTOR_ID:
                raise TLCodecError(f"expected constructor 0x{cls.CONSTRUCTOR_ID:08x}, got 0x{constructor_id:08x}")
        flags = 0
        flags, cursor = decode_int(raw_data, cursor)
        _value_proofread = bool(flags & 1)
        _value_emojify = bool(flags & 8)
        _value_text, cursor = decode_value("TextWithEntities", raw_data, cursor)
        if bool(flags & 2):
            _value_translate_to_lang, cursor = decode_string(raw_data, cursor)
        else:
            _value_translate_to_lang = None
        if bool(flags & 4):
            _value_tone, cursor = decode_value("InputAiComposeTone", raw_data, cursor)
        else:
            _value_tone = None
        return cls(
            proofread=_value_proofread,
            emojify=_value_emojify,
            text=_value_text,
            translate_to_lang=_value_translate_to_lang,
            tone=_value_tone,
        ), cursor


@dataclass(frozen=True, slots=True, kw_only=True)
class ChannelsGetFullChannel(TLRequest):
    channel: Any
    CONSTRUCTOR_ID: ClassVar[int] = 0x08736A09
    QUALNAME: ClassVar[str] = "channels.getFullChannel"
    RESULT_TYPE: ClassVar[str] = "messages.ChatFull"
    TL_FIELDS: ClassVar[tuple[TLField, ...]] = (
        TLField(
            name="channel",
            python_name="channel",
            type="InputChannel",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
    )
    TL_FLAG_GROUPS: ClassVar[tuple[TLFlagGroup, ...]] = ()

    def serialize(self) -> bytes:
        return self._serialize(boxed=True)

    def _serialize(self, *, boxed: bool = True) -> bytes:
        output = bytearray()
        if boxed:
            output.extend(encode_constructor_id(self.CONSTRUCTOR_ID))
        output.extend(encode_value("InputChannel", self.channel))
        return bytes(output)

    @classmethod
    def deserialize(cls, data: bytes | memoryview) -> Self:
        obj, offset = cls._deserialize(data)
        if offset != len(data):
            raise TLCodecError("TL object payload has trailing bytes")
        return obj

    @classmethod
    def _deserialize(cls, data: bytes | memoryview, offset: int = 0, *, boxed: bool = True) -> tuple[Self, int]:
        raw_data = data
        cursor = offset
        if boxed:
            constructor_id, cursor = decode_constructor_id(raw_data, cursor)
            if constructor_id != cls.CONSTRUCTOR_ID:
                raise TLCodecError(f"expected constructor 0x{cls.CONSTRUCTOR_ID:08x}, got 0x{constructor_id:08x}")
        _value_channel, cursor = decode_value("InputChannel", raw_data, cursor)
        return cls(channel=_value_channel), cursor


@dataclass(frozen=True, slots=True, kw_only=True)
class ChannelsEditPhoto(TLRequest):
    channel: Any
    photo: Any
    CONSTRUCTOR_ID: ClassVar[int] = 0xF12E57C9
    QUALNAME: ClassVar[str] = "channels.editPhoto"
    RESULT_TYPE: ClassVar[str] = "Updates"
    TL_FIELDS: ClassVar[tuple[TLField, ...]] = (
        TLField(
            name="channel",
            python_name="channel",
            type="InputChannel",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="photo",
            python_name="photo",
            type="InputChatPhoto",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
    )
    TL_FLAG_GROUPS: ClassVar[tuple[TLFlagGroup, ...]] = ()

    def serialize(self) -> bytes:
        return self._serialize(boxed=True)

    def _serialize(self, *, boxed: bool = True) -> bytes:
        output = bytearray()
        if boxed:
            output.extend(encode_constructor_id(self.CONSTRUCTOR_ID))
        output.extend(encode_value("InputChannel", self.channel))
        output.extend(encode_value("InputChatPhoto", self.photo))
        return bytes(output)

    @classmethod
    def deserialize(cls, data: bytes | memoryview) -> Self:
        obj, offset = cls._deserialize(data)
        if offset != len(data):
            raise TLCodecError("TL object payload has trailing bytes")
        return obj

    @classmethod
    def _deserialize(cls, data: bytes | memoryview, offset: int = 0, *, boxed: bool = True) -> tuple[Self, int]:
        raw_data = data
        cursor = offset
        if boxed:
            constructor_id, cursor = decode_constructor_id(raw_data, cursor)
            if constructor_id != cls.CONSTRUCTOR_ID:
                raise TLCodecError(f"expected constructor 0x{cls.CONSTRUCTOR_ID:08x}, got 0x{constructor_id:08x}")
        _value_channel, cursor = decode_value("InputChannel", raw_data, cursor)
        _value_photo, cursor = decode_value("InputChatPhoto", raw_data, cursor)
        return cls(channel=_value_channel, photo=_value_photo), cursor


@dataclass(frozen=True, slots=True, kw_only=True)
class ChannelsConvertToGigagroup(TLRequest):
    channel: Any
    CONSTRUCTOR_ID: ClassVar[int] = 0x0B290C69
    QUALNAME: ClassVar[str] = "channels.convertToGigagroup"
    RESULT_TYPE: ClassVar[str] = "Updates"
    TL_FIELDS: ClassVar[tuple[TLField, ...]] = (
        TLField(
            name="channel",
            python_name="channel",
            type="InputChannel",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
    )
    TL_FLAG_GROUPS: ClassVar[tuple[TLFlagGroup, ...]] = ()

    def serialize(self) -> bytes:
        return self._serialize(boxed=True)

    def _serialize(self, *, boxed: bool = True) -> bytes:
        output = bytearray()
        if boxed:
            output.extend(encode_constructor_id(self.CONSTRUCTOR_ID))
        output.extend(encode_value("InputChannel", self.channel))
        return bytes(output)

    @classmethod
    def deserialize(cls, data: bytes | memoryview) -> Self:
        obj, offset = cls._deserialize(data)
        if offset != len(data):
            raise TLCodecError("TL object payload has trailing bytes")
        return obj

    @classmethod
    def _deserialize(cls, data: bytes | memoryview, offset: int = 0, *, boxed: bool = True) -> tuple[Self, int]:
        raw_data = data
        cursor = offset
        if boxed:
            constructor_id, cursor = decode_constructor_id(raw_data, cursor)
            if constructor_id != cls.CONSTRUCTOR_ID:
                raise TLCodecError(f"expected constructor 0x{cls.CONSTRUCTOR_ID:08x}, got 0x{constructor_id:08x}")
        _value_channel, cursor = decode_value("InputChannel", raw_data, cursor)
        return cls(channel=_value_channel), cursor


@dataclass(frozen=True, slots=True, kw_only=True)
class BotsCheckDownloadFileParams(TLRequest):
    bot: Any
    file_name: str
    url: str
    CONSTRUCTOR_ID: ClassVar[int] = 0x50077589
    QUALNAME: ClassVar[str] = "bots.checkDownloadFileParams"
    RESULT_TYPE: ClassVar[str] = "Bool"
    TL_FIELDS: ClassVar[tuple[TLField, ...]] = (
        TLField(
            name="bot",
            python_name="bot",
            type="InputUser",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="file_name",
            python_name="file_name",
            type="string",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="url",
            python_name="url",
            type="string",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
    )
    TL_FLAG_GROUPS: ClassVar[tuple[TLFlagGroup, ...]] = ()

    def serialize(self) -> bytes:
        return self._serialize(boxed=True)

    def _serialize(self, *, boxed: bool = True) -> bytes:
        output = bytearray()
        if boxed:
            output.extend(encode_constructor_id(self.CONSTRUCTOR_ID))
        output.extend(encode_value("InputUser", self.bot))
        output.extend(encode_string(self.file_name))
        output.extend(encode_string(self.url))
        return bytes(output)

    @classmethod
    def deserialize(cls, data: bytes | memoryview) -> Self:
        obj, offset = cls._deserialize(data)
        if offset != len(data):
            raise TLCodecError("TL object payload has trailing bytes")
        return obj

    @classmethod
    def _deserialize(cls, data: bytes | memoryview, offset: int = 0, *, boxed: bool = True) -> tuple[Self, int]:
        raw_data = data
        cursor = offset
        if boxed:
            constructor_id, cursor = decode_constructor_id(raw_data, cursor)
            if constructor_id != cls.CONSTRUCTOR_ID:
                raise TLCodecError(f"expected constructor 0x{cls.CONSTRUCTOR_ID:08x}, got 0x{constructor_id:08x}")
        _value_bot, cursor = decode_value("InputUser", raw_data, cursor)
        _value_file_name, cursor = decode_string(raw_data, cursor)
        _value_url, cursor = decode_string(raw_data, cursor)
        return cls(bot=_value_bot, file_name=_value_file_name, url=_value_url), cursor


@dataclass(frozen=True, slots=True, kw_only=True)
class PaymentsGetSavedStarGifts(TLRequest):
    exclude_unsaved: bool = False
    exclude_saved: bool = False
    exclude_unlimited: bool = False
    exclude_unique: bool = False
    sort_by_value: bool = False
    exclude_upgradable: bool = False
    exclude_unupgradable: bool = False
    peer_color_available: bool = False
    exclude_hosted: bool = False
    peer: Any
    collection_id: int | None = None
    offset: str
    limit: int
    CONSTRUCTOR_ID: ClassVar[int] = 0xA319E569
    QUALNAME: ClassVar[str] = "payments.getSavedStarGifts"
    RESULT_TYPE: ClassVar[str] = "payments.SavedStarGifts"
    TL_FIELDS: ClassVar[tuple[TLField, ...]] = (
        TLField(
            name="exclude_unsaved",
            python_name="exclude_unsaved",
            type="true",
            flag="flags",
            flag_index=0,
            is_optional=True,
            is_true_flag=True,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="exclude_saved",
            python_name="exclude_saved",
            type="true",
            flag="flags",
            flag_index=1,
            is_optional=True,
            is_true_flag=True,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="exclude_unlimited",
            python_name="exclude_unlimited",
            type="true",
            flag="flags",
            flag_index=2,
            is_optional=True,
            is_true_flag=True,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="exclude_unique",
            python_name="exclude_unique",
            type="true",
            flag="flags",
            flag_index=4,
            is_optional=True,
            is_true_flag=True,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="sort_by_value",
            python_name="sort_by_value",
            type="true",
            flag="flags",
            flag_index=5,
            is_optional=True,
            is_true_flag=True,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="exclude_upgradable",
            python_name="exclude_upgradable",
            type="true",
            flag="flags",
            flag_index=7,
            is_optional=True,
            is_true_flag=True,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="exclude_unupgradable",
            python_name="exclude_unupgradable",
            type="true",
            flag="flags",
            flag_index=8,
            is_optional=True,
            is_true_flag=True,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="peer_color_available",
            python_name="peer_color_available",
            type="true",
            flag="flags",
            flag_index=9,
            is_optional=True,
            is_true_flag=True,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="exclude_hosted",
            python_name="exclude_hosted",
            type="true",
            flag="flags",
            flag_index=10,
            is_optional=True,
            is_true_flag=True,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="peer",
            python_name="peer",
            type="InputPeer",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="collection_id",
            python_name="collection_id",
            type="int",
            flag="flags",
            flag_index=6,
            is_optional=True,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="offset",
            python_name="offset",
            type="string",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="limit",
            python_name="limit",
            type="int",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
    )
    TL_FLAG_GROUPS: ClassVar[tuple[TLFlagGroup, ...]] = (
        TLFlagGroup(name="flags", python_name="flags", before_field_index=0),
    )

    def serialize(self) -> bytes:
        return self._serialize(boxed=True)

    def _serialize(self, *, boxed: bool = True) -> bytes:
        output = bytearray()
        if boxed:
            output.extend(encode_constructor_id(self.CONSTRUCTOR_ID))
        flags = 0
        if self.exclude_unsaved:
            flags |= 1
        if self.exclude_saved:
            flags |= 2
        if self.exclude_unlimited:
            flags |= 4
        if self.exclude_unique:
            flags |= 16
        if self.sort_by_value:
            flags |= 32
        if self.exclude_upgradable:
            flags |= 128
        if self.exclude_unupgradable:
            flags |= 256
        if self.peer_color_available:
            flags |= 512
        if self.exclude_hosted:
            flags |= 1024
        if self.collection_id is not None:
            flags |= 64
        output.extend(encode_int(flags))
        output.extend(encode_value("InputPeer", self.peer))
        if self.collection_id is not None:
            output.extend(encode_int(self.collection_id))
        output.extend(encode_string(self.offset))
        output.extend(encode_int(self.limit))
        return bytes(output)

    @classmethod
    def deserialize(cls, data: bytes | memoryview) -> Self:
        obj, offset = cls._deserialize(data)
        if offset != len(data):
            raise TLCodecError("TL object payload has trailing bytes")
        return obj

    @classmethod
    def _deserialize(cls, data: bytes | memoryview, offset: int = 0, *, boxed: bool = True) -> tuple[Self, int]:
        raw_data = data
        cursor = offset
        if boxed:
            constructor_id, cursor = decode_constructor_id(raw_data, cursor)
            if constructor_id != cls.CONSTRUCTOR_ID:
                raise TLCodecError(f"expected constructor 0x{cls.CONSTRUCTOR_ID:08x}, got 0x{constructor_id:08x}")
        flags = 0
        flags, cursor = decode_int(raw_data, cursor)
        _value_exclude_unsaved = bool(flags & 1)
        _value_exclude_saved = bool(flags & 2)
        _value_exclude_unlimited = bool(flags & 4)
        _value_exclude_unique = bool(flags & 16)
        _value_sort_by_value = bool(flags & 32)
        _value_exclude_upgradable = bool(flags & 128)
        _value_exclude_unupgradable = bool(flags & 256)
        _value_peer_color_available = bool(flags & 512)
        _value_exclude_hosted = bool(flags & 1024)
        _value_peer, cursor = decode_value("InputPeer", raw_data, cursor)
        if bool(flags & 64):
            _value_collection_id, cursor = decode_int(raw_data, cursor)
        else:
            _value_collection_id = None
        _value_offset, cursor = decode_string(raw_data, cursor)
        _value_limit, cursor = decode_int(raw_data, cursor)
        return cls(
            exclude_unsaved=_value_exclude_unsaved,
            exclude_saved=_value_exclude_saved,
            exclude_unlimited=_value_exclude_unlimited,
            exclude_unique=_value_exclude_unique,
            sort_by_value=_value_sort_by_value,
            exclude_upgradable=_value_exclude_upgradable,
            exclude_unupgradable=_value_exclude_unupgradable,
            peer_color_available=_value_peer_color_available,
            exclude_hosted=_value_exclude_hosted,
            peer=_value_peer,
            collection_id=_value_collection_id,
            offset=_value_offset,
            limit=_value_limit,
        ), cursor


@dataclass(frozen=True, slots=True, kw_only=True)
class PaymentsCheckCanSendGift(TLRequest):
    gift_id: int
    CONSTRUCTOR_ID: ClassVar[int] = 0xC0C4EDC9
    QUALNAME: ClassVar[str] = "payments.checkCanSendGift"
    RESULT_TYPE: ClassVar[str] = "payments.CheckCanSendGiftResult"
    TL_FIELDS: ClassVar[tuple[TLField, ...]] = (
        TLField(
            name="gift_id",
            python_name="gift_id",
            type="long",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
    )
    TL_FLAG_GROUPS: ClassVar[tuple[TLFlagGroup, ...]] = ()

    def serialize(self) -> bytes:
        return self._serialize(boxed=True)

    def _serialize(self, *, boxed: bool = True) -> bytes:
        output = bytearray()
        if boxed:
            output.extend(encode_constructor_id(self.CONSTRUCTOR_ID))
        output.extend(encode_long(self.gift_id))
        return bytes(output)

    @classmethod
    def deserialize(cls, data: bytes | memoryview) -> Self:
        obj, offset = cls._deserialize(data)
        if offset != len(data):
            raise TLCodecError("TL object payload has trailing bytes")
        return obj

    @classmethod
    def _deserialize(cls, data: bytes | memoryview, offset: int = 0, *, boxed: bool = True) -> tuple[Self, int]:
        raw_data = data
        cursor = offset
        if boxed:
            constructor_id, cursor = decode_constructor_id(raw_data, cursor)
            if constructor_id != cls.CONSTRUCTOR_ID:
                raise TLCodecError(f"expected constructor 0x{cls.CONSTRUCTOR_ID:08x}, got 0x{constructor_id:08x}")
        _value_gift_id, cursor = decode_long(raw_data, cursor)
        return cls(gift_id=_value_gift_id), cursor


@dataclass(frozen=True, slots=True, kw_only=True)
class PhoneGetCallConfig(TLRequest):
    pass
    CONSTRUCTOR_ID: ClassVar[int] = 0x55451FA9
    QUALNAME: ClassVar[str] = "phone.getCallConfig"
    RESULT_TYPE: ClassVar[str] = "DataJSON"
    TL_FIELDS: ClassVar[tuple[TLField, ...]] = ()
    TL_FLAG_GROUPS: ClassVar[tuple[TLFlagGroup, ...]] = ()

    def serialize(self) -> bytes:
        return self._serialize(boxed=True)

    def _serialize(self, *, boxed: bool = True) -> bytes:
        output = bytearray()
        if boxed:
            output.extend(encode_constructor_id(self.CONSTRUCTOR_ID))
        return bytes(output)

    @classmethod
    def deserialize(cls, data: bytes | memoryview) -> Self:
        obj, offset = cls._deserialize(data)
        if offset != len(data):
            raise TLCodecError("TL object payload has trailing bytes")
        return obj

    @classmethod
    def _deserialize(cls, data: bytes | memoryview, offset: int = 0, *, boxed: bool = True) -> tuple[Self, int]:
        raw_data = data
        cursor = offset
        if boxed:
            constructor_id, cursor = decode_constructor_id(raw_data, cursor)
            if constructor_id != cls.CONSTRUCTOR_ID:
                raise TLCodecError(f"expected constructor 0x{cls.CONSTRUCTOR_ID:08x}, got 0x{constructor_id:08x}")
        return cls(), cursor


class account:
    GetChatThemes = AccountGetChatThemes
    GetUniqueGiftChatThemes = AccountGetUniqueGiftChatThemes
    InstallWallPaper = AccountInstallWallPaper
    SaveMusic = AccountSaveMusic
    ToggleWebBrowserSettingsException = AccountToggleWebBrowserSettingsException


class auth:
    ImportWebTokenAuthorization = AuthImportWebTokenAuthorization


class bots:
    CheckDownloadFileParams = BotsCheckDownloadFileParams


class channels:
    ConvertToGigagroup = ChannelsConvertToGigagroup
    EditPhoto = ChannelsEditPhoto
    GetFullChannel = ChannelsGetFullChannel


class messages:
    ComposeMessageWithAI = MessagesComposeMessageWithAI
    DeletePhoneCallHistory = MessagesDeletePhoneCallHistory
    GetDialogFilters = MessagesGetDialogFilters
    GetFavedStickers = MessagesGetFavedStickers
    GetSavedHistory = MessagesGetSavedHistory
    SetChatTheme = MessagesSetChatTheme
    ToggleBotInAttachMenu = MessagesToggleBotInAttachMenu
    ToggleDialogFilterTags = MessagesToggleDialogFilterTags
    TranscribeAudio = MessagesTranscribeAudio


class payments:
    CheckCanSendGift = PaymentsCheckCanSendGift
    GetSavedStarGifts = PaymentsGetSavedStarGifts


class phone:
    GetCallConfig = PhoneGetCallConfig


class users:
    GetSavedMusicByID = UsersGetSavedMusicByID


ALL_FUNCTIONS: tuple[type[TLRequest], ...] = (
    InitConnection,
    AuthImportWebTokenAuthorization,
    AccountInstallWallPaper,
    AccountGetChatThemes,
    AccountSaveMusic,
    AccountGetUniqueGiftChatThemes,
    AccountToggleWebBrowserSettingsException,
    UsersGetSavedMusicByID,
    MessagesGetFavedStickers,
    MessagesGetDialogFilters,
    MessagesDeletePhoneCallHistory,
    MessagesSetChatTheme,
    MessagesToggleBotInAttachMenu,
    MessagesTranscribeAudio,
    MessagesGetSavedHistory,
    MessagesToggleDialogFilterTags,
    MessagesComposeMessageWithAI,
    ChannelsGetFullChannel,
    ChannelsEditPhoto,
    ChannelsConvertToGigagroup,
    BotsCheckDownloadFileParams,
    PaymentsGetSavedStarGifts,
    PaymentsCheckCanSendGift,
    PhoneGetCallConfig,
)
CONSTRUCTOR_ID_MAP: dict[int, type[TLRequest]] = {entry.CONSTRUCTOR_ID: entry for entry in ALL_FUNCTIONS}
NAME_MAP: dict[str, type[TLRequest]] = {entry.QUALNAME: entry for entry in ALL_FUNCTIONS}
__all__ = (
    "InitConnection",
    "AuthImportWebTokenAuthorization",
    "AccountInstallWallPaper",
    "AccountGetChatThemes",
    "AccountSaveMusic",
    "AccountGetUniqueGiftChatThemes",
    "AccountToggleWebBrowserSettingsException",
    "UsersGetSavedMusicByID",
    "MessagesGetFavedStickers",
    "MessagesGetDialogFilters",
    "MessagesDeletePhoneCallHistory",
    "MessagesSetChatTheme",
    "MessagesToggleBotInAttachMenu",
    "MessagesTranscribeAudio",
    "MessagesGetSavedHistory",
    "MessagesToggleDialogFilterTags",
    "MessagesComposeMessageWithAI",
    "ChannelsGetFullChannel",
    "ChannelsEditPhoto",
    "ChannelsConvertToGigagroup",
    "BotsCheckDownloadFileParams",
    "PaymentsGetSavedStarGifts",
    "PaymentsCheckCanSendGift",
    "PhoneGetCallConfig",
    "account",
    "auth",
    "bots",
    "channels",
    "messages",
    "payments",
    "phone",
    "users",
    "CONSTRUCTOR_ID_MAP",
    "NAME_MAP",
)
