"""Public API for miniproto."""

from miniproto import event_loop
from miniproto.auth import AuthKeyExchange, AuthKeyExchangeResult, AuthService
from miniproto.client import Client
from miniproto.config import ClientConfig, DeviceInfo, TransportConfig, UpdateQueueOverflowPolicy
from miniproto.errors import (
    AuthError,
    AuthKeyNotFound,
    AuthKeyRegenerationRequired,
    BadRequest,
    ClientDisconnected,
    DatacenterMigration,
    FloodWait,
    Forbidden,
    InternalServerError,
    InvalidCode,
    InvalidDatacenter,
    InvokeError,
    NotFound,
    PasswordInvalid,
    PasswordRequired,
    RequestTimeout,
    ResultTypeMismatch,
    RpcError,
    RpcTimeout,
    SessionEnvelopeError,
    SessionStorageError,
    SignUpRequired,
    TransportFlood,
    Unauthorized,
)
from miniproto.media import MediaDownloadResult, MediaUploadResult
from miniproto.observability import (
    InMemoryMetrics,
    LogFormat,
    MemoryDelta,
    MemoryMonitor,
    MetricEvent,
    MetricsSink,
    ResourceSnapshot,
    StructuredFormatter,
    configure_logging,
    current_process_id,
    emit_event,
    get_logger,
    get_metrics_sink,
    process_rss_bytes,
    record_metric,
    resource_snapshot,
    set_metrics_sink,
    to_jsonable,
)
from miniproto.session.models import (
    AuthKey,
    DCOption,
    PeerCacheEntry,
    SessionRecord,
    UpdateState,
    UserIdentity,
)
from miniproto.session.storage import (
    EncryptedSQLiteSessionStorage,
    InMemorySessionStorage,
    SessionStorage,
)
from miniproto.types import Media, Message, NewMessage, Peer, Update, User

__all__ = [
    "AuthError",
    "AuthKey",
    "AuthKeyExchange",
    "AuthKeyExchangeResult",
    "AuthKeyNotFound",
    "AuthKeyRegenerationRequired",
    "AuthService",
    "BadRequest",
    "Client",
    "ClientConfig",
    "ClientDisconnected",
    "DCOption",
    "DatacenterMigration",
    "DeviceInfo",
    "EncryptedSQLiteSessionStorage",
    "FloodWait",
    "Forbidden",
    "InMemoryMetrics",
    "InMemorySessionStorage",
    "InternalServerError",
    "InvalidCode",
    "InvalidDatacenter",
    "InvokeError",
    "LogFormat",
    "Media",
    "MediaDownloadResult",
    "MediaUploadResult",
    "MemoryDelta",
    "MemoryMonitor",
    "Message",
    "MetricEvent",
    "MetricsSink",
    "NewMessage",
    "NotFound",
    "PasswordInvalid",
    "PasswordRequired",
    "Peer",
    "PeerCacheEntry",
    "RequestTimeout",
    "ResourceSnapshot",
    "ResultTypeMismatch",
    "RpcError",
    "RpcTimeout",
    "SessionEnvelopeError",
    "SessionRecord",
    "SessionStorage",
    "SessionStorageError",
    "SignUpRequired",
    "StructuredFormatter",
    "TransportConfig",
    "TransportFlood",
    "Unauthorized",
    "Update",
    "UpdateQueueOverflowPolicy",
    "UpdateState",
    "User",
    "UserIdentity",
    "configure_logging",
    "current_process_id",
    "emit_event",
    "event_loop",
    "get_logger",
    "get_metrics_sink",
    "process_rss_bytes",
    "record_metric",
    "resource_snapshot",
    "set_metrics_sink",
    "to_jsonable",
]
