"""Public API for miniproto."""

from miniproto import event_loop
from miniproto.auth import AuthKeyExchange, AuthKeyExchangeResult, AuthService
from miniproto.client import Client
from miniproto.config import ClientConfig, DeviceInfo, TransportConfig, UpdateQueueOverflowPolicy
from miniproto.errors import (
    AmbiguousRpcResult,
    AuthError,
    AuthKeyNotFound,
    AuthKeyRegenerationRequired,
    BadRequest,
    ClientDisconnected,
    DatacenterMigration,
    FloodWait,
    Forbidden,
    InternalServerError,
    InvalidCode,
    InvalidDatacenter,
    InvokeError,
    NotFound,
    PasswordInvalid,
    PasswordRequired,
    PendingRpcLimitExceeded,
    RequestTimeout,
    ResultTypeMismatch,
    RpcError,
    RpcTimeout,
    SessionEnvelopeError,
    SessionStorageError,
    SignUpRequired,
    TransportFlood,
    Unauthorized,
)
from miniproto.file_id import (
    FILE_ID_PREFIX,
    DecodedFileId,
    decode_file_id,
    encode_file_id,
    input_media_from_file_id,
    is_file_id,
    media_from_file_id,
    try_encode_file_id,
)
from miniproto.media import (
    CdnIntegrityError,
    MediaDownloadResult,
    MediaIntegrityError,
    MediaUploadResult,
    iter_download,
)
from miniproto.observability import (
    InMemoryMetrics,
    LogFormat,
    MemoryDelta,
    MemoryMonitor,
    MetricEvent,
    MetricsSink,
    ResourceSnapshot,
    StructuredFormatter,
    configure_logging,
    current_process_id,
    emit_event,
    get_logger,
    get_metrics_sink,
    process_rss_bytes,
    record_metric,
    resource_snapshot,
    set_metrics_sink,
    to_jsonable,
)
from miniproto.session.models import AuthKey, DCOption, PeerCacheEntry, SessionRecord, UpdateState, UserIdentity
from miniproto.session.storage import EncryptedSQLiteSessionStorage, InMemorySessionStorage, SessionStorage
from miniproto.session.strings import SessionString, SessionStringFormat, export_session_string, import_session_string
from miniproto.types import Media, Message, NewMessage, Peer, Update, User

__all__ = [
    "FILE_ID_PREFIX",
    "AmbiguousRpcResult",
    "AuthError",
    "AuthKey",
    "AuthKeyExchange",
    "AuthKeyExchangeResult",
    "AuthKeyNotFound",
    "AuthKeyRegenerationRequired",
    "AuthService",
    "BadRequest",
    "CdnIntegrityError",
    "Client",
    "ClientConfig",
    "ClientDisconnected",
    "DCOption",
    "DatacenterMigration",
    "DecodedFileId",
    "DeviceInfo",
    "EncryptedSQLiteSessionStorage",
    "FloodWait",
    "Forbidden",
    "InMemoryMetrics",
    "InMemorySessionStorage",
    "InternalServerError",
    "InvalidCode",
    "InvalidDatacenter",
    "InvokeError",
    "LogFormat",
    "Media",
    "MediaDownloadResult",
    "MediaIntegrityError",
    "MediaUploadResult",
    "MemoryDelta",
    "MemoryMonitor",
    "Message",
    "MetricEvent",
    "MetricsSink",
    "NewMessage",
    "NotFound",
    "PasswordInvalid",
    "PasswordRequired",
    "Peer",
    "PeerCacheEntry",
    "PendingRpcLimitExceeded",
    "RequestTimeout",
    "ResourceSnapshot",
    "ResultTypeMismatch",
    "RpcError",
    "RpcTimeout",
    "SessionEnvelopeError",
    "SessionRecord",
    "SessionStorage",
    "SessionStorageError",
    "SessionString",
    "SessionStringFormat",
    "SignUpRequired",
    "StructuredFormatter",
    "TransportConfig",
    "TransportFlood",
    "Unauthorized",
    "Update",
    "UpdateQueueOverflowPolicy",
    "UpdateState",
    "User",
    "UserIdentity",
    "configure_logging",
    "current_process_id",
    "decode_file_id",
    "emit_event",
    "encode_file_id",
    "event_loop",
    "export_session_string",
    "get_logger",
    "get_metrics_sink",
    "import_session_string",
    "input_media_from_file_id",
    "is_file_id",
    "iter_download",
    "media_from_file_id",
    "process_rss_bytes",
    "record_metric",
    "resource_snapshot",
    "set_metrics_sink",
    "to_jsonable",
    "try_encode_file_id",
]
