[package]
edition = "2024"
license = "MIT"
name = "miniproto-native"
publish = false
rust-version = "1.96"
version = "0.1.0"

[dependencies]
pyo3 = { version = "~0.29.0", features = ["experimental-async"] }

[lib]
name = "miniproto_native"
crate-type = ["cdylib"]

[profile.release]
codegen-units = 1
incremental = true
lto = "fat"
opt-level = 3
overflow-checks = true
panic = "abort"
strip = true
