[package]
authors = ["EDM115 <miniproto@edm115.dev>"]
description = "Rust acceleration layer for the miniproto Python MTProto SDK"
edition = "2024"
license = "MIT"
name = "miniproto"
repository = "https://github.com/EDM115/miniproto"
rust-version = "1.96"
version = "0.1.0"

[dependencies]
pyo3 = { version = "~0.29.0", features = ["experimental-async"] }

[lib]
name = "miniproto_native"
crate-type = ["cdylib"]
