from __future__ import annotations

import argparse
import hashlib
import json
import shutil
import subprocess
from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from tools.schema.parser import TLParameter, TLSchema, iter_public_params, parse_schema_file

_GENERATOR_VERSION = "1"
_SCHEMA_LAYER = 214
_REPO_ROOT = Path(__file__).resolve().parents[2]
_DEFAULT_SCHEMA = _REPO_ROOT / "tools" / "schema" / "schema.tl"
_DEFAULT_METADATA = _REPO_ROOT / "tools" / "schema" / "schema-metadata.json"
_DEFAULT_ERRORS = _REPO_ROOT / "tools" / "schema" / "rpc-errors.json"
_DEFAULT_RAW_DIR = _REPO_ROOT / "src" / "miniproto" / "raw"
_DEFAULT_DOCS = _REPO_ROOT / "docs" / "raw-api.md"
_MANIFEST = (
    "src/miniproto/raw/base.py",
    "src/miniproto/raw/types.py",
    "src/miniproto/raw/functions.py",
    "src/miniproto/raw/errors.py",
    "docs/raw-api.md",
)
_HEADER = "# Generated by tools/schema/generate.py; do not edit by hand.\n# Source: tools/schema/schema.tl\n"
_SOURCE_SCHEMA_URL = "https://core.telegram.org/schema"
_SOURCE_ERRORS_URL = "https://core.telegram.org/api/errors"
_SOURCE_ERRORS_DOWNLOAD_URL = (
    "https://core.telegram.org/file/400780400111/3/RF-b0LDHWpc.202549.json/9b83afb26f1ba2f8aa"
)


@dataclass(frozen=True, slots=True)
class GeneratedOutputs:
    files: Mapping[Path, str]


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Generate miniproto raw API modules from pinned TL schema."
    )
    parser.add_argument("--schema", type=Path, default=_DEFAULT_SCHEMA)
    parser.add_argument("--metadata", type=Path, default=_DEFAULT_METADATA)
    parser.add_argument("--errors", type=Path, default=_DEFAULT_ERRORS)
    parser.add_argument("--raw-dir", type=Path, default=_DEFAULT_RAW_DIR)
    parser.add_argument("--docs", type=Path, default=_DEFAULT_DOCS)
    parser.add_argument(
        "--check", action="store_true", help="fail when generated files or metadata are stale"
    )
    args = parser.parse_args(argv)
    outputs = render_outputs(args.schema, args.metadata, args.errors, args.raw_dir, args.docs)
    stale = stale_outputs(outputs)
    if args.check:
        if stale:
            for path in stale:
                print(f"stale generated file: {path}")
            return 1
        print("schema generated files are fresh")
        return 0
    write_outputs(outputs)
    return 0


def render_outputs(
    schema_path: Path = _DEFAULT_SCHEMA,
    metadata_path: Path = _DEFAULT_METADATA,
    errors_path: Path = _DEFAULT_ERRORS,
    raw_dir: Path = _DEFAULT_RAW_DIR,
    docs_path: Path = _DEFAULT_DOCS,
) -> GeneratedOutputs:
    schema = parse_schema_file(schema_path)
    rpc_error_database = _load_rpc_error_database(errors_path)
    metadata = _metadata(schema_path, errors_path, metadata_path, schema, rpc_error_database)
    files: dict[Path, str] = {
        metadata_path: _json_document(metadata),
        raw_dir / "base.py": _render_base(),
        raw_dir / "types.py": _render_entries_module(schema.constructors, module_kind="types"),
        raw_dir / "functions.py": _render_entries_module(schema.functions, module_kind="functions"),
        raw_dir / "errors.py": _render_errors(rpc_error_database),
        docs_path: _render_docs(metadata, schema, rpc_error_database),
    }
    formatted = {
        path: _format_python(path, content) if path.suffix == ".py" else content
        for path, content in files.items()
    }
    return GeneratedOutputs(files=formatted)


def write_outputs(outputs: GeneratedOutputs) -> None:
    for path, content in outputs.files.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8", newline="\n")


def stale_outputs(outputs: GeneratedOutputs) -> tuple[Path, ...]:
    stale: list[Path] = []
    for path, expected in outputs.files.items():
        if not path.exists() or path.read_text(encoding="utf-8") != expected:
            stale.append(path)
    return tuple(stale)


def _format_python(path: Path, content: str) -> str:
    ruff = shutil.which("ruff")
    if ruff is None:
        return content
    try:
        result = subprocess.run(  # noqa: S603 - generator uses the resolved pinned dev-tool executable.
            [ruff, "format", "--stdin-filename", str(path), "-"],
            input=content,
            text=True,
            capture_output=True,
            check=False,
        )
    except FileNotFoundError:
        return content
    if result.returncode != 0:
        raise RuntimeError(f"ruff failed to format generated {path}: {result.stderr}")
    return result.stdout


def _metadata(
    schema_path: Path,
    errors_path: Path,
    metadata_path: Path,
    schema: TLSchema,
    rpc_error_database: Mapping[str, Any],
) -> dict[str, Any]:
    error_count = sum(len(errors) for errors in rpc_error_database.get("errors", {}).values())
    return {
        "layer": _SCHEMA_LAYER,
        "source_url": _SOURCE_SCHEMA_URL,
        "source_note": "Official Telegram TL schema fetched from core.telegram.org/schema and pinned in tools/schema/schema.tl.",
        "fetch_date": "2026-06-30",
        "sha256": _sha256_file(schema_path),
        "schema_format": "tl",
        "generator_version": _GENERATOR_VERSION,
        "constructor_count": len(schema.constructors),
        "function_count": len(schema.functions),
        "rpc_error_source_url": _SOURCE_ERRORS_URL,
        "rpc_error_download_url": _SOURCE_ERRORS_DOWNLOAD_URL,
        "rpc_error_sha256": _sha256_file(errors_path),
        "rpc_error_count": error_count,
        "generated_file_manifest": list(_MANIFEST),
    }


def _render_base() -> str:
    return (
        _HEADER
        + """from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass
from typing import Any, ClassVar, Self


@dataclass(frozen=True, slots=True)
class TLField:
    name: str
    python_name: str
    type: str
    flag: str | None = None
    flag_index: int | None = None
    is_optional: bool = False
    is_true_flag: bool = False
    is_vector: bool = False
    vector_item_type: str | None = None


@dataclass(frozen=True, slots=True)
class TLFlagGroup:
    name: str
    python_name: str
    before_field_index: int


class TLObject:
    CONSTRUCTOR_ID: ClassVar[int]
    QUALNAME: ClassVar[str]
    RESULT_TYPE: ClassVar[str]
    TL_FIELDS: ClassVar[tuple[TLField, ...]] = ()
    TL_FLAG_GROUPS: ClassVar[tuple[TLFlagGroup, ...]] = ()

    def serialize(self) -> bytes:
        from miniproto.tl.codec import serialize_object

        return serialize_object(self)

    @classmethod
    def deserialize(cls, data: bytes | memoryview) -> Self:
        from miniproto.tl.codec import TLCodecError, deserialize_object

        obj, offset = deserialize_object(cls, data)
        if offset != len(data):
            raise TLCodecError("TL object payload has trailing bytes")
        return obj

    def to_raw_dict(self) -> dict[str, Any]:
        return {field.name: getattr(self, field.python_name) for field in self.TL_FIELDS}


class TLConstructor(TLObject):
    pass


class TLRequest(TLObject):
    pass


def constructor_id_map(entries: tuple[type[TLObject], ...]) -> Mapping[int, type[TLObject]]:
    return {entry.CONSTRUCTOR_ID: entry for entry in entries}
"""
    )


def _render_entries_module(entries: Sequence[Any], *, module_kind: str) -> str:
    base_class = "TLConstructor" if module_kind == "types" else "TLRequest"
    base_import = (
        "TLConstructor, TLField, TLFlagGroup"
        if base_class == "TLConstructor"
        else f"TLField, TLFlagGroup, {base_class}"
    )
    ruff_noqa = (
        "# ruff: noqa: F401,N801,N806,N815,RUF022,RUF059"
        if module_kind == "types"
        else "# ruff: noqa: F401,N801,RUF022"
    )
    lines: list[str] = [
        _HEADER.rstrip(),
        ruff_noqa,
        "from __future__ import annotations",
        "",
        "from dataclasses import dataclass",
        "from typing import Any, ClassVar, Self",
        "",
        f"from miniproto.raw.base import {base_import}",
        "from miniproto.tl.codec import (",
        "    TLCodecError,",
        "    decode_bool,",
        "    decode_bytes,",
        "    decode_constructor_id,",
        "    decode_double,",
        "    decode_int,",
        "    decode_int128,",
        "    decode_int256,",
        "    decode_long,",
        "    decode_object,",
        "    decode_string,",
        "    decode_value,",
        "    decode_vector,",
        "    encode_bool,",
        "    encode_bytes,",
        "    encode_constructor_id,",
        "    encode_double,",
        "    encode_int,",
        "    encode_int128,",
        "    encode_int256,",
        "    encode_long,",
        "    encode_string,",
        "    encode_value,",
        "    encode_vector,",
        ")",
        "",
        "",
    ]
    for entry in entries:
        fields = iter_public_params(entry.params)
        lines.extend(
            [
                "@dataclass(frozen=True, slots=True, kw_only=True)",
                f"class {entry.python_class_name}({base_class}):",
            ]
        )
        if fields:
            for field in fields:
                lines.append(_field_line(field))
        else:
            lines.append("    pass")
        lines.extend(
            [
                f"    CONSTRUCTOR_ID: ClassVar[int] = 0x{entry.constructor_id_hex}",
                f"    QUALNAME: ClassVar[str] = {entry.name!r}",
                f"    RESULT_TYPE: ClassVar[str] = {entry.result_type!r}",
                f"    TL_FIELDS: ClassVar[tuple[TLField, ...]] = {_fields_tuple(fields)}",
                f"    TL_FLAG_GROUPS: ClassVar[tuple[TLFlagGroup, ...]] = {_flag_groups_tuple(entry.params)}",
                "",
                *_codec_methods(fields, entry.params),
                "",
                "",
            ]
        )
    all_class_names = [entry.python_class_name for entry in entries]
    namespace_lines, namespace_names = _namespace_classes(entries)
    lines.extend(namespace_lines)
    all_names = all_class_names + namespace_names + ["CONSTRUCTOR_ID_MAP", "NAME_MAP"]
    lines.append(f"ALL_{module_kind.upper()}: tuple[type[{base_class}], ...] = (")
    for name in all_class_names:
        lines.append(f"    {name},")
    lines.append(")")
    lines.append(
        f"CONSTRUCTOR_ID_MAP: dict[int, type[{base_class}]] = {{entry.CONSTRUCTOR_ID: entry for entry in ALL_{module_kind.upper()}}}"
    )
    lines.append(
        f"NAME_MAP: dict[str, type[{base_class}]] = {{entry.QUALNAME: entry for entry in ALL_{module_kind.upper()}}}"
    )
    lines.append(f"__all__ = {tuple(all_names)!r}")
    lines.append("")
    return "\n".join(lines)


def _field_line(field: TLParameter) -> str:
    annotation = _annotation(field)
    if field.is_true_flag:
        return f"    {field.python_name}: bool = False"
    if field.is_optional:
        return f"    {field.python_name}: {annotation} | None = None"
    return f"    {field.python_name}: {annotation}"


def _annotation(field: TLParameter) -> str:
    if field.is_vector:
        return f"tuple[{_single_annotation(field.vector_item_type or 'object')}, ...]"
    return _single_annotation(field.type)


def _single_annotation(type_name: str) -> str:
    clean = type_name.removeprefix("!")
    match clean:
        case "int" | "long" | "int128" | "int256":
            return "int"
        case "double":
            return "float"
        case "string":
            return "str"
        case "bytes":
            return "bytes"
        case "Bool" | "bool" | "true":
            return "bool"
        case "X" | "Type" | "#":
            return "Any"
        case _:
            return "Any"


def _fields_tuple(fields: Sequence[TLParameter]) -> str:
    if not fields:
        return "()"
    lines = ["("]
    for field in fields:
        lines.extend(
            [
                "    TLField(",
                f"        name={field.name!r},",
                f"        python_name={field.python_name!r},",
                f"        type={field.type!r},",
                f"        flag={field.flag!r},",
                f"        flag_index={field.flag_index!r},",
                f"        is_optional={field.is_optional!r},",
                f"        is_true_flag={field.is_true_flag!r},",
                f"        is_vector={field.is_vector!r},",
                f"        vector_item_type={field.vector_item_type!r},",
                "    ),",
            ]
        )
    lines.append(")")
    return "\n".join(lines)


def _flag_groups_tuple(params: Sequence[TLParameter]) -> str:
    groups: list[tuple[str, str, int]] = []
    public_index = 0
    for param in params:
        if param.is_flags_marker:
            groups.append((param.name, param.python_name, public_index))
        elif not param.is_template and not param.is_bare:
            public_index += 1
    if not groups:
        return "()"
    lines = ["("]
    for name, python_name, before_field_index in groups:
        lines.extend(
            [
                "    TLFlagGroup(",
                f"        name={name!r},",
                f"        python_name={python_name!r},",
                f"        before_field_index={before_field_index!r},",
                "    ),",
            ]
        )
    lines.append(")")
    return "\n".join(lines)


def _codec_methods(fields: Sequence[TLParameter], params: Sequence[TLParameter]) -> list[str]:
    lines: list[str] = [
        "    def serialize(self) -> bytes:",
        "        return self._serialize(boxed=True)",
        "",
        "    def _serialize(self, *, boxed: bool = True) -> bytes:",
        "        output = bytearray()",
        "        if boxed:",
        "            output.extend(encode_constructor_id(self.CONSTRUCTOR_ID))",
    ]
    flag_groups = _flag_group_specs(params)
    for _name, python_name, _before_field_index in flag_groups:
        lines.append(f"        {python_name} = 0")
    for field in fields:
        if not field.is_optional or field.flag is None or field.flag_index is None:
            continue
        flag_var = _flag_var(field, flag_groups)
        if field.is_true_flag:
            lines.extend(
                [
                    f"        if self.{field.python_name}:",
                    f"            {flag_var} |= {1 << field.flag_index}",
                ]
            )
        else:
            lines.extend(
                [
                    f"        if self.{field.python_name} is not None:",
                    f"            {flag_var} |= {1 << field.flag_index}",
                ]
            )
    groups_by_index = _flag_groups_by_index(flag_groups)
    for index, field in enumerate(fields):
        for _name, python_name, _before_field_index in groups_by_index.get(index, ()):
            lines.append(f"        output.extend(encode_int({python_name}))")
        if field.is_optional:
            if field.is_true_flag:
                continue
            lines.extend(
                [
                    f"        if self.{field.python_name} is not None:",
                    f"            output.extend({_encode_expr(field, f'self.{field.python_name}')})",
                ]
            )
        else:
            lines.append(
                f"        output.extend({_encode_expr(field, f'self.{field.python_name}')})"
            )
    for _name, python_name, _before_field_index in groups_by_index.get(len(fields), ()):
        lines.append(f"        output.extend(encode_int({python_name}))")
    lines.extend(
        [
            "        return bytes(output)",
            "",
            "    @classmethod",
            "    def deserialize(cls, data: bytes | memoryview) -> Self:",
            "        obj, offset = cls._deserialize(data)",
            "        if offset != len(data):",
            "            raise TLCodecError('TL object payload has trailing bytes')",
            "        return obj",
            "",
            "    @classmethod",
            "    def _deserialize(",
            "        cls, data: bytes | memoryview, offset: int = 0, *, boxed: bool = True",
            "    ) -> tuple[Self, int]:",
            "        raw_data = data",
            "        cursor = offset",
            "        if boxed:",
            "            constructor_id, cursor = decode_constructor_id(raw_data, cursor)",
            "            if constructor_id != cls.CONSTRUCTOR_ID:",
            "                raise TLCodecError(",
            "                    f'expected constructor 0x{cls.CONSTRUCTOR_ID:08x}, got 0x{constructor_id:08x}'",
            "                )",
        ]
    )
    for _name, python_name, _before_field_index in flag_groups:
        lines.append(f"        {python_name} = 0")
    for index, field in enumerate(fields):
        for _name, python_name, _before_field_index in groups_by_index.get(index, ()):
            lines.append(f"        {python_name}, cursor = decode_int(raw_data, cursor)")
        field_var = _field_value_var(field)
        if field.is_optional:
            flag_var = _flag_var(field, flag_groups)
            present_expr = f"bool({flag_var} & {1 << int(field.flag_index or 0)})"
            if field.is_true_flag:
                lines.append(f"        {field_var} = {present_expr}")
                continue
            lines.extend(
                [
                    f"        if {present_expr}:",
                    f"            {field_var}, cursor = {_decode_expr(field)}",
                    "        else:",
                    f"            {field_var} = None",
                ]
            )
        else:
            lines.append(f"        {field_var}, cursor = {_decode_expr(field)}")
    for _name, python_name, _before_field_index in groups_by_index.get(len(fields), ()):
        lines.append(f"        {python_name}, cursor = decode_int(raw_data, cursor)")
    if fields:
        lines.append("        return cls(")
        for field in fields:
            lines.append(f"            {field.python_name}={_field_value_var(field)},")
        lines.extend(["        ), cursor"])
    else:
        lines.append("        return cls(), cursor")
    return lines


def _flag_group_specs(params: Sequence[TLParameter]) -> list[tuple[str, str, int]]:
    groups: list[tuple[str, str, int]] = []
    public_index = 0
    for param in params:
        if param.is_flags_marker:
            groups.append((param.name, param.python_name, public_index))
        elif not param.is_template and not param.is_bare:
            public_index += 1
    return groups


def _flag_groups_by_index(
    groups: Sequence[tuple[str, str, int]],
) -> dict[int, tuple[tuple[str, str, int], ...]]:
    grouped: dict[int, list[tuple[str, str, int]]] = {}
    for group in groups:
        grouped.setdefault(group[2], []).append(group)
    return {index: tuple(items) for index, items in grouped.items()}


def _flag_var(field: TLParameter, groups: Sequence[tuple[str, str, int]]) -> str:
    for name, python_name, _before_field_index in groups:
        if name == field.flag:
            return python_name
    return str(field.flag)


def _field_value_var(field: TLParameter) -> str:
    return f"_value_{field.python_name}"


def _encode_expr(field: TLParameter, value_expr: str) -> str:
    if field.is_vector:
        return f"encode_vector({value_expr}, {field.vector_item_type!r})"
    match field.type:
        case "int" | "#":
            return f"encode_int({value_expr})"
        case "long":
            return f"encode_long({value_expr})"
        case "int128":
            return f"encode_int128({value_expr})"
        case "int256":
            return f"encode_int256({value_expr})"
        case "double":
            return f"encode_double({value_expr})"
        case "bytes":
            return f"encode_bytes({value_expr})"
        case "string":
            return f"encode_string({value_expr})"
        case "Bool" | "bool":
            return f"encode_bool({value_expr})"
        case "true":
            return "b''"
        case _:
            return f"encode_value({field.type!r}, {value_expr})"


def _decode_expr(field: TLParameter) -> str:
    if field.is_vector:
        return f"decode_vector(raw_data, cursor, {field.vector_item_type!r})"
    match field.type:
        case "int" | "#":
            return "decode_int(raw_data, cursor)"
        case "long":
            return "decode_long(raw_data, cursor)"
        case "int128":
            return "decode_int128(raw_data, cursor)"
        case "int256":
            return "decode_int256(raw_data, cursor)"
        case "double":
            return "decode_double(raw_data, cursor)"
        case "bytes":
            return "decode_bytes(raw_data, cursor)"
        case "string":
            return "decode_string(raw_data, cursor)"
        case "Bool" | "bool":
            return "decode_bool(raw_data, cursor)"
        case "true":
            return "True, cursor"
        case _:
            return f"decode_value({field.type!r}, raw_data, cursor)"


def _namespace_classes(entries: Sequence[Any]) -> tuple[list[str], list[str]]:
    namespaces: dict[str, list[Any]] = {}
    for entry in entries:
        if entry.namespace is not None:
            namespaces.setdefault(entry.namespace, []).append(entry)
    lines: list[str] = []
    namespace_names: list[str] = []
    for namespace in sorted(namespaces):
        class_name = namespace.replace(".", "_")
        namespace_names.append(class_name)
        lines.append(f"class {class_name}:")
        for entry in sorted(namespaces[namespace], key=lambda item: item.short_name):
            lines.append(f"    {_short_class_name(entry.short_name)} = {entry.python_class_name}")
        lines.extend(["", ""])
    return lines, namespace_names


def _short_class_name(short_name: str) -> str:
    import re

    parts = re.sub(r"([a-z0-9])([A-Z])", r"\1 \2", short_name).replace("_", " ").split()
    return "".join(part[:1].upper() + part[1:] for part in parts)


def _render_errors(database: Mapping[str, Any]) -> str:
    errors = database.get("errors", {})
    descriptions = database.get("descriptions", {})
    specs: list[tuple[str, int, tuple[str, ...], str]] = []
    for code, named_errors in sorted(errors.items(), key=lambda item: int(item[0])):
        for name, methods in sorted(named_errors.items()):
            specs.append((name, int(code), tuple(sorted(methods)), str(descriptions.get(name, ""))))
    method_map: dict[str, list[str]] = {}
    for name, _code, methods, _description in specs:
        for method in methods:
            method_map.setdefault(method, []).append(name)
    lines: list[str] = [
        _HEADER.rstrip(),
        "from __future__ import annotations",
        "",
        "from dataclasses import dataclass",
        "",
        "",
        "@dataclass(frozen=True, slots=True)",
        "class RawRPCErrorSpec:",
        "    name: str",
        "    code: int",
        "    methods: tuple[str, ...] = ()",
        "    description: str = ''",
        "",
        "",
        "RPC_ERROR_MAP: dict[tuple[str, int], RawRPCErrorSpec] = {",
    ]
    for name, code, methods, description in specs:
        lines.extend(
            [
                f"    ({name!r}, {code!r}): RawRPCErrorSpec(",
                f"        name={name!r},",
                f"        code={code!r},",
                "        methods=",
                _tuple_literal(methods, indent="        ") + ",",
                f"        description={description!r},",
                "    ),",
            ]
        )
    lines.extend(["}", "CODE_TO_ERROR_NAMES: dict[int, tuple[str, ...]] = {"])
    for code in sorted({code for _name, code, _methods, _description in specs}):
        names = tuple(
            name for name, item_code, _methods, _description in specs if item_code == code
        )
        lines.append(f"    {code!r}: {_tuple_literal(names, indent='    ')},")
    lines.extend(["}", "METHOD_TO_ERROR_NAMES: dict[str, tuple[str, ...]] = {"])
    for method in sorted(method_map):
        lines.append(
            f"    {method!r}: {_tuple_literal(tuple(sorted(set(method_map[method]))), indent='    ')},"
        )
    lines.extend(
        [
            "}",
            "",
            "",
            "def rpc_error_for_name(name: str, code: int | None = None) -> RawRPCErrorSpec | None:",
            "    if code is not None:",
            "        return RPC_ERROR_MAP.get((name, code))",
            "    matches = sorted(",
            "        (error for (error_name, _code), error in RPC_ERROR_MAP.items() if error_name == name),",
            "        key=lambda error: error.code,",
            "    )",
            "    return matches[0] if matches else None",
            "",
            "",
            "def rpc_errors_for_name(name: str) -> tuple[RawRPCErrorSpec, ...]:",
            "    return tuple(",
            "        sorted(",
            "            (error for (error_name, _code), error in RPC_ERROR_MAP.items() if error_name == name),",
            "            key=lambda error: error.code,",
            "        )",
            "    )",
            "",
            "",
            "__all__ = (",
            "    'CODE_TO_ERROR_NAMES',",
            "    'METHOD_TO_ERROR_NAMES',",
            "    'RPC_ERROR_MAP',",
            "    'RawRPCErrorSpec',",
            "    'rpc_error_for_name',",
            "    'rpc_errors_for_name',",
            ")",
            "",
        ]
    )
    return "\n".join(lines)


def _tuple_literal(values: Sequence[str], *, indent: str) -> str:
    if not values:
        return "()"
    if len(values) == 1:
        return f"({values[0]!r},)"
    inner = ["("]
    inner.extend(f"{indent}    {value!r}," for value in values)
    inner.append(f"{indent})")
    return "\n".join(inner)


def _render_docs(metadata: Mapping[str, Any], schema: TLSchema, database: Mapping[str, Any]) -> str:
    sample_functions = ", ".join(entry.name for entry in schema.functions[:8])
    sample_types = ", ".join(entry.name for entry in schema.constructors[:8])
    return f"""# Raw API

Status: generated documentation stub for Telegram Layer {metadata["layer"]}.

## Source

The raw API classes are generated from the official Telegram TL schema at [{metadata["source_url"]}]({metadata["source_url"]}). The pinned schema lives at `tools/schema/schema.tl` with SHA-256 `{metadata["sha256"]}`.

RPC error metadata is generated from Telegram's error database linked from [{metadata["rpc_error_source_url"]}]({metadata["rpc_error_source_url"]}). The pinned JSON lives at `tools/schema/rpc-errors.json` with SHA-256 `{metadata["rpc_error_sha256"]}`.

## Generated Surface

- Constructors: {metadata["constructor_count"]}
- Functions: {metadata["function_count"]}
- RPC errors: {metadata["rpc_error_count"]}
- Generated files: {", ".join(metadata["generated_file_manifest"])}

## Usage Shape

```python
from miniproto.raw import functions

request = functions.help.GetConfig()
```

## Current Limits

Phase 4 implements binary TL primitive encoding, generated object serialization/deserialization, flags, vectors, boxed constructors, and RPC error metadata. Gzip payload handling, message containers, transport framing, and RPC response correlation land in later runtime phases.

## Samples

Early generated type constructors include: {sample_types}.

Early generated functions include: {sample_functions}.
"""


def _load_rpc_error_database(path: Path) -> Mapping[str, Any]:
    if not path.exists():
        return {"errors": {}, "descriptions": {}}
    data = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(data, dict):
        raise TypeError("RPC error database must be a JSON object")
    return data


def _sha256_file(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _json_document(data: Mapping[str, Any]) -> str:
    return json.dumps(data, indent=2, sort_keys=True) + "\n"


if __name__ == "__main__":
    raise SystemExit(main())
