from __future__ import annotations

import argparse
import hashlib
import json
import shutil
import subprocess
import sys
from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from tools.schema.parser import TLParameter, TLSchema, iter_public_params, parse_schema_file
from tools.schema.rust_fast import fast_api_directions, load_fast_entries, render_python_metadata, render_rust

_GENERATOR_VERSION = "4"
_SCHEMA_LAYER = 214
_REPO_ROOT = Path(__file__).resolve().parents[2]
_DEFAULT_SCHEMA = _REPO_ROOT / "tools" / "schema" / "schema.json"
_DEFAULT_METADATA = _REPO_ROOT / "tools" / "schema" / "schema-metadata.json"
_DEFAULT_ERRORS = _REPO_ROOT / "tools" / "schema" / "rpc-errors.json"
_DEFAULT_RAW_DIR = _REPO_ROOT / "src" / "miniproto" / "raw"
_DEFAULT_DOCS = _REPO_ROOT / "docs" / "raw-api.md"
_DEFAULT_RUST_FAST_MANIFEST = _REPO_ROOT / "tools" / "schema" / "rust-fast-paths.json"
_DEFAULT_GENERATED_RUST = _REPO_ROOT / "rust" / "miniproto" / "src" / "generated_tl.rs"
_DEFAULT_FAST_METADATA = _REPO_ROOT / "src" / "miniproto" / "tl" / "fast_metadata.py"
_TYPE_BUCKET_COUNT = 64
_FUNCTION_BUCKET_COUNT = 32
_MANIFEST = (
    "src/miniproto/raw/base.py",
    "src/miniproto/raw/types.py",
    "src/miniproto/raw/types.pyi",
    "src/miniproto/raw/functions.py",
    "src/miniproto/raw/functions.pyi",
    "src/miniproto/raw/_registry.py",
    "src/miniproto/raw/_types_shards/*.py",
    "src/miniproto/raw/_function_shards/*.py",
    "src/miniproto/raw/errors.py",
    "src/miniproto/tl/fast_metadata.py",
    "rust/miniproto/src/generated_tl.rs",
    "docs/raw-api.md",
)
_HEADER = "# Generated by tools/schema/generate.py; do not edit by hand.\n# Source: tools/schema/schema.json (normalized from the pinned canonical TL schema)\n"
_SOURCE_SCHEMA_URL = "https://raw.githubusercontent.com/tdlib/td/refs/heads/master/td/generate/scheme/telegram_api.tl"
_SOURCE_LAYER_URL = "https://raw.githubusercontent.com/telegramdesktop/tdesktop/refs/heads/dev/Telegram/SourceFiles/mtproto/scheme/api.tl"
_SOURCE_SCHEMA_DOC_URL = "https://core.telegram.org/schema"
_SOURCE_ERRORS_URL = "https://core.telegram.org/api/errors"
_SOURCE_ERRORS_DOWNLOAD_URL = "https://core.telegram.org/api/errors.json"
_SOURCE_CHANGELOG_URL = "https://core.telegram.org/api/layers"


@dataclass(frozen=True, slots=True)
class GeneratedOutputs:
    files: Mapping[Path, str]
    owned_directories: tuple[Path, ...] = ()


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate miniproto raw API modules from pinned TL schema.")
    parser.add_argument("--schema", type=Path, default=_DEFAULT_SCHEMA)
    parser.add_argument("--metadata", type=Path, default=_DEFAULT_METADATA)
    parser.add_argument("--errors", type=Path, default=_DEFAULT_ERRORS)
    parser.add_argument("--raw-dir", type=Path, default=_DEFAULT_RAW_DIR)
    parser.add_argument("--docs", type=Path, default=_DEFAULT_DOCS)
    parser.add_argument("--rust-fast-manifest", type=Path, default=_DEFAULT_RUST_FAST_MANIFEST)
    parser.add_argument("--generated-rust", type=Path, default=_DEFAULT_GENERATED_RUST)
    parser.add_argument("--fast-metadata", type=Path, default=_DEFAULT_FAST_METADATA)
    parser.add_argument("--check", action="store_true", help="fail when generated files or metadata are stale")
    args = parser.parse_args(argv)
    outputs = render_outputs(
        args.schema,
        args.metadata,
        args.errors,
        args.raw_dir,
        args.docs,
        args.rust_fast_manifest,
        args.generated_rust,
        args.fast_metadata,
    )
    stale = stale_outputs(outputs)
    if args.check:
        if stale:
            for path in stale:
                print(f"stale generated file: {path}")
            return 1
        print("schema generated files are fresh")
        return 0
    write_outputs(outputs)
    return 0


def render_outputs(
    schema_path: Path = _DEFAULT_SCHEMA,
    metadata_path: Path = _DEFAULT_METADATA,
    errors_path: Path = _DEFAULT_ERRORS,
    raw_dir: Path = _DEFAULT_RAW_DIR,
    docs_path: Path = _DEFAULT_DOCS,
    rust_fast_manifest_path: Path | None = None,
    generated_rust_path: Path | None = None,
    fast_metadata_path: Path | None = None,
) -> GeneratedOutputs:
    schema = parse_schema_file(schema_path)
    rpc_error_database = _load_rpc_error_database(errors_path)
    metadata = _metadata(schema_path, errors_path, metadata_path, schema, rpc_error_database)
    fast_entries = (
        load_fast_entries(rust_fast_manifest_path, schema_path, int(metadata["schema_layer"]), schema)
        if rust_fast_manifest_path is not None
        else ()
    )
    fast_directions = fast_api_directions(fast_entries)
    type_shard_dir = raw_dir / "_types_shards"
    function_shard_dir = raw_dir / "_function_shards"
    files: dict[Path, str] = {
        metadata_path: _json_document(metadata),
        raw_dir / "base.py": _render_base(metadata),
        raw_dir / "types.py": _render_facade(schema.constructors, module_kind="types"),
        raw_dir / "types.pyi": _render_stub(schema.constructors, module_kind="types"),
        raw_dir / "functions.py": _render_facade(schema.functions, module_kind="functions"),
        raw_dir / "functions.pyi": _render_stub(schema.functions, module_kind="functions"),
        raw_dir / "_registry.py": _render_registry(schema),
        raw_dir / "errors.py": _render_errors(rpc_error_database),
        docs_path: _render_docs(metadata, schema, rpc_error_database),
    }
    if generated_rust_path is not None and fast_metadata_path is not None:
        files[generated_rust_path] = render_rust(
            fast_entries, int(metadata["schema_layer"]), str(metadata["schema_json_sha256"])
        )
        files[fast_metadata_path] = render_python_metadata(
            fast_entries, int(metadata["schema_layer"]), str(metadata["schema_json_sha256"])
        )
    files.update(
        _render_shards(
            schema.constructors,
            module_kind="types",
            shard_dir=type_shard_dir,
            bucket_count=_TYPE_BUCKET_COUNT,
            fast_directions=fast_directions,
        )
    )
    files.update(
        _render_shards(
            schema.functions,
            module_kind="functions",
            shard_dir=function_shard_dir,
            bucket_count=_FUNCTION_BUCKET_COUNT,
            fast_directions=fast_directions,
        )
    )
    formatted = {
        path: (
            _format_python(path, content)
            if path.suffix in {".py", ".pyi"}
            else _format_rust(path, content)
            if path.suffix == ".rs"
            else content
        )
        for path, content in files.items()
    }
    return GeneratedOutputs(files=formatted, owned_directories=(type_shard_dir, function_shard_dir))


def write_outputs(outputs: GeneratedOutputs) -> None:
    for path in _unexpected_owned_outputs(outputs):
        path.unlink()
    for path, content in outputs.files.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8", newline="\n")


def stale_outputs(outputs: GeneratedOutputs) -> tuple[Path, ...]:
    stale: list[Path] = []
    for path, expected in outputs.files.items():
        if not path.exists() or path.read_text(encoding="utf-8") != expected:
            stale.append(path)
    stale.extend(_unexpected_owned_outputs(outputs))
    return tuple(stale)


def _unexpected_owned_outputs(outputs: GeneratedOutputs) -> tuple[Path, ...]:
    expected = frozenset(outputs.files)
    unexpected: list[Path] = []
    for directory in outputs.owned_directories:
        if not directory.exists():
            continue
        for path in directory.glob("*.py"):
            if path in expected:
                continue
            if path.read_text(encoding="utf-8").startswith(_HEADER.splitlines()[0]):
                unexpected.append(path)
    return tuple(sorted(unexpected))


def _bucket_for_constructor_id(constructor_id: int, bucket_count: int) -> int:
    if bucket_count <= 0 or bucket_count & (bucket_count - 1):
        raise ValueError("bucket_count must be a positive power of two")
    return constructor_id & (bucket_count - 1)


def _render_shards(
    entries: Sequence[Any],
    *,
    module_kind: str,
    shard_dir: Path,
    bucket_count: int,
    fast_directions: Mapping[int, frozenset[str]],
) -> dict[Path, str]:
    buckets: dict[int, list[Any]] = {}
    for entry in entries:
        bucket = _bucket_for_constructor_id(entry.constructor_id, bucket_count)
        buckets.setdefault(bucket, []).append(entry)
    return {
        shard_dir / f"bucket_{bucket:02d}.py": _render_entries_module(
            tuple(bucket_entries), module_kind=module_kind, fast_directions=fast_directions
        )
        for bucket, bucket_entries in sorted(buckets.items())
    }


def _render_facade(entries: Sequence[Any], *, module_kind: str) -> str:
    collection_name = f"ALL_{module_kind.upper()}"
    public_names = [entry.python_class_name for entry in entries]
    namespaces = sorted({entry.namespace for entry in entries if entry.namespace is not None})
    namespace_names = [namespace.replace(".", "_") for namespace in namespaces]
    lines = [
        _HEADER.rstrip(),
        "from __future__ import annotations",
        "",
        "from miniproto.raw._registry import (",
        "    LazyClassSequence,",
        "    LazyConstructorMap,",
        "    LazyNameMap,",
        "    lazy_namespace,",
        "    resolve_class,",
        ")",
        "",
        "",
    ]
    for namespace, public_name in zip(namespaces, namespace_names, strict=True):
        lines.append(f"{public_name} = lazy_namespace({module_kind!r}, {namespace!r})")
    if namespaces:
        lines.append("")
    lines.extend(
        [
            f"{collection_name} = LazyClassSequence({module_kind!r})",
            f"CONSTRUCTOR_ID_MAP = LazyConstructorMap({module_kind!r})",
            f"NAME_MAP = LazyNameMap({module_kind!r})",
            "",
            "",
            "def __getattr__(name: str):",
            f"    resolved = resolve_class({module_kind!r}, name)",
            "    globals()[name] = resolved",
            "    return resolved",
            "",
            "",
            "def __dir__():",
            f"    return sorted(set(globals()).union({tuple(public_names)!r}))",
            "",
            "",
            f"__all__ = {tuple(public_names + namespace_names + ['CONSTRUCTOR_ID_MAP', 'NAME_MAP'])!r}",
            "",
        ]
    )
    return "\n".join(lines)


def _render_stub(entries: Sequence[Any], *, module_kind: str) -> str:
    base_class = "TLConstructor" if module_kind == "types" else "TLRequest"
    lines = [
        _HEADER.rstrip(),
        "from __future__ import annotations",
        "",
        "from collections.abc import Mapping, Sequence",
        "from typing import Any, ClassVar",
        "",
        f"from miniproto.raw.base import {base_class}",
        "",
        "",
    ]
    for entry in entries:
        fields = iter_public_params(entry.params)
        lines.extend(
            [
                f"class {entry.python_class_name}({base_class}):",
                "    CONSTRUCTOR_ID: ClassVar[int]",
                "    QUALNAME: ClassVar[str]",
                "    RESULT_TYPE: ClassVar[str]",
            ]
        )
        for field in fields:
            lines.append(f"    {field.python_name}: {_stub_annotation(field)}")
        parameters = ["self"]
        if fields:
            parameters.append("*")
            for field in fields:
                default = " = ..." if field.is_optional else ""
                parameters.append(f"{field.python_name}: {_stub_annotation(field)}{default}")
        lines.extend([f"    def __init__({', '.join(parameters)}) -> None: ...", "", ""])
    namespace_lines, _namespace_names = _namespace_classes(entries)
    lines.extend(namespace_lines)
    lines.extend(
        [
            f"ALL_{module_kind.upper()}: Sequence[type[{base_class}]]",
            f"CONSTRUCTOR_ID_MAP: Mapping[int, type[{base_class}]]",
            f"NAME_MAP: Mapping[str, type[{base_class}]]",
            "__all__: tuple[str, ...]",
            "",
        ]
    )
    return "\n".join(lines)


def _stub_annotation(field: TLParameter) -> str:
    annotation = _annotation(field)
    return f"{annotation} | None" if field.is_optional and not field.is_true_flag else annotation


def _render_registry(schema: TLSchema) -> str:
    lines = [
        _HEADER.rstrip(),
        "from __future__ import annotations",
        "",
        "import sys",
        "from collections.abc import Iterator, Mapping, Sequence",
        "from functools import cache",
        "from importlib import import_module",
        "from typing import Any",
        "",
        f"TYPE_SPECS = {_registry_specs(schema.constructors, 'types', _TYPE_BUCKET_COUNT)!r}",
        f"FUNCTION_SPECS = {_registry_specs(schema.functions, 'functions', _FUNCTION_BUCKET_COUNT)!r}",
        f"TYPE_CONSTRUCTORS = {_constructor_names(schema.constructors)!r}",
        f"FUNCTION_CONSTRUCTORS = {_constructor_names(schema.functions)!r}",
        f"TYPE_QUALNAMES = {_qualname_names(schema.constructors)!r}",
        f"FUNCTION_QUALNAMES = {_qualname_names(schema.functions)!r}",
        f"TYPE_NAMESPACES = {_registry_namespaces(schema.constructors)!r}",
        f"FUNCTION_NAMESPACES = {_registry_namespaces(schema.functions)!r}",
        "",
    ]
    lines.extend(
        """

def _kind_tables(kind: str):
    if kind == "types":
        return TYPE_SPECS, TYPE_CONSTRUCTORS, TYPE_QUALNAMES, TYPE_NAMESPACES
    if kind == "functions":
        return FUNCTION_SPECS, FUNCTION_CONSTRUCTORS, FUNCTION_QUALNAMES, FUNCTION_NAMESPACES
    raise ValueError(f"unknown raw facade kind: {kind!r}")


@cache
def resolve_class(kind: str, name: str) -> type[Any]:
    specs, _constructors, _qualnames, _namespaces = _kind_tables(kind)
    try:
        shard_module, attribute_name = specs[name]
    except KeyError:
        raise AttributeError(name) from None
    cls = getattr(import_module(shard_module), attribute_name)
    facade_name = f"miniproto.raw.{kind}"
    cls.__module__ = facade_name
    facade = sys.modules.get(facade_name)
    if facade is None:
        facade = import_module(facade_name)
    facade.__dict__.setdefault(name, cls)
    return cls


class LazyClassSequence(Sequence[type[Any]]):
    def __init__(self, kind: str) -> None:
        self._kind = kind
        self._names = tuple(_kind_tables(kind)[0])

    def __len__(self) -> int:
        return len(self._names)

    def __getitem__(self, index: int | slice):
        if isinstance(index, slice):
            return tuple(resolve_class(self._kind, name) for name in self._names[index])
        return resolve_class(self._kind, self._names[index])

    def __iter__(self) -> Iterator[type[Any]]:
        return (resolve_class(self._kind, name) for name in self._names)


class LazyConstructorMap(Mapping[int, type[Any]]):
    def __init__(self, kind: str | None = None) -> None:
        self._kind = kind

    def __len__(self) -> int:
        if self._kind is not None:
            return len(_kind_tables(self._kind)[1])
        return len(TYPE_CONSTRUCTORS) + len(FUNCTION_CONSTRUCTORS)

    def __iter__(self) -> Iterator[int]:
        if self._kind == "types":
            return iter(TYPE_CONSTRUCTORS)
        if self._kind == "functions":
            return iter(FUNCTION_CONSTRUCTORS)
        return iter((*TYPE_CONSTRUCTORS, *FUNCTION_CONSTRUCTORS))

    def __getitem__(self, constructor_id: int) -> type[Any]:
        if self._kind == "types":
            return resolve_class("types", TYPE_CONSTRUCTORS[constructor_id])
        if self._kind == "functions":
            return resolve_class("functions", FUNCTION_CONSTRUCTORS[constructor_id])
        if constructor_id in TYPE_CONSTRUCTORS:
            return resolve_class("types", TYPE_CONSTRUCTORS[constructor_id])
        return resolve_class("functions", FUNCTION_CONSTRUCTORS[constructor_id])


class LazyNameMap(Mapping[str, type[Any]]):
    def __init__(self, kind: str) -> None:
        self._kind = kind
        self._qualnames = _kind_tables(kind)[2]

    def __len__(self) -> int:
        return len(self._qualnames)

    def __iter__(self) -> Iterator[str]:
        return iter(self._qualnames)

    def __getitem__(self, qualname: str) -> type[Any]:
        return resolve_class(self._kind, self._qualnames[qualname])


class _LazyNamespaceMeta(type):
    _kind: str
    _namespace: str

    def __getattr__(cls, name: str) -> type[Any]:
        members = _kind_tables(cls._kind)[3][cls._namespace]
        try:
            public_name = members[name]
        except KeyError:
            raise AttributeError(name) from None
        resolved = resolve_class(cls._kind, public_name)
        setattr(cls, name, resolved)
        return resolved

    def __dir__(cls) -> list[str]:
        members = _kind_tables(cls._kind)[3][cls._namespace]
        return sorted(set(super().__dir__()) | set(members))


def lazy_namespace(kind: str, namespace: str) -> type[Any]:
    public_name = namespace.replace(".", "_")
    return _LazyNamespaceMeta(
        public_name,
        (),
        {
            "__module__": f"miniproto.raw.{kind}",
            "_kind": kind,
            "_namespace": namespace,
        },
    )


CONSTRUCTORS = LazyConstructorMap()
""".splitlines()
    )
    return "\n".join(lines)


def _registry_specs(entries: Sequence[Any], module_kind: str, bucket_count: int) -> dict[str, tuple[str, str]]:
    shard_package = "_types_shards" if module_kind == "types" else "_function_shards"
    return {
        entry.python_class_name: (
            f"miniproto.raw.{shard_package}.bucket_{_bucket_for_constructor_id(entry.constructor_id, bucket_count):02d}",
            entry.python_class_name,
        )
        for entry in sorted(entries, key=lambda item: item.python_class_name)
    }


def _constructor_names(entries: Sequence[Any]) -> dict[int, str]:
    return {
        entry.constructor_id: entry.python_class_name for entry in sorted(entries, key=lambda item: item.constructor_id)
    }


def _qualname_names(entries: Sequence[Any]) -> dict[str, str]:
    return {entry.name: entry.python_class_name for entry in sorted(entries, key=lambda item: item.name)}


def _registry_namespaces(entries: Sequence[Any]) -> dict[str, dict[str, str]]:
    namespaces: dict[str, dict[str, str]] = {}
    for entry in sorted(entries, key=lambda item: (item.namespace or "", item.short_name)):
        if entry.namespace is None:
            continue
        namespaces.setdefault(entry.namespace, {})[_short_class_name(entry.short_name)] = entry.python_class_name
    return namespaces


def _format_python(path: Path, content: str) -> str:
    try:
        result = subprocess.run(  # noqa: S603 - generator uses the resolved pinned dev-tool executable.
            [sys.executable, "-m", "ruff", "format", "--stdin-filename", str(path), "-"],
            input=content,
            text=True,
            capture_output=True,
            check=False,
        )
    except FileNotFoundError:
        return content
    if result.returncode != 0:
        if "No module named ruff" in result.stderr:
            return content
        raise RuntimeError(f"ruff failed to format generated {path}: {result.stderr}")
    return result.stdout


def _format_rust(path: Path, content: str) -> str:
    rustfmt = shutil.which("rustfmt")
    if rustfmt is None:
        return content
    try:
        result = subprocess.run(  # noqa: S603 - generator uses the resolved pinned Rust formatter.
            [rustfmt, "--emit", "stdout", "--edition", "2024"],
            input=content,
            text=True,
            capture_output=True,
            check=False,
        )
    except FileNotFoundError:
        return content
    if result.returncode != 0:
        raise RuntimeError(f"rustfmt failed to format generated {path}: {result.stderr}")
    return result.stdout


def _metadata(
    schema_path: Path, errors_path: Path, metadata_path: Path, schema: TLSchema, rpc_error_database: Mapping[str, Any]
) -> dict[str, Any]:
    error_count = sum(len(errors) for errors in rpc_error_database.get("errors", {}).values())
    previous = _load_existing_metadata(metadata_path)
    schema_format = "json" if schema_path.suffix == ".json" else "tl"
    schema_layer = int(previous.get("schema_layer", previous.get("layer", _SCHEMA_LAYER)))
    rpc_error_layer = rpc_error_database.get("layer", previous.get("rpc_error_layer"))
    schema_sha256 = _sha256_file(schema_path)
    metadata = dict(previous)
    metadata.update(
        {
            "layer": schema_layer,
            "schema_layer": schema_layer,
            "changelog_latest_layer": previous.get("changelog_latest_layer"),
            "canonical_source": previous.get("canonical_source", "tdlib"),
            "source_url": previous.get("source_url", _SOURCE_SCHEMA_URL),
            "schema_source_url": previous.get("schema_source_url", _SOURCE_SCHEMA_URL),
            "structural_source_url": previous.get("structural_source_url", _SOURCE_SCHEMA_URL),
            "layer_source_url": previous.get("layer_source_url", _SOURCE_LAYER_URL),
            "schema_doc_url": previous.get("schema_doc_url", _SOURCE_SCHEMA_DOC_URL),
            "source_note": previous.get(
                "source_note",
                "Canonical structure is the pinned TDLib TL schema; the layer comes from the matching Telegram Desktop end-of-file marker.",
            ),
            "documentation_merge_precedence": previous.get(
                "documentation_merge_precedence", ["tdlib", "tdesktop", "core_json"]
            ),
            "fetch_date": previous.get("fetch_date", "unknown"),
            "sha256": schema_sha256,
            "schema_sha256": schema_sha256,
            "schema_json_sha256": schema_sha256 if schema_format == "json" else previous.get("schema_json_sha256"),
            "schema_tl_sha256": previous.get("schema_tl_sha256"),
            "schema_tl_source_kind": previous.get("schema_tl_source_kind"),
            "schema_format": schema_format,
            "generator_version": _GENERATOR_VERSION,
            "constructor_count": len(schema.constructors),
            "function_count": len(schema.functions),
            "rpc_error_source_url": _SOURCE_ERRORS_URL,
            "rpc_error_download_url": previous.get("rpc_error_download_url", _SOURCE_ERRORS_DOWNLOAD_URL),
            "rpc_error_layer": rpc_error_layer,
            "rpc_error_sha256": _sha256_file(errors_path),
            "rpc_error_count": error_count,
            "changelog_source_url": previous.get("changelog_source_url", _SOURCE_CHANGELOG_URL),
            "generated_file_manifest": list(_MANIFEST),
        }
    )
    return metadata


def _render_base(metadata: Mapping[str, Any]) -> str:
    return (
        _HEADER
        + f"""from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass
from typing import Any, ClassVar, Self

RAW_API_LAYER = {int(metadata["schema_layer"])}


@dataclass(frozen=True, slots=True)
class TLField:
    name: str
    python_name: str
    type: str
    flag: str | None = None
    flag_index: int | None = None
    is_optional: bool = False
    is_true_flag: bool = False
    is_vector: bool = False
    vector_item_type: str | None = None


@dataclass(frozen=True, slots=True)
class TLFlagGroup:
    name: str
    python_name: str
    before_field_index: int


class TLObject:
    CONSTRUCTOR_ID: ClassVar[int]
    QUALNAME: ClassVar[str]
    RESULT_TYPE: ClassVar[str]
    TL_FIELDS: ClassVar[tuple[TLField, ...]] = ()
    TL_FLAG_GROUPS: ClassVar[tuple[TLFlagGroup, ...]] = ()

    def serialize(self) -> bytes:
        from miniproto.tl.codec import serialize_object

        return serialize_object(self)

    @classmethod
    def deserialize(cls, data: bytes | memoryview) -> Self:
        from miniproto.tl.codec import TLCodecError, deserialize_object

        obj, offset = deserialize_object(cls, data)
        if offset != len(data):
            raise TLCodecError("TL object payload has trailing bytes")
        return obj

    def to_raw_dict(self) -> dict[str, Any]:
        return {{field.name: getattr(self, field.python_name) for field in self.TL_FIELDS}}


class TLConstructor(TLObject):
    pass


class TLRequest(TLObject):
    pass


def constructor_id_map(entries: tuple[type[TLObject], ...]) -> Mapping[int, type[TLObject]]:
    return {{entry.CONSTRUCTOR_ID: entry for entry in entries}}
"""
    )


def _render_entries_module(
    entries: Sequence[Any], *, module_kind: str, fast_directions: Mapping[int, frozenset[str]]
) -> str:
    base_class = "TLConstructor" if module_kind == "types" else "TLRequest"
    base_import = (
        "TLConstructor, TLField, TLFlagGroup"
        if base_class == "TLConstructor"
        else f"TLField, TLFlagGroup, {base_class}"
    )
    lines: list[str] = [
        _HEADER.rstrip(),
        "from __future__ import annotations",
        "",
        "from dataclasses import dataclass",
        "from typing import Any, ClassVar, Self, cast",
        "",
        f"from miniproto.raw.base import {base_import}",
        "from miniproto.tl.codec import (",
        "    TLCodecError,",
        "    decode_bool,",
        "    decode_bytes,",
        "    decode_constructor_id,",
        "    decode_double,",
        "    decode_int,",
        "    decode_int128,",
        "    decode_int256,",
        "    decode_long,",
        "    decode_object,",
        "    decode_string,",
        "    decode_value,",
        "    decode_vector,",
        "    encode_bool,",
        "    encode_bytes,",
        "    encode_constructor_id,",
        "    encode_double,",
        "    encode_int,",
        "    encode_int128,",
        "    encode_int256,",
        "    encode_long,",
        "    encode_string,",
        "    encode_value,",
        "    encode_vector,",
        ")",
    ]
    if any(entry.constructor_id in fast_directions for entry in entries):
        lines.extend(["from miniproto.tl.fast import decode_fast, encode_fast, materialize_empty_object"])
    lines.extend(["", ""])
    for entry in entries:
        fields = iter_public_params(entry.params)
        lines.extend(
            ["@dataclass(frozen=True, slots=True, kw_only=True)", f"class {entry.python_class_name}({base_class}):"]
        )
        if fields:
            for field in fields:
                lines.append(_field_line(field))
        else:
            lines.append("    pass")
        lines.extend(
            [
                f"    CONSTRUCTOR_ID: ClassVar[int] = 0x{entry.constructor_id_hex}",
                f"    QUALNAME: ClassVar[str] = {entry.name!r}",
                f"    RESULT_TYPE: ClassVar[str] = {entry.result_type!r}",
                f"    TL_FIELDS: ClassVar[tuple[TLField, ...]] = {_fields_tuple(fields)}",
                f"    TL_FLAG_GROUPS: ClassVar[tuple[TLFlagGroup, ...]] = {_flag_groups_tuple(entry.params)}",
                "",
                *_codec_methods(
                    fields, entry.params, fast_directions=fast_directions.get(entry.constructor_id, frozenset())
                ),
                "",
                "",
            ]
        )
    all_class_names = [entry.python_class_name for entry in entries]
    namespace_lines, namespace_names = _namespace_classes(entries)
    lines.extend(namespace_lines)
    all_names = all_class_names + namespace_names + ["CONSTRUCTOR_ID_MAP", "NAME_MAP"]
    lines.append(f"ALL_{module_kind.upper()}: tuple[type[{base_class}], ...] = (")
    for name in all_class_names:
        lines.append(f"    {name},")
    lines.append(")")
    lines.append(
        f"CONSTRUCTOR_ID_MAP: dict[int, type[{base_class}]] = {{entry.CONSTRUCTOR_ID: entry for entry in ALL_{module_kind.upper()}}}"
    )
    lines.append(
        f"NAME_MAP: dict[str, type[{base_class}]] = {{entry.QUALNAME: entry for entry in ALL_{module_kind.upper()}}}"
    )
    lines.append(f"__all__ = {tuple(all_names)!r}")
    lines.append("")
    return "\n".join(lines)


def _field_line(field: TLParameter) -> str:
    annotation = _annotation(field)
    if field.is_true_flag:
        return f"    {field.python_name}: bool = False"
    if field.is_optional:
        return f"    {field.python_name}: {annotation} | None = None"
    return f"    {field.python_name}: {annotation}"


def _annotation(field: TLParameter) -> str:
    if field.is_vector:
        return f"tuple[{_single_annotation(field.vector_item_type or 'object')}, ...]"
    return _single_annotation(field.type)


def _single_annotation(type_name: str) -> str:
    clean = type_name.removeprefix("!")
    match clean:
        case "int" | "long" | "int128" | "int256":
            return "int"
        case "double":
            return "float"
        case "string":
            return "str"
        case "bytes":
            return "bytes"
        case "Bool" | "bool" | "true":
            return "bool"
        case "X" | "Type" | "#":
            return "Any"
        case _:
            return "Any"


def _fields_tuple(fields: Sequence[TLParameter]) -> str:
    if not fields:
        return "()"
    lines = ["("]
    for field in fields:
        lines.extend(
            [
                "    TLField(",
                f"        name={field.name!r},",
                f"        python_name={field.python_name!r},",
                f"        type={field.type!r},",
                f"        flag={field.flag!r},",
                f"        flag_index={field.flag_index!r},",
                f"        is_optional={field.is_optional!r},",
                f"        is_true_flag={field.is_true_flag!r},",
                f"        is_vector={field.is_vector!r},",
                f"        vector_item_type={field.vector_item_type!r},",
                "    ),",
            ]
        )
    lines.append(")")
    return "\n".join(lines)


def _flag_groups_tuple(params: Sequence[TLParameter]) -> str:
    groups: list[tuple[str, str, int]] = []
    public_index = 0
    for param in params:
        if param.is_flags_marker:
            groups.append((param.name, param.python_name, public_index))
        elif not param.is_template and not param.is_bare:
            public_index += 1
    if not groups:
        return "()"
    lines = ["("]
    for name, python_name, before_field_index in groups:
        lines.extend(
            [
                "    TLFlagGroup(",
                f"        name={name!r},",
                f"        python_name={python_name!r},",
                f"        before_field_index={before_field_index!r},",
                "    ),",
            ]
        )
    lines.append(")")
    return "\n".join(lines)


def _codec_methods(
    fields: Sequence[TLParameter], params: Sequence[TLParameter], *, fast_directions: frozenset[str]
) -> list[str]:
    lines: list[str] = [
        "    def serialize(self) -> bytes:",
        "        return self._serialize(boxed=True)",
        "",
        "    def _serialize(self, *, boxed: bool = True) -> bytes:",
    ]
    if "encode" in fast_directions:
        values = ", ".join(_fast_encode_value(field) for field in fields)
        tuple_suffix = "," if len(fields) == 1 else ""
        lines.extend(
            [
                f"        native = encode_fast(self.CONSTRUCTOR_ID, ({values}{tuple_suffix}), boxed=boxed)",
                "        if native is not None:",
                "            return native",
            ]
        )
    lines.extend(
        [
            "        output = bytearray()",
            "        if boxed:",
            "            output.extend(encode_constructor_id(self.CONSTRUCTOR_ID))",
        ]
    )
    flag_groups = _flag_group_specs(params)
    for _name, python_name, _before_field_index in flag_groups:
        lines.append(f"        {python_name} = 0")
    for field in fields:
        if not field.is_optional or field.flag is None or field.flag_index is None:
            continue
        flag_var = _flag_var(field, flag_groups)
        if field.is_true_flag:
            lines.extend(
                [f"        if self.{field.python_name}:", f"            {flag_var} |= {1 << field.flag_index}"]
            )
        else:
            lines.extend(
                [
                    f"        if self.{field.python_name} is not None:",
                    f"            {flag_var} |= {1 << field.flag_index}",
                ]
            )
    groups_by_index = _flag_groups_by_index(flag_groups)
    for index, field in enumerate(fields):
        for _name, python_name, _before_field_index in groups_by_index.get(index, ()):
            lines.append(f"        output.extend(encode_int({python_name}))")
        if field.is_optional:
            if field.is_true_flag:
                continue
            lines.extend(
                [
                    f"        if self.{field.python_name} is not None:",
                    f"            output.extend({_encode_expr(field, f'self.{field.python_name}')})",
                ]
            )
        else:
            lines.append(f"        output.extend({_encode_expr(field, f'self.{field.python_name}')})")
    for _name, python_name, _before_field_index in groups_by_index.get(len(fields), ()):
        lines.append(f"        output.extend(encode_int({python_name}))")
    lines.extend(
        [
            "        return bytes(output)",
            "",
            "    @classmethod",
            "    def deserialize(cls, data: bytes | memoryview) -> Self:",
            "        obj, offset = cls._deserialize(data)",
            "        if offset != len(data):",
            "            raise TLCodecError('TL object payload has trailing bytes')",
            "        return obj",
            "",
            "    @classmethod",
            "    def _deserialize(",
            "        cls, data: bytes | memoryview, offset: int = 0, *, boxed: bool = True",
            "    ) -> tuple[Self, int]:",
            "        raw_data = data",
        ]
    )
    if "decode" in fast_directions:
        lines.extend(
            [
                "        try:",
                "            native = decode_fast(cls.CONSTRUCTOR_ID, raw_data, offset, boxed=boxed)",
                "        except ValueError as exc:",
                "            if str(exc).startswith('expected constructor '):",
                "                raise TLCodecError(str(exc)) from exc",
                "            raise",
                "        if native is not None:",
                "            values, cursor = native",
                "            return cls(",
            ]
        )
        for index, field in enumerate(fields):
            lines.append(f"                {field.python_name}={_fast_decode_value(field, index)},")
        lines.extend(["            ), cursor"])
    lines.extend(
        [
            "        cursor = offset",
            "        if boxed:",
            "            constructor_id, cursor = decode_constructor_id(raw_data, cursor)",
            "            if constructor_id != cls.CONSTRUCTOR_ID:",
            "                raise TLCodecError(",
            "                    f'expected constructor 0x{cls.CONSTRUCTOR_ID:08x}, got 0x{constructor_id:08x}'",
            "                )",
        ]
    )
    for _name, python_name, _before_field_index in flag_groups:
        lines.append(f"        {python_name} = 0")
    for index, field in enumerate(fields):
        for _name, python_name, _before_field_index in groups_by_index.get(index, ()):
            lines.append(f"        {python_name}, cursor = decode_int(raw_data, cursor)")
        field_var = _field_value_var(field)
        if field.is_optional:
            flag_var = _flag_var(field, flag_groups)
            present_expr = f"bool({flag_var} & {1 << int(field.flag_index or 0)})"
            if field.is_true_flag:
                lines.append(f"        {field_var} = {present_expr}")
                continue
            lines.extend(
                [
                    f"        if {present_expr}:",
                    f"            {field_var}, cursor = {_decode_expr(field)}",
                    "        else:",
                    f"            {field_var} = None",
                ]
            )
        else:
            lines.append(f"        {field_var}, cursor = {_decode_expr(field)}")
    for _name, python_name, _before_field_index in groups_by_index.get(len(fields), ()):
        lines.append(f"        {python_name}, cursor = decode_int(raw_data, cursor)")
    if fields:
        lines.append("        return cls(")
        for field in fields:
            lines.append(f"            {field.python_name}={_field_value_var(field)},")
        lines.extend(["        ), cursor"])
    else:
        lines.append("        return cls(), cursor")
    return lines


def _fast_encode_value(field: TLParameter) -> str:
    value = f"self.{field.python_name}"
    clean = field.type.removeprefix("!")
    if field.is_true_flag or field.is_vector or clean in {"int", "long", "bytes", "string"}:
        return value
    return f"encode_value({field.type!r}, {value})"


def _fast_decode_value(field: TLParameter, index: int) -> str:
    if field.type.removeprefix("!") == "storage.FileType":
        return f"materialize_empty_object(values[{index}])"
    return f"cast({_annotation(field)}, values[{index}])"


def _flag_group_specs(params: Sequence[TLParameter]) -> list[tuple[str, str, int]]:
    groups: list[tuple[str, str, int]] = []
    public_index = 0
    for param in params:
        if param.is_flags_marker:
            groups.append((param.name, param.python_name, public_index))
        elif not param.is_template and not param.is_bare:
            public_index += 1
    return groups


def _flag_groups_by_index(groups: Sequence[tuple[str, str, int]]) -> dict[int, tuple[tuple[str, str, int], ...]]:
    grouped: dict[int, list[tuple[str, str, int]]] = {}
    for group in groups:
        grouped.setdefault(group[2], []).append(group)
    return {index: tuple(items) for index, items in grouped.items()}


def _flag_var(field: TLParameter, groups: Sequence[tuple[str, str, int]]) -> str:
    for name, python_name, _before_field_index in groups:
        if name == field.flag:
            return python_name
    return str(field.flag)


def _field_value_var(field: TLParameter) -> str:
    return f"_value_{field.python_name}"


def _encode_expr(field: TLParameter, value_expr: str) -> str:
    if field.is_vector:
        return f"encode_vector({value_expr}, {field.vector_item_type!r})"
    match field.type:
        case "int" | "#":
            return f"encode_int({value_expr})"
        case "long":
            return f"encode_long({value_expr})"
        case "int128":
            return f"encode_int128({value_expr})"
        case "int256":
            return f"encode_int256({value_expr})"
        case "double":
            return f"encode_double({value_expr})"
        case "bytes":
            return f"encode_bytes({value_expr})"
        case "string":
            return f"encode_string({value_expr})"
        case "Bool" | "bool":
            return f"encode_bool({value_expr})"
        case "true":
            return "b''"
        case _:
            return f"encode_value({field.type!r}, {value_expr})"


def _decode_expr(field: TLParameter) -> str:
    if field.is_vector:
        return f"decode_vector(raw_data, cursor, {field.vector_item_type!r})"
    match field.type:
        case "int" | "#":
            return "decode_int(raw_data, cursor)"
        case "long":
            return "decode_long(raw_data, cursor)"
        case "int128":
            return "decode_int128(raw_data, cursor)"
        case "int256":
            return "decode_int256(raw_data, cursor)"
        case "double":
            return "decode_double(raw_data, cursor)"
        case "bytes":
            return "decode_bytes(raw_data, cursor)"
        case "string":
            return "decode_string(raw_data, cursor)"
        case "Bool" | "bool":
            return "decode_bool(raw_data, cursor)"
        case "true":
            return "True, cursor"
        case _:
            return f"decode_value({field.type!r}, raw_data, cursor)"


def _namespace_classes(entries: Sequence[Any]) -> tuple[list[str], list[str]]:
    namespaces: dict[str, list[Any]] = {}
    for entry in entries:
        if entry.namespace is not None:
            namespaces.setdefault(entry.namespace, []).append(entry)
    lines: list[str] = []
    namespace_names: list[str] = []
    for namespace in sorted(namespaces):
        class_name = namespace.replace(".", "_")
        namespace_names.append(class_name)
        lines.append(f"class {class_name}:")
        for entry in sorted(namespaces[namespace], key=lambda item: item.short_name):
            lines.append(f"    {_short_class_name(entry.short_name)} = {entry.python_class_name}")
        lines.extend(["", ""])
    return lines, namespace_names


def _short_class_name(short_name: str) -> str:
    import re

    parts = re.sub(r"([a-z0-9])([A-Z])", r"\1 \2", short_name).replace("_", " ").split()
    return "".join(part[:1].upper() + part[1:] for part in parts)


def _render_errors(database: Mapping[str, Any]) -> str:
    errors = database.get("errors", {})
    descriptions = database.get("descriptions", {})
    specs: list[tuple[str, int, tuple[str, ...], str]] = []
    for code, named_errors in sorted(errors.items(), key=lambda item: int(item[0])):
        for name, methods in sorted(named_errors.items()):
            specs.append((name, int(code), tuple(sorted(methods)), str(descriptions.get(name, ""))))
    method_map: dict[str, list[str]] = {}
    for name, _code, methods, _description in specs:
        for method in methods:
            method_map.setdefault(method, []).append(name)
    lines: list[str] = [
        _HEADER.rstrip(),
        "from __future__ import annotations",
        "",
        "from dataclasses import dataclass",
        "",
        "",
        "@dataclass(frozen=True, slots=True)",
        "class RawRPCErrorSpec:",
        "    name: str",
        "    code: int",
        "    methods: tuple[str, ...] = ()",
        "    description: str = ''",
        "",
        "",
        "RPC_ERROR_MAP: dict[tuple[str, int], RawRPCErrorSpec] = {",
    ]
    for name, code, methods, description in specs:
        lines.extend(
            [
                f"    ({name!r}, {code!r}): RawRPCErrorSpec(",
                f"        name={name!r},",
                f"        code={code!r},",
                "        methods=",
                _tuple_literal(methods, indent="        ") + ",",
                f"        description={description!r},",
                "    ),",
            ]
        )
    lines.extend(["}", "CODE_TO_ERROR_NAMES: dict[int, tuple[str, ...]] = {"])
    for code in sorted({code for _name, code, _methods, _description in specs}):
        names = tuple(name for name, item_code, _methods, _description in specs if item_code == code)
        lines.append(f"    {code!r}: {_tuple_literal(names, indent='    ')},")
    lines.extend(["}", "METHOD_TO_ERROR_NAMES: dict[str, tuple[str, ...]] = {"])
    for method in sorted(method_map):
        lines.append(f"    {method!r}: {_tuple_literal(tuple(sorted(set(method_map[method]))), indent='    ')},")
    lines.extend(
        [
            "}",
            "",
            "",
            "def rpc_error_for_name(name: str, code: int | None = None) -> RawRPCErrorSpec | None:",
            "    if code is not None:",
            "        return RPC_ERROR_MAP.get((name, code))",
            "    matches = sorted(",
            "        (error for (error_name, _code), error in RPC_ERROR_MAP.items() if error_name == name),",
            "        key=lambda error: error.code,",
            "    )",
            "    return matches[0] if matches else None",
            "",
            "",
            "def rpc_errors_for_name(name: str) -> tuple[RawRPCErrorSpec, ...]:",
            "    return tuple(",
            "        sorted(",
            "            (error for (error_name, _code), error in RPC_ERROR_MAP.items() if error_name == name),",
            "            key=lambda error: error.code,",
            "        )",
            "    )",
            "",
            "",
            "__all__ = (",
            "    'CODE_TO_ERROR_NAMES',",
            "    'METHOD_TO_ERROR_NAMES',",
            "    'RPC_ERROR_MAP',",
            "    'RawRPCErrorSpec',",
            "    'rpc_error_for_name',",
            "    'rpc_errors_for_name',",
            ")",
            "",
        ]
    )
    return "\n".join(lines)


def _tuple_literal(values: Sequence[str], *, indent: str) -> str:
    if not values:
        return "()"
    if len(values) == 1:
        return f"({values[0]!r},)"
    inner = ["("]
    inner.extend(f"{indent}    {value!r}," for value in values)
    inner.append(f"{indent})")
    return "\n".join(inner)


def _render_docs(metadata: Mapping[str, Any], schema: TLSchema, database: Mapping[str, Any]) -> str:
    sample_functions = ", ".join(entry.name for entry in schema.functions[:8])
    sample_types = ", ".join(entry.name for entry in schema.constructors[:8])
    rpc_error_layer = metadata.get("rpc_error_layer", "unknown")
    changelog_latest_layer = metadata.get("changelog_latest_layer", "unknown")
    structural_source_url = metadata.get("structural_source_url", metadata["source_url"])
    layer_source_url = metadata.get("layer_source_url", _SOURCE_LAYER_URL)
    schema_doc_url = metadata.get("schema_doc_url", _SOURCE_SCHEMA_DOC_URL)
    source_comparison_docs = _render_source_comparison_docs(metadata)
    return f"""# Raw API

Status: generated Telegram Schema Layer {metadata["schema_layer"]} surface with implemented runtime transport support and lazy raw loading.

## Source

The raw API structure is generated from the [TDLib canonical TL schema]({structural_source_url}), pinned verbatim at `tools/schema/schema.tl` with SHA-256 `{metadata["schema_tl_sha256"]}`. Its deterministic normalized JSON model lives at `tools/schema/schema.json` with SHA-256 `{metadata["schema_json_sha256"]}`.

Schema Layer {metadata["schema_layer"]} comes only from the validated end-of-file marker in the matching [Telegram Desktop schema]({layer_source_url}). The independently pinned [core Telegram schema]({schema_doc_url}) may enrich documentation and exposes upstream drift, but it does not override TDLib structure.

## Source Compatibility

{source_comparison_docs}

RPC error metadata is generated from Telegram's error database linked from [{metadata["rpc_error_source_url"]}]({metadata["rpc_error_source_url"]}). The pinned JSON lives at `tools/schema/rpc-errors.json` with SHA-256 `{metadata["rpc_error_sha256"]}`.

## Generated Surface

- Constructors: {metadata["constructor_count"]}
- Functions: {metadata["function_count"]}
- RPC errors: {metadata["rpc_error_count"]}
- RPC errors layer: {rpc_error_layer}
- Latest changelog layer observed during update: {changelog_latest_layer}
- Generated files: {", ".join(metadata["generated_file_manifest"])}

## Usage Shape

```python
from miniproto.raw import functions

request = functions.help.GetConfig()
```

## Lazy Loading and Typing

Facade imports stay lightweight: they load generated facades and the registry, not implementation shards. Requested symbols load and cache their generated shard on first attribute, namespace, constructor-ID, or name-map lookup. Mapping and sequence iteration may realize classes as needed. The `.pyi` facades retain static type declarations. Update generated artifacts only through `uv run miniproto-schema-generate`.

## Current Runtime Scope

The runtime handles binary TL primitive encoding, generated object serialization/deserialization, flags, vectors, boxed constructors, RPC error metadata, gzip-packed payloads, message containers, transport framing, quick-ACK correlation, and RPC response correlation. A reviewed manifest selects 30 Layer 228 media and MTProto service constructors for generated Rust encode/decode paths; complete supported signatures take the native path, while every other constructor remains on the generic Python codec.

## Current Limits

Quick ACK is opt-in and confirms only early transport receipt, never RPC completion. No credentialed live Telegram trace has been run; deterministic framing, native/fallback parity, reconnect/resend, callback, and encrypted fake-server cases cover all three TCP modes.

## Samples

Early generated type constructors include: {sample_types}.

Early generated functions include: {sample_functions}.
"""


def _render_source_comparison_docs(metadata: Mapping[str, Any]) -> str:
    paragraphs = [
        "The complete deterministic declaration-level comparison is pinned at `tools/schema/schema-source-diff.json`."
    ]
    summary = metadata.get("source_comparison_summary")
    if not isinstance(summary, Mapping):
        return "\n\n".join(paragraphs)
    desktop = summary.get("tdlib_vs_tdesktop")
    if isinstance(desktop, Mapping):
        tdlib_only = desktop.get("tdlib_only", ())
        tdesktop_only = desktop.get("tdesktop_only", ())
        tdlib_only_count = len(tdlib_only)
        tdesktop_only_count = len(tdesktop_only)
        tdlib_names = ", ".join(f"`{name}`" for name in tdlib_only)
        tdesktop_names = ", ".join(f"`{name}`" for name in tdesktop_only)
        paragraph = (
            f"TDLib and Telegram Desktop overlap on {desktop.get('overlap_count', 'unknown')} declarations with "
            f"{desktop.get('changed_count', 'unknown')} structural differences. TDLib contributes {tdlib_only_count} additional {'declaration' if tdlib_only_count == 1 else 'declarations'}"
        )
        if tdlib_names:
            paragraph += f": {tdlib_names}"
        paragraph += f". Telegram Desktop contributes {tdesktop_only_count} {'declaration' if tdesktop_only_count == 1 else 'declarations'} absent from canonical TDLib"
        if tdesktop_names:
            paragraph += f": {tdesktop_names}"
        paragraph += "."
        if "null" in tdesktop_only:
            paragraph += f" Because `null` is absent from canonical TDLib, the previously generated `Null` class is intentionally absent from Layer {metadata.get('schema_layer', 'unknown')} outputs."
        paragraphs.append(paragraph)
    core = summary.get("tdlib_vs_core")
    if isinstance(core, Mapping):
        paragraphs.append(
            f"The supporting core schema overlaps on {core.get('overlap_count', 'unknown')} declarations, has {core.get('changed_count', 'unknown')} changed declarations, {core.get('tdlib_only_count', 'unknown')} TDLib-only declarations, and {core.get('core_only_count', 'unknown')} core-only declarations. These differences are drift evidence only."
        )
    return "\n\n".join(paragraphs)


def _load_rpc_error_database(path: Path) -> Mapping[str, Any]:
    if not path.exists():
        return {"errors": {}, "descriptions": {}}
    data = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(data, dict):
        raise TypeError("RPC error database must be a JSON object")
    return data


def _load_existing_metadata(path: Path) -> Mapping[str, Any]:
    if not path.exists():
        return {}
    data = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(data, dict):
        raise TypeError("schema metadata must be a JSON object")
    return data


def _sha256_file(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _json_document(data: Mapping[str, Any]) -> str:
    return json.dumps(data, indent=2, sort_keys=True) + "\n"


if __name__ == "__main__":
    raise SystemExit(main())
