# Generated by tools/schema/generate.py; do not edit by hand.
# Source: tools/schema/schema.json (normalized from the pinned canonical TL schema)
from __future__ import annotations

from dataclasses import dataclass
from typing import Any, ClassVar, Self, cast

from miniproto.raw.base import TLConstructor, TLField, TLFlagGroup
from miniproto.tl.codec import (
    TLCodecError,
    decode_bool,
    decode_bytes,
    decode_constructor_id,
    decode_double,
    decode_int,
    decode_int128,
    decode_int256,
    decode_long,
    decode_object,
    decode_string,
    decode_value,
    decode_vector,
    encode_bool,
    encode_bytes,
    encode_constructor_id,
    encode_double,
    encode_int,
    encode_int128,
    encode_int256,
    encode_long,
    encode_string,
    encode_value,
    encode_vector,
)


@dataclass(frozen=True, slots=True, kw_only=True)
class InputStickerSetThumbLegacy(TLConstructor):
    stickerset: Any
    volume_id: int
    local_id: int
    CONSTRUCTOR_ID: ClassVar[int] = 0x0DBAEAE9
    QUALNAME: ClassVar[str] = "inputStickerSetThumbLegacy"
    RESULT_TYPE: ClassVar[str] = "InputFileLocation"
    TL_FIELDS: ClassVar[tuple[TLField, ...]] = (
        TLField(
            name="stickerset",
            python_name="stickerset",
            type="InputStickerSet",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="volume_id",
            python_name="volume_id",
            type="long",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="local_id",
            python_name="local_id",
            type="int",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
    )
    TL_FLAG_GROUPS: ClassVar[tuple[TLFlagGroup, ...]] = ()

    def serialize(self) -> bytes:
        return self._serialize(boxed=True)

    def _serialize(self, *, boxed: bool = True) -> bytes:
        output = bytearray()
        if boxed:
            output.extend(encode_constructor_id(self.CONSTRUCTOR_ID))
        output.extend(encode_value("InputStickerSet", self.stickerset))
        output.extend(encode_long(self.volume_id))
        output.extend(encode_int(self.local_id))
        return bytes(output)

    @classmethod
    def deserialize(cls, data: bytes | memoryview) -> Self:
        obj, offset = cls._deserialize(data)
        if offset != len(data):
            raise TLCodecError("TL object payload has trailing bytes")
        return obj

    @classmethod
    def _deserialize(cls, data: bytes | memoryview, offset: int = 0, *, boxed: bool = True) -> tuple[Self, int]:
        raw_data = data
        cursor = offset
        if boxed:
            constructor_id, cursor = decode_constructor_id(raw_data, cursor)
            if constructor_id != cls.CONSTRUCTOR_ID:
                raise TLCodecError(f"expected constructor 0x{cls.CONSTRUCTOR_ID:08x}, got 0x{constructor_id:08x}")
        _value_stickerset, cursor = decode_value("InputStickerSet", raw_data, cursor)
        _value_volume_id, cursor = decode_long(raw_data, cursor)
        _value_local_id, cursor = decode_int(raw_data, cursor)
        return cls(stickerset=_value_stickerset, volume_id=_value_volume_id, local_id=_value_local_id), cursor


@dataclass(frozen=True, slots=True, kw_only=True)
class MessageActionChannelMigrateFrom(TLConstructor):
    title: str
    chat_id: int
    CONSTRUCTOR_ID: ClassVar[int] = 0xEA3948E9
    QUALNAME: ClassVar[str] = "messageActionChannelMigrateFrom"
    RESULT_TYPE: ClassVar[str] = "MessageAction"
    TL_FIELDS: ClassVar[tuple[TLField, ...]] = (
        TLField(
            name="title",
            python_name="title",
            type="string",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="chat_id",
            python_name="chat_id",
            type="long",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
    )
    TL_FLAG_GROUPS: ClassVar[tuple[TLFlagGroup, ...]] = ()

    def serialize(self) -> bytes:
        return self._serialize(boxed=True)

    def _serialize(self, *, boxed: bool = True) -> bytes:
        output = bytearray()
        if boxed:
            output.extend(encode_constructor_id(self.CONSTRUCTOR_ID))
        output.extend(encode_string(self.title))
        output.extend(encode_long(self.chat_id))
        return bytes(output)

    @classmethod
    def deserialize(cls, data: bytes | memoryview) -> Self:
        obj, offset = cls._deserialize(data)
        if offset != len(data):
            raise TLCodecError("TL object payload has trailing bytes")
        return obj

    @classmethod
    def _deserialize(cls, data: bytes | memoryview, offset: int = 0, *, boxed: bool = True) -> tuple[Self, int]:
        raw_data = data
        cursor = offset
        if boxed:
            constructor_id, cursor = decode_constructor_id(raw_data, cursor)
            if constructor_id != cls.CONSTRUCTOR_ID:
                raise TLCodecError(f"expected constructor 0x{cls.CONSTRUCTOR_ID:08x}, got 0x{constructor_id:08x}")
        _value_title, cursor = decode_string(raw_data, cursor)
        _value_chat_id, cursor = decode_long(raw_data, cursor)
        return cls(title=_value_title, chat_id=_value_chat_id), cursor


@dataclass(frozen=True, slots=True, kw_only=True)
class MessageActionSuggestedPostSuccess(TLConstructor):
    price: Any
    CONSTRUCTOR_ID: ClassVar[int] = 0x95DDCF69
    QUALNAME: ClassVar[str] = "messageActionSuggestedPostSuccess"
    RESULT_TYPE: ClassVar[str] = "MessageAction"
    TL_FIELDS: ClassVar[tuple[TLField, ...]] = (
        TLField(
            name="price",
            python_name="price",
            type="StarsAmount",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
    )
    TL_FLAG_GROUPS: ClassVar[tuple[TLFlagGroup, ...]] = ()

    def serialize(self) -> bytes:
        return self._serialize(boxed=True)

    def _serialize(self, *, boxed: bool = True) -> bytes:
        output = bytearray()
        if boxed:
            output.extend(encode_constructor_id(self.CONSTRUCTOR_ID))
        output.extend(encode_value("StarsAmount", self.price))
        return bytes(output)

    @classmethod
    def deserialize(cls, data: bytes | memoryview) -> Self:
        obj, offset = cls._deserialize(data)
        if offset != len(data):
            raise TLCodecError("TL object payload has trailing bytes")
        return obj

    @classmethod
    def _deserialize(cls, data: bytes | memoryview, offset: int = 0, *, boxed: bool = True) -> tuple[Self, int]:
        raw_data = data
        cursor = offset
        if boxed:
            constructor_id, cursor = decode_constructor_id(raw_data, cursor)
            if constructor_id != cls.CONSTRUCTOR_ID:
                raise TLCodecError(f"expected constructor 0x{cls.CONSTRUCTOR_ID:08x}, got 0x{constructor_id:08x}")
        _value_price, cursor = decode_value("StarsAmount", raw_data, cursor)
        return cls(price=_value_price), cursor


@dataclass(frozen=True, slots=True, kw_only=True)
class UpdateReadChannelOutbox(TLConstructor):
    channel_id: int
    max_id: int
    CONSTRUCTOR_ID: ClassVar[int] = 0xB75F99A9
    QUALNAME: ClassVar[str] = "updateReadChannelOutbox"
    RESULT_TYPE: ClassVar[str] = "Update"
    TL_FIELDS: ClassVar[tuple[TLField, ...]] = (
        TLField(
            name="channel_id",
            python_name="channel_id",
            type="long",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="max_id",
            python_name="max_id",
            type="int",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
    )
    TL_FLAG_GROUPS: ClassVar[tuple[TLFlagGroup, ...]] = ()

    def serialize(self) -> bytes:
        return self._serialize(boxed=True)

    def _serialize(self, *, boxed: bool = True) -> bytes:
        output = bytearray()
        if boxed:
            output.extend(encode_constructor_id(self.CONSTRUCTOR_ID))
        output.extend(encode_long(self.channel_id))
        output.extend(encode_int(self.max_id))
        return bytes(output)

    @classmethod
    def deserialize(cls, data: bytes | memoryview) -> Self:
        obj, offset = cls._deserialize(data)
        if offset != len(data):
            raise TLCodecError("TL object payload has trailing bytes")
        return obj

    @classmethod
    def _deserialize(cls, data: bytes | memoryview, offset: int = 0, *, boxed: bool = True) -> tuple[Self, int]:
        raw_data = data
        cursor = offset
        if boxed:
            constructor_id, cursor = decode_constructor_id(raw_data, cursor)
            if constructor_id != cls.CONSTRUCTOR_ID:
                raise TLCodecError(f"expected constructor 0x{cls.CONSTRUCTOR_ID:08x}, got 0x{constructor_id:08x}")
        _value_channel_id, cursor = decode_long(raw_data, cursor)
        _value_max_id, cursor = decode_int(raw_data, cursor)
        return cls(channel_id=_value_channel_id, max_id=_value_max_id), cursor


@dataclass(frozen=True, slots=True, kw_only=True)
class InputStickerSetID(TLConstructor):
    id: int
    access_hash: int
    CONSTRUCTOR_ID: ClassVar[int] = 0x9DE7A269
    QUALNAME: ClassVar[str] = "inputStickerSetID"
    RESULT_TYPE: ClassVar[str] = "InputStickerSet"
    TL_FIELDS: ClassVar[tuple[TLField, ...]] = (
        TLField(
            name="id",
            python_name="id",
            type="long",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="access_hash",
            python_name="access_hash",
            type="long",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
    )
    TL_FLAG_GROUPS: ClassVar[tuple[TLFlagGroup, ...]] = ()

    def serialize(self) -> bytes:
        return self._serialize(boxed=True)

    def _serialize(self, *, boxed: bool = True) -> bytes:
        output = bytearray()
        if boxed:
            output.extend(encode_constructor_id(self.CONSTRUCTOR_ID))
        output.extend(encode_long(self.id))
        output.extend(encode_long(self.access_hash))
        return bytes(output)

    @classmethod
    def deserialize(cls, data: bytes | memoryview) -> Self:
        obj, offset = cls._deserialize(data)
        if offset != len(data):
            raise TLCodecError("TL object payload has trailing bytes")
        return obj

    @classmethod
    def _deserialize(cls, data: bytes | memoryview, offset: int = 0, *, boxed: bool = True) -> tuple[Self, int]:
        raw_data = data
        cursor = offset
        if boxed:
            constructor_id, cursor = decode_constructor_id(raw_data, cursor)
            if constructor_id != cls.CONSTRUCTOR_ID:
                raise TLCodecError(f"expected constructor 0x{cls.CONSTRUCTOR_ID:08x}, got 0x{constructor_id:08x}")
        _value_id, cursor = decode_long(raw_data, cursor)
        _value_access_hash, cursor = decode_long(raw_data, cursor)
        return cls(id=_value_id, access_hash=_value_access_hash), cursor


@dataclass(frozen=True, slots=True, kw_only=True)
class InputStickerSetEmojiDefaultTopicIcons(TLConstructor):
    pass
    CONSTRUCTOR_ID: ClassVar[int] = 0x44C1F8E9
    QUALNAME: ClassVar[str] = "inputStickerSetEmojiDefaultTopicIcons"
    RESULT_TYPE: ClassVar[str] = "InputStickerSet"
    TL_FIELDS: ClassVar[tuple[TLField, ...]] = ()
    TL_FLAG_GROUPS: ClassVar[tuple[TLFlagGroup, ...]] = ()

    def serialize(self) -> bytes:
        return self._serialize(boxed=True)

    def _serialize(self, *, boxed: bool = True) -> bytes:
        output = bytearray()
        if boxed:
            output.extend(encode_constructor_id(self.CONSTRUCTOR_ID))
        return bytes(output)

    @classmethod
    def deserialize(cls, data: bytes | memoryview) -> Self:
        obj, offset = cls._deserialize(data)
        if offset != len(data):
            raise TLCodecError("TL object payload has trailing bytes")
        return obj

    @classmethod
    def _deserialize(cls, data: bytes | memoryview, offset: int = 0, *, boxed: bool = True) -> tuple[Self, int]:
        raw_data = data
        cursor = offset
        if boxed:
            constructor_id, cursor = decode_constructor_id(raw_data, cursor)
            if constructor_id != cls.CONSTRUCTOR_ID:
                raise TLCodecError(f"expected constructor 0x{cls.CONSTRUCTOR_ID:08x}, got 0x{constructor_id:08x}")
        return cls(), cursor


@dataclass(frozen=True, slots=True, kw_only=True)
class ChannelParticipantsAdmins(TLConstructor):
    pass
    CONSTRUCTOR_ID: ClassVar[int] = 0xB4608969
    QUALNAME: ClassVar[str] = "channelParticipantsAdmins"
    RESULT_TYPE: ClassVar[str] = "ChannelParticipantsFilter"
    TL_FIELDS: ClassVar[tuple[TLField, ...]] = ()
    TL_FLAG_GROUPS: ClassVar[tuple[TLFlagGroup, ...]] = ()

    def serialize(self) -> bytes:
        return self._serialize(boxed=True)

    def _serialize(self, *, boxed: bool = True) -> bytes:
        output = bytearray()
        if boxed:
            output.extend(encode_constructor_id(self.CONSTRUCTOR_ID))
        return bytes(output)

    @classmethod
    def deserialize(cls, data: bytes | memoryview) -> Self:
        obj, offset = cls._deserialize(data)
        if offset != len(data):
            raise TLCodecError("TL object payload has trailing bytes")
        return obj

    @classmethod
    def _deserialize(cls, data: bytes | memoryview, offset: int = 0, *, boxed: bool = True) -> tuple[Self, int]:
        raw_data = data
        cursor = offset
        if boxed:
            constructor_id, cursor = decode_constructor_id(raw_data, cursor)
            if constructor_id != cls.CONSTRUCTOR_ID:
                raise TLCodecError(f"expected constructor 0x{cls.CONSTRUCTOR_ID:08x}, got 0x{constructor_id:08x}")
        return cls(), cursor


@dataclass(frozen=True, slots=True, kw_only=True)
class ChannelsChannelParticipantsNotModified(TLConstructor):
    pass
    CONSTRUCTOR_ID: ClassVar[int] = 0xF0173FE9
    QUALNAME: ClassVar[str] = "channels.channelParticipantsNotModified"
    RESULT_TYPE: ClassVar[str] = "channels.ChannelParticipants"
    TL_FIELDS: ClassVar[tuple[TLField, ...]] = ()
    TL_FLAG_GROUPS: ClassVar[tuple[TLFlagGroup, ...]] = ()

    def serialize(self) -> bytes:
        return self._serialize(boxed=True)

    def _serialize(self, *, boxed: bool = True) -> bytes:
        output = bytearray()
        if boxed:
            output.extend(encode_constructor_id(self.CONSTRUCTOR_ID))
        return bytes(output)

    @classmethod
    def deserialize(cls, data: bytes | memoryview) -> Self:
        obj, offset = cls._deserialize(data)
        if offset != len(data):
            raise TLCodecError("TL object payload has trailing bytes")
        return obj

    @classmethod
    def _deserialize(cls, data: bytes | memoryview, offset: int = 0, *, boxed: bool = True) -> tuple[Self, int]:
        raw_data = data
        cursor = offset
        if boxed:
            constructor_id, cursor = decode_constructor_id(raw_data, cursor)
            if constructor_id != cls.CONSTRUCTOR_ID:
                raise TLCodecError(f"expected constructor 0x{cls.CONSTRUCTOR_ID:08x}, got 0x{constructor_id:08x}")
        return cls(), cursor


@dataclass(frozen=True, slots=True, kw_only=True)
class TopPeerCategoryForwardUsers(TLConstructor):
    pass
    CONSTRUCTOR_ID: ClassVar[int] = 0xA8406CA9
    QUALNAME: ClassVar[str] = "topPeerCategoryForwardUsers"
    RESULT_TYPE: ClassVar[str] = "TopPeerCategory"
    TL_FIELDS: ClassVar[tuple[TLField, ...]] = ()
    TL_FLAG_GROUPS: ClassVar[tuple[TLFlagGroup, ...]] = ()

    def serialize(self) -> bytes:
        return self._serialize(boxed=True)

    def _serialize(self, *, boxed: bool = True) -> bytes:
        output = bytearray()
        if boxed:
            output.extend(encode_constructor_id(self.CONSTRUCTOR_ID))
        return bytes(output)

    @classmethod
    def deserialize(cls, data: bytes | memoryview) -> Self:
        obj, offset = cls._deserialize(data)
        if offset != len(data):
            raise TLCodecError("TL object payload has trailing bytes")
        return obj

    @classmethod
    def _deserialize(cls, data: bytes | memoryview, offset: int = 0, *, boxed: bool = True) -> tuple[Self, int]:
        raw_data = data
        cursor = offset
        if boxed:
            constructor_id, cursor = decode_constructor_id(raw_data, cursor)
            if constructor_id != cls.CONSTRUCTOR_ID:
                raise TLCodecError(f"expected constructor 0x{cls.CONSTRUCTOR_ID:08x}, got 0x{constructor_id:08x}")
        return cls(), cursor


@dataclass(frozen=True, slots=True, kw_only=True)
class PageBlockHeading6(TLConstructor):
    text: Any
    CONSTRUCTOR_ID: ClassVar[int] = 0x682A41A9
    QUALNAME: ClassVar[str] = "pageBlockHeading6"
    RESULT_TYPE: ClassVar[str] = "PageBlock"
    TL_FIELDS: ClassVar[tuple[TLField, ...]] = (
        TLField(
            name="text",
            python_name="text",
            type="RichText",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
    )
    TL_FLAG_GROUPS: ClassVar[tuple[TLFlagGroup, ...]] = ()

    def serialize(self) -> bytes:
        return self._serialize(boxed=True)

    def _serialize(self, *, boxed: bool = True) -> bytes:
        output = bytearray()
        if boxed:
            output.extend(encode_constructor_id(self.CONSTRUCTOR_ID))
        output.extend(encode_value("RichText", self.text))
        return bytes(output)

    @classmethod
    def deserialize(cls, data: bytes | memoryview) -> Self:
        obj, offset = cls._deserialize(data)
        if offset != len(data):
            raise TLCodecError("TL object payload has trailing bytes")
        return obj

    @classmethod
    def _deserialize(cls, data: bytes | memoryview, offset: int = 0, *, boxed: bool = True) -> tuple[Self, int]:
        raw_data = data
        cursor = offset
        if boxed:
            constructor_id, cursor = decode_constructor_id(raw_data, cursor)
            if constructor_id != cls.CONSTRUCTOR_ID:
                raise TLCodecError(f"expected constructor 0x{cls.CONSTRUCTOR_ID:08x}, got 0x{constructor_id:08x}")
        _value_text, cursor = decode_value("RichText", raw_data, cursor)
        return cls(text=_value_text), cursor


@dataclass(frozen=True, slots=True, kw_only=True)
class ChannelAdminLogEventActionChangeUsernames(TLConstructor):
    prev_value: tuple[str, ...]
    new_value: tuple[str, ...]
    CONSTRUCTOR_ID: ClassVar[int] = 0xF04FB3A9
    QUALNAME: ClassVar[str] = "channelAdminLogEventActionChangeUsernames"
    RESULT_TYPE: ClassVar[str] = "ChannelAdminLogEventAction"
    TL_FIELDS: ClassVar[tuple[TLField, ...]] = (
        TLField(
            name="prev_value",
            python_name="prev_value",
            type="Vector<string>",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=True,
            vector_item_type="string",
        ),
        TLField(
            name="new_value",
            python_name="new_value",
            type="Vector<string>",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=True,
            vector_item_type="string",
        ),
    )
    TL_FLAG_GROUPS: ClassVar[tuple[TLFlagGroup, ...]] = ()

    def serialize(self) -> bytes:
        return self._serialize(boxed=True)

    def _serialize(self, *, boxed: bool = True) -> bytes:
        output = bytearray()
        if boxed:
            output.extend(encode_constructor_id(self.CONSTRUCTOR_ID))
        output.extend(encode_vector(self.prev_value, "string"))
        output.extend(encode_vector(self.new_value, "string"))
        return bytes(output)

    @classmethod
    def deserialize(cls, data: bytes | memoryview) -> Self:
        obj, offset = cls._deserialize(data)
        if offset != len(data):
            raise TLCodecError("TL object payload has trailing bytes")
        return obj

    @classmethod
    def _deserialize(cls, data: bytes | memoryview, offset: int = 0, *, boxed: bool = True) -> tuple[Self, int]:
        raw_data = data
        cursor = offset
        if boxed:
            constructor_id, cursor = decode_constructor_id(raw_data, cursor)
            if constructor_id != cls.CONSTRUCTOR_ID:
                raise TLCodecError(f"expected constructor 0x{cls.CONSTRUCTOR_ID:08x}, got 0x{constructor_id:08x}")
        _value_prev_value, cursor = decode_vector(raw_data, cursor, "string")
        _value_new_value, cursor = decode_vector(raw_data, cursor, "string")
        return cls(prev_value=_value_prev_value, new_value=_value_new_value), cursor


@dataclass(frozen=True, slots=True, kw_only=True)
class SecureValueErrorFiles(TLConstructor):
    type: Any
    file_hash: tuple[bytes, ...]
    text: str
    CONSTRUCTOR_ID: ClassVar[int] = 0x666220E9
    QUALNAME: ClassVar[str] = "secureValueErrorFiles"
    RESULT_TYPE: ClassVar[str] = "SecureValueError"
    TL_FIELDS: ClassVar[tuple[TLField, ...]] = (
        TLField(
            name="type",
            python_name="type",
            type="SecureValueType",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="file_hash",
            python_name="file_hash",
            type="Vector<bytes>",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=True,
            vector_item_type="bytes",
        ),
        TLField(
            name="text",
            python_name="text",
            type="string",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
    )
    TL_FLAG_GROUPS: ClassVar[tuple[TLFlagGroup, ...]] = ()

    def serialize(self) -> bytes:
        return self._serialize(boxed=True)

    def _serialize(self, *, boxed: bool = True) -> bytes:
        output = bytearray()
        if boxed:
            output.extend(encode_constructor_id(self.CONSTRUCTOR_ID))
        output.extend(encode_value("SecureValueType", self.type))
        output.extend(encode_vector(self.file_hash, "bytes"))
        output.extend(encode_string(self.text))
        return bytes(output)

    @classmethod
    def deserialize(cls, data: bytes | memoryview) -> Self:
        obj, offset = cls._deserialize(data)
        if offset != len(data):
            raise TLCodecError("TL object payload has trailing bytes")
        return obj

    @classmethod
    def _deserialize(cls, data: bytes | memoryview, offset: int = 0, *, boxed: bool = True) -> tuple[Self, int]:
        raw_data = data
        cursor = offset
        if boxed:
            constructor_id, cursor = decode_constructor_id(raw_data, cursor)
            if constructor_id != cls.CONSTRUCTOR_ID:
                raise TLCodecError(f"expected constructor 0x{cls.CONSTRUCTOR_ID:08x}, got 0x{constructor_id:08x}")
        _value_type, cursor = decode_value("SecureValueType", raw_data, cursor)
        _value_file_hash, cursor = decode_vector(raw_data, cursor, "bytes")
        _value_text, cursor = decode_string(raw_data, cursor)
        return cls(type=_value_type, file_hash=_value_file_hash, text=_value_text), cursor


@dataclass(frozen=True, slots=True, kw_only=True)
class InputTheme(TLConstructor):
    id: int
    access_hash: int
    CONSTRUCTOR_ID: ClassVar[int] = 0x3C5693E9
    QUALNAME: ClassVar[str] = "inputTheme"
    RESULT_TYPE: ClassVar[str] = "InputTheme"
    TL_FIELDS: ClassVar[tuple[TLField, ...]] = (
        TLField(
            name="id",
            python_name="id",
            type="long",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="access_hash",
            python_name="access_hash",
            type="long",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
    )
    TL_FLAG_GROUPS: ClassVar[tuple[TLFlagGroup, ...]] = ()

    def serialize(self) -> bytes:
        return self._serialize(boxed=True)

    def _serialize(self, *, boxed: bool = True) -> bytes:
        output = bytearray()
        if boxed:
            output.extend(encode_constructor_id(self.CONSTRUCTOR_ID))
        output.extend(encode_long(self.id))
        output.extend(encode_long(self.access_hash))
        return bytes(output)

    @classmethod
    def deserialize(cls, data: bytes | memoryview) -> Self:
        obj, offset = cls._deserialize(data)
        if offset != len(data):
            raise TLCodecError("TL object payload has trailing bytes")
        return obj

    @classmethod
    def _deserialize(cls, data: bytes | memoryview, offset: int = 0, *, boxed: bool = True) -> tuple[Self, int]:
        raw_data = data
        cursor = offset
        if boxed:
            constructor_id, cursor = decode_constructor_id(raw_data, cursor)
            if constructor_id != cls.CONSTRUCTOR_ID:
                raise TLCodecError(f"expected constructor 0x{cls.CONSTRUCTOR_ID:08x}, got 0x{constructor_id:08x}")
        _value_id, cursor = decode_long(raw_data, cursor)
        _value_access_hash, cursor = decode_long(raw_data, cursor)
        return cls(id=_value_id, access_hash=_value_access_hash), cursor


@dataclass(frozen=True, slots=True, kw_only=True)
class EmailVerificationCode(TLConstructor):
    code: str
    CONSTRUCTOR_ID: ClassVar[int] = 0x922E55A9
    QUALNAME: ClassVar[str] = "emailVerificationCode"
    RESULT_TYPE: ClassVar[str] = "EmailVerification"
    TL_FIELDS: ClassVar[tuple[TLField, ...]] = (
        TLField(
            name="code",
            python_name="code",
            type="string",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
    )
    TL_FLAG_GROUPS: ClassVar[tuple[TLFlagGroup, ...]] = ()

    def serialize(self) -> bytes:
        return self._serialize(boxed=True)

    def _serialize(self, *, boxed: bool = True) -> bytes:
        output = bytearray()
        if boxed:
            output.extend(encode_constructor_id(self.CONSTRUCTOR_ID))
        output.extend(encode_string(self.code))
        return bytes(output)

    @classmethod
    def deserialize(cls, data: bytes | memoryview) -> Self:
        obj, offset = cls._deserialize(data)
        if offset != len(data):
            raise TLCodecError("TL object payload has trailing bytes")
        return obj

    @classmethod
    def _deserialize(cls, data: bytes | memoryview, offset: int = 0, *, boxed: bool = True) -> tuple[Self, int]:
        raw_data = data
        cursor = offset
        if boxed:
            constructor_id, cursor = decode_constructor_id(raw_data, cursor)
            if constructor_id != cls.CONSTRUCTOR_ID:
                raise TLCodecError(f"expected constructor 0x{cls.CONSTRUCTOR_ID:08x}, got 0x{constructor_id:08x}")
        _value_code, cursor = decode_string(raw_data, cursor)
        return cls(code=_value_code), cursor


@dataclass(frozen=True, slots=True, kw_only=True)
class EmojiGroup(TLConstructor):
    title: str
    icon_emoji_id: int
    emoticons: tuple[str, ...]
    CONSTRUCTOR_ID: ClassVar[int] = 0x7A9ABDA9
    QUALNAME: ClassVar[str] = "emojiGroup"
    RESULT_TYPE: ClassVar[str] = "EmojiGroup"
    TL_FIELDS: ClassVar[tuple[TLField, ...]] = (
        TLField(
            name="title",
            python_name="title",
            type="string",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="icon_emoji_id",
            python_name="icon_emoji_id",
            type="long",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="emoticons",
            python_name="emoticons",
            type="Vector<string>",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=True,
            vector_item_type="string",
        ),
    )
    TL_FLAG_GROUPS: ClassVar[tuple[TLFlagGroup, ...]] = ()

    def serialize(self) -> bytes:
        return self._serialize(boxed=True)

    def _serialize(self, *, boxed: bool = True) -> bytes:
        output = bytearray()
        if boxed:
            output.extend(encode_constructor_id(self.CONSTRUCTOR_ID))
        output.extend(encode_string(self.title))
        output.extend(encode_long(self.icon_emoji_id))
        output.extend(encode_vector(self.emoticons, "string"))
        return bytes(output)

    @classmethod
    def deserialize(cls, data: bytes | memoryview) -> Self:
        obj, offset = cls._deserialize(data)
        if offset != len(data):
            raise TLCodecError("TL object payload has trailing bytes")
        return obj

    @classmethod
    def _deserialize(cls, data: bytes | memoryview, offset: int = 0, *, boxed: bool = True) -> tuple[Self, int]:
        raw_data = data
        cursor = offset
        if boxed:
            constructor_id, cursor = decode_constructor_id(raw_data, cursor)
            if constructor_id != cls.CONSTRUCTOR_ID:
                raise TLCodecError(f"expected constructor 0x{cls.CONSTRUCTOR_ID:08x}, got 0x{constructor_id:08x}")
        _value_title, cursor = decode_string(raw_data, cursor)
        _value_icon_emoji_id, cursor = decode_long(raw_data, cursor)
        _value_emoticons, cursor = decode_vector(raw_data, cursor, "string")
        return cls(title=_value_title, icon_emoji_id=_value_icon_emoji_id, emoticons=_value_emoticons), cursor


@dataclass(frozen=True, slots=True, kw_only=True)
class InputPeerColorCollectible(TLConstructor):
    collectible_id: int
    CONSTRUCTOR_ID: ClassVar[int] = 0xB8EA86A9
    QUALNAME: ClassVar[str] = "inputPeerColorCollectible"
    RESULT_TYPE: ClassVar[str] = "PeerColor"
    TL_FIELDS: ClassVar[tuple[TLField, ...]] = (
        TLField(
            name="collectible_id",
            python_name="collectible_id",
            type="long",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
    )
    TL_FLAG_GROUPS: ClassVar[tuple[TLFlagGroup, ...]] = ()

    def serialize(self) -> bytes:
        return self._serialize(boxed=True)

    def _serialize(self, *, boxed: bool = True) -> bytes:
        output = bytearray()
        if boxed:
            output.extend(encode_constructor_id(self.CONSTRUCTOR_ID))
        output.extend(encode_long(self.collectible_id))
        return bytes(output)

    @classmethod
    def deserialize(cls, data: bytes | memoryview) -> Self:
        obj, offset = cls._deserialize(data)
        if offset != len(data):
            raise TLCodecError("TL object payload has trailing bytes")
        return obj

    @classmethod
    def _deserialize(cls, data: bytes | memoryview, offset: int = 0, *, boxed: bool = True) -> tuple[Self, int]:
        raw_data = data
        cursor = offset
        if boxed:
            constructor_id, cursor = decode_constructor_id(raw_data, cursor)
            if constructor_id != cls.CONSTRUCTOR_ID:
                raise TLCodecError(f"expected constructor 0x{cls.CONSTRUCTOR_ID:08x}, got 0x{constructor_id:08x}")
        _value_collectible_id, cursor = decode_long(raw_data, cursor)
        return cls(collectible_id=_value_collectible_id), cursor


@dataclass(frozen=True, slots=True, kw_only=True)
class InputCollectibleUsername(TLConstructor):
    username: str
    CONSTRUCTOR_ID: ClassVar[int] = 0xE39460A9
    QUALNAME: ClassVar[str] = "inputCollectibleUsername"
    RESULT_TYPE: ClassVar[str] = "InputCollectible"
    TL_FIELDS: ClassVar[tuple[TLField, ...]] = (
        TLField(
            name="username",
            python_name="username",
            type="string",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
    )
    TL_FLAG_GROUPS: ClassVar[tuple[TLFlagGroup, ...]] = ()

    def serialize(self) -> bytes:
        return self._serialize(boxed=True)

    def _serialize(self, *, boxed: bool = True) -> bytes:
        output = bytearray()
        if boxed:
            output.extend(encode_constructor_id(self.CONSTRUCTOR_ID))
        output.extend(encode_string(self.username))
        return bytes(output)

    @classmethod
    def deserialize(cls, data: bytes | memoryview) -> Self:
        obj, offset = cls._deserialize(data)
        if offset != len(data):
            raise TLCodecError("TL object payload has trailing bytes")
        return obj

    @classmethod
    def _deserialize(cls, data: bytes | memoryview, offset: int = 0, *, boxed: bool = True) -> tuple[Self, int]:
        raw_data = data
        cursor = offset
        if boxed:
            constructor_id, cursor = decode_constructor_id(raw_data, cursor)
            if constructor_id != cls.CONSTRUCTOR_ID:
                raise TLCodecError(f"expected constructor 0x{cls.CONSTRUCTOR_ID:08x}, got 0x{constructor_id:08x}")
        _value_username, cursor = decode_string(raw_data, cursor)
        return cls(username=_value_username), cursor


@dataclass(frozen=True, slots=True, kw_only=True)
class RequirementToContactPremium(TLConstructor):
    pass
    CONSTRUCTOR_ID: ClassVar[int] = 0xE581E4E9
    QUALNAME: ClassVar[str] = "requirementToContactPremium"
    RESULT_TYPE: ClassVar[str] = "RequirementToContact"
    TL_FIELDS: ClassVar[tuple[TLField, ...]] = ()
    TL_FLAG_GROUPS: ClassVar[tuple[TLFlagGroup, ...]] = ()

    def serialize(self) -> bytes:
        return self._serialize(boxed=True)

    def _serialize(self, *, boxed: bool = True) -> bytes:
        output = bytearray()
        if boxed:
            output.extend(encode_constructor_id(self.CONSTRUCTOR_ID))
        return bytes(output)

    @classmethod
    def deserialize(cls, data: bytes | memoryview) -> Self:
        obj, offset = cls._deserialize(data)
        if offset != len(data):
            raise TLCodecError("TL object payload has trailing bytes")
        return obj

    @classmethod
    def _deserialize(cls, data: bytes | memoryview, offset: int = 0, *, boxed: bool = True) -> tuple[Self, int]:
        raw_data = data
        cursor = offset
        if boxed:
            constructor_id, cursor = decode_constructor_id(raw_data, cursor)
            if constructor_id != cls.CONSTRUCTOR_ID:
                raise TLCodecError(f"expected constructor 0x{cls.CONSTRUCTOR_ID:08x}, got 0x{constructor_id:08x}")
        return cls(), cursor


@dataclass(frozen=True, slots=True, kw_only=True)
class AiComposeTone(TLConstructor):
    creator: bool = False
    id: int
    access_hash: int
    slug: str
    title: str
    emoji_id: int | None = None
    prompt: str | None = None
    installs_count: int | None = None
    author_id: int | None = None
    example_english: Any | None = None
    CONSTRUCTOR_ID: ClassVar[int] = 0xCFF63EA9
    QUALNAME: ClassVar[str] = "aiComposeTone"
    RESULT_TYPE: ClassVar[str] = "AiComposeTone"
    TL_FIELDS: ClassVar[tuple[TLField, ...]] = (
        TLField(
            name="creator",
            python_name="creator",
            type="true",
            flag="flags",
            flag_index=0,
            is_optional=True,
            is_true_flag=True,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="id",
            python_name="id",
            type="long",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="access_hash",
            python_name="access_hash",
            type="long",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="slug",
            python_name="slug",
            type="string",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="title",
            python_name="title",
            type="string",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="emoji_id",
            python_name="emoji_id",
            type="long",
            flag="flags",
            flag_index=1,
            is_optional=True,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="prompt",
            python_name="prompt",
            type="string",
            flag="flags",
            flag_index=4,
            is_optional=True,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="installs_count",
            python_name="installs_count",
            type="int",
            flag="flags",
            flag_index=2,
            is_optional=True,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="author_id",
            python_name="author_id",
            type="long",
            flag="flags",
            flag_index=3,
            is_optional=True,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="example_english",
            python_name="example_english",
            type="AiComposeToneExample",
            flag="flags",
            flag_index=5,
            is_optional=True,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
    )
    TL_FLAG_GROUPS: ClassVar[tuple[TLFlagGroup, ...]] = (
        TLFlagGroup(name="flags", python_name="flags", before_field_index=0),
    )

    def serialize(self) -> bytes:
        return self._serialize(boxed=True)

    def _serialize(self, *, boxed: bool = True) -> bytes:
        output = bytearray()
        if boxed:
            output.extend(encode_constructor_id(self.CONSTRUCTOR_ID))
        flags = 0
        if self.creator:
            flags |= 1
        if self.emoji_id is not None:
            flags |= 2
        if self.prompt is not None:
            flags |= 16
        if self.installs_count is not None:
            flags |= 4
        if self.author_id is not None:
            flags |= 8
        if self.example_english is not None:
            flags |= 32
        output.extend(encode_int(flags))
        output.extend(encode_long(self.id))
        output.extend(encode_long(self.access_hash))
        output.extend(encode_string(self.slug))
        output.extend(encode_string(self.title))
        if self.emoji_id is not None:
            output.extend(encode_long(self.emoji_id))
        if self.prompt is not None:
            output.extend(encode_string(self.prompt))
        if self.installs_count is not None:
            output.extend(encode_int(self.installs_count))
        if self.author_id is not None:
            output.extend(encode_long(self.author_id))
        if self.example_english is not None:
            output.extend(encode_value("AiComposeToneExample", self.example_english))
        return bytes(output)

    @classmethod
    def deserialize(cls, data: bytes | memoryview) -> Self:
        obj, offset = cls._deserialize(data)
        if offset != len(data):
            raise TLCodecError("TL object payload has trailing bytes")
        return obj

    @classmethod
    def _deserialize(cls, data: bytes | memoryview, offset: int = 0, *, boxed: bool = True) -> tuple[Self, int]:
        raw_data = data
        cursor = offset
        if boxed:
            constructor_id, cursor = decode_constructor_id(raw_data, cursor)
            if constructor_id != cls.CONSTRUCTOR_ID:
                raise TLCodecError(f"expected constructor 0x{cls.CONSTRUCTOR_ID:08x}, got 0x{constructor_id:08x}")
        flags = 0
        flags, cursor = decode_int(raw_data, cursor)
        _value_creator = bool(flags & 1)
        _value_id, cursor = decode_long(raw_data, cursor)
        _value_access_hash, cursor = decode_long(raw_data, cursor)
        _value_slug, cursor = decode_string(raw_data, cursor)
        _value_title, cursor = decode_string(raw_data, cursor)
        if bool(flags & 2):
            _value_emoji_id, cursor = decode_long(raw_data, cursor)
        else:
            _value_emoji_id = None
        if bool(flags & 16):
            _value_prompt, cursor = decode_string(raw_data, cursor)
        else:
            _value_prompt = None
        if bool(flags & 4):
            _value_installs_count, cursor = decode_int(raw_data, cursor)
        else:
            _value_installs_count = None
        if bool(flags & 8):
            _value_author_id, cursor = decode_long(raw_data, cursor)
        else:
            _value_author_id = None
        if bool(flags & 32):
            _value_example_english, cursor = decode_value("AiComposeToneExample", raw_data, cursor)
        else:
            _value_example_english = None
        return cls(
            creator=_value_creator,
            id=_value_id,
            access_hash=_value_access_hash,
            slug=_value_slug,
            title=_value_title,
            emoji_id=_value_emoji_id,
            prompt=_value_prompt,
            installs_count=_value_installs_count,
            author_id=_value_author_id,
            example_english=_value_example_english,
        ), cursor


@dataclass(frozen=True, slots=True, kw_only=True)
class JoinChatBotResultApproved(TLConstructor):
    pass
    CONSTRUCTOR_ID: ClassVar[int] = 0xAE152A69
    QUALNAME: ClassVar[str] = "joinChatBotResultApproved"
    RESULT_TYPE: ClassVar[str] = "JoinChatBotResult"
    TL_FIELDS: ClassVar[tuple[TLField, ...]] = ()
    TL_FLAG_GROUPS: ClassVar[tuple[TLFlagGroup, ...]] = ()

    def serialize(self) -> bytes:
        return self._serialize(boxed=True)

    def _serialize(self, *, boxed: bool = True) -> bytes:
        output = bytearray()
        if boxed:
            output.extend(encode_constructor_id(self.CONSTRUCTOR_ID))
        return bytes(output)

    @classmethod
    def deserialize(cls, data: bytes | memoryview) -> Self:
        obj, offset = cls._deserialize(data)
        if offset != len(data):
            raise TLCodecError("TL object payload has trailing bytes")
        return obj

    @classmethod
    def _deserialize(cls, data: bytes | memoryview, offset: int = 0, *, boxed: bool = True) -> tuple[Self, int]:
        raw_data = data
        cursor = offset
        if boxed:
            constructor_id, cursor = decode_constructor_id(raw_data, cursor)
            if constructor_id != cls.CONSTRUCTOR_ID:
                raise TLCodecError(f"expected constructor 0x{cls.CONSTRUCTOR_ID:08x}, got 0x{constructor_id:08x}")
        return cls(), cursor


class channels:
    ChannelParticipantsNotModified = ChannelsChannelParticipantsNotModified


ALL_TYPES: tuple[type[TLConstructor], ...] = (
    InputStickerSetThumbLegacy,
    MessageActionChannelMigrateFrom,
    MessageActionSuggestedPostSuccess,
    UpdateReadChannelOutbox,
    InputStickerSetID,
    InputStickerSetEmojiDefaultTopicIcons,
    ChannelParticipantsAdmins,
    ChannelsChannelParticipantsNotModified,
    TopPeerCategoryForwardUsers,
    PageBlockHeading6,
    ChannelAdminLogEventActionChangeUsernames,
    SecureValueErrorFiles,
    InputTheme,
    EmailVerificationCode,
    EmojiGroup,
    InputPeerColorCollectible,
    InputCollectibleUsername,
    RequirementToContactPremium,
    AiComposeTone,
    JoinChatBotResultApproved,
)
CONSTRUCTOR_ID_MAP: dict[int, type[TLConstructor]] = {entry.CONSTRUCTOR_ID: entry for entry in ALL_TYPES}
NAME_MAP: dict[str, type[TLConstructor]] = {entry.QUALNAME: entry for entry in ALL_TYPES}
__all__ = (
    "InputStickerSetThumbLegacy",
    "MessageActionChannelMigrateFrom",
    "MessageActionSuggestedPostSuccess",
    "UpdateReadChannelOutbox",
    "InputStickerSetID",
    "InputStickerSetEmojiDefaultTopicIcons",
    "ChannelParticipantsAdmins",
    "ChannelsChannelParticipantsNotModified",
    "TopPeerCategoryForwardUsers",
    "PageBlockHeading6",
    "ChannelAdminLogEventActionChangeUsernames",
    "SecureValueErrorFiles",
    "InputTheme",
    "EmailVerificationCode",
    "EmojiGroup",
    "InputPeerColorCollectible",
    "InputCollectibleUsername",
    "RequirementToContactPremium",
    "AiComposeTone",
    "JoinChatBotResultApproved",
    "channels",
    "CONSTRUCTOR_ID_MAP",
    "NAME_MAP",
)
