# Generated by tools/schema/generate.py; do not edit by hand.
# Source: tools/schema/schema.json (normalized from the pinned canonical TL schema)
from __future__ import annotations

from dataclasses import dataclass
from typing import Any, ClassVar, Self

from miniproto.raw.base import TLConstructor, TLField, TLFlagGroup
from miniproto.tl.codec import (
    TLCodecError,
    decode_bool,
    decode_bytes,
    decode_constructor_id,
    decode_double,
    decode_int,
    decode_int128,
    decode_int256,
    decode_long,
    decode_object,
    decode_string,
    decode_value,
    decode_vector,
    encode_bool,
    encode_bytes,
    encode_constructor_id,
    encode_double,
    encode_int,
    encode_int128,
    encode_int256,
    encode_long,
    encode_string,
    encode_value,
    encode_vector,
)


@dataclass(frozen=True, slots=True, kw_only=True)
class InputFileStoryDocument(TLConstructor):
    id: Any
    CONSTRUCTOR_ID: ClassVar[int] = 0x62DC8B48
    QUALNAME: ClassVar[str] = "inputFileStoryDocument"
    RESULT_TYPE: ClassVar[str] = "InputFile"
    TL_FIELDS: ClassVar[tuple[TLField, ...]] = (
        TLField(
            name="id",
            python_name="id",
            type="InputDocument",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
    )
    TL_FLAG_GROUPS: ClassVar[tuple[TLFlagGroup, ...]] = ()

    def serialize(self) -> bytes:
        return self._serialize(boxed=True)

    def _serialize(self, *, boxed: bool = True) -> bytes:
        output = bytearray()
        if boxed:
            output.extend(encode_constructor_id(self.CONSTRUCTOR_ID))
        output.extend(encode_value("InputDocument", self.id))
        return bytes(output)

    @classmethod
    def deserialize(cls, data: bytes | memoryview) -> Self:
        obj, offset = cls._deserialize(data)
        if offset != len(data):
            raise TLCodecError("TL object payload has trailing bytes")
        return obj

    @classmethod
    def _deserialize(cls, data: bytes | memoryview, offset: int = 0, *, boxed: bool = True) -> tuple[Self, int]:
        raw_data = data
        cursor = offset
        if boxed:
            constructor_id, cursor = decode_constructor_id(raw_data, cursor)
            if constructor_id != cls.CONSTRUCTOR_ID:
                raise TLCodecError(f"expected constructor 0x{cls.CONSTRUCTOR_ID:08x}, got 0x{constructor_id:08x}")
        _value_id, cursor = decode_value("InputDocument", raw_data, cursor)
        return cls(id=_value_id), cursor


@dataclass(frozen=True, slots=True, kw_only=True)
class InputMediaPoll(TLConstructor):
    poll: Any
    correct_answers: tuple[int, ...] | None = None
    attached_media: Any | None = None
    solution: str | None = None
    solution_entities: tuple[Any, ...] | None = None
    solution_media: Any | None = None
    CONSTRUCTOR_ID: ClassVar[int] = 0x883A4108
    QUALNAME: ClassVar[str] = "inputMediaPoll"
    RESULT_TYPE: ClassVar[str] = "InputMedia"
    TL_FIELDS: ClassVar[tuple[TLField, ...]] = (
        TLField(
            name="poll",
            python_name="poll",
            type="Poll",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="correct_answers",
            python_name="correct_answers",
            type="Vector<int>",
            flag="flags",
            flag_index=0,
            is_optional=True,
            is_true_flag=False,
            is_vector=True,
            vector_item_type="int",
        ),
        TLField(
            name="attached_media",
            python_name="attached_media",
            type="InputMedia",
            flag="flags",
            flag_index=3,
            is_optional=True,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="solution",
            python_name="solution",
            type="string",
            flag="flags",
            flag_index=1,
            is_optional=True,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="solution_entities",
            python_name="solution_entities",
            type="Vector<MessageEntity>",
            flag="flags",
            flag_index=1,
            is_optional=True,
            is_true_flag=False,
            is_vector=True,
            vector_item_type="MessageEntity",
        ),
        TLField(
            name="solution_media",
            python_name="solution_media",
            type="InputMedia",
            flag="flags",
            flag_index=2,
            is_optional=True,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
    )
    TL_FLAG_GROUPS: ClassVar[tuple[TLFlagGroup, ...]] = (
        TLFlagGroup(name="flags", python_name="flags", before_field_index=0),
    )

    def serialize(self) -> bytes:
        return self._serialize(boxed=True)

    def _serialize(self, *, boxed: bool = True) -> bytes:
        output = bytearray()
        if boxed:
            output.extend(encode_constructor_id(self.CONSTRUCTOR_ID))
        flags = 0
        if self.correct_answers is not None:
            flags |= 1
        if self.attached_media is not None:
            flags |= 8
        if self.solution is not None:
            flags |= 2
        if self.solution_entities is not None:
            flags |= 2
        if self.solution_media is not None:
            flags |= 4
        output.extend(encode_int(flags))
        output.extend(encode_value("Poll", self.poll))
        if self.correct_answers is not None:
            output.extend(encode_vector(self.correct_answers, "int"))
        if self.attached_media is not None:
            output.extend(encode_value("InputMedia", self.attached_media))
        if self.solution is not None:
            output.extend(encode_string(self.solution))
        if self.solution_entities is not None:
            output.extend(encode_vector(self.solution_entities, "MessageEntity"))
        if self.solution_media is not None:
            output.extend(encode_value("InputMedia", self.solution_media))
        return bytes(output)

    @classmethod
    def deserialize(cls, data: bytes | memoryview) -> Self:
        obj, offset = cls._deserialize(data)
        if offset != len(data):
            raise TLCodecError("TL object payload has trailing bytes")
        return obj

    @classmethod
    def _deserialize(cls, data: bytes | memoryview, offset: int = 0, *, boxed: bool = True) -> tuple[Self, int]:
        raw_data = data
        cursor = offset
        if boxed:
            constructor_id, cursor = decode_constructor_id(raw_data, cursor)
            if constructor_id != cls.CONSTRUCTOR_ID:
                raise TLCodecError(f"expected constructor 0x{cls.CONSTRUCTOR_ID:08x}, got 0x{constructor_id:08x}")
        flags = 0
        flags, cursor = decode_int(raw_data, cursor)
        _value_poll, cursor = decode_value("Poll", raw_data, cursor)
        if bool(flags & 1):
            _value_correct_answers, cursor = decode_vector(raw_data, cursor, "int")
        else:
            _value_correct_answers = None
        if bool(flags & 8):
            _value_attached_media, cursor = decode_value("InputMedia", raw_data, cursor)
        else:
            _value_attached_media = None
        if bool(flags & 2):
            _value_solution, cursor = decode_string(raw_data, cursor)
        else:
            _value_solution = None
        if bool(flags & 2):
            _value_solution_entities, cursor = decode_vector(raw_data, cursor, "MessageEntity")
        else:
            _value_solution_entities = None
        if bool(flags & 4):
            _value_solution_media, cursor = decode_value("InputMedia", raw_data, cursor)
        else:
            _value_solution_media = None
        return cls(
            poll=_value_poll,
            correct_answers=_value_correct_answers,
            attached_media=_value_attached_media,
            solution=_value_solution,
            solution_entities=_value_solution_entities,
            solution_media=_value_solution_media,
        ), cursor


@dataclass(frozen=True, slots=True, kw_only=True)
class UserStatusRecently(TLConstructor):
    by_me: bool = False
    CONSTRUCTOR_ID: ClassVar[int] = 0x7B197DC8
    QUALNAME: ClassVar[str] = "userStatusRecently"
    RESULT_TYPE: ClassVar[str] = "UserStatus"
    TL_FIELDS: ClassVar[tuple[TLField, ...]] = (
        TLField(
            name="by_me",
            python_name="by_me",
            type="true",
            flag="flags",
            flag_index=0,
            is_optional=True,
            is_true_flag=True,
            is_vector=False,
            vector_item_type=None,
        ),
    )
    TL_FLAG_GROUPS: ClassVar[tuple[TLFlagGroup, ...]] = (
        TLFlagGroup(name="flags", python_name="flags", before_field_index=0),
    )

    def serialize(self) -> bytes:
        return self._serialize(boxed=True)

    def _serialize(self, *, boxed: bool = True) -> bytes:
        output = bytearray()
        if boxed:
            output.extend(encode_constructor_id(self.CONSTRUCTOR_ID))
        flags = 0
        if self.by_me:
            flags |= 1
        output.extend(encode_int(flags))
        return bytes(output)

    @classmethod
    def deserialize(cls, data: bytes | memoryview) -> Self:
        obj, offset = cls._deserialize(data)
        if offset != len(data):
            raise TLCodecError("TL object payload has trailing bytes")
        return obj

    @classmethod
    def _deserialize(cls, data: bytes | memoryview, offset: int = 0, *, boxed: bool = True) -> tuple[Self, int]:
        raw_data = data
        cursor = offset
        if boxed:
            constructor_id, cursor = decode_constructor_id(raw_data, cursor)
            if constructor_id != cls.CONSTRUCTOR_ID:
                raise TLCodecError(f"expected constructor 0x{cls.CONSTRUCTOR_ID:08x}, got 0x{constructor_id:08x}")
        flags = 0
        flags, cursor = decode_int(raw_data, cursor)
        _value_by_me = bool(flags & 1)
        return cls(by_me=_value_by_me), cursor


@dataclass(frozen=True, slots=True, kw_only=True)
class MessageMediaGame(TLConstructor):
    game: Any
    CONSTRUCTOR_ID: ClassVar[int] = 0xFDB19008
    QUALNAME: ClassVar[str] = "messageMediaGame"
    RESULT_TYPE: ClassVar[str] = "MessageMedia"
    TL_FIELDS: ClassVar[tuple[TLField, ...]] = (
        TLField(
            name="game",
            python_name="game",
            type="Game",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
    )
    TL_FLAG_GROUPS: ClassVar[tuple[TLFlagGroup, ...]] = ()

    def serialize(self) -> bytes:
        return self._serialize(boxed=True)

    def _serialize(self, *, boxed: bool = True) -> bytes:
        output = bytearray()
        if boxed:
            output.extend(encode_constructor_id(self.CONSTRUCTOR_ID))
        output.extend(encode_value("Game", self.game))
        return bytes(output)

    @classmethod
    def deserialize(cls, data: bytes | memoryview) -> Self:
        obj, offset = cls._deserialize(data)
        if offset != len(data):
            raise TLCodecError("TL object payload has trailing bytes")
        return obj

    @classmethod
    def _deserialize(cls, data: bytes | memoryview, offset: int = 0, *, boxed: bool = True) -> tuple[Self, int]:
        raw_data = data
        cursor = offset
        if boxed:
            constructor_id, cursor = decode_constructor_id(raw_data, cursor)
            if constructor_id != cls.CONSTRUCTOR_ID:
                raise TLCodecError(f"expected constructor 0x{cls.CONSTRUCTOR_ID:08x}, got 0x{constructor_id:08x}")
        _value_game, cursor = decode_value("Game", raw_data, cursor)
        return cls(game=_value_game), cursor


@dataclass(frozen=True, slots=True, kw_only=True)
class MessageActionRequestedPeerSentMe(TLConstructor):
    button_id: int
    peers: tuple[Any, ...]
    CONSTRUCTOR_ID: ClassVar[int] = 0x93B31848
    QUALNAME: ClassVar[str] = "messageActionRequestedPeerSentMe"
    RESULT_TYPE: ClassVar[str] = "MessageAction"
    TL_FIELDS: ClassVar[tuple[TLField, ...]] = (
        TLField(
            name="button_id",
            python_name="button_id",
            type="int",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="peers",
            python_name="peers",
            type="Vector<RequestedPeer>",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=True,
            vector_item_type="RequestedPeer",
        ),
    )
    TL_FLAG_GROUPS: ClassVar[tuple[TLFlagGroup, ...]] = ()

    def serialize(self) -> bytes:
        return self._serialize(boxed=True)

    def _serialize(self, *, boxed: bool = True) -> bytes:
        output = bytearray()
        if boxed:
            output.extend(encode_constructor_id(self.CONSTRUCTOR_ID))
        output.extend(encode_int(self.button_id))
        output.extend(encode_vector(self.peers, "RequestedPeer"))
        return bytes(output)

    @classmethod
    def deserialize(cls, data: bytes | memoryview) -> Self:
        obj, offset = cls._deserialize(data)
        if offset != len(data):
            raise TLCodecError("TL object payload has trailing bytes")
        return obj

    @classmethod
    def _deserialize(cls, data: bytes | memoryview, offset: int = 0, *, boxed: bool = True) -> tuple[Self, int]:
        raw_data = data
        cursor = offset
        if boxed:
            constructor_id, cursor = decode_constructor_id(raw_data, cursor)
            if constructor_id != cls.CONSTRUCTOR_ID:
                raise TLCodecError(f"expected constructor 0x{cls.CONSTRUCTOR_ID:08x}, got 0x{constructor_id:08x}")
        _value_button_id, cursor = decode_int(raw_data, cursor)
        _value_peers, cursor = decode_vector(raw_data, cursor, "RequestedPeer")
        return cls(button_id=_value_button_id, peers=_value_peers), cursor


@dataclass(frozen=True, slots=True, kw_only=True)
class InputMessagesFilterDocument(TLConstructor):
    pass
    CONSTRUCTOR_ID: ClassVar[int] = 0x9EDDF188
    QUALNAME: ClassVar[str] = "inputMessagesFilterDocument"
    RESULT_TYPE: ClassVar[str] = "MessagesFilter"
    TL_FIELDS: ClassVar[tuple[TLField, ...]] = ()
    TL_FLAG_GROUPS: ClassVar[tuple[TLFlagGroup, ...]] = ()

    def serialize(self) -> bytes:
        return self._serialize(boxed=True)

    def _serialize(self, *, boxed: bool = True) -> bytes:
        output = bytearray()
        if boxed:
            output.extend(encode_constructor_id(self.CONSTRUCTOR_ID))
        return bytes(output)

    @classmethod
    def deserialize(cls, data: bytes | memoryview) -> Self:
        obj, offset = cls._deserialize(data)
        if offset != len(data):
            raise TLCodecError("TL object payload has trailing bytes")
        return obj

    @classmethod
    def _deserialize(cls, data: bytes | memoryview, offset: int = 0, *, boxed: bool = True) -> tuple[Self, int]:
        raw_data = data
        cursor = offset
        if boxed:
            constructor_id, cursor = decode_constructor_id(raw_data, cursor)
            if constructor_id != cls.CONSTRUCTOR_ID:
                raise TLCodecError(f"expected constructor 0x{cls.CONSTRUCTOR_ID:08x}, got 0x{constructor_id:08x}")
        return cls(), cursor


@dataclass(frozen=True, slots=True, kw_only=True)
class UpdateChannelMessageViews(TLConstructor):
    channel_id: int
    id: int
    views: int
    CONSTRUCTOR_ID: ClassVar[int] = 0xF226AC08
    QUALNAME: ClassVar[str] = "updateChannelMessageViews"
    RESULT_TYPE: ClassVar[str] = "Update"
    TL_FIELDS: ClassVar[tuple[TLField, ...]] = (
        TLField(
            name="channel_id",
            python_name="channel_id",
            type="long",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="id",
            python_name="id",
            type="int",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="views",
            python_name="views",
            type="int",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
    )
    TL_FLAG_GROUPS: ClassVar[tuple[TLFlagGroup, ...]] = ()

    def serialize(self) -> bytes:
        return self._serialize(boxed=True)

    def _serialize(self, *, boxed: bool = True) -> bytes:
        output = bytearray()
        if boxed:
            output.extend(encode_constructor_id(self.CONSTRUCTOR_ID))
        output.extend(encode_long(self.channel_id))
        output.extend(encode_int(self.id))
        output.extend(encode_int(self.views))
        return bytes(output)

    @classmethod
    def deserialize(cls, data: bytes | memoryview) -> Self:
        obj, offset = cls._deserialize(data)
        if offset != len(data):
            raise TLCodecError("TL object payload has trailing bytes")
        return obj

    @classmethod
    def _deserialize(cls, data: bytes | memoryview, offset: int = 0, *, boxed: bool = True) -> tuple[Self, int]:
        raw_data = data
        cursor = offset
        if boxed:
            constructor_id, cursor = decode_constructor_id(raw_data, cursor)
            if constructor_id != cls.CONSTRUCTOR_ID:
                raise TLCodecError(f"expected constructor 0x{cls.CONSTRUCTOR_ID:08x}, got 0x{constructor_id:08x}")
        _value_channel_id, cursor = decode_long(raw_data, cursor)
        _value_id, cursor = decode_int(raw_data, cursor)
        _value_views, cursor = decode_int(raw_data, cursor)
        return cls(channel_id=_value_channel_id, id=_value_id, views=_value_views), cursor


@dataclass(frozen=True, slots=True, kw_only=True)
class UpdateStickerSets(TLConstructor):
    masks: bool = False
    emojis: bool = False
    CONSTRUCTOR_ID: ClassVar[int] = 0x31C24808
    QUALNAME: ClassVar[str] = "updateStickerSets"
    RESULT_TYPE: ClassVar[str] = "Update"
    TL_FIELDS: ClassVar[tuple[TLField, ...]] = (
        TLField(
            name="masks",
            python_name="masks",
            type="true",
            flag="flags",
            flag_index=0,
            is_optional=True,
            is_true_flag=True,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="emojis",
            python_name="emojis",
            type="true",
            flag="flags",
            flag_index=1,
            is_optional=True,
            is_true_flag=True,
            is_vector=False,
            vector_item_type=None,
        ),
    )
    TL_FLAG_GROUPS: ClassVar[tuple[TLFlagGroup, ...]] = (
        TLFlagGroup(name="flags", python_name="flags", before_field_index=0),
    )

    def serialize(self) -> bytes:
        return self._serialize(boxed=True)

    def _serialize(self, *, boxed: bool = True) -> bytes:
        output = bytearray()
        if boxed:
            output.extend(encode_constructor_id(self.CONSTRUCTOR_ID))
        flags = 0
        if self.masks:
            flags |= 1
        if self.emojis:
            flags |= 2
        output.extend(encode_int(flags))
        return bytes(output)

    @classmethod
    def deserialize(cls, data: bytes | memoryview) -> Self:
        obj, offset = cls._deserialize(data)
        if offset != len(data):
            raise TLCodecError("TL object payload has trailing bytes")
        return obj

    @classmethod
    def _deserialize(cls, data: bytes | memoryview, offset: int = 0, *, boxed: bool = True) -> tuple[Self, int]:
        raw_data = data
        cursor = offset
        if boxed:
            constructor_id, cursor = decode_constructor_id(raw_data, cursor)
            if constructor_id != cls.CONSTRUCTOR_ID:
                raise TLCodecError(f"expected constructor 0x{cls.CONSTRUCTOR_ID:08x}, got 0x{constructor_id:08x}")
        flags = 0
        flags, cursor = decode_int(raw_data, cursor)
        _value_masks = bool(flags & 1)
        _value_emojis = bool(flags & 2)
        return cls(masks=_value_masks, emojis=_value_emojis), cursor


@dataclass(frozen=True, slots=True, kw_only=True)
class UpdatePinnedChannelMessages(TLConstructor):
    pinned: bool = False
    channel_id: int
    messages: tuple[int, ...]
    pts: int
    pts_count: int
    CONSTRUCTOR_ID: ClassVar[int] = 0x5BB98608
    QUALNAME: ClassVar[str] = "updatePinnedChannelMessages"
    RESULT_TYPE: ClassVar[str] = "Update"
    TL_FIELDS: ClassVar[tuple[TLField, ...]] = (
        TLField(
            name="pinned",
            python_name="pinned",
            type="true",
            flag="flags",
            flag_index=0,
            is_optional=True,
            is_true_flag=True,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="channel_id",
            python_name="channel_id",
            type="long",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="messages",
            python_name="messages",
            type="Vector<int>",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=True,
            vector_item_type="int",
        ),
        TLField(
            name="pts",
            python_name="pts",
            type="int",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="pts_count",
            python_name="pts_count",
            type="int",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
    )
    TL_FLAG_GROUPS: ClassVar[tuple[TLFlagGroup, ...]] = (
        TLFlagGroup(name="flags", python_name="flags", before_field_index=0),
    )

    def serialize(self) -> bytes:
        return self._serialize(boxed=True)

    def _serialize(self, *, boxed: bool = True) -> bytes:
        output = bytearray()
        if boxed:
            output.extend(encode_constructor_id(self.CONSTRUCTOR_ID))
        flags = 0
        if self.pinned:
            flags |= 1
        output.extend(encode_int(flags))
        output.extend(encode_long(self.channel_id))
        output.extend(encode_vector(self.messages, "int"))
        output.extend(encode_int(self.pts))
        output.extend(encode_int(self.pts_count))
        return bytes(output)

    @classmethod
    def deserialize(cls, data: bytes | memoryview) -> Self:
        obj, offset = cls._deserialize(data)
        if offset != len(data):
            raise TLCodecError("TL object payload has trailing bytes")
        return obj

    @classmethod
    def _deserialize(cls, data: bytes | memoryview, offset: int = 0, *, boxed: bool = True) -> tuple[Self, int]:
        raw_data = data
        cursor = offset
        if boxed:
            constructor_id, cursor = decode_constructor_id(raw_data, cursor)
            if constructor_id != cls.CONSTRUCTOR_ID:
                raise TLCodecError(f"expected constructor 0x{cls.CONSTRUCTOR_ID:08x}, got 0x{constructor_id:08x}")
        flags = 0
        flags, cursor = decode_int(raw_data, cursor)
        _value_pinned = bool(flags & 1)
        _value_channel_id, cursor = decode_long(raw_data, cursor)
        _value_messages, cursor = decode_vector(raw_data, cursor, "int")
        _value_pts, cursor = decode_int(raw_data, cursor)
        _value_pts_count, cursor = decode_int(raw_data, cursor)
        return cls(
            pinned=_value_pinned,
            channel_id=_value_channel_id,
            messages=_value_messages,
            pts=_value_pts,
            pts_count=_value_pts_count,
        ), cursor


@dataclass(frozen=True, slots=True, kw_only=True)
class UpdateMonoForumNoPaidException(TLConstructor):
    exception: bool = False
    channel_id: int
    saved_peer_id: Any
    CONSTRUCTOR_ID: ClassVar[int] = 0x9F812B08
    QUALNAME: ClassVar[str] = "updateMonoForumNoPaidException"
    RESULT_TYPE: ClassVar[str] = "Update"
    TL_FIELDS: ClassVar[tuple[TLField, ...]] = (
        TLField(
            name="exception",
            python_name="exception",
            type="true",
            flag="flags",
            flag_index=0,
            is_optional=True,
            is_true_flag=True,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="channel_id",
            python_name="channel_id",
            type="long",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="saved_peer_id",
            python_name="saved_peer_id",
            type="Peer",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
    )
    TL_FLAG_GROUPS: ClassVar[tuple[TLFlagGroup, ...]] = (
        TLFlagGroup(name="flags", python_name="flags", before_field_index=0),
    )

    def serialize(self) -> bytes:
        return self._serialize(boxed=True)

    def _serialize(self, *, boxed: bool = True) -> bytes:
        output = bytearray()
        if boxed:
            output.extend(encode_constructor_id(self.CONSTRUCTOR_ID))
        flags = 0
        if self.exception:
            flags |= 1
        output.extend(encode_int(flags))
        output.extend(encode_long(self.channel_id))
        output.extend(encode_value("Peer", self.saved_peer_id))
        return bytes(output)

    @classmethod
    def deserialize(cls, data: bytes | memoryview) -> Self:
        obj, offset = cls._deserialize(data)
        if offset != len(data):
            raise TLCodecError("TL object payload has trailing bytes")
        return obj

    @classmethod
    def _deserialize(cls, data: bytes | memoryview, offset: int = 0, *, boxed: bool = True) -> tuple[Self, int]:
        raw_data = data
        cursor = offset
        if boxed:
            constructor_id, cursor = decode_constructor_id(raw_data, cursor)
            if constructor_id != cls.CONSTRUCTOR_ID:
                raise TLCodecError(f"expected constructor 0x{cls.CONSTRUCTOR_ID:08x}, got 0x{constructor_id:08x}")
        flags = 0
        flags, cursor = decode_int(raw_data, cursor)
        _value_exception = bool(flags & 1)
        _value_channel_id, cursor = decode_long(raw_data, cursor)
        _value_saved_peer_id, cursor = decode_value("Peer", raw_data, cursor)
        return cls(exception=_value_exception, channel_id=_value_channel_id, saved_peer_id=_value_saved_peer_id), cursor


@dataclass(frozen=True, slots=True, kw_only=True)
class InputEncryptedFileBigUploaded(TLConstructor):
    id: int
    parts: int
    key_fingerprint: int
    CONSTRUCTOR_ID: ClassVar[int] = 0x2DC173C8
    QUALNAME: ClassVar[str] = "inputEncryptedFileBigUploaded"
    RESULT_TYPE: ClassVar[str] = "InputEncryptedFile"
    TL_FIELDS: ClassVar[tuple[TLField, ...]] = (
        TLField(
            name="id",
            python_name="id",
            type="long",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="parts",
            python_name="parts",
            type="int",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="key_fingerprint",
            python_name="key_fingerprint",
            type="int",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
    )
    TL_FLAG_GROUPS: ClassVar[tuple[TLFlagGroup, ...]] = ()

    def serialize(self) -> bytes:
        return self._serialize(boxed=True)

    def _serialize(self, *, boxed: bool = True) -> bytes:
        output = bytearray()
        if boxed:
            output.extend(encode_constructor_id(self.CONSTRUCTOR_ID))
        output.extend(encode_long(self.id))
        output.extend(encode_int(self.parts))
        output.extend(encode_int(self.key_fingerprint))
        return bytes(output)

    @classmethod
    def deserialize(cls, data: bytes | memoryview) -> Self:
        obj, offset = cls._deserialize(data)
        if offset != len(data):
            raise TLCodecError("TL object payload has trailing bytes")
        return obj

    @classmethod
    def _deserialize(cls, data: bytes | memoryview, offset: int = 0, *, boxed: bool = True) -> tuple[Self, int]:
        raw_data = data
        cursor = offset
        if boxed:
            constructor_id, cursor = decode_constructor_id(raw_data, cursor)
            if constructor_id != cls.CONSTRUCTOR_ID:
                raise TLCodecError(f"expected constructor 0x{cls.CONSTRUCTOR_ID:08x}, got 0x{constructor_id:08x}")
        _value_id, cursor = decode_long(raw_data, cursor)
        _value_parts, cursor = decode_int(raw_data, cursor)
        _value_key_fingerprint, cursor = decode_int(raw_data, cursor)
        return cls(id=_value_id, parts=_value_parts, key_fingerprint=_value_key_fingerprint), cursor


@dataclass(frozen=True, slots=True, kw_only=True)
class NotifyForumTopic(TLConstructor):
    peer: Any
    top_msg_id: int
    CONSTRUCTOR_ID: ClassVar[int] = 0x226E6308
    QUALNAME: ClassVar[str] = "notifyForumTopic"
    RESULT_TYPE: ClassVar[str] = "NotifyPeer"
    TL_FIELDS: ClassVar[tuple[TLField, ...]] = (
        TLField(
            name="peer",
            python_name="peer",
            type="Peer",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="top_msg_id",
            python_name="top_msg_id",
            type="int",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
    )
    TL_FLAG_GROUPS: ClassVar[tuple[TLFlagGroup, ...]] = ()

    def serialize(self) -> bytes:
        return self._serialize(boxed=True)

    def _serialize(self, *, boxed: bool = True) -> bytes:
        output = bytearray()
        if boxed:
            output.extend(encode_constructor_id(self.CONSTRUCTOR_ID))
        output.extend(encode_value("Peer", self.peer))
        output.extend(encode_int(self.top_msg_id))
        return bytes(output)

    @classmethod
    def deserialize(cls, data: bytes | memoryview) -> Self:
        obj, offset = cls._deserialize(data)
        if offset != len(data):
            raise TLCodecError("TL object payload has trailing bytes")
        return obj

    @classmethod
    def _deserialize(cls, data: bytes | memoryview, offset: int = 0, *, boxed: bool = True) -> tuple[Self, int]:
        raw_data = data
        cursor = offset
        if boxed:
            constructor_id, cursor = decode_constructor_id(raw_data, cursor)
            if constructor_id != cls.CONSTRUCTOR_ID:
                raise TLCodecError(f"expected constructor 0x{cls.CONSTRUCTOR_ID:08x}, got 0x{constructor_id:08x}")
        _value_peer, cursor = decode_value("Peer", raw_data, cursor)
        _value_top_msg_id, cursor = decode_int(raw_data, cursor)
        return cls(peer=_value_peer, top_msg_id=_value_top_msg_id), cursor


@dataclass(frozen=True, slots=True, kw_only=True)
class SendMessageGamePlayAction(TLConstructor):
    pass
    CONSTRUCTOR_ID: ClassVar[int] = 0xDD6A8F48
    QUALNAME: ClassVar[str] = "sendMessageGamePlayAction"
    RESULT_TYPE: ClassVar[str] = "SendMessageAction"
    TL_FIELDS: ClassVar[tuple[TLField, ...]] = ()
    TL_FLAG_GROUPS: ClassVar[tuple[TLFlagGroup, ...]] = ()

    def serialize(self) -> bytes:
        return self._serialize(boxed=True)

    def _serialize(self, *, boxed: bool = True) -> bytes:
        output = bytearray()
        if boxed:
            output.extend(encode_constructor_id(self.CONSTRUCTOR_ID))
        return bytes(output)

    @classmethod
    def deserialize(cls, data: bytes | memoryview) -> Self:
        obj, offset = cls._deserialize(data)
        if offset != len(data):
            raise TLCodecError("TL object payload has trailing bytes")
        return obj

    @classmethod
    def _deserialize(cls, data: bytes | memoryview, offset: int = 0, *, boxed: bool = True) -> tuple[Self, int]:
        raw_data = data
        cursor = offset
        if boxed:
            constructor_id, cursor = decode_constructor_id(raw_data, cursor)
            if constructor_id != cls.CONSTRUCTOR_ID:
                raise TLCodecError(f"expected constructor 0x{cls.CONSTRUCTOR_ID:08x}, got 0x{constructor_id:08x}")
        return cls(), cursor


@dataclass(frozen=True, slots=True, kw_only=True)
class InputPrivacyKeyForwards(TLConstructor):
    pass
    CONSTRUCTOR_ID: ClassVar[int] = 0xA4DD4C08
    QUALNAME: ClassVar[str] = "inputPrivacyKeyForwards"
    RESULT_TYPE: ClassVar[str] = "InputPrivacyKey"
    TL_FIELDS: ClassVar[tuple[TLField, ...]] = ()
    TL_FLAG_GROUPS: ClassVar[tuple[TLFlagGroup, ...]] = ()

    def serialize(self) -> bytes:
        return self._serialize(boxed=True)

    def _serialize(self, *, boxed: bool = True) -> bytes:
        output = bytearray()
        if boxed:
            output.extend(encode_constructor_id(self.CONSTRUCTOR_ID))
        return bytes(output)

    @classmethod
    def deserialize(cls, data: bytes | memoryview) -> Self:
        obj, offset = cls._deserialize(data)
        if offset != len(data):
            raise TLCodecError("TL object payload has trailing bytes")
        return obj

    @classmethod
    def _deserialize(cls, data: bytes | memoryview, offset: int = 0, *, boxed: bool = True) -> tuple[Self, int]:
        raw_data = data
        cursor = offset
        if boxed:
            constructor_id, cursor = decode_constructor_id(raw_data, cursor)
            if constructor_id != cls.CONSTRUCTOR_ID:
                raise TLCodecError(f"expected constructor 0x{cls.CONSTRUCTOR_ID:08x}, got 0x{constructor_id:08x}")
        return cls(), cursor


@dataclass(frozen=True, slots=True, kw_only=True)
class PrivacyKeyPhoneP2P(TLConstructor):
    pass
    CONSTRUCTOR_ID: ClassVar[int] = 0x39491CC8
    QUALNAME: ClassVar[str] = "privacyKeyPhoneP2P"
    RESULT_TYPE: ClassVar[str] = "PrivacyKey"
    TL_FIELDS: ClassVar[tuple[TLField, ...]] = ()
    TL_FLAG_GROUPS: ClassVar[tuple[TLFlagGroup, ...]] = ()

    def serialize(self) -> bytes:
        return self._serialize(boxed=True)

    def _serialize(self, *, boxed: bool = True) -> bytes:
        output = bytearray()
        if boxed:
            output.extend(encode_constructor_id(self.CONSTRUCTOR_ID))
        return bytes(output)

    @classmethod
    def deserialize(cls, data: bytes | memoryview) -> Self:
        obj, offset = cls._deserialize(data)
        if offset != len(data):
            raise TLCodecError("TL object payload has trailing bytes")
        return obj

    @classmethod
    def _deserialize(cls, data: bytes | memoryview, offset: int = 0, *, boxed: bool = True) -> tuple[Self, int]:
        raw_data = data
        cursor = offset
        if boxed:
            constructor_id, cursor = decode_constructor_id(raw_data, cursor)
            if constructor_id != cls.CONSTRUCTOR_ID:
                raise TLCodecError(f"expected constructor 0x{cls.CONSTRUCTOR_ID:08x}, got 0x{constructor_id:08x}")
        return cls(), cursor


@dataclass(frozen=True, slots=True, kw_only=True)
class DocumentAttributeVideo(TLConstructor):
    round_message: bool = False
    supports_streaming: bool = False
    nosound: bool = False
    duration: float
    w: int
    h: int
    preload_prefix_size: int | None = None
    video_start_ts: float | None = None
    video_codec: str | None = None
    CONSTRUCTOR_ID: ClassVar[int] = 0x43C57C48
    QUALNAME: ClassVar[str] = "documentAttributeVideo"
    RESULT_TYPE: ClassVar[str] = "DocumentAttribute"
    TL_FIELDS: ClassVar[tuple[TLField, ...]] = (
        TLField(
            name="round_message",
            python_name="round_message",
            type="true",
            flag="flags",
            flag_index=0,
            is_optional=True,
            is_true_flag=True,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="supports_streaming",
            python_name="supports_streaming",
            type="true",
            flag="flags",
            flag_index=1,
            is_optional=True,
            is_true_flag=True,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="nosound",
            python_name="nosound",
            type="true",
            flag="flags",
            flag_index=3,
            is_optional=True,
            is_true_flag=True,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="duration",
            python_name="duration",
            type="double",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="w",
            python_name="w",
            type="int",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="h",
            python_name="h",
            type="int",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="preload_prefix_size",
            python_name="preload_prefix_size",
            type="int",
            flag="flags",
            flag_index=2,
            is_optional=True,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="video_start_ts",
            python_name="video_start_ts",
            type="double",
            flag="flags",
            flag_index=4,
            is_optional=True,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="video_codec",
            python_name="video_codec",
            type="string",
            flag="flags",
            flag_index=5,
            is_optional=True,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
    )
    TL_FLAG_GROUPS: ClassVar[tuple[TLFlagGroup, ...]] = (
        TLFlagGroup(name="flags", python_name="flags", before_field_index=0),
    )

    def serialize(self) -> bytes:
        return self._serialize(boxed=True)

    def _serialize(self, *, boxed: bool = True) -> bytes:
        output = bytearray()
        if boxed:
            output.extend(encode_constructor_id(self.CONSTRUCTOR_ID))
        flags = 0
        if self.round_message:
            flags |= 1
        if self.supports_streaming:
            flags |= 2
        if self.nosound:
            flags |= 8
        if self.preload_prefix_size is not None:
            flags |= 4
        if self.video_start_ts is not None:
            flags |= 16
        if self.video_codec is not None:
            flags |= 32
        output.extend(encode_int(flags))
        output.extend(encode_double(self.duration))
        output.extend(encode_int(self.w))
        output.extend(encode_int(self.h))
        if self.preload_prefix_size is not None:
            output.extend(encode_int(self.preload_prefix_size))
        if self.video_start_ts is not None:
            output.extend(encode_double(self.video_start_ts))
        if self.video_codec is not None:
            output.extend(encode_string(self.video_codec))
        return bytes(output)

    @classmethod
    def deserialize(cls, data: bytes | memoryview) -> Self:
        obj, offset = cls._deserialize(data)
        if offset != len(data):
            raise TLCodecError("TL object payload has trailing bytes")
        return obj

    @classmethod
    def _deserialize(cls, data: bytes | memoryview, offset: int = 0, *, boxed: bool = True) -> tuple[Self, int]:
        raw_data = data
        cursor = offset
        if boxed:
            constructor_id, cursor = decode_constructor_id(raw_data, cursor)
            if constructor_id != cls.CONSTRUCTOR_ID:
                raise TLCodecError(f"expected constructor 0x{cls.CONSTRUCTOR_ID:08x}, got 0x{constructor_id:08x}")
        flags = 0
        flags, cursor = decode_int(raw_data, cursor)
        _value_round_message = bool(flags & 1)
        _value_supports_streaming = bool(flags & 2)
        _value_nosound = bool(flags & 8)
        _value_duration, cursor = decode_double(raw_data, cursor)
        _value_w, cursor = decode_int(raw_data, cursor)
        _value_h, cursor = decode_int(raw_data, cursor)
        if bool(flags & 4):
            _value_preload_prefix_size, cursor = decode_int(raw_data, cursor)
        else:
            _value_preload_prefix_size = None
        if bool(flags & 16):
            _value_video_start_ts, cursor = decode_double(raw_data, cursor)
        else:
            _value_video_start_ts = None
        if bool(flags & 32):
            _value_video_codec, cursor = decode_string(raw_data, cursor)
        else:
            _value_video_codec = None
        return cls(
            round_message=_value_round_message,
            supports_streaming=_value_supports_streaming,
            nosound=_value_nosound,
            duration=_value_duration,
            w=_value_w,
            h=_value_h,
            preload_prefix_size=_value_preload_prefix_size,
            video_start_ts=_value_video_start_ts,
            video_codec=_value_video_codec,
        ), cursor


@dataclass(frozen=True, slots=True, kw_only=True)
class WebPageEmpty(TLConstructor):
    id: int
    url: str | None = None
    CONSTRUCTOR_ID: ClassVar[int] = 0x211A1788
    QUALNAME: ClassVar[str] = "webPageEmpty"
    RESULT_TYPE: ClassVar[str] = "WebPage"
    TL_FIELDS: ClassVar[tuple[TLField, ...]] = (
        TLField(
            name="id",
            python_name="id",
            type="long",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="url",
            python_name="url",
            type="string",
            flag="flags",
            flag_index=0,
            is_optional=True,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
    )
    TL_FLAG_GROUPS: ClassVar[tuple[TLFlagGroup, ...]] = (
        TLFlagGroup(name="flags", python_name="flags", before_field_index=0),
    )

    def serialize(self) -> bytes:
        return self._serialize(boxed=True)

    def _serialize(self, *, boxed: bool = True) -> bytes:
        output = bytearray()
        if boxed:
            output.extend(encode_constructor_id(self.CONSTRUCTOR_ID))
        flags = 0
        if self.url is not None:
            flags |= 1
        output.extend(encode_int(flags))
        output.extend(encode_long(self.id))
        if self.url is not None:
            output.extend(encode_string(self.url))
        return bytes(output)

    @classmethod
    def deserialize(cls, data: bytes | memoryview) -> Self:
        obj, offset = cls._deserialize(data)
        if offset != len(data):
            raise TLCodecError("TL object payload has trailing bytes")
        return obj

    @classmethod
    def _deserialize(cls, data: bytes | memoryview, offset: int = 0, *, boxed: bool = True) -> tuple[Self, int]:
        raw_data = data
        cursor = offset
        if boxed:
            constructor_id, cursor = decode_constructor_id(raw_data, cursor)
            if constructor_id != cls.CONSTRUCTOR_ID:
                raise TLCodecError(f"expected constructor 0x{cls.CONSTRUCTOR_ID:08x}, got 0x{constructor_id:08x}")
        flags = 0
        flags, cursor = decode_int(raw_data, cursor)
        _value_id, cursor = decode_long(raw_data, cursor)
        if bool(flags & 1):
            _value_url, cursor = decode_string(raw_data, cursor)
        else:
            _value_url = None
        return cls(id=_value_id, url=_value_url), cursor


@dataclass(frozen=True, slots=True, kw_only=True)
class InputStickerSetAnimatedEmoji(TLConstructor):
    pass
    CONSTRUCTOR_ID: ClassVar[int] = 0x028703C8
    QUALNAME: ClassVar[str] = "inputStickerSetAnimatedEmoji"
    RESULT_TYPE: ClassVar[str] = "InputStickerSet"
    TL_FIELDS: ClassVar[tuple[TLField, ...]] = ()
    TL_FLAG_GROUPS: ClassVar[tuple[TLFlagGroup, ...]] = ()

    def serialize(self) -> bytes:
        return self._serialize(boxed=True)

    def _serialize(self, *, boxed: bool = True) -> bytes:
        output = bytearray()
        if boxed:
            output.extend(encode_constructor_id(self.CONSTRUCTOR_ID))
        return bytes(output)

    @classmethod
    def deserialize(cls, data: bytes | memoryview) -> Self:
        obj, offset = cls._deserialize(data)
        if offset != len(data):
            raise TLCodecError("TL object payload has trailing bytes")
        return obj

    @classmethod
    def _deserialize(cls, data: bytes | memoryview, offset: int = 0, *, boxed: bool = True) -> tuple[Self, int]:
        raw_data = data
        cursor = offset
        if boxed:
            constructor_id, cursor = decode_constructor_id(raw_data, cursor)
            if constructor_id != cls.CONSTRUCTOR_ID:
                raise TLCodecError(f"expected constructor 0x{cls.CONSTRUCTOR_ID:08x}, got 0x{constructor_id:08x}")
        return cls(), cursor


@dataclass(frozen=True, slots=True, kw_only=True)
class ReplyKeyboardForceReply(TLConstructor):
    single_use: bool = False
    selective: bool = False
    placeholder: str | None = None
    CONSTRUCTOR_ID: ClassVar[int] = 0x86B40B08
    QUALNAME: ClassVar[str] = "replyKeyboardForceReply"
    RESULT_TYPE: ClassVar[str] = "ReplyMarkup"
    TL_FIELDS: ClassVar[tuple[TLField, ...]] = (
        TLField(
            name="single_use",
            python_name="single_use",
            type="true",
            flag="flags",
            flag_index=1,
            is_optional=True,
            is_true_flag=True,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="selective",
            python_name="selective",
            type="true",
            flag="flags",
            flag_index=2,
            is_optional=True,
            is_true_flag=True,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="placeholder",
            python_name="placeholder",
            type="string",
            flag="flags",
            flag_index=3,
            is_optional=True,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
    )
    TL_FLAG_GROUPS: ClassVar[tuple[TLFlagGroup, ...]] = (
        TLFlagGroup(name="flags", python_name="flags", before_field_index=0),
    )

    def serialize(self) -> bytes:
        return self._serialize(boxed=True)

    def _serialize(self, *, boxed: bool = True) -> bytes:
        output = bytearray()
        if boxed:
            output.extend(encode_constructor_id(self.CONSTRUCTOR_ID))
        flags = 0
        if self.single_use:
            flags |= 2
        if self.selective:
            flags |= 4
        if self.placeholder is not None:
            flags |= 8
        output.extend(encode_int(flags))
        if self.placeholder is not None:
            output.extend(encode_string(self.placeholder))
        return bytes(output)

    @classmethod
    def deserialize(cls, data: bytes | memoryview) -> Self:
        obj, offset = cls._deserialize(data)
        if offset != len(data):
            raise TLCodecError("TL object payload has trailing bytes")
        return obj

    @classmethod
    def _deserialize(cls, data: bytes | memoryview, offset: int = 0, *, boxed: bool = True) -> tuple[Self, int]:
        raw_data = data
        cursor = offset
        if boxed:
            constructor_id, cursor = decode_constructor_id(raw_data, cursor)
            if constructor_id != cls.CONSTRUCTOR_ID:
                raise TLCodecError(f"expected constructor 0x{cls.CONSTRUCTOR_ID:08x}, got 0x{constructor_id:08x}")
        flags = 0
        flags, cursor = decode_int(raw_data, cursor)
        _value_single_use = bool(flags & 2)
        _value_selective = bool(flags & 4)
        if bool(flags & 8):
            _value_placeholder, cursor = decode_string(raw_data, cursor)
        else:
            _value_placeholder = None
        return cls(single_use=_value_single_use, selective=_value_selective, placeholder=_value_placeholder), cursor


@dataclass(frozen=True, slots=True, kw_only=True)
class MessagesArchivedStickers(TLConstructor):
    count: int
    sets: tuple[Any, ...]
    CONSTRUCTOR_ID: ClassVar[int] = 0x4FCBA9C8
    QUALNAME: ClassVar[str] = "messages.archivedStickers"
    RESULT_TYPE: ClassVar[str] = "messages.ArchivedStickers"
    TL_FIELDS: ClassVar[tuple[TLField, ...]] = (
        TLField(
            name="count",
            python_name="count",
            type="int",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="sets",
            python_name="sets",
            type="Vector<StickerSetCovered>",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=True,
            vector_item_type="StickerSetCovered",
        ),
    )
    TL_FLAG_GROUPS: ClassVar[tuple[TLFlagGroup, ...]] = ()

    def serialize(self) -> bytes:
        return self._serialize(boxed=True)

    def _serialize(self, *, boxed: bool = True) -> bytes:
        output = bytearray()
        if boxed:
            output.extend(encode_constructor_id(self.CONSTRUCTOR_ID))
        output.extend(encode_int(self.count))
        output.extend(encode_vector(self.sets, "StickerSetCovered"))
        return bytes(output)

    @classmethod
    def deserialize(cls, data: bytes | memoryview) -> Self:
        obj, offset = cls._deserialize(data)
        if offset != len(data):
            raise TLCodecError("TL object payload has trailing bytes")
        return obj

    @classmethod
    def _deserialize(cls, data: bytes | memoryview, offset: int = 0, *, boxed: bool = True) -> tuple[Self, int]:
        raw_data = data
        cursor = offset
        if boxed:
            constructor_id, cursor = decode_constructor_id(raw_data, cursor)
            if constructor_id != cls.CONSTRUCTOR_ID:
                raise TLCodecError(f"expected constructor 0x{cls.CONSTRUCTOR_ID:08x}, got 0x{constructor_id:08x}")
        _value_count, cursor = decode_int(raw_data, cursor)
        _value_sets, cursor = decode_vector(raw_data, cursor, "StickerSetCovered")
        return cls(count=_value_count, sets=_value_sets), cursor


@dataclass(frozen=True, slots=True, kw_only=True)
class PageBlockDivider(TLConstructor):
    pass
    CONSTRUCTOR_ID: ClassVar[int] = 0xDB20B188
    QUALNAME: ClassVar[str] = "pageBlockDivider"
    RESULT_TYPE: ClassVar[str] = "PageBlock"
    TL_FIELDS: ClassVar[tuple[TLField, ...]] = ()
    TL_FLAG_GROUPS: ClassVar[tuple[TLFlagGroup, ...]] = ()

    def serialize(self) -> bytes:
        return self._serialize(boxed=True)

    def _serialize(self, *, boxed: bool = True) -> bytes:
        output = bytearray()
        if boxed:
            output.extend(encode_constructor_id(self.CONSTRUCTOR_ID))
        return bytes(output)

    @classmethod
    def deserialize(cls, data: bytes | memoryview) -> Self:
        obj, offset = cls._deserialize(data)
        if offset != len(data):
            raise TLCodecError("TL object payload has trailing bytes")
        return obj

    @classmethod
    def _deserialize(cls, data: bytes | memoryview, offset: int = 0, *, boxed: bool = True) -> tuple[Self, int]:
        raw_data = data
        cursor = offset
        if boxed:
            constructor_id, cursor = decode_constructor_id(raw_data, cursor)
            if constructor_id != cls.CONSTRUCTOR_ID:
                raise TLCodecError(f"expected constructor 0x{cls.CONSTRUCTOR_ID:08x}, got 0x{constructor_id:08x}")
        return cls(), cursor


@dataclass(frozen=True, slots=True, kw_only=True)
class PhoneCallProtocol(TLConstructor):
    udp_p2p: bool = False
    udp_reflector: bool = False
    min_layer: int
    max_layer: int
    library_versions: tuple[str, ...]
    CONSTRUCTOR_ID: ClassVar[int] = 0xFC878FC8
    QUALNAME: ClassVar[str] = "phoneCallProtocol"
    RESULT_TYPE: ClassVar[str] = "PhoneCallProtocol"
    TL_FIELDS: ClassVar[tuple[TLField, ...]] = (
        TLField(
            name="udp_p2p",
            python_name="udp_p2p",
            type="true",
            flag="flags",
            flag_index=0,
            is_optional=True,
            is_true_flag=True,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="udp_reflector",
            python_name="udp_reflector",
            type="true",
            flag="flags",
            flag_index=1,
            is_optional=True,
            is_true_flag=True,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="min_layer",
            python_name="min_layer",
            type="int",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="max_layer",
            python_name="max_layer",
            type="int",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="library_versions",
            python_name="library_versions",
            type="Vector<string>",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=True,
            vector_item_type="string",
        ),
    )
    TL_FLAG_GROUPS: ClassVar[tuple[TLFlagGroup, ...]] = (
        TLFlagGroup(name="flags", python_name="flags", before_field_index=0),
    )

    def serialize(self) -> bytes:
        return self._serialize(boxed=True)

    def _serialize(self, *, boxed: bool = True) -> bytes:
        output = bytearray()
        if boxed:
            output.extend(encode_constructor_id(self.CONSTRUCTOR_ID))
        flags = 0
        if self.udp_p2p:
            flags |= 1
        if self.udp_reflector:
            flags |= 2
        output.extend(encode_int(flags))
        output.extend(encode_int(self.min_layer))
        output.extend(encode_int(self.max_layer))
        output.extend(encode_vector(self.library_versions, "string"))
        return bytes(output)

    @classmethod
    def deserialize(cls, data: bytes | memoryview) -> Self:
        obj, offset = cls._deserialize(data)
        if offset != len(data):
            raise TLCodecError("TL object payload has trailing bytes")
        return obj

    @classmethod
    def _deserialize(cls, data: bytes | memoryview, offset: int = 0, *, boxed: bool = True) -> tuple[Self, int]:
        raw_data = data
        cursor = offset
        if boxed:
            constructor_id, cursor = decode_constructor_id(raw_data, cursor)
            if constructor_id != cls.CONSTRUCTOR_ID:
                raise TLCodecError(f"expected constructor 0x{cls.CONSTRUCTOR_ID:08x}, got 0x{constructor_id:08x}")
        flags = 0
        flags, cursor = decode_int(raw_data, cursor)
        _value_udp_p2p = bool(flags & 1)
        _value_udp_reflector = bool(flags & 2)
        _value_min_layer, cursor = decode_int(raw_data, cursor)
        _value_max_layer, cursor = decode_int(raw_data, cursor)
        _value_library_versions, cursor = decode_vector(raw_data, cursor, "string")
        return cls(
            udp_p2p=_value_udp_p2p,
            udp_reflector=_value_udp_reflector,
            min_layer=_value_min_layer,
            max_layer=_value_max_layer,
            library_versions=_value_library_versions,
        ), cursor


@dataclass(frozen=True, slots=True, kw_only=True)
class ChannelAdminLogEventActionChangeLinkedChat(TLConstructor):
    prev_value: int
    new_value: int
    CONSTRUCTOR_ID: ClassVar[int] = 0x050C7AC8
    QUALNAME: ClassVar[str] = "channelAdminLogEventActionChangeLinkedChat"
    RESULT_TYPE: ClassVar[str] = "ChannelAdminLogEventAction"
    TL_FIELDS: ClassVar[tuple[TLField, ...]] = (
        TLField(
            name="prev_value",
            python_name="prev_value",
            type="long",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="new_value",
            python_name="new_value",
            type="long",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
    )
    TL_FLAG_GROUPS: ClassVar[tuple[TLFlagGroup, ...]] = ()

    def serialize(self) -> bytes:
        return self._serialize(boxed=True)

    def _serialize(self, *, boxed: bool = True) -> bytes:
        output = bytearray()
        if boxed:
            output.extend(encode_constructor_id(self.CONSTRUCTOR_ID))
        output.extend(encode_long(self.prev_value))
        output.extend(encode_long(self.new_value))
        return bytes(output)

    @classmethod
    def deserialize(cls, data: bytes | memoryview) -> Self:
        obj, offset = cls._deserialize(data)
        if offset != len(data):
            raise TLCodecError("TL object payload has trailing bytes")
        return obj

    @classmethod
    def _deserialize(cls, data: bytes | memoryview, offset: int = 0, *, boxed: bool = True) -> tuple[Self, int]:
        raw_data = data
        cursor = offset
        if boxed:
            constructor_id, cursor = decode_constructor_id(raw_data, cursor)
            if constructor_id != cls.CONSTRUCTOR_ID:
                raise TLCodecError(f"expected constructor 0x{cls.CONSTRUCTOR_ID:08x}, got 0x{constructor_id:08x}")
        _value_prev_value, cursor = decode_long(raw_data, cursor)
        _value_new_value, cursor = decode_long(raw_data, cursor)
        return cls(prev_value=_value_prev_value, new_value=_value_new_value), cursor


@dataclass(frozen=True, slots=True, kw_only=True)
class ChannelAdminLogEventActionEditTopic(TLConstructor):
    prev_topic: Any
    new_topic: Any
    CONSTRUCTOR_ID: ClassVar[int] = 0xF06FE208
    QUALNAME: ClassVar[str] = "channelAdminLogEventActionEditTopic"
    RESULT_TYPE: ClassVar[str] = "ChannelAdminLogEventAction"
    TL_FIELDS: ClassVar[tuple[TLField, ...]] = (
        TLField(
            name="prev_topic",
            python_name="prev_topic",
            type="ForumTopic",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="new_topic",
            python_name="new_topic",
            type="ForumTopic",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
    )
    TL_FLAG_GROUPS: ClassVar[tuple[TLFlagGroup, ...]] = ()

    def serialize(self) -> bytes:
        return self._serialize(boxed=True)

    def _serialize(self, *, boxed: bool = True) -> bytes:
        output = bytearray()
        if boxed:
            output.extend(encode_constructor_id(self.CONSTRUCTOR_ID))
        output.extend(encode_value("ForumTopic", self.prev_topic))
        output.extend(encode_value("ForumTopic", self.new_topic))
        return bytes(output)

    @classmethod
    def deserialize(cls, data: bytes | memoryview) -> Self:
        obj, offset = cls._deserialize(data)
        if offset != len(data):
            raise TLCodecError("TL object payload has trailing bytes")
        return obj

    @classmethod
    def _deserialize(cls, data: bytes | memoryview, offset: int = 0, *, boxed: bool = True) -> tuple[Self, int]:
        raw_data = data
        cursor = offset
        if boxed:
            constructor_id, cursor = decode_constructor_id(raw_data, cursor)
            if constructor_id != cls.CONSTRUCTOR_ID:
                raise TLCodecError(f"expected constructor 0x{cls.CONSTRUCTOR_ID:08x}, got 0x{constructor_id:08x}")
        _value_prev_topic, cursor = decode_value("ForumTopic", raw_data, cursor)
        _value_new_topic, cursor = decode_value("ForumTopic", raw_data, cursor)
        return cls(prev_topic=_value_prev_topic, new_topic=_value_new_topic), cursor


@dataclass(frozen=True, slots=True, kw_only=True)
class SecureValueTypeRentalAgreement(TLConstructor):
    pass
    CONSTRUCTOR_ID: ClassVar[int] = 0x8B883488
    QUALNAME: ClassVar[str] = "secureValueTypeRentalAgreement"
    RESULT_TYPE: ClassVar[str] = "SecureValueType"
    TL_FIELDS: ClassVar[tuple[TLField, ...]] = ()
    TL_FLAG_GROUPS: ClassVar[tuple[TLFlagGroup, ...]] = ()

    def serialize(self) -> bytes:
        return self._serialize(boxed=True)

    def _serialize(self, *, boxed: bool = True) -> bytes:
        output = bytearray()
        if boxed:
            output.extend(encode_constructor_id(self.CONSTRUCTOR_ID))
        return bytes(output)

    @classmethod
    def deserialize(cls, data: bytes | memoryview) -> Self:
        obj, offset = cls._deserialize(data)
        if offset != len(data):
            raise TLCodecError("TL object payload has trailing bytes")
        return obj

    @classmethod
    def _deserialize(cls, data: bytes | memoryview, offset: int = 0, *, boxed: bool = True) -> tuple[Self, int]:
        raw_data = data
        cursor = offset
        if boxed:
            constructor_id, cursor = decode_constructor_id(raw_data, cursor)
            if constructor_id != cls.CONSTRUCTOR_ID:
                raise TLCodecError(f"expected constructor 0x{cls.CONSTRUCTOR_ID:08x}, got 0x{constructor_id:08x}")
        return cls(), cursor


@dataclass(frozen=True, slots=True, kw_only=True)
class PageRelatedArticle(TLConstructor):
    url: str
    webpage_id: int
    title: str | None = None
    description: str | None = None
    photo_id: int | None = None
    author: str | None = None
    published_date: int | None = None
    CONSTRUCTOR_ID: ClassVar[int] = 0xB390DC08
    QUALNAME: ClassVar[str] = "pageRelatedArticle"
    RESULT_TYPE: ClassVar[str] = "PageRelatedArticle"
    TL_FIELDS: ClassVar[tuple[TLField, ...]] = (
        TLField(
            name="url",
            python_name="url",
            type="string",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="webpage_id",
            python_name="webpage_id",
            type="long",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="title",
            python_name="title",
            type="string",
            flag="flags",
            flag_index=0,
            is_optional=True,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="description",
            python_name="description",
            type="string",
            flag="flags",
            flag_index=1,
            is_optional=True,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="photo_id",
            python_name="photo_id",
            type="long",
            flag="flags",
            flag_index=2,
            is_optional=True,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="author",
            python_name="author",
            type="string",
            flag="flags",
            flag_index=3,
            is_optional=True,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="published_date",
            python_name="published_date",
            type="int",
            flag="flags",
            flag_index=4,
            is_optional=True,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
    )
    TL_FLAG_GROUPS: ClassVar[tuple[TLFlagGroup, ...]] = (
        TLFlagGroup(name="flags", python_name="flags", before_field_index=0),
    )

    def serialize(self) -> bytes:
        return self._serialize(boxed=True)

    def _serialize(self, *, boxed: bool = True) -> bytes:
        output = bytearray()
        if boxed:
            output.extend(encode_constructor_id(self.CONSTRUCTOR_ID))
        flags = 0
        if self.title is not None:
            flags |= 1
        if self.description is not None:
            flags |= 2
        if self.photo_id is not None:
            flags |= 4
        if self.author is not None:
            flags |= 8
        if self.published_date is not None:
            flags |= 16
        output.extend(encode_int(flags))
        output.extend(encode_string(self.url))
        output.extend(encode_long(self.webpage_id))
        if self.title is not None:
            output.extend(encode_string(self.title))
        if self.description is not None:
            output.extend(encode_string(self.description))
        if self.photo_id is not None:
            output.extend(encode_long(self.photo_id))
        if self.author is not None:
            output.extend(encode_string(self.author))
        if self.published_date is not None:
            output.extend(encode_int(self.published_date))
        return bytes(output)

    @classmethod
    def deserialize(cls, data: bytes | memoryview) -> Self:
        obj, offset = cls._deserialize(data)
        if offset != len(data):
            raise TLCodecError("TL object payload has trailing bytes")
        return obj

    @classmethod
    def _deserialize(cls, data: bytes | memoryview, offset: int = 0, *, boxed: bool = True) -> tuple[Self, int]:
        raw_data = data
        cursor = offset
        if boxed:
            constructor_id, cursor = decode_constructor_id(raw_data, cursor)
            if constructor_id != cls.CONSTRUCTOR_ID:
                raise TLCodecError(f"expected constructor 0x{cls.CONSTRUCTOR_ID:08x}, got 0x{constructor_id:08x}")
        flags = 0
        flags, cursor = decode_int(raw_data, cursor)
        _value_url, cursor = decode_string(raw_data, cursor)
        _value_webpage_id, cursor = decode_long(raw_data, cursor)
        if bool(flags & 1):
            _value_title, cursor = decode_string(raw_data, cursor)
        else:
            _value_title = None
        if bool(flags & 2):
            _value_description, cursor = decode_string(raw_data, cursor)
        else:
            _value_description = None
        if bool(flags & 4):
            _value_photo_id, cursor = decode_long(raw_data, cursor)
        else:
            _value_photo_id = None
        if bool(flags & 8):
            _value_author, cursor = decode_string(raw_data, cursor)
        else:
            _value_author = None
        if bool(flags & 16):
            _value_published_date, cursor = decode_int(raw_data, cursor)
        else:
            _value_published_date = None
        return cls(
            url=_value_url,
            webpage_id=_value_webpage_id,
            title=_value_title,
            description=_value_description,
            photo_id=_value_photo_id,
            author=_value_author,
            published_date=_value_published_date,
        ), cursor


@dataclass(frozen=True, slots=True, kw_only=True)
class BaseThemeDay(TLConstructor):
    pass
    CONSTRUCTOR_ID: ClassVar[int] = 0xFBD81688
    QUALNAME: ClassVar[str] = "baseThemeDay"
    RESULT_TYPE: ClassVar[str] = "BaseTheme"
    TL_FIELDS: ClassVar[tuple[TLField, ...]] = ()
    TL_FLAG_GROUPS: ClassVar[tuple[TLFlagGroup, ...]] = ()

    def serialize(self) -> bytes:
        return self._serialize(boxed=True)

    def _serialize(self, *, boxed: bool = True) -> bytes:
        output = bytearray()
        if boxed:
            output.extend(encode_constructor_id(self.CONSTRUCTOR_ID))
        return bytes(output)

    @classmethod
    def deserialize(cls, data: bytes | memoryview) -> Self:
        obj, offset = cls._deserialize(data)
        if offset != len(data):
            raise TLCodecError("TL object payload has trailing bytes")
        return obj

    @classmethod
    def _deserialize(cls, data: bytes | memoryview, offset: int = 0, *, boxed: bool = True) -> tuple[Self, int]:
        raw_data = data
        cursor = offset
        if boxed:
            constructor_id, cursor = decode_constructor_id(raw_data, cursor)
            if constructor_id != cls.CONSTRUCTOR_ID:
                raise TLCodecError(f"expected constructor 0x{cls.CONSTRUCTOR_ID:08x}, got 0x{constructor_id:08x}")
        return cls(), cursor


@dataclass(frozen=True, slots=True, kw_only=True)
class GroupCallParticipantVideo(TLConstructor):
    paused: bool = False
    endpoint: str
    source_groups: tuple[Any, ...]
    audio_source: int | None = None
    CONSTRUCTOR_ID: ClassVar[int] = 0x67753AC8
    QUALNAME: ClassVar[str] = "groupCallParticipantVideo"
    RESULT_TYPE: ClassVar[str] = "GroupCallParticipantVideo"
    TL_FIELDS: ClassVar[tuple[TLField, ...]] = (
        TLField(
            name="paused",
            python_name="paused",
            type="true",
            flag="flags",
            flag_index=0,
            is_optional=True,
            is_true_flag=True,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="endpoint",
            python_name="endpoint",
            type="string",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="source_groups",
            python_name="source_groups",
            type="Vector<GroupCallParticipantVideoSourceGroup>",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=True,
            vector_item_type="GroupCallParticipantVideoSourceGroup",
        ),
        TLField(
            name="audio_source",
            python_name="audio_source",
            type="int",
            flag="flags",
            flag_index=1,
            is_optional=True,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
    )
    TL_FLAG_GROUPS: ClassVar[tuple[TLFlagGroup, ...]] = (
        TLFlagGroup(name="flags", python_name="flags", before_field_index=0),
    )

    def serialize(self) -> bytes:
        return self._serialize(boxed=True)

    def _serialize(self, *, boxed: bool = True) -> bytes:
        output = bytearray()
        if boxed:
            output.extend(encode_constructor_id(self.CONSTRUCTOR_ID))
        flags = 0
        if self.paused:
            flags |= 1
        if self.audio_source is not None:
            flags |= 2
        output.extend(encode_int(flags))
        output.extend(encode_string(self.endpoint))
        output.extend(encode_vector(self.source_groups, "GroupCallParticipantVideoSourceGroup"))
        if self.audio_source is not None:
            output.extend(encode_int(self.audio_source))
        return bytes(output)

    @classmethod
    def deserialize(cls, data: bytes | memoryview) -> Self:
        obj, offset = cls._deserialize(data)
        if offset != len(data):
            raise TLCodecError("TL object payload has trailing bytes")
        return obj

    @classmethod
    def _deserialize(cls, data: bytes | memoryview, offset: int = 0, *, boxed: bool = True) -> tuple[Self, int]:
        raw_data = data
        cursor = offset
        if boxed:
            constructor_id, cursor = decode_constructor_id(raw_data, cursor)
            if constructor_id != cls.CONSTRUCTOR_ID:
                raise TLCodecError(f"expected constructor 0x{cls.CONSTRUCTOR_ID:08x}, got 0x{constructor_id:08x}")
        flags = 0
        flags, cursor = decode_int(raw_data, cursor)
        _value_paused = bool(flags & 1)
        _value_endpoint, cursor = decode_string(raw_data, cursor)
        _value_source_groups, cursor = decode_vector(raw_data, cursor, "GroupCallParticipantVideoSourceGroup")
        if bool(flags & 2):
            _value_audio_source, cursor = decode_int(raw_data, cursor)
        else:
            _value_audio_source = None
        return cls(
            paused=_value_paused,
            endpoint=_value_endpoint,
            source_groups=_value_source_groups,
            audio_source=_value_audio_source,
        ), cursor


@dataclass(frozen=True, slots=True, kw_only=True)
class ChatThemeUniqueGift(TLConstructor):
    gift: Any
    theme_settings: tuple[Any, ...]
    CONSTRUCTOR_ID: ClassVar[int] = 0x3458F9C8
    QUALNAME: ClassVar[str] = "chatThemeUniqueGift"
    RESULT_TYPE: ClassVar[str] = "ChatTheme"
    TL_FIELDS: ClassVar[tuple[TLField, ...]] = (
        TLField(
            name="gift",
            python_name="gift",
            type="StarGift",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="theme_settings",
            python_name="theme_settings",
            type="Vector<ThemeSettings>",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=True,
            vector_item_type="ThemeSettings",
        ),
    )
    TL_FLAG_GROUPS: ClassVar[tuple[TLFlagGroup, ...]] = ()

    def serialize(self) -> bytes:
        return self._serialize(boxed=True)

    def _serialize(self, *, boxed: bool = True) -> bytes:
        output = bytearray()
        if boxed:
            output.extend(encode_constructor_id(self.CONSTRUCTOR_ID))
        output.extend(encode_value("StarGift", self.gift))
        output.extend(encode_vector(self.theme_settings, "ThemeSettings"))
        return bytes(output)

    @classmethod
    def deserialize(cls, data: bytes | memoryview) -> Self:
        obj, offset = cls._deserialize(data)
        if offset != len(data):
            raise TLCodecError("TL object payload has trailing bytes")
        return obj

    @classmethod
    def _deserialize(cls, data: bytes | memoryview, offset: int = 0, *, boxed: bool = True) -> tuple[Self, int]:
        raw_data = data
        cursor = offset
        if boxed:
            constructor_id, cursor = decode_constructor_id(raw_data, cursor)
            if constructor_id != cls.CONSTRUCTOR_ID:
                raise TLCodecError(f"expected constructor 0x{cls.CONSTRUCTOR_ID:08x}, got 0x{constructor_id:08x}")
        _value_gift, cursor = decode_value("StarGift", raw_data, cursor)
        _value_theme_settings, cursor = decode_vector(raw_data, cursor, "ThemeSettings")
        return cls(gift=_value_gift, theme_settings=_value_theme_settings), cursor


@dataclass(frozen=True, slots=True, kw_only=True)
class BotMenuButtonDefault(TLConstructor):
    pass
    CONSTRUCTOR_ID: ClassVar[int] = 0x7533A588
    QUALNAME: ClassVar[str] = "botMenuButtonDefault"
    RESULT_TYPE: ClassVar[str] = "BotMenuButton"
    TL_FIELDS: ClassVar[tuple[TLField, ...]] = ()
    TL_FLAG_GROUPS: ClassVar[tuple[TLFlagGroup, ...]] = ()

    def serialize(self) -> bytes:
        return self._serialize(boxed=True)

    def _serialize(self, *, boxed: bool = True) -> bytes:
        output = bytearray()
        if boxed:
            output.extend(encode_constructor_id(self.CONSTRUCTOR_ID))
        return bytes(output)

    @classmethod
    def deserialize(cls, data: bytes | memoryview) -> Self:
        obj, offset = cls._deserialize(data)
        if offset != len(data):
            raise TLCodecError("TL object payload has trailing bytes")
        return obj

    @classmethod
    def _deserialize(cls, data: bytes | memoryview, offset: int = 0, *, boxed: bool = True) -> tuple[Self, int]:
        raw_data = data
        cursor = offset
        if boxed:
            constructor_id, cursor = decode_constructor_id(raw_data, cursor)
            if constructor_id != cls.CONSTRUCTOR_ID:
                raise TLCodecError(f"expected constructor 0x{cls.CONSTRUCTOR_ID:08x}, got 0x{constructor_id:08x}")
        return cls(), cursor


@dataclass(frozen=True, slots=True, kw_only=True)
class MessageExtendedMediaPreview(TLConstructor):
    w: int | None = None
    h: int | None = None
    thumb: Any | None = None
    video_duration: int | None = None
    CONSTRUCTOR_ID: ClassVar[int] = 0xAD628CC8
    QUALNAME: ClassVar[str] = "messageExtendedMediaPreview"
    RESULT_TYPE: ClassVar[str] = "MessageExtendedMedia"
    TL_FIELDS: ClassVar[tuple[TLField, ...]] = (
        TLField(
            name="w",
            python_name="w",
            type="int",
            flag="flags",
            flag_index=0,
            is_optional=True,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="h",
            python_name="h",
            type="int",
            flag="flags",
            flag_index=0,
            is_optional=True,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="thumb",
            python_name="thumb",
            type="PhotoSize",
            flag="flags",
            flag_index=1,
            is_optional=True,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="video_duration",
            python_name="video_duration",
            type="int",
            flag="flags",
            flag_index=2,
            is_optional=True,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
    )
    TL_FLAG_GROUPS: ClassVar[tuple[TLFlagGroup, ...]] = (
        TLFlagGroup(name="flags", python_name="flags", before_field_index=0),
    )

    def serialize(self) -> bytes:
        return self._serialize(boxed=True)

    def _serialize(self, *, boxed: bool = True) -> bytes:
        output = bytearray()
        if boxed:
            output.extend(encode_constructor_id(self.CONSTRUCTOR_ID))
        flags = 0
        if self.w is not None:
            flags |= 1
        if self.h is not None:
            flags |= 1
        if self.thumb is not None:
            flags |= 2
        if self.video_duration is not None:
            flags |= 4
        output.extend(encode_int(flags))
        if self.w is not None:
            output.extend(encode_int(self.w))
        if self.h is not None:
            output.extend(encode_int(self.h))
        if self.thumb is not None:
            output.extend(encode_value("PhotoSize", self.thumb))
        if self.video_duration is not None:
            output.extend(encode_int(self.video_duration))
        return bytes(output)

    @classmethod
    def deserialize(cls, data: bytes | memoryview) -> Self:
        obj, offset = cls._deserialize(data)
        if offset != len(data):
            raise TLCodecError("TL object payload has trailing bytes")
        return obj

    @classmethod
    def _deserialize(cls, data: bytes | memoryview, offset: int = 0, *, boxed: bool = True) -> tuple[Self, int]:
        raw_data = data
        cursor = offset
        if boxed:
            constructor_id, cursor = decode_constructor_id(raw_data, cursor)
            if constructor_id != cls.CONSTRUCTOR_ID:
                raise TLCodecError(f"expected constructor 0x{cls.CONSTRUCTOR_ID:08x}, got 0x{constructor_id:08x}")
        flags = 0
        flags, cursor = decode_int(raw_data, cursor)
        if bool(flags & 1):
            _value_w, cursor = decode_int(raw_data, cursor)
        else:
            _value_w = None
        if bool(flags & 1):
            _value_h, cursor = decode_int(raw_data, cursor)
        else:
            _value_h = None
        if bool(flags & 2):
            _value_thumb, cursor = decode_value("PhotoSize", raw_data, cursor)
        else:
            _value_thumb = None
        if bool(flags & 4):
            _value_video_duration, cursor = decode_int(raw_data, cursor)
        else:
            _value_video_duration = None
        return cls(w=_value_w, h=_value_h, thumb=_value_thumb, video_duration=_value_video_duration), cursor


@dataclass(frozen=True, slots=True, kw_only=True)
class HelpPeerColors(TLConstructor):
    hash: int
    colors: tuple[Any, ...]
    CONSTRUCTOR_ID: ClassVar[int] = 0x00F8ED08
    QUALNAME: ClassVar[str] = "help.peerColors"
    RESULT_TYPE: ClassVar[str] = "help.PeerColors"
    TL_FIELDS: ClassVar[tuple[TLField, ...]] = (
        TLField(
            name="hash",
            python_name="hash",
            type="int",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="colors",
            python_name="colors",
            type="Vector<help.PeerColorOption>",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=True,
            vector_item_type="help.PeerColorOption",
        ),
    )
    TL_FLAG_GROUPS: ClassVar[tuple[TLFlagGroup, ...]] = ()

    def serialize(self) -> bytes:
        return self._serialize(boxed=True)

    def _serialize(self, *, boxed: bool = True) -> bytes:
        output = bytearray()
        if boxed:
            output.extend(encode_constructor_id(self.CONSTRUCTOR_ID))
        output.extend(encode_int(self.hash))
        output.extend(encode_vector(self.colors, "help.PeerColorOption"))
        return bytes(output)

    @classmethod
    def deserialize(cls, data: bytes | memoryview) -> Self:
        obj, offset = cls._deserialize(data)
        if offset != len(data):
            raise TLCodecError("TL object payload has trailing bytes")
        return obj

    @classmethod
    def _deserialize(cls, data: bytes | memoryview, offset: int = 0, *, boxed: bool = True) -> tuple[Self, int]:
        raw_data = data
        cursor = offset
        if boxed:
            constructor_id, cursor = decode_constructor_id(raw_data, cursor)
            if constructor_id != cls.CONSTRUCTOR_ID:
                raise TLCodecError(f"expected constructor 0x{cls.CONSTRUCTOR_ID:08x}, got 0x{constructor_id:08x}")
        _value_hash, cursor = decode_int(raw_data, cursor)
        _value_colors, cursor = decode_vector(raw_data, cursor, "help.PeerColorOption")
        return cls(hash=_value_hash, colors=_value_colors), cursor


@dataclass(frozen=True, slots=True, kw_only=True)
class AccountPaidMessagesRevenue(TLConstructor):
    stars_amount: int
    CONSTRUCTOR_ID: ClassVar[int] = 0x1E109708
    QUALNAME: ClassVar[str] = "account.paidMessagesRevenue"
    RESULT_TYPE: ClassVar[str] = "account.PaidMessagesRevenue"
    TL_FIELDS: ClassVar[tuple[TLField, ...]] = (
        TLField(
            name="stars_amount",
            python_name="stars_amount",
            type="long",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
    )
    TL_FLAG_GROUPS: ClassVar[tuple[TLFlagGroup, ...]] = ()

    def serialize(self) -> bytes:
        return self._serialize(boxed=True)

    def _serialize(self, *, boxed: bool = True) -> bytes:
        output = bytearray()
        if boxed:
            output.extend(encode_constructor_id(self.CONSTRUCTOR_ID))
        output.extend(encode_long(self.stars_amount))
        return bytes(output)

    @classmethod
    def deserialize(cls, data: bytes | memoryview) -> Self:
        obj, offset = cls._deserialize(data)
        if offset != len(data):
            raise TLCodecError("TL object payload has trailing bytes")
        return obj

    @classmethod
    def _deserialize(cls, data: bytes | memoryview, offset: int = 0, *, boxed: bool = True) -> tuple[Self, int]:
        raw_data = data
        cursor = offset
        if boxed:
            constructor_id, cursor = decode_constructor_id(raw_data, cursor)
            if constructor_id != cls.CONSTRUCTOR_ID:
                raise TLCodecError(f"expected constructor 0x{cls.CONSTRUCTOR_ID:08x}, got 0x{constructor_id:08x}")
        _value_stars_amount, cursor = decode_long(raw_data, cursor)
        return cls(stars_amount=_value_stars_amount), cursor


@dataclass(frozen=True, slots=True, kw_only=True)
class StarGiftAuctionAcquiredGift(TLConstructor):
    name_hidden: bool = False
    peer: Any
    date: int
    bid_amount: int
    round: int
    pos: int
    message: Any | None = None
    gift_num: int | None = None
    CONSTRUCTOR_ID: ClassVar[int] = 0x42B00348
    QUALNAME: ClassVar[str] = "starGiftAuctionAcquiredGift"
    RESULT_TYPE: ClassVar[str] = "StarGiftAuctionAcquiredGift"
    TL_FIELDS: ClassVar[tuple[TLField, ...]] = (
        TLField(
            name="name_hidden",
            python_name="name_hidden",
            type="true",
            flag="flags",
            flag_index=0,
            is_optional=True,
            is_true_flag=True,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="peer",
            python_name="peer",
            type="Peer",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="date",
            python_name="date",
            type="int",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="bid_amount",
            python_name="bid_amount",
            type="long",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="round",
            python_name="round",
            type="int",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="pos",
            python_name="pos",
            type="int",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="message",
            python_name="message",
            type="TextWithEntities",
            flag="flags",
            flag_index=1,
            is_optional=True,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="gift_num",
            python_name="gift_num",
            type="int",
            flag="flags",
            flag_index=2,
            is_optional=True,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
    )
    TL_FLAG_GROUPS: ClassVar[tuple[TLFlagGroup, ...]] = (
        TLFlagGroup(name="flags", python_name="flags", before_field_index=0),
    )

    def serialize(self) -> bytes:
        return self._serialize(boxed=True)

    def _serialize(self, *, boxed: bool = True) -> bytes:
        output = bytearray()
        if boxed:
            output.extend(encode_constructor_id(self.CONSTRUCTOR_ID))
        flags = 0
        if self.name_hidden:
            flags |= 1
        if self.message is not None:
            flags |= 2
        if self.gift_num is not None:
            flags |= 4
        output.extend(encode_int(flags))
        output.extend(encode_value("Peer", self.peer))
        output.extend(encode_int(self.date))
        output.extend(encode_long(self.bid_amount))
        output.extend(encode_int(self.round))
        output.extend(encode_int(self.pos))
        if self.message is not None:
            output.extend(encode_value("TextWithEntities", self.message))
        if self.gift_num is not None:
            output.extend(encode_int(self.gift_num))
        return bytes(output)

    @classmethod
    def deserialize(cls, data: bytes | memoryview) -> Self:
        obj, offset = cls._deserialize(data)
        if offset != len(data):
            raise TLCodecError("TL object payload has trailing bytes")
        return obj

    @classmethod
    def _deserialize(cls, data: bytes | memoryview, offset: int = 0, *, boxed: bool = True) -> tuple[Self, int]:
        raw_data = data
        cursor = offset
        if boxed:
            constructor_id, cursor = decode_constructor_id(raw_data, cursor)
            if constructor_id != cls.CONSTRUCTOR_ID:
                raise TLCodecError(f"expected constructor 0x{cls.CONSTRUCTOR_ID:08x}, got 0x{constructor_id:08x}")
        flags = 0
        flags, cursor = decode_int(raw_data, cursor)
        _value_name_hidden = bool(flags & 1)
        _value_peer, cursor = decode_value("Peer", raw_data, cursor)
        _value_date, cursor = decode_int(raw_data, cursor)
        _value_bid_amount, cursor = decode_long(raw_data, cursor)
        _value_round, cursor = decode_int(raw_data, cursor)
        _value_pos, cursor = decode_int(raw_data, cursor)
        if bool(flags & 2):
            _value_message, cursor = decode_value("TextWithEntities", raw_data, cursor)
        else:
            _value_message = None
        if bool(flags & 4):
            _value_gift_num, cursor = decode_int(raw_data, cursor)
        else:
            _value_gift_num = None
        return cls(
            name_hidden=_value_name_hidden,
            peer=_value_peer,
            date=_value_date,
            bid_amount=_value_bid_amount,
            round=_value_round,
            pos=_value_pos,
            message=_value_message,
            gift_num=_value_gift_num,
        ), cursor


@dataclass(frozen=True, slots=True, kw_only=True)
class InputStarGiftAuctionSlug(TLConstructor):
    slug: str
    CONSTRUCTOR_ID: ClassVar[int] = 0x7AB58308
    QUALNAME: ClassVar[str] = "inputStarGiftAuctionSlug"
    RESULT_TYPE: ClassVar[str] = "InputStarGiftAuction"
    TL_FIELDS: ClassVar[tuple[TLField, ...]] = (
        TLField(
            name="slug",
            python_name="slug",
            type="string",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
    )
    TL_FLAG_GROUPS: ClassVar[tuple[TLFlagGroup, ...]] = ()

    def serialize(self) -> bytes:
        return self._serialize(boxed=True)

    def _serialize(self, *, boxed: bool = True) -> bytes:
        output = bytearray()
        if boxed:
            output.extend(encode_constructor_id(self.CONSTRUCTOR_ID))
        output.extend(encode_string(self.slug))
        return bytes(output)

    @classmethod
    def deserialize(cls, data: bytes | memoryview) -> Self:
        obj, offset = cls._deserialize(data)
        if offset != len(data):
            raise TLCodecError("TL object payload has trailing bytes")
        return obj

    @classmethod
    def _deserialize(cls, data: bytes | memoryview, offset: int = 0, *, boxed: bool = True) -> tuple[Self, int]:
        raw_data = data
        cursor = offset
        if boxed:
            constructor_id, cursor = decode_constructor_id(raw_data, cursor)
            if constructor_id != cls.CONSTRUCTOR_ID:
                raise TLCodecError(f"expected constructor 0x{cls.CONSTRUCTOR_ID:08x}, got 0x{constructor_id:08x}")
        _value_slug, cursor = decode_string(raw_data, cursor)
        return cls(slug=_value_slug), cursor


@dataclass(frozen=True, slots=True, kw_only=True)
class MessagesComposedRichMessageWithAI(TLConstructor):
    result: Any
    CONSTRUCTOR_ID: ClassVar[int] = 0x4C4537C8
    QUALNAME: ClassVar[str] = "messages.composedRichMessageWithAI"
    RESULT_TYPE: ClassVar[str] = "messages.ComposedRichMessageWithAI"
    TL_FIELDS: ClassVar[tuple[TLField, ...]] = (
        TLField(
            name="result",
            python_name="result",
            type="RichMessage",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
    )
    TL_FLAG_GROUPS: ClassVar[tuple[TLFlagGroup, ...]] = ()

    def serialize(self) -> bytes:
        return self._serialize(boxed=True)

    def _serialize(self, *, boxed: bool = True) -> bytes:
        output = bytearray()
        if boxed:
            output.extend(encode_constructor_id(self.CONSTRUCTOR_ID))
        output.extend(encode_value("RichMessage", self.result))
        return bytes(output)

    @classmethod
    def deserialize(cls, data: bytes | memoryview) -> Self:
        obj, offset = cls._deserialize(data)
        if offset != len(data):
            raise TLCodecError("TL object payload has trailing bytes")
        return obj

    @classmethod
    def _deserialize(cls, data: bytes | memoryview, offset: int = 0, *, boxed: bool = True) -> tuple[Self, int]:
        raw_data = data
        cursor = offset
        if boxed:
            constructor_id, cursor = decode_constructor_id(raw_data, cursor)
            if constructor_id != cls.CONSTRUCTOR_ID:
                raise TLCodecError(f"expected constructor 0x{cls.CONSTRUCTOR_ID:08x}, got 0x{constructor_id:08x}")
        _value_result, cursor = decode_value("RichMessage", raw_data, cursor)
        return cls(result=_value_result), cursor


class account:
    PaidMessagesRevenue = AccountPaidMessagesRevenue


class help:
    PeerColors = HelpPeerColors


class messages:
    ArchivedStickers = MessagesArchivedStickers
    ComposedRichMessageWithAI = MessagesComposedRichMessageWithAI


ALL_TYPES: tuple[type[TLConstructor], ...] = (
    InputFileStoryDocument,
    InputMediaPoll,
    UserStatusRecently,
    MessageMediaGame,
    MessageActionRequestedPeerSentMe,
    InputMessagesFilterDocument,
    UpdateChannelMessageViews,
    UpdateStickerSets,
    UpdatePinnedChannelMessages,
    UpdateMonoForumNoPaidException,
    InputEncryptedFileBigUploaded,
    NotifyForumTopic,
    SendMessageGamePlayAction,
    InputPrivacyKeyForwards,
    PrivacyKeyPhoneP2P,
    DocumentAttributeVideo,
    WebPageEmpty,
    InputStickerSetAnimatedEmoji,
    ReplyKeyboardForceReply,
    MessagesArchivedStickers,
    PageBlockDivider,
    PhoneCallProtocol,
    ChannelAdminLogEventActionChangeLinkedChat,
    ChannelAdminLogEventActionEditTopic,
    SecureValueTypeRentalAgreement,
    PageRelatedArticle,
    BaseThemeDay,
    GroupCallParticipantVideo,
    ChatThemeUniqueGift,
    BotMenuButtonDefault,
    MessageExtendedMediaPreview,
    HelpPeerColors,
    AccountPaidMessagesRevenue,
    StarGiftAuctionAcquiredGift,
    InputStarGiftAuctionSlug,
    MessagesComposedRichMessageWithAI,
)
CONSTRUCTOR_ID_MAP: dict[int, type[TLConstructor]] = {entry.CONSTRUCTOR_ID: entry for entry in ALL_TYPES}
NAME_MAP: dict[str, type[TLConstructor]] = {entry.QUALNAME: entry for entry in ALL_TYPES}
__all__ = (
    "InputFileStoryDocument",
    "InputMediaPoll",
    "UserStatusRecently",
    "MessageMediaGame",
    "MessageActionRequestedPeerSentMe",
    "InputMessagesFilterDocument",
    "UpdateChannelMessageViews",
    "UpdateStickerSets",
    "UpdatePinnedChannelMessages",
    "UpdateMonoForumNoPaidException",
    "InputEncryptedFileBigUploaded",
    "NotifyForumTopic",
    "SendMessageGamePlayAction",
    "InputPrivacyKeyForwards",
    "PrivacyKeyPhoneP2P",
    "DocumentAttributeVideo",
    "WebPageEmpty",
    "InputStickerSetAnimatedEmoji",
    "ReplyKeyboardForceReply",
    "MessagesArchivedStickers",
    "PageBlockDivider",
    "PhoneCallProtocol",
    "ChannelAdminLogEventActionChangeLinkedChat",
    "ChannelAdminLogEventActionEditTopic",
    "SecureValueTypeRentalAgreement",
    "PageRelatedArticle",
    "BaseThemeDay",
    "GroupCallParticipantVideo",
    "ChatThemeUniqueGift",
    "BotMenuButtonDefault",
    "MessageExtendedMediaPreview",
    "HelpPeerColors",
    "AccountPaidMessagesRevenue",
    "StarGiftAuctionAcquiredGift",
    "InputStarGiftAuctionSlug",
    "MessagesComposedRichMessageWithAI",
    "account",
    "help",
    "messages",
    "CONSTRUCTOR_ID_MAP",
    "NAME_MAP",
)
