# Generated by tools/schema/generate.py; do not edit by hand.
# Source: tools/schema/schema.json (normalized from the pinned canonical TL schema)
from __future__ import annotations

from dataclasses import dataclass
from typing import Any, ClassVar, Self, cast

from miniproto.raw.base import TLConstructor, TLField, TLFlagGroup
from miniproto.tl.codec import (
    TLCodecError,
    decode_bool,
    decode_bytes,
    decode_constructor_id,
    decode_double,
    decode_int,
    decode_int128,
    decode_int256,
    decode_long,
    decode_object,
    decode_string,
    decode_value,
    decode_vector,
    encode_bool,
    encode_bytes,
    encode_constructor_id,
    encode_double,
    encode_int,
    encode_int128,
    encode_int256,
    encode_long,
    encode_string,
    encode_value,
    encode_vector,
)
from miniproto.tl.fast import decode_fast, encode_fast, materialize_empty_object


@dataclass(frozen=True, slots=True, kw_only=True)
class InputUserEmpty(TLConstructor):
    pass
    CONSTRUCTOR_ID: ClassVar[int] = 0xB98886CF
    QUALNAME: ClassVar[str] = "inputUserEmpty"
    RESULT_TYPE: ClassVar[str] = "InputUser"
    TL_FIELDS: ClassVar[tuple[TLField, ...]] = ()
    TL_FLAG_GROUPS: ClassVar[tuple[TLFlagGroup, ...]] = ()

    def serialize(self) -> bytes:
        return self._serialize(boxed=True)

    def _serialize(self, *, boxed: bool = True) -> bytes:
        output = bytearray()
        if boxed:
            output.extend(encode_constructor_id(self.CONSTRUCTOR_ID))
        return bytes(output)

    @classmethod
    def deserialize(cls, data: bytes | memoryview) -> Self:
        obj, offset = cls._deserialize(data)
        if offset != len(data):
            raise TLCodecError("TL object payload has trailing bytes")
        return obj

    @classmethod
    def _deserialize(cls, data: bytes | memoryview, offset: int = 0, *, boxed: bool = True) -> tuple[Self, int]:
        raw_data = data
        cursor = offset
        if boxed:
            constructor_id, cursor = decode_constructor_id(raw_data, cursor)
            if constructor_id != cls.CONSTRUCTOR_ID:
                raise TLCodecError(f"expected constructor 0x{cls.CONSTRUCTOR_ID:08x}, got 0x{constructor_id:08x}")
        return cls(), cursor


@dataclass(frozen=True, slots=True, kw_only=True)
class UpdatePtsChanged(TLConstructor):
    pass
    CONSTRUCTOR_ID: ClassVar[int] = 0x3354678F
    QUALNAME: ClassVar[str] = "updatePtsChanged"
    RESULT_TYPE: ClassVar[str] = "Update"
    TL_FIELDS: ClassVar[tuple[TLField, ...]] = ()
    TL_FLAG_GROUPS: ClassVar[tuple[TLFlagGroup, ...]] = ()

    def serialize(self) -> bytes:
        return self._serialize(boxed=True)

    def _serialize(self, *, boxed: bool = True) -> bytes:
        output = bytearray()
        if boxed:
            output.extend(encode_constructor_id(self.CONSTRUCTOR_ID))
        return bytes(output)

    @classmethod
    def deserialize(cls, data: bytes | memoryview) -> Self:
        obj, offset = cls._deserialize(data)
        if offset != len(data):
            raise TLCodecError("TL object payload has trailing bytes")
        return obj

    @classmethod
    def _deserialize(cls, data: bytes | memoryview, offset: int = 0, *, boxed: bool = True) -> tuple[Self, int]:
        raw_data = data
        cursor = offset
        if boxed:
            constructor_id, cursor = decode_constructor_id(raw_data, cursor)
            if constructor_id != cls.CONSTRUCTOR_ID:
                raise TLCodecError(f"expected constructor 0x{cls.CONSTRUCTOR_ID:08x}, got 0x{constructor_id:08x}")
        return cls(), cursor


@dataclass(frozen=True, slots=True, kw_only=True)
class UpdateDialogFilters(TLConstructor):
    pass
    CONSTRUCTOR_ID: ClassVar[int] = 0x3504914F
    QUALNAME: ClassVar[str] = "updateDialogFilters"
    RESULT_TYPE: ClassVar[str] = "Update"
    TL_FIELDS: ClassVar[tuple[TLField, ...]] = ()
    TL_FLAG_GROUPS: ClassVar[tuple[TLFlagGroup, ...]] = ()

    def serialize(self) -> bytes:
        return self._serialize(boxed=True)

    def _serialize(self, *, boxed: bool = True) -> bytes:
        output = bytearray()
        if boxed:
            output.extend(encode_constructor_id(self.CONSTRUCTOR_ID))
        return bytes(output)

    @classmethod
    def deserialize(cls, data: bytes | memoryview) -> Self:
        obj, offset = cls._deserialize(data)
        if offset != len(data):
            raise TLCodecError("TL object payload has trailing bytes")
        return obj

    @classmethod
    def _deserialize(cls, data: bytes | memoryview, offset: int = 0, *, boxed: bool = True) -> tuple[Self, int]:
        raw_data = data
        cursor = offset
        if boxed:
            constructor_id, cursor = decode_constructor_id(raw_data, cursor)
            if constructor_id != cls.CONSTRUCTOR_ID:
                raise TLCodecError(f"expected constructor 0x{cls.CONSTRUCTOR_ID:08x}, got 0x{constructor_id:08x}")
        return cls(), cursor


@dataclass(frozen=True, slots=True, kw_only=True)
class UpdateQuickReplyMessage(TLConstructor):
    message: Any
    CONSTRUCTOR_ID: ClassVar[int] = 0x3E050D0F
    QUALNAME: ClassVar[str] = "updateQuickReplyMessage"
    RESULT_TYPE: ClassVar[str] = "Update"
    TL_FIELDS: ClassVar[tuple[TLField, ...]] = (
        TLField(
            name="message",
            python_name="message",
            type="Message",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
    )
    TL_FLAG_GROUPS: ClassVar[tuple[TLFlagGroup, ...]] = ()

    def serialize(self) -> bytes:
        return self._serialize(boxed=True)

    def _serialize(self, *, boxed: bool = True) -> bytes:
        output = bytearray()
        if boxed:
            output.extend(encode_constructor_id(self.CONSTRUCTOR_ID))
        output.extend(encode_value("Message", self.message))
        return bytes(output)

    @classmethod
    def deserialize(cls, data: bytes | memoryview) -> Self:
        obj, offset = cls._deserialize(data)
        if offset != len(data):
            raise TLCodecError("TL object payload has trailing bytes")
        return obj

    @classmethod
    def _deserialize(cls, data: bytes | memoryview, offset: int = 0, *, boxed: bool = True) -> tuple[Self, int]:
        raw_data = data
        cursor = offset
        if boxed:
            constructor_id, cursor = decode_constructor_id(raw_data, cursor)
            if constructor_id != cls.CONSTRUCTOR_ID:
                raise TLCodecError(f"expected constructor 0x{cls.CONSTRUCTOR_ID:08x}, got 0x{constructor_id:08x}")
        _value_message, cursor = decode_value("Message", raw_data, cursor)
        return cls(message=_value_message), cursor


@dataclass(frozen=True, slots=True, kw_only=True)
class UpdateSentPhoneCode(TLConstructor):
    sent_code: Any
    CONSTRUCTOR_ID: ClassVar[int] = 0x504AA18F
    QUALNAME: ClassVar[str] = "updateSentPhoneCode"
    RESULT_TYPE: ClassVar[str] = "Update"
    TL_FIELDS: ClassVar[tuple[TLField, ...]] = (
        TLField(
            name="sent_code",
            python_name="sent_code",
            type="auth.SentCode",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
    )
    TL_FLAG_GROUPS: ClassVar[tuple[TLFlagGroup, ...]] = ()

    def serialize(self) -> bytes:
        return self._serialize(boxed=True)

    def _serialize(self, *, boxed: bool = True) -> bytes:
        output = bytearray()
        if boxed:
            output.extend(encode_constructor_id(self.CONSTRUCTOR_ID))
        output.extend(encode_value("auth.SentCode", self.sent_code))
        return bytes(output)

    @classmethod
    def deserialize(cls, data: bytes | memoryview) -> Self:
        obj, offset = cls._deserialize(data)
        if offset != len(data):
            raise TLCodecError("TL object payload has trailing bytes")
        return obj

    @classmethod
    def _deserialize(cls, data: bytes | memoryview, offset: int = 0, *, boxed: bool = True) -> tuple[Self, int]:
        raw_data = data
        cursor = offset
        if boxed:
            constructor_id, cursor = decode_constructor_id(raw_data, cursor)
            if constructor_id != cls.CONSTRUCTOR_ID:
                raise TLCodecError(f"expected constructor 0x{cls.CONSTRUCTOR_ID:08x}, got 0x{constructor_id:08x}")
        _value_sent_code, cursor = decode_value("auth.SentCode", raw_data, cursor)
        return cls(sent_code=_value_sent_code), cursor


@dataclass(frozen=True, slots=True, kw_only=True)
class UpdateGroupCallChainBlocks(TLConstructor):
    call: Any
    sub_chain_id: int
    blocks: tuple[bytes, ...]
    next_offset: int
    CONSTRUCTOR_ID: ClassVar[int] = 0xA477288F
    QUALNAME: ClassVar[str] = "updateGroupCallChainBlocks"
    RESULT_TYPE: ClassVar[str] = "Update"
    TL_FIELDS: ClassVar[tuple[TLField, ...]] = (
        TLField(
            name="call",
            python_name="call",
            type="InputGroupCall",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="sub_chain_id",
            python_name="sub_chain_id",
            type="int",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="blocks",
            python_name="blocks",
            type="Vector<bytes>",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=True,
            vector_item_type="bytes",
        ),
        TLField(
            name="next_offset",
            python_name="next_offset",
            type="int",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
    )
    TL_FLAG_GROUPS: ClassVar[tuple[TLFlagGroup, ...]] = ()

    def serialize(self) -> bytes:
        return self._serialize(boxed=True)

    def _serialize(self, *, boxed: bool = True) -> bytes:
        output = bytearray()
        if boxed:
            output.extend(encode_constructor_id(self.CONSTRUCTOR_ID))
        output.extend(encode_value("InputGroupCall", self.call))
        output.extend(encode_int(self.sub_chain_id))
        output.extend(encode_vector(self.blocks, "bytes"))
        output.extend(encode_int(self.next_offset))
        return bytes(output)

    @classmethod
    def deserialize(cls, data: bytes | memoryview) -> Self:
        obj, offset = cls._deserialize(data)
        if offset != len(data):
            raise TLCodecError("TL object payload has trailing bytes")
        return obj

    @classmethod
    def _deserialize(cls, data: bytes | memoryview, offset: int = 0, *, boxed: bool = True) -> tuple[Self, int]:
        raw_data = data
        cursor = offset
        if boxed:
            constructor_id, cursor = decode_constructor_id(raw_data, cursor)
            if constructor_id != cls.CONSTRUCTOR_ID:
                raise TLCodecError(f"expected constructor 0x{cls.CONSTRUCTOR_ID:08x}, got 0x{constructor_id:08x}")
        _value_call, cursor = decode_value("InputGroupCall", raw_data, cursor)
        _value_sub_chain_id, cursor = decode_int(raw_data, cursor)
        _value_blocks, cursor = decode_vector(raw_data, cursor, "bytes")
        _value_next_offset, cursor = decode_int(raw_data, cursor)
        return cls(
            call=_value_call, sub_chain_id=_value_sub_chain_id, blocks=_value_blocks, next_offset=_value_next_offset
        ), cursor


@dataclass(frozen=True, slots=True, kw_only=True)
class InputPrivacyValueAllowChatParticipants(TLConstructor):
    chats: tuple[int, ...]
    CONSTRUCTOR_ID: ClassVar[int] = 0x840649CF
    QUALNAME: ClassVar[str] = "inputPrivacyValueAllowChatParticipants"
    RESULT_TYPE: ClassVar[str] = "InputPrivacyRule"
    TL_FIELDS: ClassVar[tuple[TLField, ...]] = (
        TLField(
            name="chats",
            python_name="chats",
            type="Vector<long>",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=True,
            vector_item_type="long",
        ),
    )
    TL_FLAG_GROUPS: ClassVar[tuple[TLFlagGroup, ...]] = ()

    def serialize(self) -> bytes:
        return self._serialize(boxed=True)

    def _serialize(self, *, boxed: bool = True) -> bytes:
        output = bytearray()
        if boxed:
            output.extend(encode_constructor_id(self.CONSTRUCTOR_ID))
        output.extend(encode_vector(self.chats, "long"))
        return bytes(output)

    @classmethod
    def deserialize(cls, data: bytes | memoryview) -> Self:
        obj, offset = cls._deserialize(data)
        if offset != len(data):
            raise TLCodecError("TL object payload has trailing bytes")
        return obj

    @classmethod
    def _deserialize(cls, data: bytes | memoryview, offset: int = 0, *, boxed: bool = True) -> tuple[Self, int]:
        raw_data = data
        cursor = offset
        if boxed:
            constructor_id, cursor = decode_constructor_id(raw_data, cursor)
            if constructor_id != cls.CONSTRUCTOR_ID:
                raise TLCodecError(f"expected constructor 0x{cls.CONSTRUCTOR_ID:08x}, got 0x{constructor_id:08x}")
        _value_chats, cursor = decode_vector(raw_data, cursor, "long")
        return cls(chats=_value_chats), cursor


@dataclass(frozen=True, slots=True, kw_only=True)
class MessageEntitySpoiler(TLConstructor):
    offset: int
    length: int
    CONSTRUCTOR_ID: ClassVar[int] = 0x32CA960F
    QUALNAME: ClassVar[str] = "messageEntitySpoiler"
    RESULT_TYPE: ClassVar[str] = "MessageEntity"
    TL_FIELDS: ClassVar[tuple[TLField, ...]] = (
        TLField(
            name="offset",
            python_name="offset",
            type="int",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="length",
            python_name="length",
            type="int",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
    )
    TL_FLAG_GROUPS: ClassVar[tuple[TLFlagGroup, ...]] = ()

    def serialize(self) -> bytes:
        return self._serialize(boxed=True)

    def _serialize(self, *, boxed: bool = True) -> bytes:
        output = bytearray()
        if boxed:
            output.extend(encode_constructor_id(self.CONSTRUCTOR_ID))
        output.extend(encode_int(self.offset))
        output.extend(encode_int(self.length))
        return bytes(output)

    @classmethod
    def deserialize(cls, data: bytes | memoryview) -> Self:
        obj, offset = cls._deserialize(data)
        if offset != len(data):
            raise TLCodecError("TL object payload has trailing bytes")
        return obj

    @classmethod
    def _deserialize(cls, data: bytes | memoryview, offset: int = 0, *, boxed: bool = True) -> tuple[Self, int]:
        raw_data = data
        cursor = offset
        if boxed:
            constructor_id, cursor = decode_constructor_id(raw_data, cursor)
            if constructor_id != cls.CONSTRUCTOR_ID:
                raise TLCodecError(f"expected constructor 0x{cls.CONSTRUCTOR_ID:08x}, got 0x{constructor_id:08x}")
        _value_offset, cursor = decode_int(raw_data, cursor)
        _value_length, cursor = decode_int(raw_data, cursor)
        return cls(offset=_value_offset, length=_value_length), cursor


@dataclass(frozen=True, slots=True, kw_only=True)
class TextEmpty(TLConstructor):
    pass
    CONSTRUCTOR_ID: ClassVar[int] = 0xDC3D824F
    QUALNAME: ClassVar[str] = "textEmpty"
    RESULT_TYPE: ClassVar[str] = "RichText"
    TL_FIELDS: ClassVar[tuple[TLField, ...]] = ()
    TL_FLAG_GROUPS: ClassVar[tuple[TLFlagGroup, ...]] = ()

    def serialize(self) -> bytes:
        return self._serialize(boxed=True)

    def _serialize(self, *, boxed: bool = True) -> bytes:
        output = bytearray()
        if boxed:
            output.extend(encode_constructor_id(self.CONSTRUCTOR_ID))
        return bytes(output)

    @classmethod
    def deserialize(cls, data: bytes | memoryview) -> Self:
        obj, offset = cls._deserialize(data)
        if offset != len(data):
            raise TLCodecError("TL object payload has trailing bytes")
        return obj

    @classmethod
    def _deserialize(cls, data: bytes | memoryview, offset: int = 0, *, boxed: bool = True) -> tuple[Self, int]:
        raw_data = data
        cursor = offset
        if boxed:
            constructor_id, cursor = decode_constructor_id(raw_data, cursor)
            if constructor_id != cls.CONSTRUCTOR_ID:
                raise TLCodecError(f"expected constructor 0x{cls.CONSTRUCTOR_ID:08x}, got 0x{constructor_id:08x}")
        return cls(), cursor


@dataclass(frozen=True, slots=True, kw_only=True)
class TextImage(TLConstructor):
    document_id: int
    w: int
    h: int
    CONSTRUCTOR_ID: ClassVar[int] = 0x081CCF4F
    QUALNAME: ClassVar[str] = "textImage"
    RESULT_TYPE: ClassVar[str] = "RichText"
    TL_FIELDS: ClassVar[tuple[TLField, ...]] = (
        TLField(
            name="document_id",
            python_name="document_id",
            type="long",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="w",
            python_name="w",
            type="int",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="h",
            python_name="h",
            type="int",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
    )
    TL_FLAG_GROUPS: ClassVar[tuple[TLFlagGroup, ...]] = ()

    def serialize(self) -> bytes:
        return self._serialize(boxed=True)

    def _serialize(self, *, boxed: bool = True) -> bytes:
        output = bytearray()
        if boxed:
            output.extend(encode_constructor_id(self.CONSTRUCTOR_ID))
        output.extend(encode_long(self.document_id))
        output.extend(encode_int(self.w))
        output.extend(encode_int(self.h))
        return bytes(output)

    @classmethod
    def deserialize(cls, data: bytes | memoryview) -> Self:
        obj, offset = cls._deserialize(data)
        if offset != len(data):
            raise TLCodecError("TL object payload has trailing bytes")
        return obj

    @classmethod
    def _deserialize(cls, data: bytes | memoryview, offset: int = 0, *, boxed: bool = True) -> tuple[Self, int]:
        raw_data = data
        cursor = offset
        if boxed:
            constructor_id, cursor = decode_constructor_id(raw_data, cursor)
            if constructor_id != cls.CONSTRUCTOR_ID:
                raise TLCodecError(f"expected constructor 0x{cls.CONSTRUCTOR_ID:08x}, got 0x{constructor_id:08x}")
        _value_document_id, cursor = decode_long(raw_data, cursor)
        _value_w, cursor = decode_int(raw_data, cursor)
        _value_h, cursor = decode_int(raw_data, cursor)
        return cls(document_id=_value_document_id, w=_value_w, h=_value_h), cursor


@dataclass(frozen=True, slots=True, kw_only=True)
class InputPaymentCredentialsSaved(TLConstructor):
    id: str
    tmp_password: bytes
    CONSTRUCTOR_ID: ClassVar[int] = 0xC10EB2CF
    QUALNAME: ClassVar[str] = "inputPaymentCredentialsSaved"
    RESULT_TYPE: ClassVar[str] = "InputPaymentCredentials"
    TL_FIELDS: ClassVar[tuple[TLField, ...]] = (
        TLField(
            name="id",
            python_name="id",
            type="string",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="tmp_password",
            python_name="tmp_password",
            type="bytes",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
    )
    TL_FLAG_GROUPS: ClassVar[tuple[TLFlagGroup, ...]] = ()

    def serialize(self) -> bytes:
        return self._serialize(boxed=True)

    def _serialize(self, *, boxed: bool = True) -> bytes:
        output = bytearray()
        if boxed:
            output.extend(encode_constructor_id(self.CONSTRUCTOR_ID))
        output.extend(encode_string(self.id))
        output.extend(encode_bytes(self.tmp_password))
        return bytes(output)

    @classmethod
    def deserialize(cls, data: bytes | memoryview) -> Self:
        obj, offset = cls._deserialize(data)
        if offset != len(data):
            raise TLCodecError("TL object payload has trailing bytes")
        return obj

    @classmethod
    def _deserialize(cls, data: bytes | memoryview, offset: int = 0, *, boxed: bool = True) -> tuple[Self, int]:
        raw_data = data
        cursor = offset
        if boxed:
            constructor_id, cursor = decode_constructor_id(raw_data, cursor)
            if constructor_id != cls.CONSTRUCTOR_ID:
                raise TLCodecError(f"expected constructor 0x{cls.CONSTRUCTOR_ID:08x}, got 0x{constructor_id:08x}")
        _value_id, cursor = decode_string(raw_data, cursor)
        _value_tmp_password, cursor = decode_bytes(raw_data, cursor)
        return cls(id=_value_id, tmp_password=_value_tmp_password), cursor


@dataclass(frozen=True, slots=True, kw_only=True)
class UploadCdnFile(TLConstructor):
    bytes: bytes
    CONSTRUCTOR_ID: ClassVar[int] = 0xA99FCA4F
    QUALNAME: ClassVar[str] = "upload.cdnFile"
    RESULT_TYPE: ClassVar[str] = "upload.CdnFile"
    TL_FIELDS: ClassVar[tuple[TLField, ...]] = (
        TLField(
            name="bytes",
            python_name="bytes",
            type="bytes",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
    )
    TL_FLAG_GROUPS: ClassVar[tuple[TLFlagGroup, ...]] = ()

    def serialize(self) -> bytes:
        return self._serialize(boxed=True)

    def _serialize(self, *, boxed: bool = True) -> bytes:
        native = encode_fast(self.CONSTRUCTOR_ID, (self.bytes,), boxed=boxed)
        if native is not None:
            return native
        output = bytearray()
        if boxed:
            output.extend(encode_constructor_id(self.CONSTRUCTOR_ID))
        output.extend(encode_bytes(self.bytes))
        return bytes(output)

    @classmethod
    def deserialize(cls, data: bytes | memoryview) -> Self:
        obj, offset = cls._deserialize(data)
        if offset != len(data):
            raise TLCodecError("TL object payload has trailing bytes")
        return obj

    @classmethod
    def _deserialize(cls, data: bytes | memoryview, offset: int = 0, *, boxed: bool = True) -> tuple[Self, int]:
        raw_data = data
        try:
            native = decode_fast(cls.CONSTRUCTOR_ID, raw_data, offset, boxed=boxed)
        except ValueError as exc:
            if str(exc).startswith("expected constructor "):
                raise TLCodecError(str(exc)) from exc
            raise
        if native is not None:
            values, cursor = native
            return cls(bytes=cast(bytes, values[0])), cursor
        cursor = offset
        if boxed:
            constructor_id, cursor = decode_constructor_id(raw_data, cursor)
            if constructor_id != cls.CONSTRUCTOR_ID:
                raise TLCodecError(f"expected constructor 0x{cls.CONSTRUCTOR_ID:08x}, got 0x{constructor_id:08x}")
        _value_bytes, cursor = decode_bytes(raw_data, cursor)
        return cls(bytes=_value_bytes), cursor


@dataclass(frozen=True, slots=True, kw_only=True)
class SecureValueError(TLConstructor):
    type: Any
    hash: bytes
    text: str
    CONSTRUCTOR_ID: ClassVar[int] = 0x869D758F
    QUALNAME: ClassVar[str] = "secureValueError"
    RESULT_TYPE: ClassVar[str] = "SecureValueError"
    TL_FIELDS: ClassVar[tuple[TLField, ...]] = (
        TLField(
            name="type",
            python_name="type",
            type="SecureValueType",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="hash",
            python_name="hash",
            type="bytes",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="text",
            python_name="text",
            type="string",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
    )
    TL_FLAG_GROUPS: ClassVar[tuple[TLFlagGroup, ...]] = ()

    def serialize(self) -> bytes:
        return self._serialize(boxed=True)

    def _serialize(self, *, boxed: bool = True) -> bytes:
        output = bytearray()
        if boxed:
            output.extend(encode_constructor_id(self.CONSTRUCTOR_ID))
        output.extend(encode_value("SecureValueType", self.type))
        output.extend(encode_bytes(self.hash))
        output.extend(encode_string(self.text))
        return bytes(output)

    @classmethod
    def deserialize(cls, data: bytes | memoryview) -> Self:
        obj, offset = cls._deserialize(data)
        if offset != len(data):
            raise TLCodecError("TL object payload has trailing bytes")
        return obj

    @classmethod
    def _deserialize(cls, data: bytes | memoryview, offset: int = 0, *, boxed: bool = True) -> tuple[Self, int]:
        raw_data = data
        cursor = offset
        if boxed:
            constructor_id, cursor = decode_constructor_id(raw_data, cursor)
            if constructor_id != cls.CONSTRUCTOR_ID:
                raise TLCodecError(f"expected constructor 0x{cls.CONSTRUCTOR_ID:08x}, got 0x{constructor_id:08x}")
        _value_type, cursor = decode_value("SecureValueType", raw_data, cursor)
        _value_hash, cursor = decode_bytes(raw_data, cursor)
        _value_text, cursor = decode_string(raw_data, cursor)
        return cls(type=_value_type, hash=_value_hash, text=_value_text), cursor


@dataclass(frozen=True, slots=True, kw_only=True)
class AccountSentEmailCode(TLConstructor):
    email_pattern: str
    length: int
    CONSTRUCTOR_ID: ClassVar[int] = 0x811F854F
    QUALNAME: ClassVar[str] = "account.sentEmailCode"
    RESULT_TYPE: ClassVar[str] = "account.SentEmailCode"
    TL_FIELDS: ClassVar[tuple[TLField, ...]] = (
        TLField(
            name="email_pattern",
            python_name="email_pattern",
            type="string",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="length",
            python_name="length",
            type="int",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
    )
    TL_FLAG_GROUPS: ClassVar[tuple[TLFlagGroup, ...]] = ()

    def serialize(self) -> bytes:
        return self._serialize(boxed=True)

    def _serialize(self, *, boxed: bool = True) -> bytes:
        output = bytearray()
        if boxed:
            output.extend(encode_constructor_id(self.CONSTRUCTOR_ID))
        output.extend(encode_string(self.email_pattern))
        output.extend(encode_int(self.length))
        return bytes(output)

    @classmethod
    def deserialize(cls, data: bytes | memoryview) -> Self:
        obj, offset = cls._deserialize(data)
        if offset != len(data):
            raise TLCodecError("TL object payload has trailing bytes")
        return obj

    @classmethod
    def _deserialize(cls, data: bytes | memoryview, offset: int = 0, *, boxed: bool = True) -> tuple[Self, int]:
        raw_data = data
        cursor = offset
        if boxed:
            constructor_id, cursor = decode_constructor_id(raw_data, cursor)
            if constructor_id != cls.CONSTRUCTOR_ID:
                raise TLCodecError(f"expected constructor 0x{cls.CONSTRUCTOR_ID:08x}, got 0x{constructor_id:08x}")
        _value_email_pattern, cursor = decode_string(raw_data, cursor)
        _value_length, cursor = decode_int(raw_data, cursor)
        return cls(email_pattern=_value_email_pattern, length=_value_length), cursor


@dataclass(frozen=True, slots=True, kw_only=True)
class InputThemeSettings(TLConstructor):
    message_colors_animated: bool = False
    base_theme: Any
    accent_color: int
    outbox_accent_color: int | None = None
    message_colors: tuple[int, ...] | None = None
    wallpaper: Any | None = None
    wallpaper_settings: Any | None = None
    CONSTRUCTOR_ID: ClassVar[int] = 0x8FDE504F
    QUALNAME: ClassVar[str] = "inputThemeSettings"
    RESULT_TYPE: ClassVar[str] = "InputThemeSettings"
    TL_FIELDS: ClassVar[tuple[TLField, ...]] = (
        TLField(
            name="message_colors_animated",
            python_name="message_colors_animated",
            type="true",
            flag="flags",
            flag_index=2,
            is_optional=True,
            is_true_flag=True,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="base_theme",
            python_name="base_theme",
            type="BaseTheme",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="accent_color",
            python_name="accent_color",
            type="int",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="outbox_accent_color",
            python_name="outbox_accent_color",
            type="int",
            flag="flags",
            flag_index=3,
            is_optional=True,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="message_colors",
            python_name="message_colors",
            type="Vector<int>",
            flag="flags",
            flag_index=0,
            is_optional=True,
            is_true_flag=False,
            is_vector=True,
            vector_item_type="int",
        ),
        TLField(
            name="wallpaper",
            python_name="wallpaper",
            type="InputWallPaper",
            flag="flags",
            flag_index=1,
            is_optional=True,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="wallpaper_settings",
            python_name="wallpaper_settings",
            type="WallPaperSettings",
            flag="flags",
            flag_index=1,
            is_optional=True,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
    )
    TL_FLAG_GROUPS: ClassVar[tuple[TLFlagGroup, ...]] = (
        TLFlagGroup(name="flags", python_name="flags", before_field_index=0),
    )

    def serialize(self) -> bytes:
        return self._serialize(boxed=True)

    def _serialize(self, *, boxed: bool = True) -> bytes:
        output = bytearray()
        if boxed:
            output.extend(encode_constructor_id(self.CONSTRUCTOR_ID))
        flags = 0
        if self.message_colors_animated:
            flags |= 4
        if self.outbox_accent_color is not None:
            flags |= 8
        if self.message_colors is not None:
            flags |= 1
        if self.wallpaper is not None:
            flags |= 2
        if self.wallpaper_settings is not None:
            flags |= 2
        output.extend(encode_int(flags))
        output.extend(encode_value("BaseTheme", self.base_theme))
        output.extend(encode_int(self.accent_color))
        if self.outbox_accent_color is not None:
            output.extend(encode_int(self.outbox_accent_color))
        if self.message_colors is not None:
            output.extend(encode_vector(self.message_colors, "int"))
        if self.wallpaper is not None:
            output.extend(encode_value("InputWallPaper", self.wallpaper))
        if self.wallpaper_settings is not None:
            output.extend(encode_value("WallPaperSettings", self.wallpaper_settings))
        return bytes(output)

    @classmethod
    def deserialize(cls, data: bytes | memoryview) -> Self:
        obj, offset = cls._deserialize(data)
        if offset != len(data):
            raise TLCodecError("TL object payload has trailing bytes")
        return obj

    @classmethod
    def _deserialize(cls, data: bytes | memoryview, offset: int = 0, *, boxed: bool = True) -> tuple[Self, int]:
        raw_data = data
        cursor = offset
        if boxed:
            constructor_id, cursor = decode_constructor_id(raw_data, cursor)
            if constructor_id != cls.CONSTRUCTOR_ID:
                raise TLCodecError(f"expected constructor 0x{cls.CONSTRUCTOR_ID:08x}, got 0x{constructor_id:08x}")
        flags = 0
        flags, cursor = decode_int(raw_data, cursor)
        _value_message_colors_animated = bool(flags & 4)
        _value_base_theme, cursor = decode_value("BaseTheme", raw_data, cursor)
        _value_accent_color, cursor = decode_int(raw_data, cursor)
        if bool(flags & 8):
            _value_outbox_accent_color, cursor = decode_int(raw_data, cursor)
        else:
            _value_outbox_accent_color = None
        if bool(flags & 1):
            _value_message_colors, cursor = decode_vector(raw_data, cursor, "int")
        else:
            _value_message_colors = None
        if bool(flags & 2):
            _value_wallpaper, cursor = decode_value("InputWallPaper", raw_data, cursor)
        else:
            _value_wallpaper = None
        if bool(flags & 2):
            _value_wallpaper_settings, cursor = decode_value("WallPaperSettings", raw_data, cursor)
        else:
            _value_wallpaper_settings = None
        return cls(
            message_colors_animated=_value_message_colors_animated,
            base_theme=_value_base_theme,
            accent_color=_value_accent_color,
            outbox_accent_color=_value_outbox_accent_color,
            message_colors=_value_message_colors,
            wallpaper=_value_wallpaper,
            wallpaper_settings=_value_wallpaper_settings,
        ), cursor


@dataclass(frozen=True, slots=True, kw_only=True)
class GlobalPrivacySettings(TLConstructor):
    archive_and_mute_new_noncontact_peers: bool = False
    keep_archived_unmuted: bool = False
    keep_archived_folders: bool = False
    hide_read_marks: bool = False
    new_noncontact_peers_require_premium: bool = False
    display_gifts_button: bool = False
    noncontact_peers_paid_stars: int | None = None
    disallowed_gifts: Any | None = None
    CONSTRUCTOR_ID: ClassVar[int] = 0xFE41B34F
    QUALNAME: ClassVar[str] = "globalPrivacySettings"
    RESULT_TYPE: ClassVar[str] = "GlobalPrivacySettings"
    TL_FIELDS: ClassVar[tuple[TLField, ...]] = (
        TLField(
            name="archive_and_mute_new_noncontact_peers",
            python_name="archive_and_mute_new_noncontact_peers",
            type="true",
            flag="flags",
            flag_index=0,
            is_optional=True,
            is_true_flag=True,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="keep_archived_unmuted",
            python_name="keep_archived_unmuted",
            type="true",
            flag="flags",
            flag_index=1,
            is_optional=True,
            is_true_flag=True,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="keep_archived_folders",
            python_name="keep_archived_folders",
            type="true",
            flag="flags",
            flag_index=2,
            is_optional=True,
            is_true_flag=True,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="hide_read_marks",
            python_name="hide_read_marks",
            type="true",
            flag="flags",
            flag_index=3,
            is_optional=True,
            is_true_flag=True,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="new_noncontact_peers_require_premium",
            python_name="new_noncontact_peers_require_premium",
            type="true",
            flag="flags",
            flag_index=4,
            is_optional=True,
            is_true_flag=True,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="display_gifts_button",
            python_name="display_gifts_button",
            type="true",
            flag="flags",
            flag_index=7,
            is_optional=True,
            is_true_flag=True,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="noncontact_peers_paid_stars",
            python_name="noncontact_peers_paid_stars",
            type="long",
            flag="flags",
            flag_index=5,
            is_optional=True,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="disallowed_gifts",
            python_name="disallowed_gifts",
            type="DisallowedGiftsSettings",
            flag="flags",
            flag_index=6,
            is_optional=True,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
    )
    TL_FLAG_GROUPS: ClassVar[tuple[TLFlagGroup, ...]] = (
        TLFlagGroup(name="flags", python_name="flags", before_field_index=0),
    )

    def serialize(self) -> bytes:
        return self._serialize(boxed=True)

    def _serialize(self, *, boxed: bool = True) -> bytes:
        output = bytearray()
        if boxed:
            output.extend(encode_constructor_id(self.CONSTRUCTOR_ID))
        flags = 0
        if self.archive_and_mute_new_noncontact_peers:
            flags |= 1
        if self.keep_archived_unmuted:
            flags |= 2
        if self.keep_archived_folders:
            flags |= 4
        if self.hide_read_marks:
            flags |= 8
        if self.new_noncontact_peers_require_premium:
            flags |= 16
        if self.display_gifts_button:
            flags |= 128
        if self.noncontact_peers_paid_stars is not None:
            flags |= 32
        if self.disallowed_gifts is not None:
            flags |= 64
        output.extend(encode_int(flags))
        if self.noncontact_peers_paid_stars is not None:
            output.extend(encode_long(self.noncontact_peers_paid_stars))
        if self.disallowed_gifts is not None:
            output.extend(encode_value("DisallowedGiftsSettings", self.disallowed_gifts))
        return bytes(output)

    @classmethod
    def deserialize(cls, data: bytes | memoryview) -> Self:
        obj, offset = cls._deserialize(data)
        if offset != len(data):
            raise TLCodecError("TL object payload has trailing bytes")
        return obj

    @classmethod
    def _deserialize(cls, data: bytes | memoryview, offset: int = 0, *, boxed: bool = True) -> tuple[Self, int]:
        raw_data = data
        cursor = offset
        if boxed:
            constructor_id, cursor = decode_constructor_id(raw_data, cursor)
            if constructor_id != cls.CONSTRUCTOR_ID:
                raise TLCodecError(f"expected constructor 0x{cls.CONSTRUCTOR_ID:08x}, got 0x{constructor_id:08x}")
        flags = 0
        flags, cursor = decode_int(raw_data, cursor)
        _value_archive_and_mute_new_noncontact_peers = bool(flags & 1)
        _value_keep_archived_unmuted = bool(flags & 2)
        _value_keep_archived_folders = bool(flags & 4)
        _value_hide_read_marks = bool(flags & 8)
        _value_new_noncontact_peers_require_premium = bool(flags & 16)
        _value_display_gifts_button = bool(flags & 128)
        if bool(flags & 32):
            _value_noncontact_peers_paid_stars, cursor = decode_long(raw_data, cursor)
        else:
            _value_noncontact_peers_paid_stars = None
        if bool(flags & 64):
            _value_disallowed_gifts, cursor = decode_value("DisallowedGiftsSettings", raw_data, cursor)
        else:
            _value_disallowed_gifts = None
        return cls(
            archive_and_mute_new_noncontact_peers=_value_archive_and_mute_new_noncontact_peers,
            keep_archived_unmuted=_value_keep_archived_unmuted,
            keep_archived_folders=_value_keep_archived_folders,
            hide_read_marks=_value_hide_read_marks,
            new_noncontact_peers_require_premium=_value_new_noncontact_peers_require_premium,
            display_gifts_button=_value_display_gifts_button,
            noncontact_peers_paid_stars=_value_noncontact_peers_paid_stars,
            disallowed_gifts=_value_disallowed_gifts,
        ), cursor


@dataclass(frozen=True, slots=True, kw_only=True)
class InputGroupCall(TLConstructor):
    id: int
    access_hash: int
    CONSTRUCTOR_ID: ClassVar[int] = 0xD8AA840F
    QUALNAME: ClassVar[str] = "inputGroupCall"
    RESULT_TYPE: ClassVar[str] = "InputGroupCall"
    TL_FIELDS: ClassVar[tuple[TLField, ...]] = (
        TLField(
            name="id",
            python_name="id",
            type="long",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="access_hash",
            python_name="access_hash",
            type="long",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
    )
    TL_FLAG_GROUPS: ClassVar[tuple[TLFlagGroup, ...]] = ()

    def serialize(self) -> bytes:
        return self._serialize(boxed=True)

    def _serialize(self, *, boxed: bool = True) -> bytes:
        output = bytearray()
        if boxed:
            output.extend(encode_constructor_id(self.CONSTRUCTOR_ID))
        output.extend(encode_long(self.id))
        output.extend(encode_long(self.access_hash))
        return bytes(output)

    @classmethod
    def deserialize(cls, data: bytes | memoryview) -> Self:
        obj, offset = cls._deserialize(data)
        if offset != len(data):
            raise TLCodecError("TL object payload has trailing bytes")
        return obj

    @classmethod
    def _deserialize(cls, data: bytes | memoryview, offset: int = 0, *, boxed: bool = True) -> tuple[Self, int]:
        raw_data = data
        cursor = offset
        if boxed:
            constructor_id, cursor = decode_constructor_id(raw_data, cursor)
            if constructor_id != cls.CONSTRUCTOR_ID:
                raise TLCodecError(f"expected constructor 0x{cls.CONSTRUCTOR_ID:08x}, got 0x{constructor_id:08x}")
        _value_id, cursor = decode_long(raw_data, cursor)
        _value_access_hash, cursor = decode_long(raw_data, cursor)
        return cls(id=_value_id, access_hash=_value_access_hash), cursor


@dataclass(frozen=True, slots=True, kw_only=True)
class MessagesSponsoredMessagesEmpty(TLConstructor):
    pass
    CONSTRUCTOR_ID: ClassVar[int] = 0x1839490F
    QUALNAME: ClassVar[str] = "messages.sponsoredMessagesEmpty"
    RESULT_TYPE: ClassVar[str] = "messages.SponsoredMessages"
    TL_FIELDS: ClassVar[tuple[TLField, ...]] = ()
    TL_FLAG_GROUPS: ClassVar[tuple[TLFlagGroup, ...]] = ()

    def serialize(self) -> bytes:
        return self._serialize(boxed=True)

    def _serialize(self, *, boxed: bool = True) -> bytes:
        output = bytearray()
        if boxed:
            output.extend(encode_constructor_id(self.CONSTRUCTOR_ID))
        return bytes(output)

    @classmethod
    def deserialize(cls, data: bytes | memoryview) -> Self:
        obj, offset = cls._deserialize(data)
        if offset != len(data):
            raise TLCodecError("TL object payload has trailing bytes")
        return obj

    @classmethod
    def _deserialize(cls, data: bytes | memoryview, offset: int = 0, *, boxed: bool = True) -> tuple[Self, int]:
        raw_data = data
        cursor = offset
        if boxed:
            constructor_id, cursor = decode_constructor_id(raw_data, cursor)
            if constructor_id != cls.CONSTRUCTOR_ID:
                raise TLCodecError(f"expected constructor 0x{cls.CONSTRUCTOR_ID:08x}, got 0x{constructor_id:08x}")
        return cls(), cursor


@dataclass(frozen=True, slots=True, kw_only=True)
class StoryItemDeleted(TLConstructor):
    id: int
    CONSTRUCTOR_ID: ClassVar[int] = 0x51E6EE4F
    QUALNAME: ClassVar[str] = "storyItemDeleted"
    RESULT_TYPE: ClassVar[str] = "StoryItem"
    TL_FIELDS: ClassVar[tuple[TLField, ...]] = (
        TLField(
            name="id",
            python_name="id",
            type="int",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
    )
    TL_FLAG_GROUPS: ClassVar[tuple[TLFlagGroup, ...]] = ()

    def serialize(self) -> bytes:
        return self._serialize(boxed=True)

    def _serialize(self, *, boxed: bool = True) -> bytes:
        output = bytearray()
        if boxed:
            output.extend(encode_constructor_id(self.CONSTRUCTOR_ID))
        output.extend(encode_int(self.id))
        return bytes(output)

    @classmethod
    def deserialize(cls, data: bytes | memoryview) -> Self:
        obj, offset = cls._deserialize(data)
        if offset != len(data):
            raise TLCodecError("TL object payload has trailing bytes")
        return obj

    @classmethod
    def _deserialize(cls, data: bytes | memoryview, offset: int = 0, *, boxed: bool = True) -> tuple[Self, int]:
        raw_data = data
        cursor = offset
        if boxed:
            constructor_id, cursor = decode_constructor_id(raw_data, cursor)
            if constructor_id != cls.CONSTRUCTOR_ID:
                raise TLCodecError(f"expected constructor 0x{cls.CONSTRUCTOR_ID:08x}, got 0x{constructor_id:08x}")
        _value_id, cursor = decode_int(raw_data, cursor)
        return cls(id=_value_id), cursor


@dataclass(frozen=True, slots=True, kw_only=True)
class PaymentsCheckedGiftCode(TLConstructor):
    via_giveaway: bool = False
    from_id: Any | None = None
    giveaway_msg_id: int | None = None
    to_id: int | None = None
    date: int
    days: int
    used_date: int | None = None
    chats: tuple[Any, ...]
    users: tuple[Any, ...]
    CONSTRUCTOR_ID: ClassVar[int] = 0xEB983F8F
    QUALNAME: ClassVar[str] = "payments.checkedGiftCode"
    RESULT_TYPE: ClassVar[str] = "payments.CheckedGiftCode"
    TL_FIELDS: ClassVar[tuple[TLField, ...]] = (
        TLField(
            name="via_giveaway",
            python_name="via_giveaway",
            type="true",
            flag="flags",
            flag_index=2,
            is_optional=True,
            is_true_flag=True,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="from_id",
            python_name="from_id",
            type="Peer",
            flag="flags",
            flag_index=4,
            is_optional=True,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="giveaway_msg_id",
            python_name="giveaway_msg_id",
            type="int",
            flag="flags",
            flag_index=3,
            is_optional=True,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="to_id",
            python_name="to_id",
            type="long",
            flag="flags",
            flag_index=0,
            is_optional=True,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="date",
            python_name="date",
            type="int",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="days",
            python_name="days",
            type="int",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="used_date",
            python_name="used_date",
            type="int",
            flag="flags",
            flag_index=1,
            is_optional=True,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="chats",
            python_name="chats",
            type="Vector<Chat>",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=True,
            vector_item_type="Chat",
        ),
        TLField(
            name="users",
            python_name="users",
            type="Vector<User>",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=True,
            vector_item_type="User",
        ),
    )
    TL_FLAG_GROUPS: ClassVar[tuple[TLFlagGroup, ...]] = (
        TLFlagGroup(name="flags", python_name="flags", before_field_index=0),
    )

    def serialize(self) -> bytes:
        return self._serialize(boxed=True)

    def _serialize(self, *, boxed: bool = True) -> bytes:
        output = bytearray()
        if boxed:
            output.extend(encode_constructor_id(self.CONSTRUCTOR_ID))
        flags = 0
        if self.via_giveaway:
            flags |= 4
        if self.from_id is not None:
            flags |= 16
        if self.giveaway_msg_id is not None:
            flags |= 8
        if self.to_id is not None:
            flags |= 1
        if self.used_date is not None:
            flags |= 2
        output.extend(encode_int(flags))
        if self.from_id is not None:
            output.extend(encode_value("Peer", self.from_id))
        if self.giveaway_msg_id is not None:
            output.extend(encode_int(self.giveaway_msg_id))
        if self.to_id is not None:
            output.extend(encode_long(self.to_id))
        output.extend(encode_int(self.date))
        output.extend(encode_int(self.days))
        if self.used_date is not None:
            output.extend(encode_int(self.used_date))
        output.extend(encode_vector(self.chats, "Chat"))
        output.extend(encode_vector(self.users, "User"))
        return bytes(output)

    @classmethod
    def deserialize(cls, data: bytes | memoryview) -> Self:
        obj, offset = cls._deserialize(data)
        if offset != len(data):
            raise TLCodecError("TL object payload has trailing bytes")
        return obj

    @classmethod
    def _deserialize(cls, data: bytes | memoryview, offset: int = 0, *, boxed: bool = True) -> tuple[Self, int]:
        raw_data = data
        cursor = offset
        if boxed:
            constructor_id, cursor = decode_constructor_id(raw_data, cursor)
            if constructor_id != cls.CONSTRUCTOR_ID:
                raise TLCodecError(f"expected constructor 0x{cls.CONSTRUCTOR_ID:08x}, got 0x{constructor_id:08x}")
        flags = 0
        flags, cursor = decode_int(raw_data, cursor)
        _value_via_giveaway = bool(flags & 4)
        if bool(flags & 16):
            _value_from_id, cursor = decode_value("Peer", raw_data, cursor)
        else:
            _value_from_id = None
        if bool(flags & 8):
            _value_giveaway_msg_id, cursor = decode_int(raw_data, cursor)
        else:
            _value_giveaway_msg_id = None
        if bool(flags & 1):
            _value_to_id, cursor = decode_long(raw_data, cursor)
        else:
            _value_to_id = None
        _value_date, cursor = decode_int(raw_data, cursor)
        _value_days, cursor = decode_int(raw_data, cursor)
        if bool(flags & 2):
            _value_used_date, cursor = decode_int(raw_data, cursor)
        else:
            _value_used_date = None
        _value_chats, cursor = decode_vector(raw_data, cursor, "Chat")
        _value_users, cursor = decode_vector(raw_data, cursor, "User")
        return cls(
            via_giveaway=_value_via_giveaway,
            from_id=_value_from_id,
            giveaway_msg_id=_value_giveaway_msg_id,
            to_id=_value_to_id,
            date=_value_date,
            days=_value_days,
            used_date=_value_used_date,
            chats=_value_chats,
            users=_value_users,
        ), cursor


@dataclass(frozen=True, slots=True, kw_only=True)
class PeerColor(TLConstructor):
    color: int | None = None
    background_emoji_id: int | None = None
    CONSTRUCTOR_ID: ClassVar[int] = 0xB54B5ACF
    QUALNAME: ClassVar[str] = "peerColor"
    RESULT_TYPE: ClassVar[str] = "PeerColor"
    TL_FIELDS: ClassVar[tuple[TLField, ...]] = (
        TLField(
            name="color",
            python_name="color",
            type="int",
            flag="flags",
            flag_index=0,
            is_optional=True,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="background_emoji_id",
            python_name="background_emoji_id",
            type="long",
            flag="flags",
            flag_index=1,
            is_optional=True,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
    )
    TL_FLAG_GROUPS: ClassVar[tuple[TLFlagGroup, ...]] = (
        TLFlagGroup(name="flags", python_name="flags", before_field_index=0),
    )

    def serialize(self) -> bytes:
        return self._serialize(boxed=True)

    def _serialize(self, *, boxed: bool = True) -> bytes:
        output = bytearray()
        if boxed:
            output.extend(encode_constructor_id(self.CONSTRUCTOR_ID))
        flags = 0
        if self.color is not None:
            flags |= 1
        if self.background_emoji_id is not None:
            flags |= 2
        output.extend(encode_int(flags))
        if self.color is not None:
            output.extend(encode_int(self.color))
        if self.background_emoji_id is not None:
            output.extend(encode_long(self.background_emoji_id))
        return bytes(output)

    @classmethod
    def deserialize(cls, data: bytes | memoryview) -> Self:
        obj, offset = cls._deserialize(data)
        if offset != len(data):
            raise TLCodecError("TL object payload has trailing bytes")
        return obj

    @classmethod
    def _deserialize(cls, data: bytes | memoryview, offset: int = 0, *, boxed: bool = True) -> tuple[Self, int]:
        raw_data = data
        cursor = offset
        if boxed:
            constructor_id, cursor = decode_constructor_id(raw_data, cursor)
            if constructor_id != cls.CONSTRUCTOR_ID:
                raise TLCodecError(f"expected constructor 0x{cls.CONSTRUCTOR_ID:08x}, got 0x{constructor_id:08x}")
        flags = 0
        flags, cursor = decode_int(raw_data, cursor)
        if bool(flags & 1):
            _value_color, cursor = decode_int(raw_data, cursor)
        else:
            _value_color = None
        if bool(flags & 2):
            _value_background_emoji_id, cursor = decode_long(raw_data, cursor)
        else:
            _value_background_emoji_id = None
        return cls(color=_value_color, background_emoji_id=_value_background_emoji_id), cursor


@dataclass(frozen=True, slots=True, kw_only=True)
class SmsjobsEligibleToJoin(TLConstructor):
    terms_url: str
    monthly_sent_sms: int
    CONSTRUCTOR_ID: ClassVar[int] = 0xDC8B44CF
    QUALNAME: ClassVar[str] = "smsjobs.eligibleToJoin"
    RESULT_TYPE: ClassVar[str] = "smsjobs.EligibilityToJoin"
    TL_FIELDS: ClassVar[tuple[TLField, ...]] = (
        TLField(
            name="terms_url",
            python_name="terms_url",
            type="string",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="monthly_sent_sms",
            python_name="monthly_sent_sms",
            type="int",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
    )
    TL_FLAG_GROUPS: ClassVar[tuple[TLFlagGroup, ...]] = ()

    def serialize(self) -> bytes:
        return self._serialize(boxed=True)

    def _serialize(self, *, boxed: bool = True) -> bytes:
        output = bytearray()
        if boxed:
            output.extend(encode_constructor_id(self.CONSTRUCTOR_ID))
        output.extend(encode_string(self.terms_url))
        output.extend(encode_int(self.monthly_sent_sms))
        return bytes(output)

    @classmethod
    def deserialize(cls, data: bytes | memoryview) -> Self:
        obj, offset = cls._deserialize(data)
        if offset != len(data):
            raise TLCodecError("TL object payload has trailing bytes")
        return obj

    @classmethod
    def _deserialize(cls, data: bytes | memoryview, offset: int = 0, *, boxed: bool = True) -> tuple[Self, int]:
        raw_data = data
        cursor = offset
        if boxed:
            constructor_id, cursor = decode_constructor_id(raw_data, cursor)
            if constructor_id != cls.CONSTRUCTOR_ID:
                raise TLCodecError(f"expected constructor 0x{cls.CONSTRUCTOR_ID:08x}, got 0x{constructor_id:08x}")
        _value_terms_url, cursor = decode_string(raw_data, cursor)
        _value_monthly_sent_sms, cursor = decode_int(raw_data, cursor)
        return cls(terms_url=_value_terms_url, monthly_sent_sms=_value_monthly_sent_sms), cursor


@dataclass(frozen=True, slots=True, kw_only=True)
class RequestedPeerChat(TLConstructor):
    chat_id: int
    title: str | None = None
    photo: Any | None = None
    CONSTRUCTOR_ID: ClassVar[int] = 0x7307544F
    QUALNAME: ClassVar[str] = "requestedPeerChat"
    RESULT_TYPE: ClassVar[str] = "RequestedPeer"
    TL_FIELDS: ClassVar[tuple[TLField, ...]] = (
        TLField(
            name="chat_id",
            python_name="chat_id",
            type="long",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="title",
            python_name="title",
            type="string",
            flag="flags",
            flag_index=0,
            is_optional=True,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="photo",
            python_name="photo",
            type="Photo",
            flag="flags",
            flag_index=2,
            is_optional=True,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
    )
    TL_FLAG_GROUPS: ClassVar[tuple[TLFlagGroup, ...]] = (
        TLFlagGroup(name="flags", python_name="flags", before_field_index=0),
    )

    def serialize(self) -> bytes:
        return self._serialize(boxed=True)

    def _serialize(self, *, boxed: bool = True) -> bytes:
        output = bytearray()
        if boxed:
            output.extend(encode_constructor_id(self.CONSTRUCTOR_ID))
        flags = 0
        if self.title is not None:
            flags |= 1
        if self.photo is not None:
            flags |= 4
        output.extend(encode_int(flags))
        output.extend(encode_long(self.chat_id))
        if self.title is not None:
            output.extend(encode_string(self.title))
        if self.photo is not None:
            output.extend(encode_value("Photo", self.photo))
        return bytes(output)

    @classmethod
    def deserialize(cls, data: bytes | memoryview) -> Self:
        obj, offset = cls._deserialize(data)
        if offset != len(data):
            raise TLCodecError("TL object payload has trailing bytes")
        return obj

    @classmethod
    def _deserialize(cls, data: bytes | memoryview, offset: int = 0, *, boxed: bool = True) -> tuple[Self, int]:
        raw_data = data
        cursor = offset
        if boxed:
            constructor_id, cursor = decode_constructor_id(raw_data, cursor)
            if constructor_id != cls.CONSTRUCTOR_ID:
                raise TLCodecError(f"expected constructor 0x{cls.CONSTRUCTOR_ID:08x}, got 0x{constructor_id:08x}")
        flags = 0
        flags, cursor = decode_int(raw_data, cursor)
        _value_chat_id, cursor = decode_long(raw_data, cursor)
        if bool(flags & 1):
            _value_title, cursor = decode_string(raw_data, cursor)
        else:
            _value_title = None
        if bool(flags & 4):
            _value_photo, cursor = decode_value("Photo", raw_data, cursor)
        else:
            _value_photo = None
        return cls(chat_id=_value_chat_id, title=_value_title, photo=_value_photo), cursor


@dataclass(frozen=True, slots=True, kw_only=True)
class FactCheck(TLConstructor):
    need_check: bool = False
    country: str | None = None
    text: Any | None = None
    hash: int
    CONSTRUCTOR_ID: ClassVar[int] = 0xB89BFCCF
    QUALNAME: ClassVar[str] = "factCheck"
    RESULT_TYPE: ClassVar[str] = "FactCheck"
    TL_FIELDS: ClassVar[tuple[TLField, ...]] = (
        TLField(
            name="need_check",
            python_name="need_check",
            type="true",
            flag="flags",
            flag_index=0,
            is_optional=True,
            is_true_flag=True,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="country",
            python_name="country",
            type="string",
            flag="flags",
            flag_index=1,
            is_optional=True,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="text",
            python_name="text",
            type="TextWithEntities",
            flag="flags",
            flag_index=1,
            is_optional=True,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="hash",
            python_name="hash",
            type="long",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
    )
    TL_FLAG_GROUPS: ClassVar[tuple[TLFlagGroup, ...]] = (
        TLFlagGroup(name="flags", python_name="flags", before_field_index=0),
    )

    def serialize(self) -> bytes:
        return self._serialize(boxed=True)

    def _serialize(self, *, boxed: bool = True) -> bytes:
        output = bytearray()
        if boxed:
            output.extend(encode_constructor_id(self.CONSTRUCTOR_ID))
        flags = 0
        if self.need_check:
            flags |= 1
        if self.country is not None:
            flags |= 2
        if self.text is not None:
            flags |= 2
        output.extend(encode_int(flags))
        if self.country is not None:
            output.extend(encode_string(self.country))
        if self.text is not None:
            output.extend(encode_value("TextWithEntities", self.text))
        output.extend(encode_long(self.hash))
        return bytes(output)

    @classmethod
    def deserialize(cls, data: bytes | memoryview) -> Self:
        obj, offset = cls._deserialize(data)
        if offset != len(data):
            raise TLCodecError("TL object payload has trailing bytes")
        return obj

    @classmethod
    def _deserialize(cls, data: bytes | memoryview, offset: int = 0, *, boxed: bool = True) -> tuple[Self, int]:
        raw_data = data
        cursor = offset
        if boxed:
            constructor_id, cursor = decode_constructor_id(raw_data, cursor)
            if constructor_id != cls.CONSTRUCTOR_ID:
                raise TLCodecError(f"expected constructor 0x{cls.CONSTRUCTOR_ID:08x}, got 0x{constructor_id:08x}")
        flags = 0
        flags, cursor = decode_int(raw_data, cursor)
        _value_need_check = bool(flags & 1)
        if bool(flags & 2):
            _value_country, cursor = decode_string(raw_data, cursor)
        else:
            _value_country = None
        if bool(flags & 2):
            _value_text, cursor = decode_value("TextWithEntities", raw_data, cursor)
        else:
            _value_text = None
        _value_hash, cursor = decode_long(raw_data, cursor)
        return cls(need_check=_value_need_check, country=_value_country, text=_value_text, hash=_value_hash), cursor


@dataclass(frozen=True, slots=True, kw_only=True)
class InputPasskeyCredentialPublicKey(TLConstructor):
    id: str
    raw_id: str
    response: Any
    CONSTRUCTOR_ID: ClassVar[int] = 0x3C27B78F
    QUALNAME: ClassVar[str] = "inputPasskeyCredentialPublicKey"
    RESULT_TYPE: ClassVar[str] = "InputPasskeyCredential"
    TL_FIELDS: ClassVar[tuple[TLField, ...]] = (
        TLField(
            name="id",
            python_name="id",
            type="string",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="raw_id",
            python_name="raw_id",
            type="string",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
        TLField(
            name="response",
            python_name="response",
            type="InputPasskeyResponse",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
    )
    TL_FLAG_GROUPS: ClassVar[tuple[TLFlagGroup, ...]] = ()

    def serialize(self) -> bytes:
        return self._serialize(boxed=True)

    def _serialize(self, *, boxed: bool = True) -> bytes:
        output = bytearray()
        if boxed:
            output.extend(encode_constructor_id(self.CONSTRUCTOR_ID))
        output.extend(encode_string(self.id))
        output.extend(encode_string(self.raw_id))
        output.extend(encode_value("InputPasskeyResponse", self.response))
        return bytes(output)

    @classmethod
    def deserialize(cls, data: bytes | memoryview) -> Self:
        obj, offset = cls._deserialize(data)
        if offset != len(data):
            raise TLCodecError("TL object payload has trailing bytes")
        return obj

    @classmethod
    def _deserialize(cls, data: bytes | memoryview, offset: int = 0, *, boxed: bool = True) -> tuple[Self, int]:
        raw_data = data
        cursor = offset
        if boxed:
            constructor_id, cursor = decode_constructor_id(raw_data, cursor)
            if constructor_id != cls.CONSTRUCTOR_ID:
                raise TLCodecError(f"expected constructor 0x{cls.CONSTRUCTOR_ID:08x}, got 0x{constructor_id:08x}")
        _value_id, cursor = decode_string(raw_data, cursor)
        _value_raw_id, cursor = decode_string(raw_data, cursor)
        _value_response, cursor = decode_value("InputPasskeyResponse", raw_data, cursor)
        return cls(id=_value_id, raw_id=_value_raw_id, response=_value_response), cursor


@dataclass(frozen=True, slots=True, kw_only=True)
class MessagesTranslatedRichMessage(TLConstructor):
    result: tuple[Any, ...]
    CONSTRUCTOR_ID: ClassVar[int] = 0x4203998F
    QUALNAME: ClassVar[str] = "messages.translatedRichMessage"
    RESULT_TYPE: ClassVar[str] = "messages.TranslatedRichMessage"
    TL_FIELDS: ClassVar[tuple[TLField, ...]] = (
        TLField(
            name="result",
            python_name="result",
            type="Vector<RichMessage>",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=True,
            vector_item_type="RichMessage",
        ),
    )
    TL_FLAG_GROUPS: ClassVar[tuple[TLFlagGroup, ...]] = ()

    def serialize(self) -> bytes:
        return self._serialize(boxed=True)

    def _serialize(self, *, boxed: bool = True) -> bytes:
        output = bytearray()
        if boxed:
            output.extend(encode_constructor_id(self.CONSTRUCTOR_ID))
        output.extend(encode_vector(self.result, "RichMessage"))
        return bytes(output)

    @classmethod
    def deserialize(cls, data: bytes | memoryview) -> Self:
        obj, offset = cls._deserialize(data)
        if offset != len(data):
            raise TLCodecError("TL object payload has trailing bytes")
        return obj

    @classmethod
    def _deserialize(cls, data: bytes | memoryview, offset: int = 0, *, boxed: bool = True) -> tuple[Self, int]:
        raw_data = data
        cursor = offset
        if boxed:
            constructor_id, cursor = decode_constructor_id(raw_data, cursor)
            if constructor_id != cls.CONSTRUCTOR_ID:
                raise TLCodecError(f"expected constructor 0x{cls.CONSTRUCTOR_ID:08x}, got 0x{constructor_id:08x}")
        _value_result, cursor = decode_vector(raw_data, cursor, "RichMessage")
        return cls(result=_value_result), cursor


@dataclass(frozen=True, slots=True, kw_only=True)
class InlineButtonTypeUserProfile(TLConstructor):
    user_id: int
    CONSTRUCTOR_ID: ClassVar[int] = 0x3FA33FCF
    QUALNAME: ClassVar[str] = "inlineButtonTypeUserProfile"
    RESULT_TYPE: ClassVar[str] = "InlineButtonType"
    TL_FIELDS: ClassVar[tuple[TLField, ...]] = (
        TLField(
            name="user_id",
            python_name="user_id",
            type="long",
            flag=None,
            flag_index=None,
            is_optional=False,
            is_true_flag=False,
            is_vector=False,
            vector_item_type=None,
        ),
    )
    TL_FLAG_GROUPS: ClassVar[tuple[TLFlagGroup, ...]] = ()

    def serialize(self) -> bytes:
        return self._serialize(boxed=True)

    def _serialize(self, *, boxed: bool = True) -> bytes:
        output = bytearray()
        if boxed:
            output.extend(encode_constructor_id(self.CONSTRUCTOR_ID))
        output.extend(encode_long(self.user_id))
        return bytes(output)

    @classmethod
    def deserialize(cls, data: bytes | memoryview) -> Self:
        obj, offset = cls._deserialize(data)
        if offset != len(data):
            raise TLCodecError("TL object payload has trailing bytes")
        return obj

    @classmethod
    def _deserialize(cls, data: bytes | memoryview, offset: int = 0, *, boxed: bool = True) -> tuple[Self, int]:
        raw_data = data
        cursor = offset
        if boxed:
            constructor_id, cursor = decode_constructor_id(raw_data, cursor)
            if constructor_id != cls.CONSTRUCTOR_ID:
                raise TLCodecError(f"expected constructor 0x{cls.CONSTRUCTOR_ID:08x}, got 0x{constructor_id:08x}")
        _value_user_id, cursor = decode_long(raw_data, cursor)
        return cls(user_id=_value_user_id), cursor


class account:
    SentEmailCode = AccountSentEmailCode


class messages:
    SponsoredMessagesEmpty = MessagesSponsoredMessagesEmpty
    TranslatedRichMessage = MessagesTranslatedRichMessage


class payments:
    CheckedGiftCode = PaymentsCheckedGiftCode


class smsjobs:
    EligibleToJoin = SmsjobsEligibleToJoin


class upload:
    CdnFile = UploadCdnFile


ALL_TYPES: tuple[type[TLConstructor], ...] = (
    InputUserEmpty,
    UpdatePtsChanged,
    UpdateDialogFilters,
    UpdateQuickReplyMessage,
    UpdateSentPhoneCode,
    UpdateGroupCallChainBlocks,
    InputPrivacyValueAllowChatParticipants,
    MessageEntitySpoiler,
    TextEmpty,
    TextImage,
    InputPaymentCredentialsSaved,
    UploadCdnFile,
    SecureValueError,
    AccountSentEmailCode,
    InputThemeSettings,
    GlobalPrivacySettings,
    InputGroupCall,
    MessagesSponsoredMessagesEmpty,
    StoryItemDeleted,
    PaymentsCheckedGiftCode,
    PeerColor,
    SmsjobsEligibleToJoin,
    RequestedPeerChat,
    FactCheck,
    InputPasskeyCredentialPublicKey,
    MessagesTranslatedRichMessage,
    InlineButtonTypeUserProfile,
)
CONSTRUCTOR_ID_MAP: dict[int, type[TLConstructor]] = {entry.CONSTRUCTOR_ID: entry for entry in ALL_TYPES}
NAME_MAP: dict[str, type[TLConstructor]] = {entry.QUALNAME: entry for entry in ALL_TYPES}
__all__ = (
    "InputUserEmpty",
    "UpdatePtsChanged",
    "UpdateDialogFilters",
    "UpdateQuickReplyMessage",
    "UpdateSentPhoneCode",
    "UpdateGroupCallChainBlocks",
    "InputPrivacyValueAllowChatParticipants",
    "MessageEntitySpoiler",
    "TextEmpty",
    "TextImage",
    "InputPaymentCredentialsSaved",
    "UploadCdnFile",
    "SecureValueError",
    "AccountSentEmailCode",
    "InputThemeSettings",
    "GlobalPrivacySettings",
    "InputGroupCall",
    "MessagesSponsoredMessagesEmpty",
    "StoryItemDeleted",
    "PaymentsCheckedGiftCode",
    "PeerColor",
    "SmsjobsEligibleToJoin",
    "RequestedPeerChat",
    "FactCheck",
    "InputPasskeyCredentialPublicKey",
    "MessagesTranslatedRichMessage",
    "InlineButtonTypeUserProfile",
    "account",
    "messages",
    "payments",
    "smsjobs",
    "upload",
    "CONSTRUCTOR_ID_MAP",
    "NAME_MAP",
)
